### ISSUE TITLE
是否可以使用spigot版的towny

### ISSUE THREAD

**Issue by TRLWeiss** [Luohuayu/CatServer#100]
本人多次尝试安装dynmap-towny，发现必须安装前置插件spigot版towny。但spigot版towny正确安装后，好像输入/dynmap指令根本没用，只能运行forge版，希望修复下

**Comment by Luohuayu** [comment]
dynmap-towny已经停更, 1.9之后只有forge版本

**Comment by TRLWeiss** [comment]
emmm，但是catserver也不支持安装插件版的towny

**Comment by Luohuayu** [comment]
已测试可以正常使用

**Comment by TRLWeiss** [comment]
请问所用的是哪个版本的spigot-dynmap呢
我用的是dynmap-3.0-beta-10-spigot.jar
运行时显示：
[dynmap] Enabling dynmap v3.0-beta-10-257
 [Server thread/INFO]: [dynmap] Dynmap is disabled (unsupported platform)

输入/dynmap指令，正常；
进入卫星地图，无加载
