### ISSUE TITLE
Some problems with world dimensions

### ISSUE THREAD

**Issue by eugene-reim** [Luohuayu/CatServer#101]
1. MystCraft mod doesn't teleport to overworld dimension.
2. If we relog when being in nether then server spawn us underground of overworld worldspawn

**Comment by Luohuayu** [comment]
The portal is not created or cannot be teleported?

**Comment by eugene-reim** [comment]
Teleporting after relog back to the otherworld

чт, 26 мар. 2020 г., 15:29 Luohuayu <notifications@github.com>:

**Comment by eugene-reim** [comment]
And in MystCraft cannot be teleported

чт, 26 мар. 2020 г., 15:29 Luohuayu <notifications@github.com>:

**Comment by Luohuayu** [comment]
Fixed
https://github.com/Luohuayu/CatServer/commit/f0dc77dafa473585d6116c57a01cd465a77547d1
