### ISSUE TITLE
吃炼金化学的物品炸服：NoSuchMethodError: net.minecraft.util.FoodStats.func_75119_b(F)V

### ISSUE THREAD

**Issue by RisingInIris2017** [Luohuayu/CatServer#103]
#### Mod 版本:

alchemistry-1.0.36

#### Forge 版本
forge-1.12.2-14.23.5.2847

#### 单人游戏？多人游戏？

多人游戏，服务端 [CatServer-a38f3e1-universal](https://github.com/Luohuayu/CatServer/releases/tag/20.01.31)

#### 安装的MOD：
崩溃报告中有。

#### 如何复现
1. 吃 Alchemistry 炼金化学mod的氰化钾。
2. 服务端崩溃。

#### 崩溃报告链接：
https://paste.ubuntu.com/p/FPtffPmqvR/

**Comment by Luohuayu** [comment]
该MOD在服务端调用客户端方法, 请与作者反馈
