### ISSUE TITLE
RefinedStorage模组导致服务端崩溃

### ISSUE THREAD

**Issue by RisingInIris2017** [Luohuayu/CatServer#104]
#### Mod 版本:

refinedstorage-1.6.15

#### Forge 版本
forge-1.12.2-14.23.5.2847

#### 单人游戏？多人游戏？

多人游戏，服务端 [CatServer-a38f3e1-universal](https://github.com/Luohuayu/CatServer/releases/tag/20.01.31)

#### 安装的MOD：
崩溃报告中有。

## 问题描述
崩溃时是深夜一点，玩家在挂机时突然崩溃。

#### 崩溃报告链接：
https://paste.ubuntu.com/p/QgYqNqKYKD/

**Comment by Luohuayu** [comment]
应该是MOD自身问题, 请向作者反馈
