### ISSUE TITLE
Projectile can't do correct damage to Entities.

### ISSUE THREAD

**Issue by TUCAOEVER** [Luohuayu/CatServer#105]
I am using MMoItems which could be found on SpigotMC
https://www.spigotmc.org/resources/mmoitems-premium.39267/
When i am using bow to shoot, arrow could not do correct damage(which had been edited by MMoItems) to Entities.
And i have tried using Spigot. It works well.
So i can confirm it's Cat Server issue.

**Comment by Luohuayu** [comment]
Are you using the universal version? Please provide more information
