### ISSUE TITLE
水产养殖 钓鱼竿 鱼钩消失

### ISSUE THREAD

**Issue by Shuazijun** [Luohuayu/CatServer#107]
如题,使用核心: CatServer-abd368c-async.jar
水产养殖Mod版本: Aquaculture-1.12.2-1.6.8.jar
控制台报错: defineId called for: class net.minecraft.entity.projectile.EntityFishHook from class com.teammetallurgy.aquaculture.handlers.EntityCustomFishHook
已向mod作者发出issues,得到回复.作者认为这是服务器核心的锅,应该找服务器核心反馈.

**Comment by Luohuayu** [comment]
有没有试过稳定版

**Comment by Luohuayu** [comment]
稳定版未复现该问题

**Comment by Shuazijun** [comment]
太难了,mod多 不用多线不是爆炸么,还是e5 2667v2 这种U

**Comment by Shuazijun** [comment]
测试了,同环境,用稳定版核心,一样报错,钩子消失

**Comment by Luohuayu** [comment]
请排除其他MOD和插件
