### ISSUE TITLE
玩家被NPC打中导致服务端崩溃 Description: Ticking player

### ISSUE THREAD

**Issue by RisingInIris2017** [Luohuayu/CatServer#108]
#### Mod 版本:

不确定是什么MOD导致的崩溃。

#### Forge 版本
forge-1.12.2-14.23.5.2847

#### 单人游戏？多人游戏？

多人游戏，服务端 CatServer-4ab46b6-async

#### 安装的MOD：
崩溃报告中有。

## 问题描述
玩家反馈说，被NPC打中掉入岩浆中，突然服务器崩溃。
#### 崩溃报告链接：
https://paste.ubuntu.com/p/VCkyX9QxwM/

**Comment by Luohuayu** [comment]
请尝试在稳定版复现再反馈

**Comment by RisingInIris2017** [comment]
已经在稳定版复现，发在新的 Issue 当中。
