### ISSUE TITLE
玩家被NPC打中导致服务端崩溃 Description: Ticking player

### ISSUE THREAD

**Issue by RisingInIris2017** [Luohuayu/CatServer#111]
#### Mod 版本:

不确定是什么MOD导致的崩溃。

#### Forge 版本
forge-1.12.2-14.23.5.2847

#### 单人游戏？多人游戏？

多人游戏，服务端 CatServer-b10faff-universal

#### 安装的MOD：
崩溃报告中有。

## 问题描述
服务器突然崩溃，没有明显的预兆。
#### 崩溃报告链接：
https://paste.ubuntu.com/p/VCkyX9QxwM/

此 Issue 中，崩溃报告中的 Stacktrace 与 https://github.com/Luohuayu/CatServer/issues/108 接近，
怀疑是同一个 Bug 导致。

**Comment by Luohuayu** [comment]
安装MOD过多无法判断哪个造成的

**Comment by Luohuayu** [comment]
建议询问玩家崩溃前进行的操作

**Comment by RisingInIris2017** [comment]
> 建议询问玩家崩溃前进行的操作

询问过了，的确是服务器突然崩溃，突然。
这个玩家身上带有的药水效果也不明确。
我尝试使用/effect 玩家ID clear 命令试一试，但是不确定怎么复现这个 bug。

**Comment by Luohuayu** [comment]
GokiStats的问题
https://github.com/InfinityStudio/GokiStats/issues/42
