### ISSUE TITLE
Request compatibility FTB Utilities

### ISSUE THREAD

**Issue by EnterFor** [Luohuayu/CatServer#114]
Only block declared features can be used
Other functions or command consoles will report errors
Can I ask you to be compatible with this mod?
Please

Version: Universal
ForgeServer no error

**Comment by Luohuayu** [comment]
Please provide detailed error information

**Comment by EnterFor** [comment]
First, the leaderboard function is not available
No data is logged and the console is error free

Other error logs are lost
I will continue to give feedback when they appear again. Thank you for your reply

**Comment by EnterFor** [comment]
A tutorial on FTB utilities
https://www.bilibili.com/video/av30126800

**Comment by Luohuayu** [comment]
暂无计划提供兼容
