### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by dayd21git** [Luohuayu/CatServer#115]
Hello! Have you noticed that chickens and other mobs behave strangely in your async-core?

Chickens: constantly waving their wings.
Slugs: endlessly make a jump sound
Other mobs: not tested

This is not the last bug I found.
I would like to help you find problems in the hope that your work will be worthy. Can I post them here?

P.S. google translate

**Comment by dayd21git** [comment]
Please do not close discussions in which the problem has not been resolved, so that others can see the reason for it and do not ask unnecessary questions.

P.S. google translate

**Comment by dayd21git** [comment]
Not all territory is unloaded when the player has left it.
You can also observe that from time to time the territory is loaded randomly.
In fact, there are 300 of them.
Not async version.
[https://i.ibb.co/zXd09Yn/Scr01.jpg](url)

**Comment by dayd21git** [comment]
Sometimes there are such errors(no-async-version):
https://pastebin.com/5gQEcUNE

**Comment by dayd21git** [comment]
How about the CraftTweaker? As I understand it, in the new version of the server-core, this block does not delete recipes(crafts). Am I wrong?

**Comment by Luohuayu** [comment]
No longer accepts async issues
