### ISSUE TITLE
弓箭问题

### ISSUE THREAD

**Issue by Bkm016** [Luohuayu/CatServer#116]
@Luohuayu @KomiMoe 

```kotlin
    @EventHandler(priority = EventPriority.HIGH, ignoreCancelled = true)
    fun damage(e: EntityDamageByEntityEvent) {
        // ...
    }
```

只要是弓箭命中生物就永远不会触发上面这个监听器，`ignoreCancelled = false` 后可用。

**Comment by Bkm016** [comment]
如果被其他插件 `setCancelled(true)` 后弓箭应该会弹开。
但现在弓箭能够正常对生物造成原版伤害，应该不是插件冲突。

**Comment by Luohuayu** [comment]
使用最新的稳定版测试未复现

**Comment by Bkm016** [comment]
测试版本 CatServer-e805c1f-async
`This server is running CatServer version git-CatServerAsync-1.12.2-e805c1f (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT, Forge version 14.23.5.2847)` 

是最新版吗

**Comment by Bkm016** [comment]
我再检查一下是不是某些操作导致，因同样插件 bukkit 环境下正常

**Comment by Luohuayu** [comment]
尝试使用稳定版
