### ISSUE TITLE
活塞推动虚无世界的嗜血结晶实体会导致崩服

### ISSUE THREAD

**Issue by Tewi-wanli** [Luohuayu/CatServer#12]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  MKUPTCoreMod (MKUPT-1.1-9.18.jar)
Contact their authors BEFORE contacting forge

// Don't be sad, have a hug! <3

Time: 19-10-12 上午11:12
Description: Ticking block entity

java.lang.ArrayIndexOutOfBoundsException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:2173)

-- Block entity being ticked --
Details:
	Name: minecraft:piston // net.minecraft.tileentity.TileEntityPiston
	Block type: ID #4 (tile.stonebrick // net.minecraft.block.Block // minecraft:cobblestone)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (5649,44,2163), Chunk: (at 1,2,3 in 353,135; contains blocks 5648,0,2160 to 5663,255,2175), Region: (11,4; contains chunks 352,128 to 383,159, blocks 5632,0,2048 to 6143,255,2559)
	Actual block type: ID #4 (tile.stonebrick // net.minecraft.block.Block // minecraft:cobblestone)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:2173)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:747)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:935)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:469)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:804)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658)
	at java.lang.Thread.run(Unknown Source)

-- Affected level --
Details:
	Level name: world
	All players: 5 total; [EntityPlayerMP['Metis_A'/2587176, l='world', x=-3768.91, y=250.00, z=-1967.67](Metis_A at -3768.9128562170135,250.0,-1967.672161509964), EntityPlayerMP['112'/2476310, l='world', x=6290.30, y=40.00, z=9685.30](112 at 6290.300000011921,40.0,9685.302329900442), EntityPlayerMP['dawfoiao'/2774563, l='world', x=9958.38, y=65.00, z=-5589.52](dawfoiao at 9958.378980076637,65.0,-5589.521925844861), EntityPlayerMP['xms666'/2770896, l='world', x=5653.75, y=42.00, z=2167.32](xms666 at 5653.751822995074,42.0,2167.3248003034496), EntityPlayerMP['Xpp'/2571474, l='world', x=3611.61, y=68.25, z=9211.21](Xpp at 3611.609444823191,68.24918714173913,9211.207009027794)]
	Chunk stats: ServerChunkCache: 831 Drop: 0
	Level seed: -4703487379267468829
	Level generator: ID 29 - RTG, ver 0. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-188,64,256), Chunk: (at 4,4,0 in -12,16; contains blocks -192,0,256 to -177,255,271), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 90228046 game time, 90325749 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 155675 (now: false), thunder time: 103281 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false

**Comment by Luohuayu** [comment]
报错信息不完整
