### ISSUE TITLE
无法正常触发某些事件

### ISSUE THREAD

**Issue by Joket-abc** [Luohuayu/CatServer#123]
在原版服务器使用鸡蛋仍动物会触发EntityDamageEvent和EntityDamageByEntityEvent事件，但是最新稳定版cat端（CatServer-05e5dcd-universal.jar）不行，导致一些插件(EggCatcher)失效。

**Comment by Luohuayu** [comment]
Forge的伤害处理和Bukkit冲突, 一直在修都没修好

**Comment by Joket-abc** [comment]
> Forge的伤害处理和Bukkit冲突, 一直在修都没修好

因为古老的cat pro版本是可以触发这两个事件的，或许可以出个选项来选择伤害处理是Forge还是Bukkit优先？

**Comment by Luohuayu** [comment]
已修复

**Comment by Joket-abc** [comment]
测试 CatServer-8a186f9-universal.jar 还是同样鸡蛋扔动物无法触发伤害事件

**Comment by Joket-abc** [comment]
> 已修复

测试 CatServer-8a186f9-universal.jar 还是同样的鸡蛋扔动物无法触发伤害事件
