### ISSUE TITLE
在一次交互中同时触发两次交互事件

### ISSUE THREAD

**Issue by KioProject123** [Luohuayu/CatServer#124]
左键交互没有这个问题，只在右键交互有。
测试环境最新稳定版 CatServer-05e5dcd-universal.jar

**Comment by TUCAOEVER** [comment]
你是不是在用 额外植物学...? 魔术手指还有几个遗物都是会触发两次交互事件的(虽然是右手 但是左右手都会触发) 其他物品没有这个问题 应该是MOD导致的

**Comment by KioProject123** [comment]
补图，事件后的数字为时间戳
[https://s2.ax1x.com/2020/02/29/3r5EfU.png](https://s2.ax1x.com/2020/02/29/3r5EfU.png)

**Comment by KioProject123** [comment]
> 你是不是在用额外植物学...？魔术手指还有几个遗物都是会触发两次交互事件的（虽然是右手但是左右手都会触发）其他物品没有这个问题应该是MOD导致的

我是在无mod无插件的环境下测试的

**Comment by Luohuayu** [comment]
高版本特性 两次交互分别为左手和右手

**Comment by Luohuayu** [comment]
可以在Spigot测试一下

**Comment by KioProject123** [comment]
确认
