### ISSUE TITLE
拔刀问题

### ISSUE THREAD

**Issue by Jo-maYple** [Luohuayu/CatServer#127]
https://paste.ubuntu.com/p/FVj8nsTXvS/

**Comment by ThePennitentOne** [comment]
Looks like tinkers tool leveling dosen't like slashblade katanas, maybe try setting them to not be afected by the leveling process or something, Dose it work propply on regular forge?

**Comment by Luohuayu** [comment]
拔刀与匠魂冲突, 请反馈给MOD作者
