### ISSUE TITLE
建议在Bukkit.yml添加禁止Mod世界生成相关开关

### ISSUE THREAD

**Issue by MMotherFucker** [Luohuayu/CatServer#140]
建议添加一个像1.7.10一样的设置,在Uranium包括KC中都有这个设置
可以开关禁用生成世界
例如:
-----------------------------
world-settings:
  sh:
    enabled: true
  pl:
    enabled: true
  et:
    enabled: true
  ev:
    enabled: true
  im:
    enabled: true
  cp:
    enabled: true
  cd:
    enabled: true
  cr:
    enabled: true
  cl:
    enabled: true
  acv:
    enabled: true
  ll:
    enabled: true
  lc:
    enabled: true
  bt:
    enabled: true
  rn:
    enabled: true
  nether:
    enabled: false
  vp:
    enabled: true
  lb:
    enabled: true
  ds:
    enabled: true
  gk:
    enabled: true
  gd:
    enabled: true
  dp:
    enabled: true
  lu:
    enabled: true
  ir:
    enabled: true
  my:
    enabled: true
  pc:
    enabled: true
  hv:
    enabled: true
  ab:
    enabled: true
  the_end:
    enabled: false
-------------------------------
类似这种的开关,可以更好的节省不必要的世界生成,

**Comment by Luohuayu** [comment]
请在MOD配置禁用世界, 强行禁用会造成某些MOD报错甚至崩溃
