### ISSUE TITLE
AOA3(虚无世界3) 传送门失效的问题

### ISSUE THREAD

**Issue by airdm** [Luohuayu/CatServer#141]
可以从主世界 传送到aoa3的世界中 但是无法返回也无法使用aoa3世界中的任何其他传送门
传送时后台提示 moved wrongly!
世界生成正常 在world文件中所有AOA3的世界都已经正常生成只不过名字有点奇怪.
在单机中生成的世界都是用英文命名的 在服务端生成的世界都是DIM数字 生成的
单机"AoA_Abyss" 服务端"DIM800"
我也检查过AOA3的配置文件 我发现是相同的没有任何变化
请问如何解决这个问题

**Comment by Luohuayu** [comment]
Bukkit修改了传送机制导致传送门无法使用 请使用插件代替传送门功能
