### ISSUE TITLE
主循环崩溃

### ISSUE THREAD

**Issue by StarchierOrb** [Luohuayu/CatServer#144]
服务器隔一段时间之后会无征兆崩溃
崩溃报告：https://paste.ubuntu.com/p/DzHQ9NkSXG/

**Comment by Luohuayu** [comment]
请提供debug.log

**Comment by StarchierOrb** [comment]
截取了蹦服前几分钟的debug.log，没有异常报错

https://paste.ubuntu.com/p/xtH2pPQMgM/

**Comment by Luohuayu** [comment]
完整log里有没有`Try to asynchronously `等内容

**Comment by StarchierOrb** [comment]
有，玩家打开天境mod的饰品背包会出现，然后整个日志除了插件常规报错，还有ic2的护甲报错
https://paste.ubuntu.com/p/7vVHvTZzqn/

**Comment by StarchierOrb** [comment]
换成多线程版后也会出现相同类型的报错，但不会崩溃
https://paste.ubuntu.com/p/2623Dsj96S/

**Comment by Luohuayu** [comment]
https://github.com/Luohuayu/CatServer/commit/d427cbd005064aa53b11474cb8eb4da18ceec428

**Comment by Luohuayu** [comment]
尝试更新到最新releases

**Comment by StarchierOrb** [comment]
更新后家具mod的电脑方块无法正常使用了，玩家使用电脑方块会直接掉线，并且物品会被全部吞掉,
报错应该是异步给物品被拦截了
报错：https://paste.ubuntu.com/p/QwbZD688br/

**Comment by Luohuayu** [comment]
家具MOD异步操作造成的服务端崩溃, 请向MOD作者反馈
