### ISSUE TITLE
Rcon会导致CPU使用率达到100%

### ISSUE THREAD

**Issue by H-H-Dang** [Luohuayu/CatServer#147]
![ECA724EEECC9A3BDDA4BA0CD0EE12A55](https://user-images.githubusercontent.com/56497239/76943383-3a93b600-693a-11ea-9097-f4232294aa55.gif)
稳定版和异步都会这样子，没有安装任何插件和mod（原版不会这样子，只有1%左右的浮动）   
到了100%后他就一直那样了等了几分钟还是100%，Rcon客户端试过一个C#实现的和一个c实现的都是这样子。

**Comment by Luohuayu** [comment]
请使用最新版本构建
https://github.com/Luohuayu/CatServer/commit/69319e3a370e908e287a47a1b3369b4046665722
