### ISSUE TITLE
懒人AE2  大型装配室服务器重启后断开连接

### ISSUE THREAD

**Issue by EnterFor** [Luohuayu/CatServer#148]
https://github.com/phantamanta44/Lazy-AE2/issues/25

细节：组装完装配室之后，可以正常连接。
如果服务器重启，连接到装配室的线缆会掉落。
玩家具有安全终端，如果是AE2自身问题，就关闭这个问题8，可能没救

**Comment by Luohuayu** [comment]
不提供对AE2的任何支持

**Comment by EnterFor** [comment]
懒人AE2是扩展模组，大型装配室是懒人AE2的多方块结构

**Comment by Luohuayu** [comment]
无法判断问题是否因为AE2造成, AE2不适合在任何非原版Forge使用, 所以不提供支持
