### ISSUE TITLE
railcraft导致的崩溃问题及解决方案

### ISSUE THREAD

**Issue by DictXiong** [Luohuayu/CatServer#149]
**crash report**: https://paste.ubuntu.com/p/BDWXwPhsWf/

**原因**: railcraft自定义了漏斗矿车类`EntityCartHopper` (父类`CartBaseContainer`从`EntityMinecartContainer`继承), 它在`org.bukkit.craftbukkit.entity`包的`CraftEntity.getEntity()`方法中无法被正常识别为漏斗矿车 (仅识别为普通矿车), 导致它在`net.minecraft.entity.item.EntityMinecartContainer.getOwner()`中的`cart`对象不是`InventoryHolder`类的实现, 所以返回了空指针, 在`net.minecraft.tileentity.TileEntityHopper.java`的457行的`destination.getOwner().getInventory()`抛出空指针异常.

**解决方法**: `net.minecraft.entity.item.EntityMinecartContainer.getOwner()` 添加一行, 具体实现如下

```
\\import catserver.server.inventory.CatCustomInventory;import net.minecraft.inventory.IInventory;
public InventoryHolder getOwner() {
        org.bukkit.entity.Entity cart = getBukkitEntity();
        if(cart instanceof InventoryHolder) return (InventoryHolder) cart; 
        else if (this instanceof IInventory) return new CatCustomInventory((IInventory) this); \\new line here
        return null;
    }
```

**Comment by Luohuayu** [comment]
已修复
https://github.com/Luohuayu/CatServer/commit/e0176d5773e7115e40b196cd6704bc96afb54a9e
