### ISSUE TITLE
请求兼容imipet插件

### ISSUE THREAD

**Issue by ALandXLT** [Luohuayu/CatServer#150]
imipet2.5.2在猫端无法召唤宠物
插件地址 http://www.imipet.com/resources/2/

**Comment by Luohuayu** [comment]
不开源插件请反馈作者自行兼容

**Comment by ALandXLT** [comment]
插件作者说是猫端不兼容
![QQ截图20200323122451](https://user-images.githubusercontent.com/43927061/77281333-bb1f3180-6d01-11ea-9315-32ef8a301edf.png)
