### ISSUE TITLE
玩家正常游玩过程中服务端崩溃：Ticking player

### ISSUE THREAD

**Issue by RisingInIris2017** [Luohuayu/CatServer#154]
#### Catserver 版本

CatServer-84310a9-universal

#### 完整的MOD列表 - Installed mods:
https://paste.ubuntu.com/p/m6HV7zFZZW/

#### 完整的插件列表 - Installed plugins:
![QQ截图20200325225829](https://user-images.githubusercontent.com/28519848/77550529-2d536a00-6eec-11ea-9848-7fba3bee8667.png)

## 崩溃报告的链接 - Link to full crash log

以下是五个不同的玩家在服务器上游玩过程中突然发生服务器崩溃对应的崩溃报告。
报错的 Stacktrace 完全相同，推测是同一 Bug 导致。
1. https://paste.ubuntu.com/p/3m3JbNJtBJ/
2. https://paste.ubuntu.com/p/DtqMfgyS6K/
3. https://paste.ubuntu.com/p/wGH33VgXd5/
4. https://paste.ubuntu.com/p/c7D8htdVCf/
5. https://paste.ubuntu.com/p/Yx4zx6vn2X/
#### 产生Bug的步骤 - How to reproduce:

询问上述五个玩家得知，崩溃都是突然发生，之前没有什么异常的表现。

**Comment by Luohuayu** [comment]
非服务端问题, 请检查安装的MOD
