### ISSUE TITLE
找不到玩家的饱食度，传送书虚无世界3 崩溃

### ISSUE THREAD

**Issue by songyuesheng** [Luohuayu/CatServer#155]
![QQ图片20200326183520](https://user-images.githubusercontent.com/62697884/77638206-bffa1480-6f91-11ea-852b-5dcff610c81d.png)
[debug.log](https://github.com/Luohuayu/CatServer/files/4386620/debug.log)
[latest.log](https://github.com/Luohuayu/CatServer/files/4386621/latest.log)
[crash-2020-03-26_11.26.24-server.txt](https://github.com/Luohuayu/CatServer/files/4386622/crash-2020-03-26_11.26.24-server.txt)
![QQ图片20200326183526](https://user-images.githubusercontent.com/62697884/77638228-c4bec880-6f91-11ea-8290-ad4632cfcf9e.png)

已经上传 报告，请求作者修复兼容虚无世界3.2.6传送书mod

**Comment by Luohuayu** [comment]
非服务端问题 请向MOD作者反馈
