### ISSUE TITLE
console errors 

### ISSUE THREAD

**Issue by HeberonYT** [Luohuayu/CatServer#161]
Hi, I want to report that my server's console throws these errors randomly, even when the server is empty.
I'm not sure of the cause, but I guess it's the core of the server that is executing some task and fails to complete.

Forge: 14.23.5.2847
CatServer 1.12.2-3440193

https://pastebin.com/raw/4Q8f1wLH

**Comment by Luohuayu** [comment]
May be caused by a mod command completion, please check mods
