### ISSUE TITLE
Spawn egg loses attributes

### ISSUE THREAD

**Issue by HeberonYT** [Luohuayu/CatServer#162]
Forge: 14.23.5.2847
CatServer 1.12.2-3440193

Hello, since using CatServer I have had problems with eggs to spawn entities.
When I get an egg from the jei, it becomes invalid egg and it doesn't work to spawn the entity, this happens instantly and at other times it happens when I move from place in my inventory.
I know it is not easy to understand, so I have captured a small video where you can see how the eggs are replaced when they are in the inventory.
This is fixed when I run the server with the forge jar.

https://i.gyazo.com/9d1e4f20b4245e4ddec86df09966f873.mp4

https://i.gyazo.com/199d54deaff7c7a71993d075085b64ac.mp4

**Comment by Luohuayu** [comment]
Fixed
