### ISSUE TITLE
虚无世界3(AoA3)其他维度传回主世界的传送门不工作

### ISSUE THREAD

**Issue by Youwenqwq** [Luohuayu/CatServer#167]
### 相关信息

测试用的配置:
CPU:R9 3900X
内存分配:6G
测试Forge官服版本:14.23.5.2847
Catserver版本:CatServer-3440193-universal.jar
Catserver多线程版本也测试过,用的是最终版,问题依旧
虚无世界3版本:3.2.6

### Bug现象
在Catserver使用虚无世界3时，其他维度传送到主世界的传送门不工作，具体表现为站在传送门内，有声音但不传送，主世界传送到其他维度的传送门并没有此问题

### 后台提示
Bug出现期间后台无任何报错，debug.log也无任何报错

### 测试
使用forge官方服务器无任何问题，测试期间两个服务端都仅安装了虚无世界Mod，Catserver未安装插件，且两服务端生成的配置文件没有改动

基本可以确认是Catserver的问题，但是不排除其他原因,能否可以通过修改服务端来解决问题

**Comment by MMotherFucker** [comment]
此项为虚无世界Mod本身问题,这个配置在服务器内的现象正常,我也是开虚无服的，我认为没必要改.

**Comment by Youwenqwq** [comment]
> 此项为虚无世界Mod本身问题,这个配置在服务器内的现象正常,我也是开虚无服的，我认为没必要改.

这个是因为Bukkit修改了传送门机制导致的问题|还是得看服务器类型吧，我这个服务器比较偏向原版玩法， 不喜欢安装各种玩法插件，商店插件，传送插件啥的都没装(issue啊喂)

**Comment by Luohuayu** [comment]
已修复 传送门需要重新放置

**Comment by Youwenqwq** [comment]
> 已修复 传送门需要重新放置

谢谢了
