### ISSUE TITLE
CatServerBUG报告

### ISSUE THREAD

**Issue by ItsDia** [Luohuayu/CatServer#17]
1.不支持MOD指令
2.不显示计分板（有可能是不兼容FeatherBoard）
暂时就这两个BUG。。。后续我还会继续回报，望尽快修复

**Comment by ItsDia** [comment]
ProtocolLib亲测也不支持-

**Comment by Luohuayu** [comment]
1.已在1.0.9修复
2.实测计分板类插件可用,因FeatherBoard为付费插件无法测试

**Comment by Luohuayu** [comment]
ProtocolLib将在之后版本尝试兼容
