### ISSUE TITLE
URGENT - the server stopped starting!

### ISSUE THREAD

**Issue by BlackBaroness** [Luohuayu/CatServer#171]
Yesterday everything worked fine, today the console just freezes for a few minutes after ` Preparing start region for level 0`. There are 2 problems: `GC overhead limit exceeded` and `Java heap space`.

After removing all the flags and starting the server these problems stayed. I googled it, changed flags but nothing

**Comment by BlackBaroness** [comment]
I think it's because of the world. I have a 15000x12000 world limited by WorldBorder. This is strange, because only yesterday the world was quietly loading.

The latest version of the core, universal.

**Comment by Luohuayu** [comment]
Please set up enough memory
