### ISSUE TITLE
NetherEX issues

### ISSUE THREAD

**Issue by DerpDays** [Luohuayu/CatServer#172]
While using the catserver the mod NetherEX fails to generate the world properly, however when using normal forge or sponge it generates perfectly well, we would prefer to have it generate naturally instead of having to pre-generate the entire nether

Link to mod: https://www.curseforge.com/minecraft/mc-mods/netherex 
Mod Version: v2.0.15 (https://www.curseforge.com/minecraft/mc-mods/netherex/files/2783989)
Catserver Version: v20.04.14 (CatServer-3867946-universal.jar) (Latest)

**Comment by Luohuayu** [comment]
Fix later

**Comment by Luohuayu** [comment]
Upgrade to the latest version (20.05.05)
Add -1 to `autoUnloadDimensions` in catserver.yml

**Comment by DerpDays** [comment]
Thanks I'll try it out :)

**Comment by Forbidden-A** [comment]
@Luohuayu there is no version 20.05.05 yet, did you mean that we should wait until thats released?

**Comment by Luohuayu** [comment]
> 
> 
> @Luohuayu there is no version 20.05.05 yet, did you mean that we should wait until thats released?

Upload failed due to network problems
Re-uploaded

**Comment by Forbidden-A** [comment]
> > @Luohuayu there is no version 20.05.05 yet, did you mean that we should wait until thats released?
> 
> Upload failed due to network problems
> Re-uploaded

Thank you very much, the problem seems to be fixed, I will confirm shortly

**Comment by Forbidden-A** [comment]
> > > @Luohuayu there is no version 20.05.05 yet, did you mean that we should wait until thats released?
> > 
> > 
> > Upload failed due to network problems
> > Re-uploaded
> 
> Thank you very much, the problem seems to be fixed, I will confirm shortly

Works
