### ISSUE TITLE
Hello. I'd like to talk a little bit about Cubic Chunks.

### ISSUE THREAD

**Issue by Wonkun** [Luohuayu/CatServer#177]
I'm the one who leads a large-scale project. I wanted to increase the height limit of the game, so I applied the CubicChunks mode to the catservers mode bucket. But I think the bucket and the mode are not compatible. Is there any solution? I'd like to apply two modes. (CubicChunks, CubicWorldGen)

**Comment by Luohuayu** [comment]
CubicChunks break chunk handle, it's impossible to compatible

**Comment by Wonkun** [comment]
Isn't there any way?

**Comment by Wonkun** [comment]
> CubicChunks break chunk handle, it's impossible to compatible

Isn't there any way?
