### ISSUE TITLE
Draconic Evolution Issues

### ISSUE THREAD

**Issue by DerpDays** [Luohuayu/CatServer#178]
When catserver is used along with draconic evolution, catserver prevents items from being put into the machines, when tested on plain forge and sponge it works perfectly fine.

**Comment by Luohuayu** [comment]
What machines?

**Comment by Forbidden-A** [comment]
> What machines?

All of them

**Comment by DerpDays** [comment]
^

**Comment by MinuteSphinx** [comment]
includes all machines even in other mods like mekanism,thermal foundation

**Comment by Luohuayu** [comment]
Draconic Evolution works fine. Unable to reproduce the problem. Please check other things.
