### ISSUE TITLE
CatServer using LuckPerms in cracked server

### ISSUE THREAD

**Issue by Heriptik** [Luohuayu/CatServer#179]
Hello, i make this repport today because LuckPerms don't work in cracked server in CatServer.

I preferred to make a short video what to explain (poor english)

[https://drive.google.com/file/d/1BD7fUy9ETKWlZ5hxG5jDrlTWfnu5O_cz/view?usp=sharing](https://drive.google.com/file/d/1BD7fUy9ETKWlZ5hxG5jDrlTWfnu5O_cz/view?usp=sharing)

I inquired and found this on the LuckPerms wiki [https://imgur.com/a/hWyBMxj](https://imgur.com/a/hWyBMxj)

I hope you can solve my problem, if it's my handling that is not good, tell me what i should do

thanks

**Comment by Luohuayu** [comment]
I use LuckPerms in offline mode without any problems
