### ISSUE TITLE
CatServerBUG报告

### ISSUE THREAD

**Issue by ItsDia** [Luohuayu/CatServer#18]
1.不支持Title指令

**Comment by Luohuayu** [comment]
将在下一版本解决

**Comment by Luohuayu** [comment]
无法复现

**Comment by Luohuayu** [comment]
测试title指令可用
![1](https://user-images.githubusercontent.com/29095770/43035309-e6051bee-8d1f-11e8-9e1b-b40e9269baed.png)

**Comment by ItsDia** [comment]
我这边用title没提示啊- -

**Comment by ItsDia** [comment]
o,大概是不支持颜色？

**Comment by ItsDia** [comment]
我这边用EastLandPickupMessage不会提示

**Comment by Luohuayu** [comment]
收费插件的兼容问题,这边没法测试和解决

**Comment by ItsDia** [comment]
好的= =

**Comment by ItsDia** [comment]
大佬可以留一个QQ吗，到时候回报BUG也方便

**Comment by Luohuayu** [comment]
开发/反馈QQ群: 801482055
