### ISSUE TITLE
与flanmod不兼容（好像）

### ISSUE THREAD

**Issue by username-ui** [Luohuayu/CatServer#180]
安装flanmod和Modern.Warfare-Content.Pack-1.12.2-5.5.1（flan的包）后启动在最后闪退

---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 20-4-20 上午11:28
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
	at com.flansmod.apocalypse.common.world.buildings.WorldGenSkeleton.func_180709_b(WorldGenSkeleton.java:24)
	at com.flansmod.apocalypse.common.world.ChunkProviderApocalypse.func_185931_b(ChunkProviderApocalypse.java:388)
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1163)
	at net.minecraft.world.chunk.Chunk.populateCB(Chunk.java:1142)
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:165)
	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:426)
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:389)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:327)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:602)
	at java.lang.Thread.run(Thread.java:748)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_242, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM GraalVM CE 20.0.0 (mixed mode), Oracle Corporation
	Memory: 3789220144 bytes (3613 MB) / 4116185088 bytes (3925 MB) up to 4116185088 bytes (3925 MB)
	JVM Flags: 2 total; -Xms4096M -Xmx4096M
	IntCache: cache: 0, tcache: 0, allocated: 1, tallocated: 34
	CraftBukkit Information: 
   Running: CatServer version git-CatServer-1.12.2-f218cf9 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT) true
   Plugins: {}
   Warnings: DEFAULT
   Reload Count: 0
   Threads: { WAITING NonBlockingInputStreamThread: [java.lang.Object.wait(Native Method), jline.internal.NonBlockingInputStream.run(NonBlockingInputStream.java:275), java.lang.Thread.run(Thread.java:748)], RUNNABLE JVMCI-native CompilerThread0: [], RUNNABLE Server thread: [java.lang.Thread.dumpThreads(Native Method), java.lang.Thread.getAllStackTraces(Thread.java:1610), org.bukkit.craftbukkit.v1_12_R1.CraftCrashReport.call(CraftCrashReport.java:29), net.minecraft.crash.CrashReportCategory.func_189529_a(CrashReportCategory.java:96), net.minecraft.crash.CrashReport.func_71504_g(CrashReport.java:120), net.minecraft.crash.CrashReport.<init>(CrashReport.java:41), net.minecraft.server.MinecraftServer.run(MinecraftServer.java:665), java.lang.Thread.run(Thread.java:748)], RUNNABLE Signal Dispatcher: [], WAITING Reference Handler: [java.lang.Object.wait(Native Method), java.lang.Object.wait(Object.java:502), java.lang.ref.Reference.tryHandlePending(Reference.java:191), java.lang.ref.Reference$ReferenceHandler.run(Reference.java:153)], RUNNABLE Netty Server IO #0: [sun.nio.ch.WindowsSelectorImpl$SubSelector.poll0(Native Method), sun.nio.ch.WindowsSelectorImpl$SubSelector.poll(WindowsSelectorImpl.java:296), sun.nio.ch.WindowsSelectorImpl$SubSelector.access$400(WindowsSelectorImpl.java:278), sun.nio.ch.WindowsSelectorImpl.doSelect(WindowsSelectorImpl.java:159), sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86), sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97), io.netty.channel.nio.SelectedSelectionKeySetSelector.select(SelectedSelectionKeySetSelector.java:62), io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:732), io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:388), io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858), java.lang.Thread.run(Thread.java:748)], RUNNABLE Attach Listener: [], RUNNABLE Server console handler: [org.fusesource.jansi.internal.Kernel32.ReadConsoleInputW(Native Method), org.fusesource.jansi.internal.Kernel32.readConsoleInputHelper(Kernel32.java:761), org.fusesource.jansi.internal.Kernel32.readConsoleKeyInput(Kernel32.java:794), org.fusesource.jansi.internal.WindowsSupport.readConsoleInput(WindowsSupport.java:97), jline.WindowsTerminal.readConsoleInput(WindowsTerminal.java:214), jline.WindowsTerminal.access$000(WindowsTerminal.java:54), jline.WindowsTerminal$1.read(WindowsTerminal.java:156), jline.internal.NonBlockingInputStream.read(NonBlockingInputStream.java:166), jline.internal.NonBlockingInputStream.read(NonBlockingInputStream.java:135), jline.internal.NonBlockingInputStream.read(NonBlockingInputStream.java:243), jline.internal.InputStreamReader.read(InputStreamReader.java:257), jline.internal.InputStreamReader.read(InputStreamReader.java:194), jline.console.ConsoleReader.readCharacter(ConsoleReader.java:2136), jline.console.ConsoleReader.readCharacter(ConsoleReader.java:2126), jline.console.ConsoleReader.readBinding(ConsoleReader.java:2211), jline.console.ConsoleReader.readLine(ConsoleReader.java:2460), jline.console.ConsoleReader.readLine(ConsoleReader.java:2372), net.minecraft.server.dedicated.DedicatedServer$2.run(DedicatedServer.java:120)], WAITING HotSpotGraalManagement Bean Registration: [java.lang.Object.wait(Native Method), java.lang.Object.wait(Object.java:502), org.graalvm.compiler.hotspot.management.libgraal.runtime.SVMHotSpotGraalRuntimeMBean$Factory.run(SVMHotSpotGraalRuntimeMBean.java:474)], RUNNABLE JVMCI-native CompilerThread1: [], WAITING Finalizer: [java.lang.Object.wait(Native Method), java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:144), java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:165), java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:216)], TIMED_WAITING Server Infinisleeper: [java.lang.Thread.sleep(Native Method), net.minecraft.server.dedicated.DedicatedServer$1.run(DedicatedServer.java:92)], RUNNABLE DestroyJavaVM: [], TIMED_WAITING Craft Scheduler Thread - 1: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215), java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:460), java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:362), java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:941), java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1073), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624), java.lang.Thread.run(Thread.java:748)], TIMED_WAITING Craft Scheduler Thread - 0: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215), java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:460), java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:362), java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:941), java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1073), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624), java.lang.Thread.run(Thread.java:748)], TIMED_WAITING ForkJoinPool.commonPool-worker-1: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.ForkJoinPool.awaitWork(ForkJoinPool.java:1824), java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1693), java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)], TIMED_WAITING Craft Scheduler Thread - 2: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215), java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:460), java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:362), java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:941), java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1073), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624), java.lang.Thread.run(Thread.java:748)], RUNNABLE Thread-5: [java.io.FileOutputStream.writeBytes(Native Method), java.io.FileOutputStream.write(FileOutputStream.java:326), java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82), java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140), java.io.PrintStream.write(PrintStream.java:451), java.io.PrintStream.write(PrintStream.java:449), org.fusesource.jansi.AnsiOutputStream.write(AnsiOutputStream.java:82), java.io.FilterOutputStream.write(FilterOutputStream.java:125), java.io.PrintStream.write(PrintStream.java:480), java.io.FilterOutputStream.write(FilterOutputStream.java:97), org.bukkit.craftbukkit.v1_12_R1.util.TerminalConsoleWriterThread.run(TerminalConsoleWriterThread.java:40), java.lang.Thread.run(Thread.java:748)], TIMED_WAITING Craft Scheduler Thread - 3: [sun.misc.Unsafe.park(Native Method), java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215), java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:460), java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:362), java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:941), java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1073), java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134), java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624), java.lang.Thread.run(Thread.java:748)], TIMED_WAITING Spigot Watchdog Thread: [java.lang.Thread.sleep(Native Method), org.spigotmc.WatchdogThread.run(WatchdogThread.java:99)], WAITING Snooper Timer: [java.lang.Object.wait(Native Method), java.lang.Object.wait(Object.java:502), java.util.TimerThread.mainLoop(Timer.java:526), java.util.TimerThread.run(Timer.java:505)], RUNNABLE JVMCI-native CompilerThread2: [],}
   
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 6 mods loaded, 6 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                 | Version      | Source                          | Signature |
	|:------ |:------------------ |:------------ |:------------------------------- |:--------- |
	| LCHIJA | minecraft          | 1.12.2       | minecraft.jar                   | None      |
	| LCHIJA | mcp                | 9.42         | minecraft.jar                   | None      |
	| LCHIJA | FML                | 8.0.99.99    | CatServer-f218cf9-universal.jar | None      |
	| LCHIJA | forge              | 14.23.5.2854 | CatServer-f218cf9-universal.jar | None      |
	| LCHIJA | flansmod           | 5.5.1        | Flan.s.Mod-1.12.2-5.5.1.jar     | None      |
	| LCHIJA | flansmodapocalypse | 1.0          | Flan.s.Mod-1.12.2-5.5.1.jar     | None      |

	Loaded coremods (and transformers): 
	Profiler Position: N/A (disabled)
	Player Count: 0 / 20; []
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by Luohuayu** [comment]
flanmod自身问题
