### ISSUE TITLE
常见问题和提交Issues前必看

### ISSUE THREAD

**Issue by Luohuayu** [Luohuayu/CatServer#181]
**提交Issues前请仔细阅读以下内容, Issues务必使用标准模板(除非没有相应模板, 但标题一定要写明版本号). 无效Issues将直接关闭, 多次违反将屏蔽:**
1.请确保服务端是最新版本, MOD和插件是正确版本
2.只接受服务端兼容性问题反馈, 这里不是给你看报错的地方, MOD和插件自身问题请反馈相应作者处理
3.请先搜索类似问题是否已经有人反馈, 不接受重复的反馈
4.请明确哪个MOD或插件造成的问题, 不接受包含大量MOD或插件的整合包造成的不明确的问题反馈
5.有报错使用发完整报错, 没报错的详细图文描述或者视频(不接受百度云等需要登录才能查看的网盘)
6.不接受任何不开源MOD和插件的反馈
7.不要提交任何关于Sponge支持及MC版本更新(我们只提供常用版本的开发维护)的建议

**已知不兼容的MOD:**
FastWorkbench(仅1.12.2) (可使用[修改版](https://github.com/Luohuayu/FastWorkbench))
FTB Utilities (默认情况聊天处理功能不可用, 需要将catserver.yml文件的waitForgeServerChatEvent选项设置为true. 该选项仅限1.12.2, 其他版本暂未实现)
Applied Energistics 2 ([相关链接](https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/3950#issuecomment-471179599))
~~TheBetweenlands(仅1.12.2) ([开启死亡掉落导致复制戒指](https://github.com/Luohuayu/CatServer/issues/204))~~ (#914 开启regatherCapability选项可解决)
ShinColle(仅1.12.2) ([无法正确处理PlayerEvent.Clone事件](https://github.com/Luohuayu/CatServer/issues/433))

**已知不兼容的插件:**
ProtocolSupport/ViaVersion/ViaBackwards (Forge你还想跨版本?)
IllegalStack (部分功能不可用)
ProtocolLib 4.5.x(1.12.2请使用[4.3.0](https://github.com/dmulloy2/ProtocolLib/releases/tag/4.3.0)或[4.6.0+](https://github.com/dmulloy2/ProtocolLib/releases)版本, 1.16.5请使用[4.6.0+](https://github.com/dmulloy2/ProtocolLib/releases)版本. 建议关闭background compiler选项)
FAWE (不支持MOD方块)

**如何支持跨服:**
1.12.2:
将CatServer的spigot.yml文件的bungeecord选项设置为true
将BungeeCord的config.yml文件的ip_forward和forge_support选项设置为true
(推荐使用BungeeCord的[WaterFall](https://papermc.io/downloads#Waterfall)分支, 如出现实体异常可将waterfall.yml文件的disable_entity_metadata_rewrite选项设置为true)

1.16.5:
****注意: 由于1.13+以上原生Forge不支持跨服, 跨服功能由lightfall提供, 出现任何问题请反馈lightfall或使用其他跨服工具****
将CatServer的spigot.yml文件的bungeecord选项设置为true
使用[lightfall](https://github.com/Luohuayu/lightfall-releases/tree/master/lightfall)代替BungeeCord, 配置方法同1.12.2
客户端需要安装[lightfall-client](https://github.com/Luohuayu/lightfall-releases/tree/master/lightfall-client)作为MOD

_EDIT: 2025.02.04_

**Comment by yilangyo** [comment]
can not work with wizardry https://www.curseforge.com/minecraft/mc-mods/wizardry-mod
