### ISSUE TITLE
Use items from mods in plugins

### ISSUE THREAD

**Issue by michalk2k04** [Luohuayu/CatServer#182]
Hi, I have a problem with items from modifications and plugins.
For example
having the essentials plugin.
It works :
"/ minecraft: give michalk2k04 tp: stone_boots"
and this not:
"/give michalk2k04 tp: stone_boots"
Can this be changed in the next update?
I would be grateful!
Unless there is already a solution.
It works the same with all plugins!
Worldedit does not copy blocks from mods.
Multiverse does not import blocks with the world.

This is a very serious problem, if you don't change it I will have to change the engine! Anyway, not only me ...

**Comment by PiggiesGoSqueal** [comment]
Would this even be possible for them to add? Sounds like plugin developers would need to add the support?

Also, if "_/ minecraft: give ...._" works and "_/give ...._" does not, couldn't you just create an alias to make "_/give ..._" perform "_/ minecraft ..._"?

For example, MyCommand is a plugin that allows creating aliases and custom commands. You could use it to type in:
_/give pinkpig3777 tp: stone_boots_
Then it would perform:
_/ minecraft: give pinkpig3777 tp: stone_boots_

Also, you would only need to create ONE alias for the command.
**The username**, **tp:**, and **<item_name>** would be placeholders.

Please Note:
I probably won't check this page again. However, if you are interested the plugin page is:
  - https://dev.bukkit.org/projects/mycommand
  - And the developer is very responsive. :)

**Comment by Luohuayu** [comment]
Use command `/give michalk2k04 tp_stone_boots`
This is an issue with Essentials and not a server issue

You can use the [Forge WorldEdit](https://www.curseforge.com/minecraft/mc-mods/worldedit) to copy the mod block

Forge will not load block IDs from other worlds, so you need to keep the ID consistent to import using Multiverse

**Comment by michalk2k04** [comment]
I use wordedit for Islandworld plugin all plugin not include items or block from mod. Sry for my English.
In older engines, everything worked correctly, you could fix it. I guess you would have to modify the system of connecting plugins and mods quite heavily. I checked it on many plugins. And no plugin on / kit worked ... This is not a plugin problem.

**Comment by michalk2k04** [comment]
Unfortunately, I can't use forge wordedit because the schematic uses the Islandworld plugin and it also can't load anything from mods ...

**Comment by michalk2k04** [comment]
Its bug of server not plugins or mods. Minecraft normalny load items from mod plugins not

**Comment by michalk2k04** [comment]
I would be glad if you took care of it, it would certainly help me and not only me: D

**Comment by michalk2k04** [comment]
Pls set this to bug and repair this in free time 🙃😃
