### ISSUE TITLE
关于虚无世界服务器对传送门兼容后的问题

### ISSUE THREAD

**Issue by MMotherFucker** [Luohuayu/CatServer#184]
首先
更新核心之后,我服务器地图下的成就全部被重置！玩家上线成就全部被重置！
另外一个重大的BUG是,如果使用类似BetterRtp的传送插件,传送至末地或者地狱,未经原版传送门/Mod提供的传送门进行传送,世界将无法破坏（并且也无提示）！
你可以自己在本地服务器进行测试确认！
希望能够修复！
并不是所有服务器都要以原版的玩法进行开放的！

**Comment by Luohuayu** [comment]
1.最近几次更新均未修改任何跟成就有关的代码
2.使用BetterRtp传送到末地或地狱, 未复现世界无法破坏的问题
