### ISSUE TITLE
Mobs

### ISSUE THREAD

**Issue by mogcid** [Luohuayu/CatServer#185]
I have a problem I cannot type a mob with the sword and with the hand and with any object even the empty hand and moreover the mod chicken with the item chicken catcher in hand does not work for recovered chickens

**Comment by Luohuayu** [comment]
I don't understand what you are talking about.
A problem with a mod?

**Comment by mogcid** [comment]
already I can't hit 1 mob anywhere, empty hand ... don't walk
After I use a mod called chicken and to get a chicken you have to use the chicken catcher and it doesn't work as if there was an inventory bu

**Comment by Luohuayu** [comment]
Please give me the download link of the MOD
