### ISSUE TITLE
Gamestages forge mod does not save player data

### ISSUE THREAD

**Issue by blacksythe** [Luohuayu/CatServer#188]
[latest.log](https://github.com/Luohuayu/CatServer/files/4566574/latest.log)
[debug.log](https://github.com/Luohuayu/CatServer/files/4566575/debug.log)

Overview: When a player recieves a certain advancement it ranks them up in stages
This data is supposed to be saved as nbt data but it isnt and is lost when the player logs off

Forge: Sevtech latest version
catserver: latest git release
Spigot plugins installed but error occurs with no plugins at all --resolved

**Comment by Luohuayu** [comment]
I tested on Forge server and Gamestages will not save NBT data when the player logout.
It may be a problem with the MOD itself.

**Comment by Luohuayu** [comment]
You need to wait for a while to automatically save or run `save-all` command to force save

**Comment by blacksythe** [comment]
This does not work. I have ran the save-all on multiplayer and the information is not saved. My resolution was rebuilding the game stages functionality with spigot plugins. Will report to gamestages may have broken with newer forge versions
