### ISSUE TITLE
Luckperms don't works

### ISSUE THREAD

**Issue by Heriptik** [Luohuayu/CatServer#193]
Hello, i try to execute LuckPerms in my server (latest catserver update) but this plugin puts error in the console : [https://hastebin.com/lamelasizo.rb](https://hastebin.com/lamelasizo.rb)

I use catserver in offline-mod and I noticed that when I switch it to online-mod, the error disappears

thanks for your help

**Comment by Luohuayu** [comment]
Please check your Luckperms version

**Comment by Heriptik** [comment]
I use this version : LuckPerms-Bukkit-5.0.148.jar

**Comment by Luohuayu** [comment]
The error seems to be the plugin problem, please try another version

**Comment by Heriptik** [comment]
Ok, can you advise me a version?

**Comment by Luohuayu** [comment]
LuckPerms-Bukkit-5.0.72
I use it and it works fine

**Comment by Heriptik** [comment]
Same error : [https://hastebin.com/qeheqegeko.rb](https://hastebin.com/qeheqegeko.rb)

And my server no longer responding [https://imgur.com/YfzGvnc](https://imgur.com/YfzGvnc)

**Comment by Luohuayu** [comment]
Check other things. The plugin works, I am using.

**Comment by Heriptik** [comment]
In offline or online mod ?

I have a new error with GroupManager [https://hastebin.com/afamimirab.rb](https://hastebin.com/afamimirab.rb)

**Comment by Luohuayu** [comment]
> 
> 
> In offline or online mod ?
> 
> I have a new error with GroupManager https://hastebin.com/afamimirab.rb

Offline mode.
GroupManager should also work.

**Comment by blacksythe** [comment]
![image](https://user-images.githubusercontent.com/11398873/81180077-6fb79e80-8fa2-11ea-8c55-8ed4dd2d8be0.png)
Working on latest

**Comment by Heriptik** [comment]
Me too it's works in online-mod, but i need in offline.

I tried with the latest spigot 1.12.2 and I have no errors, with exactly the same configuration, I think the problem comes from CatServer

I made a video to explain the problem, you can see if the server is in **online-mod=true**, there is no problem, i can build and write in the chat, but if the server is in **online-mod=false**, i can't write in the chat, and a command in the console close the server.

I have pixelmon reforged 7.2.2 mod and just luckperms plugin.

[https://drive.google.com/file/d/1BD7fUy9ETKWlZ5hxG5jDrlTWfnu5O_cz/view?usp=sharing](https://drive.google.com/file/d/1BD7fUy9ETKWlZ5hxG5jDrlTWfnu5O_cz/view?usp=sharing)

**Comment by Luohuayu** [comment]
> 
> 
> Me too it's works in online-mod, but i need in offline.
> 
> I tried with the latest spigot 1.12.2 and I have no errors, with exactly the same configuration, I think the problem comes from CatServer
> 
> I made a video to explain the problem, you can see if the server is in **online-mod=true**, there is no problem, i can build and write in the chat, but if the server is in **online-mod=false**, i can't write in the chat, and a command in the console close the server.
> 
> I have pixelmon reforged 7.2.2 mod and just luckperms plugin.
> 
> https://drive.google.com/file/d/1BD7fUy9ETKWlZ5hxG5jDrlTWfnu5O_cz/view?usp=sharing

Unable to reproduce the problem, please try to delete the plugin data directory

**Comment by Forbidden-A** [comment]
> Hello, i try to execute LuckPerms in my server (latest catserver update) but this plugin puts error in the console : https://hastebin.com/lamelasizo.rb
> 
> I use catserver in offline-mod and I noticed that when I switch it to online-mod, the error disappears
> 
> thanks for your help

update your luckperms, on all of your servers
