### ISSUE TITLE
Support dropped for Porous

### ISSUE THREAD

**Issue by regix1** [Luohuayu/CatServer#194]
I've been with Catserver for along time, watching it grow and waiting on a stable release.
With the old Catserver, there was something called Porous. This allowed you to install sponge plugins/mods/whatever onto your server.

My Question:
Why was support dropped for this?
Did sponge contact you and say you couldn't do this?
It worked really well with the old version of Catserver.

Thank you

**Comment by Luohuayu** [comment]
Porous is an unofficial, non-open source project that cannot be supported.
CatServer has no plans to be compatible with Sponge.
