### ISSUE TITLE
所有mod物品都提示未知的物品:xxx

### ISSUE THREAD

**Issue by sweetapple-233** [Luohuayu/CatServer#195]
![image](https://user-images.githubusercontent.com/32138943/81284253-745a8080-9090-11ea-9ff4-c43df4d87259.png)
catserver最新版(5.5更新的，essX从最新版回退到目前的2.17.2.70仍然无用。最新版是.77

letest.log : https://gist.github.com/sweetapple-233/2285097268ec1b8e65ad4d8500132fb5

essX config.yml : https://gist.github.com/sweetapple-233/a1755511ed9df7f9b34ec6b7fe86b454

kits.yml : https://gist.github.com/sweetapple-233/b59e75c23ab39d116a67ca39c11f743a

事情起因是想要在kits.yml里面加mod的物品给新来的玩家
然后加完了测试一下说不存在或者被禁止了。
我去后台一看写着[Essentials] 未知的物品名称:waystones_waystone
![image](https://user-images.githubusercontent.com/32138943/81283845-e41c3b80-908f-11ea-961e-0a7409e620a7.png)

一开始以为是不是自己输入错误了。然后开始用/give 命令来拿waystones_waystone。发现也提醒了未知的物品名称。
然后使用/itemdb查看物品id。
![image](https://user-images.githubusercontent.com/32138943/81284051-2a719a80-9090-11ea-8cbf-00fd8a291495.png)
把物品数字id和文字全称都试过了。然后还以为是不是插件有毛病。看了看coreprotect里面写的名称也是一样的。就很纳闷不知道怎么回事
只要是原版的物品就可以/give或者添加到kit里面正常获取
每一次修改kits.yml后都有/ess reload确保加载了。

有找过essX的作者询问问题。对方回复catserver他没有官方支持。或许要来问问你这边。于是前来求助，感谢你的帮忙。。

**Comment by Luohuayu** [comment]
尝试更换2.15.0.1版本, 之后的版本为支持1.13版本以上不再兼容旧的ID

**Comment by sweetapple-233** [comment]
> 尝试更换2.15.0.1版本, 之后的版本为支持1.13版本以上不再兼容旧的ID

![KH(Z``7Z3ND$S$X_WT6_`KV](https://user-images.githubusercontent.com/32138943/81318494-ec409f00-90c0-11ea-8804-048f94fed00a.jpg)
感谢帮助！问题已经成功解决了
