### ISSUE TITLE
forge执行指令权限失效

### ISSUE THREAD

**Issue by Coloryr** [Luohuayu/CatServer#196]
看了两个mod的命令执行发现
![ok](https://user-images.githubusercontent.com/26276037/81493114-3f3c7100-92d0-11ea-8391-67d5a5386540.png)
这个的指令执行权限是正常的  

但是下面这方法
![no](https://user-images.githubusercontent.com/26276037/81493121-55e2c800-92d0-11ea-9e38-b4d14a246114.png)
执行命令的时候就会提示权限不够

**Comment by Luohuayu** [comment]
请提供权限错误的MOD下载地址和完整源码

**Comment by Coloryr** [comment]
BetterQuesting和ResearchTable

ResearchTable的用不了，自己已经修复了
