### ISSUE TITLE
Immersive Engineering Divide by 0

### ISSUE THREAD

**Issue by blacksythe** [Luohuayu/CatServer#197]
Causes an instant server crash when adding ore's to the crusher
Tested on a forge only version, no crash.
[crash-2020-05-10_09.46.06-server.txt](https://github.com/Luohuayu/CatServer/files/4609056/crash-2020-05-10_09.46.06-server.txt)

Forge server version
forge-1.12.2-14.23.5.2854.jar

Catserver
latest in releases

**Comment by Luohuayu** [comment]
Unable to reproduce. Please try to troubleshoot problems caused by other mods.
