### ISSUE TITLE
Embers Exchange Table

### ISSUE THREAD

**Issue by blacksythe** [Luohuayu/CatServer#198]
having some issues with embers, exchange table, setup correctly, works on forge server and single players makinjg a glimmer crystals. The animations do not show up and the glimmer crystal is not made.

Looked though logs and debugs + server console, no messages or debug info appears to be being recorded.

Pack is PO3
Latest Catserver releases

**Comment by Luohuayu** [comment]
Please provide a specific mod name and item and reopen the issue.
