### ISSUE TITLE
i can't turn my server to offline mode

### ISSUE THREAD

**Issue by ghost** [Luohuayu/CatServer#199]
Hello, I want to connect my server created with catserver to my bungeecord, so I have to put my server in CRACK, but every time I switch my server to CRACK, it automatically switches back to PREMIUM.
Can you help me ?

**Comment by adsa562** [comment]
Are you using any Minecraft Web Admin Panel for your server?
Some Admin Panel can override the settings you change in **server.properties**.

**Comment by ghost** [comment]
No, i use my computer
