### ISSUE TITLE
Enchanced building guide refuses to place blocks

### ISSUE THREAD

**Issue by wesleytech** [Luohuayu/CatServer#201]
information:
Catserver version: CatServer-ac735a0-universal
PO3 version: 3.3.57
issue:
the enchanced building guide (from openblocks) refuses to work on a multiplayer server. works fine in singleplayer

**Comment by Forbidden-A** [comment]
By refuses to work we mean that it doesn't place blocks and when you get close to the preview, it disappears

**Comment by Luohuayu** [comment]
Please provide a specific mod name and item and reopen the issue.
