### ISSUE TITLE
Unable to download libraries via the Website or via the Software.

### ISSUE THREAD

**Issue by SirOMGitsYOU** [Luohuayu/CatServer#202]
Running catserver won't download the libraries just sits waiting for a while, trying to download them from the website also presents a 504 gateway time out. 

Possibly an issue with the Catserver hosting website?

![image](https://user-images.githubusercontent.com/20475516/83433649-55ea6980-a431-11ea-9e72-25b104a6731e.png)

**Comment by Luohuayu** [comment]
Use the link to download:
https://github.com/Luohuayu/CatServerRes/blob/master/libraries.zip
