### ISSUE TITLE
关于nyx在夜晚下流星会直接崩溃的问题

### ISSUE THREAD

**Issue by endingpng** [Luohuayu/CatServer#205]
我用原版+forge试了下，似乎不会崩溃
catserver版本：CatServer-de043b8-universal
mod：Nyx-1.3.0.jar
https://www.curseforge.com/minecraft/mc-mods/nyx/files
这是崩溃报告
[crash-2020-06-13_00.47.50-server.txt](https://github.com/Luohuayu/CatServer/files/4772156/crash-2020-06-13_00.47.50-server.txt)

**Comment by Luohuayu** [comment]
已修复
