### ISSUE TITLE
forge的反射表好像炸了

### ISSUE THREAD

**Issue by Coloryr** [Luohuayu/CatServer#211]
https://paste.ubuntu.com/p/Hhmc7KVStq/

用ObfuscationReflectionHelper.setPrivateValue会炸，用ReflectionHelper.setPrivateValue就没问题

例如
ReflectionHelper.setPrivateValue(EntityLiving.class, (EntityLiving) entity, false, "field_82179_bU", null);
这样可以用
ObfuscationReflectionHelper.setPrivateValue(EntityLiving.class, (EntityLiving) entity, false, "persistenceRequired");
这样就不行

**Comment by Luohuayu** [comment]
服务端没有修改forge映射表 建议先在原版forge测试

**Comment by Coloryr** [comment]
原版forge正常，上了catserver就炸了

**Comment by Coloryr** [comment]
也不是啥大问题，能看就看吧，mod都能自己改
