### ISSUE TITLE
ActuallyAdditions的方块放置器无效

### ISSUE THREAD

**Issue by harrynhj** [Luohuayu/CatServer#213]
服务器核心版本:CatServer-5fd7768-universal.jar
mod版本:ActuallyAdditions-1.12.2-r151-2
没有安装任何插件
方块放置器在有红石信号（激活模式）并且有方块的情况下不放置方块
![image](https://user-images.githubusercontent.com/24500348/85112674-9b51b980-b1db-11ea-8871-b2d2172b2fec.png)
![image](https://user-images.githubusercontent.com/24500348/85112692-a3a9f480-b1db-11ea-8dd7-f078092ea521.png)

**Comment by Luohuayu** [comment]
https://github.com/Ellpeck/ActuallyAdditions/blob/ded3877b419a1514994bc454f299302a94c80b4b/src/main/java/de/ellpeck/actuallyadditions/mod/util/NetHandlerSpaghettiServer.java#L46
MOD传递的MinecraftServer的参数为null导致异常 请向MOD作者反馈
