### ISSUE TITLE
Server deadlock

### ISSUE THREAD

**Issue by GDVE** [Luohuayu/CatServer#215]
Greetings! The server deadlockat a certain point in time.

I started warmroast and connected to the server process and this is what I saw:
![image](https://user-images.githubusercontent.com/19783608/85233525-b99ffb00-b40f-11ea-983f-fd4a4a15effb.png)

Mods:
![Screenshot_3](https://user-images.githubusercontent.com/19783608/85233546-dfc59b00-b40f-11ea-95c6-339955c8f25a.png)

**Comment by Luohuayu** [comment]
Others have encountered the same problem on the Forge server.
This looks like a bug from Forge.
