### ISSUE TITLE
PixelExtras Permissions Not Working

### ISSUE THREAD

**Issue by Foulest** [Luohuayu/CatServer#217]
PixelExtras: https://pixelmonmod.com/mirror/core/5.1.2/

Using LuckPerms, latest version in the plugins folder.
Using Pixelmon, version 8.0.2.

When a player tries to run the command **/ivs**, instead of trying to check **pixelextras.command.ivs**, it checks **minecraft.command.ivs** instead. I've talked to Pixelmon support and they say that this is CatServer's problem.

**Comment by Foulest** [comment]
If I change the permission to **minecraft.command.command**, it works.

Here's what they say:
> There is a permission remap using Catserver and it doesn't take the mod id but the minecraft modid :/ (in their forge implementation)

**Comment by Luohuayu** [comment]
CatServer has always used `minecraft.command.<command>` permission for mod, if change it, anyone need to modify configuration after the update. So no plan to change it.
