### ISSUE TITLE
Updating Netty

### ISSUE THREAD

**Issue by Foulest** [Luohuayu/CatServer#219]
Please update Netty.
https://bugs.mojang.com/browse/MC-118372
https://bugs.mojang.com/browse/MC-118733

Players randomly get kicked and can't join back with no error messages.

**Comment by GDVE** [comment]
Sometimes a similar problem appears.

**Comment by bigenergy** [comment]
+1

**Comment by Luohuayu** [comment]
Replace libraries.info file in the jar to update netty: https://paste.ubuntu.com/p/w6mSQ5CMcR/

**Comment by ghost** [comment]
Have the same issue.

**Comment by Luohuayu** [comment]
Updated
