### ISSUE TITLE
载入EssX后Give指令无法获取带minecraft:前缀的物品

### ISSUE THREAD

**Issue by Becods** [Luohuayu/CatServer#22]
服务端版本：CatServer-126dc91-universal.jar
OS：CentOS 7.7.1908
Java：1.8.0_232
EssX版本：2.17.1.18
就像这样
![bluer_11-09_06-49.png](https://i.loli.net/2019/11/09/6K4Jfjsgv1EUpGa.png)

**Comment by Luohuayu** [comment]
EssX2.15.0.1测试该指令可用,请检查是否为插件版本问题

**Comment by Becods** [comment]
更换到2.15.0.60后问题解决，估计是为了兼容1.13后全英文id而做出的修改所导致的bug
