### ISSUE TITLE
玩家在交错次元使用匠魂武器攻击导致服务器崩溃

### ISSUE THREAD

**Issue by Caishangqi** [Luohuayu/CatServer#220]
玩家在交错次元打怪物的时候造成了服务器崩溃,测试后单人并没有此问题故猜测可能是服务器兼容问题
错误[报告](https://paste.ubuntu.com/p/6sjNjgtsjs/)
at com.sosnitzka.taiga.traits.TraitReviving.onEntityKill(TraitReviving.java:37)
这个reviving属性是匠魂的可以让生物复活(可能有点帮助😭)
使用的服务器版本是最新的,以确定单人无任何问题

**Comment by Luohuayu** [comment]
func_75616_a对应createEntityByID方法为客户端方法
请反馈MOD作者

**Comment by Caishangqi** [comment]
谢谢
