### ISSUE TITLE
玩家使用匠魂武器击杀暮色boss后崩溃

### ISSUE THREAD

**Issue by Caishangqi** [Luohuayu/CatServer#221]
玩家在用匠魂武器并且有(Slaughtering)特性时,攻击boss并且杀死boss一瞬间导致服务器崩溃,
使用的是最新版本的Catserver,所用插件修改怪物血量是(FMXT)
报错[记录](https://paste.ubuntu.com/p/bnpDW4qNmn/)

报错: java.lang.IllegalArgumentException: bound must be positive

**Comment by Luohuayu** [comment]
MOD未判断掉落物数量造成的问题 与服务端无关
