### ISSUE TITLE
CraftMapView getId always return 0

### ISSUE THREAD

**Issue by IM-IgniteDEV** [Luohuayu/CatServer#226]
Hi i found a critical bug in catserver.

When i create map via Bukkit.createMap(world): it always return 0 as id

spigot:

![image](https://user-images.githubusercontent.com/31209154/86397577-5c743700-bca4-11ea-880a-f4467f565986.png)

catserver:

![image](https://user-images.githubusercontent.com/31209154/86397608-6bf38000-bca4-11ea-849f-7f2ed1185b77.png)

This is getId method from CraftMapView

![image](https://user-images.githubusercontent.com/31209154/86397636-7dd52300-bca4-11ea-8646-ef1fcbeb84d3.png)

**Comment by Luohuayu** [comment]
Fixed
