### ISSUE TITLE
Exception caught during firing event net.minecraftforge.fml.common.gameevent.TickEvent$ServerTickEvent@46b55b1a: java.util.ConcurrentModificationException: null

### ISSUE THREAD

**Issue by texbobcatv2** [Luohuayu/CatServer#227]
SERVER boots then crashes about 30 seconds later

[crash-2020-07-02_20.49.59-server.txt](https://github.com/Luohuayu/CatServer/files/4866648/crash-2020-07-02_20.49.59-server.txt)

**Comment by Luohuayu** [comment]
Report to appliedenergistics2
