### ISSUE TITLE
Reduced TPS due to tickEntity

### ISSUE THREAD

**Issue by GeorgeMelikyan** [Luohuayu/CatServer#230]
Hello! Thanks for amazing job!  But I have a problem. 
I run **CatServer-bd3db8e-universal**.
When more than 50 players come to the server, I get 10 TPS on powerful hardware (i7 7700k 4x4.3Ghz).

In timings, **tickEntity** has a large load:
https://timings.spigotmc.org/?url=zisobuwapi

I applied various settings in **spigot.yml**, but it didn't help.
Will greatly appreciate it if you could consider this issue. Thanks!

**Comment by Luohuayu** [comment]
Need to use spark to generate more detailed analysis
https://github.com/lucko/spark

**Comment by Da-Spud** [comment]
Whats your Modlist, as im having the same issue only with 3 players online, tho i am using CatServer-1.12.2-a1adbd7

https://timings.spigotmc.org/?url=xoqefiwuyu

**Comment by GeorgeMelikyan** [comment]
I use this mods:
![image](https://user-images.githubusercontent.com/26774482/88212175-7f6c8800-cc5f-11ea-9c68-d8c0689dc56b.png)



> Whats your Modlist, as im having the same issue only with 3 players online, tho i am using CatServer-1.12.2-a1adbd7
> 
> https://timings.spigotmc.org/?url=xoqefiwuyu

**Comment by Da-Spud** [comment]
Ah you have much less mods than I do that would explain a lot atlaest, tho im still getting the issue with only 300 entities
https://docs.google.com/spreadsheets/d/1AuN3stCaBHjedIFuid3iq4_dZ7YvHWzZnlVWeGtFDi8/edit#gid=0

**Comment by LLjo** [comment]
same here, around 6-8 players is max for me before lag occurs, and that's with 120 mods
