### ISSUE TITLE
Crash server Frost Walker & Concrete Powder

### ISSUE THREAD

**Issue by Heriptik** [Luohuayu/CatServer#233]
Hi, I just reported two very annoying bugs since they instant crash the server.

 - Frost Walkers on Moded Shoes ([https://paste.ubuntu.com/p/FGMgZrTfqx/](https://paste.ubuntu.com/p/FGMgZrTfqx/))
 - Concrete powder on water ([https://paste.ubuntu.com/p/WHj3Kc35Jq/](https://paste.ubuntu.com/p/WHj3Kc35Jq/))

thanks for your help !

**Comment by LLjo** [comment]
Strange, i just tried both things and didnt get any crash at all.

**Comment by Luohuayu** [comment]
Have you ever deleted a MOD?

**Comment by Heriptik** [comment]
I don't have deleted mod

**Comment by Luohuayu** [comment]
Please upload debug.log

**Comment by Heriptik** [comment]
https://drive.google.com/file/d/14wRWEsoDwRPlkDA0DovSeWzQ7hDL3dfB/view?usp=sharing

**Comment by Luohuayu** [comment]
`[21:40:41] [Server thread/DEBUG] [FML]: Registry Block: Fixed minecraft:blocks id mismatch minecraft:concrete_powder: 252 (init) -> 344 (map).`
It seems that your world id data may be corrupted. The block id of minecraft is remapped.
You may need to regenerate a world.

**Comment by Heriptik** [comment]
I use a world that i made on a minecraft forge server, i dont know how vanilla minecraft id changed.

I have just 56 id block (vanilla) modified, it's not possible for you indicate to the server (plugin) to use the forge id instead of vanilla minecraft ? I don't think I'm the only one with this problem
