### ISSUE TITLE
Disconnect when breaking a block after updating to latest realease

### ISSUE THREAD

**Issue by alowave223** [Luohuayu/CatServer#237]
Hello! When i updated CatServer to latest commit 20.07.28 i get this error on breaking any block

https://hastebin.com/bavaqahaqe.rb

plugins: 
![image](https://user-images.githubusercontent.com/49539029/88730328-818e8500-d13e-11ea-9477-54eb77ed2497.png)

**Comment by Luohuayu** [comment]
What mods have you installed?

**Comment by alowave223** [comment]
https://api.mcsrvstat.us/2/40.127.198.136:25565

**Comment by Luohuayu** [comment]
It seems that it may be a problem with Hammer Core

**Comment by alowave223** [comment]
I check it soon

**Comment by alowave223** [comment]
So, I reinstalled all the mods and reinstalled the CatServer, if possible, updated to the latest version, at this time I removed unnecessary mods and Its no longer crash. Maybe crash cause by one of mods i deleted.
