### ISSUE TITLE
Chunk d'ont unload correctly

### ISSUE THREAD

**Issue by Heriptik** [Luohuayu/CatServer#238]
Hi, i have a pixelmon server in CatServer hybride and I noticed, chunk d'ont unload correctly.
At the same time, the server has been open since 20 hours and i have 47K chunks charged. [https://imgur.com/VoCDR9K](https://imgur.com/VoCDR9K) 4 in view distance and 80-100 players online simultaneously

My [Bukkit](https://paste.ubuntu.com/p/GGYWYRQ788/)
My [CatServer](https://paste.ubuntu.com/p/H8hyQ6QWnh/)
My [Spigot](https://pastebin.com/raw/Ed6xcM8a)

thanks for your help

**Comment by Heriptik** [comment]
I have 19 players connected in my server, the server has been opened since 25 hours and i have 49K chunks charged.

[https://imgur.com/ZFOmeeg](https://imgur.com/ZFOmeeg)

**Comment by day-d** [comment]
I confirm that this problem exists. However, it can also be caused by certain modifications, such as a mod Unloader.

**Comment by dayd21git** [comment]
> I have 19 players connected in my server, the server has been opened since 25 hours and i have 49K chunks charged.
> 
> https://imgur.com/ZFOmeeg

I confirm that this problem exists. However, it can also be caused by certain modifications, such as a mod Unloader and ExtraUtilits2(quantum quarry).

**Comment by Luohuayu** [comment]
Please check which mods will keep the chunk loaded

**Comment by dayd21git** [comment]
> Please check which mods will keep the chunk loaded

I don't quite understand how to do this, but I would be very happy if You could give me a hint

**Comment by Heriptik** [comment]
I use this mod : [screen](https://imgur.com/MBd3mgr)

I think is Phosphor or BiomesOPlenty

**Comment by Heriptik** [comment]
News ?
