### ISSUE TITLE
Crash with SpongeForge

### ISSUE THREAD

**Issue by Eddi2015** [Luohuayu/CatServer#24]
I compiled the latest CatServer from source and set it all up. It runs well, but when I add SongeForge to the mods folder the server doesn't start. Here's the latest log: https://privatebin.net/?937490f5d5d2652b#bo8LSlFoPXUIIbscqWPRkMtFML8v/K8pKDUfMQYdvLY=

**Comment by Luohuayu** [comment]
Do not support Sponge
