### ISSUE TITLE
catserver.yml

### ISSUE THREAD

**Issue by dayd21git** [Luohuayu/CatServer#241]
How do I find out what the settings in this file are responsible for?

**Comment by TheNullablePrototype** [comment]
As far as I know, the author does not provide a detailed description. You can guess by the name of the parameters. What exactly are you interested in?

**Comment by dayd21git** [comment]
It is bad that the author does not give a description of the available options.
For example, when and how the "autoUnloadDimensions"option is triggered.
If the author does not comment, we will have to open the source code and understand the logic of these options yourself.

**Comment by TheNullablePrototype** [comment]
According to the code in CatServer
if **all chunks of the world are unloaded** _and_
the target world **is not Bukkit World** _and_
its **id** is in the list of the **autoUnloadDimensions** parameter

then this world is being unloaded.

In other words, this parameter is responsible for the fact that all the worlds(their IDs) entered in the autoUnloadDimensions parameter will be unloaded "as soon as they are ready for it", if they were not created using Bukkit.

https://github.com/Luohuayu/CatServer/commit/d2395e455967c3624d23eb03545c4c4ffd2df0c8
