### ISSUE TITLE
Bug with Attribute Modifiers

### ISSUE THREAD

**Issue by OfficialTheosis** [Luohuayu/CatServer#242]
Hello.

I have created a plugin which adds a heart to the player upon the right-clicking of a certain item. It does this by creating an attribute modifier to the "generic max health" attribute and setting the "amount" value appropriately.

Essentially, this is what the plugin does under certain conditions.
`AttributeInstance maxHealth = player.getAttribute(Attribute.GENERIC_MAX_HEALTH);`
`maxHealth.addModifier(new AttributeModifier(ATTRIBUTE_MODIFIER_NAME, 2, Operation.ADD_NUMBER));`

It doesn't seem to actually do anything though.

I also know that there's nothing wrong with the plugin because I have tested it on a 1.12.2 Spigot server and it works fine.

Hope you can fix this one. :)

**Comment by OfficialTheosis** [comment]
PS: Not sure if this is the same with other attributes as I haven't tested it, but it is definitely the case with "generic max health".

**Comment by Luohuayu** [comment]
Fixed
