### ISSUE TITLE
无重生屏幕mod不支持猫端

### ISSUE THREAD

**Issue by Dr-WeiAL** [Luohuayu/CatServer#244]
刚刚试了一下forge端，是可以用的，但是猫端上无法启动
https://www.mcmod.cn/class/1243.html
https://minecraft.curseforge.com/projects/nsr-no-respawn-screen
https://github.com/jredfox/norespawnscreen
[2020-08-11-7.log.gz](https://github.com/Luohuayu/CatServer/files/5057911/2020-08-11-7.log.gz)

**Comment by Luohuayu** [comment]
前置MOD使用ASM修改服务端, 与Bukkit冲突无法兼容
可使用同样功能插件代替
