### ISSUE TITLE
玩家掉入虚空后崩服

### ISSUE THREAD

**Issue by Coloryr** [Luohuayu/CatServer#248]
https://paste.ubuntu.com/p/BHb8BZFkWx/
用的是版本CatServer-c2fd278-universal
在abyssalcraft世界导致的

**Comment by Luohuayu** [comment]
已修复

**Comment by Coloryr** [comment]
没修完，还有一处
https://paste.ubuntu.com/p/TphksYyCrr/

**Comment by ghost** [comment]
再发一个吧
