### ISSUE TITLE
Please display the console information in different colors.

### ISSUE THREAD

**Issue by Denaris01** [Luohuayu/CatServer#250]
Hello,

can you display the different server information info, warning and error in different colors? Then I could very easily see errors when starting the server and look for them. The other two hybrid servers magma and mohist have this feature. The information "Server thread/" could also be left out. Then there is more space in one line for the Windows Console.
Many thanks.

Another Server:
![Screen-2020-08-17_22-26-14](https://user-images.githubusercontent.com/22527229/90442090-5a422c80-e0da-11ea-987d-611ff929b253.png)

CatServer:
![Screen-2020-08-17_22-44-04](https://user-images.githubusercontent.com/22527229/90442712-5cf15180-e0db-11ea-89bb-b4dcf8dffbd6.png)

**Comment by Luohuayu** [comment]
Thread is important information. Different colors will look messy.
If you need, you can modify log4j yourself.
