### ISSUE TITLE
AdvancedRocketry causes crash once world has finished loading

### ISSUE THREAD

**Issue by sappykun** [Luohuayu/CatServer#251]
Catserver version: CatServer-20c1883-universal.jar
OS: Ubuntu 18.04
Java version:
```
openjdk version "1.8.0_265"
OpenJDK Runtime Environment (build 1.8.0_265-8u265-b01-0ubuntu2~18.04-b01)
OpenJDK 64-Bit Server VM (build 25.265-b01, mixed mode)
```

Mods:
- AdvancedRocketry-1.12.2-1.7.0-221-universal.jar
- LibVulpes-1.12.2-0.4.2-75-universal.jar

Github pages for mods:
- https://github.com/zmaster587/AdvancedRocketry
- https://github.com/zmaster587/LibVulpes

Crash report:
- https://pastebin.com/H9JTm2rD

Server console output:
- https://pastebin.com/BfichTFL

I am running an older version of Advanced Rocketry because I am trying to start an Enigmatica2Expert 1.81a server, which comes with that version of Advanced Rocketry.
The current version of Advanced Rocketry is 1.7.0-232, but the same crash also occurs on this version.

**Comment by Luohuayu** [comment]
Please report to AdvancedRocketry

**Comment by sappykun** [comment]
https://github.com/zmaster587/AdvancedRocketry/issues/1899#issuecomment-678003362

Advanced Rocketry devs suggest Catserver is modifying how ore generation is being handled and that the issue is with Catserver, not Advanced Rocketry.

**Comment by Luohuayu** [comment]
> 
> 
> [zmaster587/AdvancedRocketry#1899 (comment)](https://github.com/zmaster587/AdvancedRocketry/issues/1899#issuecomment-678003362)
> 
> Advanced Rocketry devs suggest Catserver is modifying how ore generation is being handled and that the issue is with Catserver, not Advanced Rocketry.

The same problem happened before in Forge. Could it be a dimension ID conflict?
