### ISSUE TITLE
神奇宝贝服卡顿

### ISSUE THREAD

**Issue by JiarenA** [Luohuayu/CatServer#252]
https://spark.lucko.me/#GwG1SzsioS
在线人数在40左右
麻烦了

**Comment by Luohuayu** [comment]
1.有玩家在跑图, 建议预生成区块和限制worldGenMaxTick到更低
2.实体移动计算占用过大, 建议将max-tick-time.entity设置更小

CatServer优化教程: https://www.mcbbs.net/thread-1085422-1-1.html

**Comment by JiarenA** [comment]
在线60人
tps在10以下
上面说的相关参数已调整
新的spark
https://spark.lucko.me/#em2u9B9A1h

**Comment by Luohuayu** [comment]
最大的占用依然是玩家跑图

**Comment by JiarenA** [comment]
那该怎么办....

**Comment by Luohuayu** [comment]
> 
> 
> 那该怎么办....

用worldborder限制边界和预生成填充
