### ISSUE TITLE
Encoding

### ISSUE THREAD

**Issue by dayd21git** [Luohuayu/CatServer#255]
Hi. Please tell us how to fix it. The Cyrillic alphabet is not displayed correctly. I think it's the UTF-8!

start.bat:
@ECHO OFF
java -Dfile.encoding=utf-8 -Xincgc -Xmx24G -jar server.jar
PAUSE

OC: Win7 x64
Screen: https://dropmefiles.com/M9ib9

**Comment by Luohuayu** [comment]
Not need `-Dfile.encoding=utf-8`, remove it

**Comment by dayd21git** [comment]
Not help. Maybe this is the case in Windows?
I noticed that the result is different from the previous one.

start.bat:
@echo OFF
java -Xincgc -Xmx24G -jar server.jar
PAUSE

OC: Win7 x64
Screen: https://dropmefiles.com/yYkXG
