### ISSUE TITLE
Bungeecord IP Forwarding

### ISSUE THREAD

**Issue by Frinn38** [Luohuayu/CatServer#26]
Bungeecord have an option called "ip-forwarding" which pass the player ip and UUID to the server when connecting from the proxy. (even if the server is in offline mode which is usually the case when using bungeecord)

By default spigot support this feature when the "bungeecord" config is set to true in spigot.yml file.
But also by default forge does not support ip-forwarding, from what I know this cause an error during the handshake protocol which make the client time out.

The only way I know to make thid works with forge is to add spongeforge to the server and enable ip-forwarding in the bungeecord module.

I made some tests with bungeecord and CatServer but I was unable to use ip-forwarding (time out everytime) even when enabling it in spigot, probably because of forge.

Since CatServer is a combination of minecraft, forge and spigot I hope you can find a way to solve this issue which last for 5 years (since forge updated to 1.8 if I remember well).

Thanks for all your work past and future on this project.

**Comment by Luohuayu** [comment]
https://github.com/Luohuayu/CatServer/blob/1.12.2/patches/net/minecraft/network/handshake/client/C00Handshake.java.patch#L36
This code implements compatibility with bungeecord (IP Forwarding must be enabled)

**Comment by Frinn38** [comment]
Ok found the problem, bungeecord IP forwarding work as well on a catserver but ONLY when connecting with a forge client, vanilla clients get time out even if there is no mods on the catserver.
Is it intended ?

**Comment by Luohuayu** [comment]
After BungeeCord forwards, server cannot get the client is Forge or Vanilla

**Comment by Frinn38** [comment]
Well it does work using a spongeforge server (vanilla clients can connect the server with ip forward enabled)
[Here](https://github.com/SpongePowered/SpongeForge/blob/stable-7/src/main/java/org/spongepowered/mod/mixin/core/network/handshake/client/C00HandshakeMixin_Forge.java) is their bungeecord implementation code that is a bit different than your.

**Comment by Luohuayu** [comment]
Which build of BungeeCord are you using?

**Comment by Frinn38** [comment]
I use the latest [Waterfall](https://papermc.io/ci/job/Waterfall/) build as bungeecord proxy

**Comment by Luohuayu** [comment]
CatServer need to support old version of bungeecord (Many China people are using), it can't implementation allow vanilla client connect to server like spongeforge

**Comment by Luohuayu** [comment]
I tried to use the code of spongeforge, which would make it impossible to use old version of bungeecord

**Comment by Frinn38** [comment]
For curiosity what is the old bungeecord version you use ?

Well the fact that vanilla client can't connect to catserver with ip-forwarding is not really important because usually some mods will be required on both side ^^ So I will close this issue.

Thanks for your time, I will go back to you if I have another issue with catserver, that's great to have a developer who answer that fast to issues ;)

**Comment by Luohuayu** [comment]
HexaCord and BungeeCord, it not send client is forge, so CatServer needs to treat all clients as forge
