### ISSUE TITLE
【BUG】猫端（版本a118ddc）与家具模组（MrCrayfish's Furniture Mod）的交互BUG

### ISSUE THREAD

**Issue by Lznkicalt** [Luohuayu/CatServer#260]
猫端版本为a118ddc（2020年9月最新）时，玩家在服务器内，与家具模组的电器进行交互时，会掉线，如图所示。
将猫端版本更换为更古早的ac735a0，问题解决。

Mod链接：https://www.curseforge.com/minecraft/mc-mods/mrcrayfish-furniture-mod

![图片](https://user-images.githubusercontent.com/28718617/92980313-3a7b0a00-f4c8-11ea-80d5-afdd4d0a7ab0.png)

**Comment by Lznkicalt** [comment]
猫端版本为a118ddc（2020年9月最新）时，玩家在服务器内，与家具模组的电器进行交互时，会掉线，如图所示。
将猫端版本更换为更古早的ac735a0，问题解决。

**Comment by Accir** [comment]
Having the same issue

**Comment by Accir** [comment]
Stack trace when closing TV GUI from that mod
https://pastebin.com/avsnhfeA

**Comment by Luohuayu** [comment]
新版已增加Paper的异步拦截功能, 防止MOD在网络线程操作造成崩服
请反馈MOD作者

**Comment by Luohuayu** [comment]
https://github.com/MrCrayfish/MrCrayfishFurnitureMod/issues/578
https://github.com/MrCrayfish/MrCrayfishFurnitureMod/issues/208
https://github.com/MrCrayfish/MrCrayfishFurnitureMod/issues/394
