### ISSUE TITLE
Can you add paper patches?

### ISSUE THREAD

**Issue by Zilacon** [Luohuayu/CatServer#264]
Adding paper would add a lot more performance to the server.
Also adding the 1.15.2 world generation fix would greatly speed up world generation, so worlds dont take days to generate.

Would it be possible to add these to CatServer?
Im coming from using Mohist because they've refused to fix their issues with mods and plugins for months. CatServer doesn't seem to have any of the issues ive faced on Mohist as of late.

**Comment by TheNullablePrototype** [comment]
Most likely, the developer will need a lot of time to do this. You can create a pull request yourself and offer it. if your change does not cause errors after tests, it will be added to the main branch.

**Comment by Luohuayu** [comment]
Some Paper patches have been added. Patches that do not apply to Forge servers will not be added.
