### ISSUE TITLE
Weird glitch on death

### ISSUE THREAD

**Issue by Zaphara94** [Luohuayu/CatServer#266]
Every time a player dies on our server, they respawn as a half dead animated body. Pic attached. This only seems to happen on catserver, not in single player. 
![2020-09-30_20 23 54](https://user-images.githubusercontent.com/25303524/94753127-46394e00-035b-11eb-89bf-8242435aa8d4.png)

**Comment by Luohuayu** [comment]
Not compatible with FirstAid mod

**Comment by Zaphara94** [comment]
thank you for your quick response!
