### ISSUE TITLE
Problem with IllegalStack/ProtocolLib plugins?

### ISSUE THREAD

**Issue by IITFA** [Luohuayu/CatServer#267]
Just tried CatServer for the first time and saw this error in the console after player login:
https://pastebin.com/raw/njGr6DV4

This error seems to happen every so often, not just at login of player.

**Comment by Luohuayu** [comment]
Please change ProtocolLib version to 4.3.0

**Comment by IITFA** [comment]
Changing to version 4.3.0 causes a lot of modded blocks to be invisible until right-clicked and cannot be stepped on. Changing back to the latest protocollib fixes that invisible block issue. So this issue isn't really "fixed" with that solution.

**Comment by Luohuayu** [comment]
Most of plugins is not compatible with modded blocks
