### ISSUE TITLE
巫师艺术wizardry-0.11.1崩溃

### ISSUE THREAD

**Issue by Mypty** [Luohuayu/CatServer#269]
Catserver 版本
CatServer-eb3ed0a-universal

Mod 本体版本
[wizardry-0.11.1](https://minecraft.curseforge.com/projects/wizardry-mod)

问题描述
截至编写这条 issue 时，使用的 Catserver 和wizardry-0.11.1 MOD 都是最新版本。

没有安装除前置外其它多余的 MOD 
附上错误报告
[debug.log](https://github.com/Luohuayu/CatServer/files/5353896/debug.log)

**Comment by Luohuayu** [comment]
不兼容LibrarianLib
