### ISSUE TITLE
LittleTiles崩服，ClassCastException

### ISSUE THREAD

**Issue by ChloePrime** [Luohuayu/CatServer#271]
[crash-2020-10-26_19.05.43-server.txt](https://github.com/Luohuayu/CatServer/files/5438422/crash-2020-10-26_19.05.43-server.txt)

群里大佬说找CatServer提交Issue

Littletiles1.5.0Pre68
CatServer-eaf1885-universal

**Comment by Luohuayu** [comment]
已修复
