### ISSUE TITLE
Bug Report freeze player

### ISSUE THREAD

**Issue by MaxifeuxG** [Luohuayu/CatServer#272]
**To Reproduce**
Steps to reproduce the crash:
1. just wait and play

**Versions (please complete the following information)**
 - Forge: 14.23.5.2854
 - CastServer: CatServer-65a5f07-universal.jar

**Crash Log**
 https://gist.github.com/MaxifeuxG/bf141472fad9b810aaf10d309a423723

**Additional context**
I think the bug comes from my broadcast plugin https://www.spigotmc.org/resources/autobroadcaster.16824/

**Comment by Luohuayu** [comment]
AutoBroadcaster plugin illegally update block in the asynchronous thread, it will cause the server to crash. Please report the plugin author.
