### ISSUE TITLE
猫猫端和roughmobs会裂开

### ISSUE THREAD

**Issue by mcmso** [Luohuayu/CatServer#274]
https://paste.ubuntu.com/p/8MV5jGCMMk/

**Comment by Luohuayu** [comment]
已修复 https://github.com/Luohuayu/CatServer/commit/74dfe41e565179291456c11ad3c42e14dfb3eac6
请编译dev分支进行测试

**Comment by mcmso** [comment]
> 已修复 [74dfe41](https://github.com/Luohuayu/CatServer/commit/74dfe41e565179291456c11ad3c42e14dfb3eac6)
> 请编译dev分支进行测试

谢谢大佬，已解决
