### ISSUE TITLE
Inspirations的生长机制导致crash

### ISSUE THREAD

**Issue by mcmso** [Luohuayu/CatServer#275]
https://paste.ubuntu.com/p/wVY55Z92m8/

**Comment by mcmso** [comment]
Inspirations的问题这玩意改了原版生长机制
找到配置文件   inspirations.cfg
把true改成false
# Adds seeds for additional vanilla plants, including cactus, sugar cane, carrots, and potatoes. [default: true]
    B:moreSeeds=true
把这个种子关掉可以临时解决，但我还是希望能兼容一下，谢谢

**Comment by Luohuayu** [comment]
已修复
