### ISSUE TITLE
BugReport with CustomNPCs

### ISSUE THREAD

**Issue by MaxifeuxG** [Luohuayu/CatServer#276]
To Reproduce
Steps to reproduce the crash:

-open a custom npcs trade menu

Versions (please complete the following information)

Forge: 14.23.5.2854
CastServer: CatServer-999edd9b-universal.jar
Customnpcs:1.12.2 | 04-jul-2020

Crash Log

https://gist.github.com/MaxifeuxG/41d4a9add24a83ebb2666ebc7399a3b2

**Comment by Luohuayu** [comment]
Please report to CustomNPCs author

**Comment by Noppes** [comment]
@Luohuayu how do you expect me to fix this when it crashes in your mod

**Comment by Noppes** [comment]
Oh sorry didnt read it correct, its not a crash just a warning, `the java.lang.RuntimeException: null` part had me confused. 

@MaxifeuxG looks like catserver has a disableAsyncCatchWarn config option somewhere, set it to true

**Comment by TheNullablePrototype** [comment]
@Noppes Why you open inventory in an async thread?

**Comment by Noppes** [comment]
@TheNullablePrototype because I needed another packet to arrive at the player first so I put a slight delay on the openGui

**Comment by TheNullablePrototype** [comment]
@Noppes You can open the GUI in the main thread(MinecraftServer#addScheduledTask()) after the desired delay?
