### ISSUE TITLE
BetterQuesting 更好的任务模组可重复任务进度显示问题

### ISSUE THREAD

**Issue by GoblinCwl** [Luohuayu/CatServer#279]
服务端版本：CatServer-999edd9b-universal.jar
模组版本：BetterQuesting-3.5.329，StandardExpansion-3.4.173.jar
# 问题描述：
将任务properties属性repeatTime设置后，任务可以在完成时进入CD，CD结束后可以再次完成任务。在CatServer服务器中，等待CD结束后，显示的任务进度不会重置，实际上是再次完成任务进度仍然可以完成任务，但是显示错误。
# 服务端测试：
设置一个任务，需要击杀5只僵尸，奖励是1个基岩，并且设置了10秒钟的冷却时间，此时任务栏显示[击杀任务-击杀僵尸0/5]，然后去杀僵尸，杀完后提示任务完成，此时任务栏显示[击杀任务-击杀僵尸5/5]，当任务完成后，领取奖励基岩，任务进入10秒CD，CD结束后，任务栏显示的仍然是[击杀任务-击杀僵尸5/5]，并且奖励领取的按钮是亮的（若未完成任务进度，领取按钮是灰色且无法点击），但是点击也不可以领取奖励，不过，你再去杀5只僵尸，就可以领取了。
# 单人测试：
在单人游戏中，任务完成时显示5/5，领取奖励后进入CD，CD结束后显示为0/5，才是正常的。
# 其他服务端测试：
未做测试，如有需要可告知。
# 备注：
如果描述不清晰可告知，我会录个视频。
![1](https://user-images.githubusercontent.com/40445489/99189335-acf3b900-279b-11eb-9b96-bab0ecd14d47.png)

**Comment by Luohuayu** [comment]
MOD本身有问题, 不知道有没有修复
请先尝试在Forge官服上测试

**Comment by GoblinCwl** [comment]
官服也存在此问题。
