### ISSUE TITLE
Suggestion: Add OpenCubicChunks support.

### ISSUE THREAD

**Issue by NightScale5755** [Luohuayu/CatServer#28]
Heyo.

I know it's more than likely hard to do, but can support for OpenCubicChunks be added???
I know you guys got quark support added... So I'm sure ya'll could get OCC working
heck, I'd be willing to pay money for it, if it's really hard to do

**Comment by TheDarkDnKTv** [comment]
It is useless and complitly hard. As this mod changing fundamental structures of vanilla minecraft as same success will break any mods which somehow connected to chunk data. I will not understand for which purposes you needed unlimited world size on all 3 directions, if you can simply change max height in your world generator properties.

**Comment by Luohuayu** [comment]
It's unable to be compatible
