### ISSUE TITLE
FTB Revelation 3.3.0 broken FTBUtilities

### ISSUE THREAD

**Issue by YerLocalSenpai** [Luohuayu/CatServer#280]
So, I am using CatServer for the FTB Revelation 3.3.0 modpack and for some reason CatServer breaks the leaderboard stats and the chat format in the FTB Utilities mod. https://prnt.sc/vo9nzo

**Comment by YerLocalSenpai** [comment]
Since those two things are broken in FTBUtilities there may be more broken in it. Also thanks in advance, I appreciate your work with the creation of CatServer, it is an amazing resource!

**Comment by Luohuayu** [comment]
Leaderboard statistics have been fixed: https://github.com/Luohuayu/CatServer/commit/ca87460e85e93e7f4c95fdbd55b4c940ab8c24b8

**Comment by Luohuayu** [comment]
Since Bukkit modified the chat code, the mod is not compatible with the plugin.
This can be difficult to fix.

**Comment by Luohuayu** [comment]
Try to https://github.com/Luohuayu/CatServer/commit/11b35a6e9c973d85f6565b684c3171cbab2ebb67
And enable `waitForgeServerChatEvent` option.
Should have been fixed.
@YerLocalSenpai
