### ISSUE TITLE
MorePlanets dupe on CatServer

### ISSUE THREAD

**Issue by bigenergy** [Luohuayu/CatServer#291]
https://github.com/SteveKunG/MorePlanets/issues/101

the dupe is reproducible only on catserver

**Comment by Luohuayu** [comment]
I cannot reproduce this problem.

CatServer: 5e246d7
MorePlanets: 2.2.0-GC281
IC2: 2.8.170
Advanced Solar Panels: 4.3.0
Galacticraft: 4.0.2.281

**Comment by bigenergy** [comment]
i will check again

**Comment by bigenergy** [comment]
i checked this again and again with my mod list and it seems dupe works
Perhaps some mod breaks the mechanics of this block or hopper..

**Comment by Luohuayu** [comment]
> 
> 
> i checked this again and again with my mod list and it seems dupe works
> Perhaps some mod breaks the mechanics of this block or hopper..

Please try to exclude other mods and test
