### ISSUE TITLE
Crash using FastWorkbench

### ISSUE THREAD

**Issue by Frinn38** [Luohuayu/CatServer#30]
CatServer crash during server start when [FastWorkbench ](https://www.curseforge.com/minecraft/mc-mods/fastworkbench)mod is installed.

Here is the crash report : https://pastebin.com/aBMbTk88

**Comment by Luohuayu** [comment]
Build and use this branch:
https://github.com/Luohuayu/FastWorkbench

**Comment by Frinn38** [comment]
Thanks
