### ISSUE TITLE
Twilight forest and deep dark death crash

### ISSUE THREAD

**Issue by Accir** [Luohuayu/CatServer#300]
Hello I'm recieving a server crash whenever a player dies in either deep dark or twilight forest. This has been happening for a while and with different CatServer versions.

Current CatServer version: 21.01.01

Crash report: 
[crash-2021-01-27_01.32.23-server.txt](https://github.com/Luohuayu/CatServer/files/5884175/crash-2021-01-27_01.32.23-server.txt)

**Comment by Luohuayu** [comment]
Please report to the mod author
