### ISSUE TITLE
Server Crash - AE2 Autocrafting with Plethora

### ISSUE THREAD

**Issue by Owningle** [Luohuayu/CatServer#303]
Modpack used: Enigmatica 2 Expert 1.82

Mod Versions:
  - Plethora: 1.12.2-1.2.3
  - CC:Tweaked: 1.12.2-1.89.2

Description:
Trying to request to autocraft an item using a computer from CC:Tweaked and plethora's AE2 api, the server will hang, and then crash.

Computercraft lua code:
```
me = peripheral.wrap("back")
me.findItem("planks").craft(1)
```

![Screenshot 2021-02-06 172811](https://user-images.githubusercontent.com/34453764/107125271-b70bec00-68a0-11eb-93c4-095b6a434b52.png)

Logs:
  - Log: https://pastebin.com/EAXTX4CN
  - Debug: https://pastebin.com/6Tfr3qSf

I have tested this on a normal forge server, as well as a server running another Forge+Bukkit+Spigot solution, and both worked correctly, which is why i believe this to be an issue with CatServer, and not the mods.

**Comment by Luohuayu** [comment]
Fixed.
