### ISSUE TITLE
不兼容ImproveLib

### ISSUE THREAD

**Issue by Huaxidesu** [Luohuayu/CatServer#305]
模组地址https://www.mcbbs.net/thread-1061428-1-1.html
日志
[crash-2021-02-08_19.16.31-server.txt](https://github.com/Luohuayu/CatServer/files/5943417/crash-2021-02-08_19.16.31-server.txt)
[latest (1).log](https://github.com/Luohuayu/CatServer/files/5943418/latest.1.log)
[debug.zip](https://github.com/Luohuayu/CatServer/files/5943419/debug.zip)

**Comment by Luohuayu** [comment]
该MOD不支持服务端

**Comment by Huaxidesu** [comment]
> 该MOD不支持服务端
我联系了该模组作者，作者表示在即将的4.0版本就会兼容catserver，感谢解答
