### ISSUE TITLE
Spam console

### ISSUE THREAD

**Issue by Heriptik** [Luohuayu/CatServer#306]
Hi, i use latest CatServer version (1.12.2-6677882)

And i have this error spammed my console : [https://pastebin.ubuntu.com/p/zNs5JfCGDC/](https://pastebin.ubuntu.com/p/zNs5JfCGDC/)

Thanks for your help !

**Comment by Luohuayu** [comment]
Need full log (debug.log)

**Comment by Heriptik** [comment]
My latest debug log

**Comment by Luohuayu** [comment]
`[05:00:15] [Server thread/DEBUG] [FML]: Registry Block: Fixed minecraft:blocks id mismatch minecraft:structure_block: 255 (init) -> 329 (map).`
`[05:00:15] [Server thread/DEBUG] [FML]: Registry Block: Fixed minecraft:blocks id mismatch minecraft:bone_block: 216 (init) -> 334 (map).`

`[05:00:16] [Server thread/DEBUG] [FML]: Inject block failure PIXELMON_BAUXITE_ORE with ID 209.`
`[05:00:16] [Server thread/DEBUG] [FML]: Inject block failure PIXELMON_ARTICUNO_SHRINE with ID 213.`

It seems that block id data of your world has been corrupted. You may need to regenerate the world.

**Comment by Heriptik** [comment]
Ok, but i  can't regenerate my world, i have 6 month + progress on this. Do you have another solution?

**Comment by Luohuayu** [comment]
Try to restore level.dat file from backup

**Comment by Luohuayu** [comment]
https://github.com/Luohuayu/CatServer/issues/306

**Comment by Luohuayu** [comment]
https://github.com/Luohuayu/CatServer/issues/314
