### ISSUE TITLE
There is an error with the plugin not working properly on catserver.

### ISSUE THREAD

**Issue by HongMint88** [Luohuayu/CatServer#307]
Spigot has confirmed that it is operating normally.
The plugin that assumes an error occurs is ProtocolLib 4.4.0.(https://www.spigotmc.org/resources/protocollib.1997/history)
And the plugin that runs with ProtocolLib is Artmap 2.7.4.(https://gitlab.com/BlockStack/ArtMap/-/releases?after=eyJpZCI6IjE0NDMwNzYifQ)
None of the artmap plugins are working. Only a message about the command appears.
There was no error message in the bucket, no response, and no folder was created for that plugin.

![image](https://user-images.githubusercontent.com/78477698/107798336-4fbdd280-6d9f-11eb-8792-a89464c10844.png)

For your information, there is no problem with the plugin version. Just in case, I applied all other versions, but they didn't work properly.(The types of errors were slightly different, but all of them appear to have been errors in ProtocolLib)

**Comment by Luohuayu** [comment]
Use ProtocolLib 4.6.0+
