### ISSUE TITLE
Antivirus Threat report

### ISSUE THREAD

**Issue by MaKlgz** [Luohuayu/CatServer#308]
My antivirus Bitdefender show me a scan report.
It said CatServer has a java trojan issue.
![擷取](https://user-images.githubusercontent.com/8119942/107849689-feaded00-6e37-11eb-8a7b-84794e56a00f.PNG)

The report points to a class.
CatServer-6677882-universal.jar=>org/bukkit/craftbukkit/v1_12_R1/CraftSound.class

I also upload the last CatServer-6677882-universal.jar to virustotal site.
The result:
![擷取1](https://user-images.githubusercontent.com/8119942/107849818-a88d7980-6e38-11eb-8322-2c3dd6887b45.PNG)

I think there are some code behavior be detected similar to trojan in CraftSound.class by Bitdefender database.
Could the issue be fixed?

**Comment by Luohuayu** [comment]
https://github.com/Luohuayu/CatServer/blob/1.12.2/src/main/java/org/bukkit/craftbukkit/CraftSound.java
The class does not have any virus code. You can ignore it or modify and build yourself.
