### ISSUE TITLE
[1.12.2] Server don't start, last catserver

### ISSUE THREAD

**Issue by Heriptik** [Luohuayu/CatServer#314]
Hi,

I would like update catserver from **CatServer-6677882** to **CatServer-f2bc11f** but my server don't start, i have this crash repport : [https://pastebin.ubuntu.com/p/K2dP7Q4Bmn/](https://pastebin.ubuntu.com/p/K2dP7Q4Bmn/)

thanks

**Comment by ChrisJStone** [comment]
Are there any other errors in your log?

**Comment by Heriptik** [comment]
I have just this crash repport

**Comment by ChrisJStone** [comment]
Okay, It appears that the error is coming from phosphor. I haven't used foamfix so I don't know anything about it. I would try to either remove phosphor and foamfix and see if that will resolve the issue. Or try loading your world in a forge only server instance with the same mod set and then reload on your catserver. What I do know is that a lot of mods will use asm injection to directly modify the byte code. Based on the error in your crash report it appears this is what is going on. The injection is position dependent. As such after the craftbukkit and forge patches are applied the resulting bytecode's will not be at the same position as they would be with just forge. If it's a one time only change to the structure of level.dat then using a forge only server instance should resolve the issue. If not then either the mods or catserver would need to be patched.

**Comment by Luohuayu** [comment]
I can’t reproduce it with phosphor. Is your world generated in 1.12.2? Can you upload level.dat?

**Comment by Heriptik** [comment]
My level.dat and my map generated in 1.12.2

I use latest 1.12.2 Biomes O' Plenty and Latest Pixelmon reforged (8.1.2)

[level.zip](https://github.com/Luohuayu/CatServer/files/6143059/level.zip)

**Comment by Luohuayu** [comment]
Need a method to support remap of block id, without breaking plugins
