### ISSUE TITLE
Linux控制台一些按键无法正常工作 

### ISSUE THREAD

**Issue by anytinz** [Luohuayu/CatServer#316]
Linux系统为Debian 10。乱码的按键包括方向键和退格键，方向键会变成 ^[[A 、^[[B 、^[[C 、^[[D ，退格键会变成 ^H 。
上面的问题我已经通过安装 rlwrap 并运行 rlwrap java -jar <jar> 解决。
依旧不正常的是 Tab 自动补全，在安装 rlwrap 之前按 Tab 的反应是输入 “        ” 这样的长空格，安装之后无反应。
我在使用 Openssh 连接或者键盘直连到 Linux 进行操作的后问题依旧出现，所以基本可以排除是我设置问题；且这些问题只会在运行 Release 提供的 Jar 上才会出现，包括像原版服务器、Forge 服务器以及系统自带的 Shell 均无问题（但是我没有测试过Spigot）。

**Comment by Luohuayu** [comment]
没有找到可以复现这个问题的环境
Forge的jline已经升级到了3.5.1, 但Spigot和插件依赖2.13, 所以CatServer依然保持这个版本
猜测可能是jline2.13和系统编码为ANSI导致(因为测试环境都是UTF-8)
另外建议试试Spigot会不会有这个问题

**Comment by anytinz** [comment]
在Spigot 1.16.5、1.12.2下键盘均正常工作；我的系统环境均为UTF-8。

在开启最新版本CatServer且不带任何Plugins和Mods的情况下问题依旧出现。

如果需要的话我可以开一台完全一样的虚拟机以供调试。

![Snipaste_2021-04-01_21-42-15](https://user-images.githubusercontent.com/24619961/113304463-a32ab680-9334-11eb-9393-7a159d2b602d.png)
（Spigot 1.16.5）
![Snipaste_2021-04-01_21-48-24](https://user-images.githubusercontent.com/24619961/113304618-c9505680-9334-11eb-8933-fa9e4aab6c5a.png)
（Spigot 1.12.2）
![Snipaste_2021-04-01_21-45-33](https://user-images.githubusercontent.com/24619961/113304652-d10ffb00-9334-11eb-89e4-08196921b602.png)
（系统环境以及版本）

**Comment by Luohuayu** [comment]
尝试最新版本

**Comment by Luohuayu** [comment]
最新版本如果依然存在这个问题请重新反馈
