### ISSUE TITLE
神马问题？自动生成一个实体Louhuayu？

### ISSUE THREAD

**Issue by Guangsudalao** [Luohuayu/CatServer#318]
![image](https://user-images.githubusercontent.com/73008998/113404798-564deb00-93db-11eb-9219-dcbf86730b4d.png)

**Comment by jiajiaxd** [comment]
![image](https://user-images.githubusercontent.com/51043917/113504947-4dd9e980-956e-11eb-8da1-2943f32d0d7e.png)
