### ISSUE TITLE
FastAsyncWorldEdit报错且时有无法//undo完全

### ISSUE THREAD

**Issue by ghost** [Luohuayu/CatServer#319]
日志:
[latest (2).log](https://github.com/Luohuayu/CatServer/files/6254213/latest.2.log)
插件：
https://ci.athion.net/job/FastAsyncWorldEdit/
麻烦提供一个可用无报错的FAWE版本...

**Comment by Luohuayu** [comment]
FastAsyncWorldEdit不兼容MOD方块
