### ISSUE TITLE
[1.12.2] Cannot use plug-in skins.

### ISSUE THREAD

**Issue by Redviera** [Luohuayu/CatServer#323]
Cannot use plug-in skins. 

https://drive.google.com/file/d/195gbTcqMe2i30UQMorg_nox6lMBhoX7h/view?usp=sharing

**Comment by AlexanderMC8533** [comment]
> Cannot use plug-in skins.
> 
> https://drive.google.com/file/d/195gbTcqMe2i30UQMorg_nox6lMBhoX7h/view?usp=sharing

can you use tmp.link
we cant access to google in china
