### ISSUE TITLE
FTBQuests lags

### ISSUE THREAD

**Issue by bigenergy** [Luohuayu/CatServer#324]
FTBQuests causes tps server lags due to inventory check
https://spark.lucko.me/AfVk2u8VFd

![image](https://user-images.githubusercontent.com/17977139/115953577-043d4880-a4f5-11eb-8bf4-aa331e0c2322.png)

**Comment by BartolomeoDR** [comment]
☺ wow . i never saw this.

**Comment by Luohuayu** [comment]
Not catserver problem
