### ISSUE TITLE
新版本能不能打包下

### ISSUE THREAD

**Issue by 56025192** [Luohuayu/CatServer#331]
新版本能不能打包下

**Comment by Luohuayu** [comment]
可以git clone之后使用gradlew build自行构建

**Comment by 56025192** [comment]
> 可以git clone之后使用gradlew build自行构建

构建环境配置不来

**Comment by Luohuayu** [comment]
不需要额外配置构建环境

**Comment by 56025192** [comment]
那需要什么呢   我不管怎么搞都报错

**Comment by Luohuayu** [comment]
请提供完整日志

**Comment by 56025192** [comment]
实在是搞不来    一整天了

**Comment by 56025192** [comment]
IDEA或Eclipse都试过了

**Comment by Luohuayu** [comment]
请提供完整日志

**Comment by Luohuayu** [comment]
不修改代码不需要IDEA或Eclipse, 直接gradlew build就能构建

**Comment by 56025192** [comment]
直接部署gradle后用cmd构建吗？？？

**Comment by Luohuayu** [comment]
cmd切换到clone的目录 运行gradlew build命令

**Comment by 56025192** [comment]
好的我试试

**Comment by 56025192** [comment]
环境就一个gradle需要git吗

**Comment by Luohuayu** [comment]
需要git来克隆项目

**Comment by 56025192** [comment]
好的

**Comment by 56025192** [comment]
Task :makeJarCatserver FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':makeJarCatserver'.
> Could not execute build using Gradle installation 'C:\Users\17606\.gradle\wrapper\dists\gradle-4.9-all\491wbe0x5d54n9cojs2p0zv90\gradle-4.9'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 7m 48s
20 actionable tasks: 20 executed

**Comment by 56025192** [comment]
出现这个错误

**Comment by Luohuayu** [comment]
尝试清除gradle缓存, 挂梯子再构建

**Comment by Luohuayu** [comment]
已发布最新版本
