### ISSUE TITLE
 [LaunchWrapper]: Unable to launch java.lang.ClassNotFoundException: net.minecraft.server.MinecraftServer

### ISSUE THREAD

**Issue by Yecgaa1** [Luohuayu/CatServer#334]
您好，这个问题可能非常基础，甚至是我没有正确按照步骤所造成的，但我没有其他方法知道如何解决这个问题，非常抱歉
[2021-06-24-3.txt](https://github.com/Luohuayu/CatServer/files/6709397/2021-06-24-3.txt)

**Comment by Luohuayu** [comment]
Forged Carpet使用mixin修改服务端, 暂不兼容

**Comment by Yecgaa1** [comment]
当我禁用它后问题解决了，非常感谢您迅速的回答
