### ISSUE TITLE
工业等mod物品重新登入的NBT标签丢失问题

### ISSUE THREAD

**Issue by XenWayne** [Luohuayu/CatServer#335]
问题主要表现在工业mod的导线、风力计、patchoulimod的自定义手册、匠魂物品、拔刀剑等。
登出服务器再登入，有一定概率复现NBT标签错乱，具体表现为“导线与导线不能堆叠”，风力计和量子护甲的电量在再次登入时清空。NBT标签显示为"0个标签"等。
![image](https://user-images.githubusercontent.com/54123699/123438545-5e48b000-d603-11eb-9a25-56cb902fea93.png)

**Comment by Luohuayu** [comment]
无法在最新版服务端复现, 请排查和确定造成问题的具体MOD/插件

**Comment by XenWayne** [comment]
抱歉
我意识到这不是Catserver本身造成的问题。
经过排查后
发现这是多世界背包隔离插件MultiInv机制导致的问题。
感谢跟进

**Comment by Luohuayu** [comment]
MultiInv自己实现的物品序列化, 不能兼容自定义NBT, 无法从服务端解决
