### ISSUE TITLE
Server don't start

### ISSUE THREAD

**Issue by Heriptik** [Luohuayu/CatServer#337]
Hi, i use the CatServer build 6677882

Because, I can't update more recent, I have this crash report: [https://pastebin.ubuntu.com/p/tVWFjp4cbZ/](https://pastebin.ubuntu.com/p/tVWFjp4cbZ/)

The problem being that I have corrupted blocks but I can't make backup.
Would it be possible to put in catserv options  a boolean which bypass this protection ?

I cannot delete my level.dat because I have a lot of players on my server.
Hoping this could be added.

thanks

**Comment by Heriptik** [comment]
Hi news ?

**Comment by Luohuayu** [comment]
Duplicate of #314
