### ISSUE TITLE
unknow bug

### ISSUE THREAD

**Issue by Coloryr** [Luohuayu/CatServer#34]
用的是异步版本
https://paste.ubuntu.com/p/nRHR9HGrC3/

**Comment by RupticMC** [comment]
For a temporary fix, kill the chicken or remove the region.

**Comment by Coloryr** [comment]
If not use Async vision,it can work

**Comment by Luohuayu** [comment]
线程队列过长无法处理, 配置文件加大线程池数量或者更换性能更好的CPU

**Comment by Coloryr** [comment]
我试试
