### ISSUE TITLE
IC2物品名称丢失

### ISSUE THREAD

**Issue by luluxiaoyu** [Luohuayu/CatServer#344]
使用版本为当前最新版
问题如图
![image](https://user-images.githubusercontent.com/58876608/127248550-b65afc71-f2fd-4d29-b4b2-86cb502ce6ee.png)

**Comment by Luohuayu** [comment]
"最新版"指的是服务端还是MOD, 具体版本号是多少?
是否已在Forge服务端测试过相同版本的MOD?

**Comment by Luohuayu** [comment]
看图片应该是JEI, 猜测与服务端无关

**Comment by luluxiaoyu** [comment]
是的 是自动汉化mod问题 不好意思
