### ISSUE TITLE
The problem with the bed

### ISSUE THREAD

**Issue by Sergo467** [Luohuayu/CatServer#347]
The problem occurs when you log in to the server again and only if the essentialsx plugin is available.
It consists in the fact that when I lie down on the bed, the morning does not come and I continue to lie on the bed.
When deleting the essentialsx plugin, this error is corrected.
I also want to note that when the account is first logged on to the server, everything works well, but if you restart the client with this account and log on to the server, you will not be able to sleep.
The operator's mode and its absence do not affect this in any way.
Since this does not happen in vanilla, I think that cat server is to blame for this.

Versions:
CatServer-26208f0-universal.jar
EssentialsX-2.18.2.0.jar

**Comment by Luohuayu** [comment]
If a player has `essentials.sleepingignored` permission, Essentials will prevent sleep.

**Comment by TheDarkDnKTv** [comment]
I met same issue. Even adding perm as "- -essentials.sleepingignored" not solved.
At beging when world time was fine, it was working. But after using essentials's /day command, after while it began to not working.
