### ISSUE TITLE
Player Timed out

### ISSUE THREAD

**Issue by Pumpkin797** [Luohuayu/CatServer#349]
Some players suddenly disconnect and have ERROR!
It's the latest Catserver（26208f0）
This is part of the log
https://paste.ubuntu.com/p/gx4mFvvrKd/

**Comment by Pumpkin797** [comment]
@KomiMoe @Luohuayu

**Comment by komimoe** [comment]
edited

**Comment by coolxitech** [comment]
是不是不兼容bungeecord,直接连接超时
