### ISSUE TITLE
Virus Detected on Downloading

### ISSUE THREAD

**Issue by SynergiAios** [Luohuayu/CatServer#352]
Currently on Windows 10 - no Virus Detection Software installed. Just blank Windows 10 with it's internals like Windows Defender. Trying downloading the catserver.jar -> Virus Detected, blocked. 

Is it because of bad code signing or anything else? What is going on?

**Comment by SynergiAios** [comment]
![Screenshot 2021-08-23 122416](https://user-images.githubusercontent.com/10873296/130432286-21781b88-c66b-4fb2-8f80-4fdf7b3a6af6.png)

**Comment by Luohuayu** [comment]
It is a false report. You can review the code and build it yourself.

**Comment by Luohuayu** [comment]
Fixed https://github.com/Luohuayu/CatServer/commit/30a7d3ee499a21768a46dc3076b2e941b84665b8
lmao
