### ISSUE TITLE
[1.12.2] The villager's gui cannot be opened

### ISSUE THREAD

**Issue by Thexiaoyu** [Luohuayu/CatServer#354]
I submit a bug
This vulnerability is not friendly to command players
The gui interface of the villagers often cannot be opened
Re-enter the server to be normal
Sometimes it’s not normal
Hope to be fixed

**Comment by Luohuayu** [comment]
Are you Chinese? Speaking Chinese can describe the problem better.
能用中文详细的描述问题吗

**Comment by dreamaximum** [comment]
> Are you Chinese? Speaking Chinese can describe the problem better.
> 能用中文详细的描述问题吗
绷不住了
