### ISSUE TITLE
Not loading blocks

### ISSUE THREAD

**Issue by LufuEZ** [Luohuayu/CatServer#36]
Thats happen when i enter in server. To fix i need teleport between world's.

Screenshot: [https://ibb.co/yBVKFjN](url)
![Screenshot](https://user-images.githubusercontent.com/57304394/69993511-40f95000-154c-11ea-86e7-fed813839f25.png)

**Comment by Luohuayu** [comment]
Which world you teleport to

**Comment by ConnorTron110** [comment]
What version of catserver are you using?

**Comment by LufuEZ** [comment]
I'm sorry, I've been quite busy lately and I haven't been able to answer. I am using the latest version of catserver. I simply teleport to any world, world or anyone I created.

**Comment by Luohuayu** [comment]
Does your client or server have VanillaFix or FoamFix?

**Comment by Luohuayu** [comment]
I need to know which mods or plugins you have installed
