### ISSUE TITLE
world border for per world cannot be set.

### ISSUE THREAD

**Issue by speccycy** [Luohuayu/CatServer#367]
CatServer-d1fba12-universal

When I set worldborder or use the command /worldborder set 800 in the world I want that is not Main world.
It will set every world it has to all 800 Blocks. Borders cannot be set for each world. Even if I edited in that world's level.dat file.

Like borders are based on the Main world only and cannot be separated from each other.

Border main world
![image](https://user-images.githubusercontent.com/68125477/136701128-e6272c68-1184-4a35-822f-a858e96c156e.png)

Border other worlds
![image](https://user-images.githubusercontent.com/68125477/136701177-72178364-3235-4a1a-b9d7-ff50ccbf524e.png)

![image](https://user-images.githubusercontent.com/68125477/136701626-1ac88669-274b-4665-bea3-4463b2e7e208.png)

**Comment by komimoe** [comment]
I think this is a feature, not a bug. you can set it by plugins.

**Comment by Luohuayu** [comment]
Not a bug. It's the same in Spigot.
