### ISSUE TITLE
关于mm的伪装功能和核心的问题

### ISSUE THREAD

**Issue by Chizuru233** [Luohuayu/CatServer#369]
我的伪装插件LibsDisguises貌似在catserver内运行会出问题

如果是spigotmc上最新版本的话 它会直接失去伪装功能
如果是采用低版本的 它可以伪装 但是启动的时候伪装就刷了一大堆错误，就没执行到触发监听器，导致我其他的插件根本监听不到
[latest.log](https://github.com/Luohuayu/CatServer/files/7328149/latest.log)

**Comment by Chizuru233** [comment]
已经构建并使用了1.12dev分支内修复版(patcher目录下新增了LibsDisguisesPatcher）
依然有报错，log已上传
[latest.log](https://github.com/Luohuayu/CatServer/files/7418222/latest.log)

**Comment by LLjo** [comment]
hey will this be implemented and working in the next update? 

Atm I can only use libsdisguises 9.9.9 but that one does not work with mythic mobs 4.9.1 for some reason :/
