### ISSUE TITLE
无法使用FastWorkbench

### ISSUE THREAD

**Issue by Slix919509299** [Luohuayu/CatServer#37]
使用LagGoggles这个MOD之后无法启动服务器
且不生成crash文件 
https://paste.ubuntu.com/p/7vRrsK5W9h/
这是一个很好的查询服务器和客户端卡顿原因的MOD希望可以修理

**Comment by Luohuayu** [comment]
不兼容FastWorkbench
请使用这个版本: https://github.com/Luohuayu/FastWorkbench
