### ISSUE TITLE
在服务端的伪装的报错

### ISSUE THREAD

**Issue by Chizuru233** [Luohuayu/CatServer#370]
这里发现问题大概是服务端缺了一些包
log已上传
[latest.log](https://github.com/Luohuayu/CatServer/files/7351090/latest.log)

**Comment by Chizuru233** [comment]
补充：ProtocolLib 版本4.7  LibsDisguises 版本10.0.15  MythicMobs 版本4.7.2

**Comment by Chizuru233** [comment]
补充，更加完全的log日志
[latest.log](https://github.com/Luohuayu/CatServer/files/7374134/latest.log)

**Comment by Luohuayu** [comment]
重复 #369
