### ISSUE TITLE
NMS partially obfuscated

### ISSUE THREAD

**Issue by AlexProgrammerDE** [Luohuayu/CatServer#373]
Hi! [SkinsRestorer](https://www.spigotmc.org/resources/skinsrestorer.2124/) dev here. Our plugin recently stopped working on this server software. I quickly wrote a class dumper and this is the output:
```
[09:46:56] [Server thread/INFO]: class net.minecraft.network.play.server.SPacketPlayerListItem
[09:46:56] [Server thread/INFO]: Classname: SPacketPlayerListItem
Fields:
a | a
b | List
Methods:
toString | String
a | void
b | void
a | void
a | void
Child Classes:
b
Classname: b
Fields:
b | int
c | GameType
d | GameProfile
e | ITextComponent
a | SPacketPlayerListItem
Methods:
toString | String
b | int
d | ITextComponent
a | GameProfile
c | GameType
Child Classes:
a
Classname: a
Fields:
ADD_PLAYER | a
UPDATE_GAME_MODE | a
UPDATE_LATENCY | a
UPDATE_DISPLAY_NAME | a
REMOVE_PLAYER | a
f | a[]
Methods:
values | a[]
valueOf | a
Enum Constants:
aaaaa
```
The child class "a" is supposed to be called "Action". Because of that issue, our plugin can not create the required packets using reflection anymore. Seemingly, something is broken with the mappings that are being applied to nms.
Would be more than happy if you could look into this. Thanks!

**Comment by Luohuayu** [comment]
https://github.com/Luohuayu/CatServer/commit/dcb9e4184da820d8e0cb6a146f539dbec2f4b5cc
Related to this commit?

**Comment by AlexProgrammerDE** [comment]
That is quite unlikely. One of the first bug reports was on 13th of October. That's 17 days ago and the linked commit was 6 days ago. 
![Screenshot_20211030-113700_Discord-Canary.jpg](https://user-images.githubusercontent.com/40795980/139527923-ba709e27-d916-4a58-96f8-117288665320.jpg)
I assume 21.10.04 introduced the bug and downgrading to 21.09.16 fixed it.

**Comment by Luohuayu** [comment]
The latest build test SkinsRestorer works fine. The problem should have been fixed.

**Comment by AlexProgrammerDE** [comment]
Ok cool. Will test once I'm back home.

**Comment by AlexProgrammerDE** [comment]
Works great. Thanks! ^w^
