### ISSUE TITLE
同一tick只能攻击一个目标

### ISSUE THREAD

**Issue by guyue36** [Luohuayu/CatServer#378]
好像同一tick只能攻击一个目标，我记得很久以前是可以同一时间攻击多个目标

**Comment by Luohuayu** [comment]
1.12.2特性

**Comment by guyue36** [comment]
不是，原来低版本catsever核心的1.12.2都是可以一次性攻击多个目标的，后面随着更新catsever核心就不行了

**Comment by Luohuayu** [comment]
spigot和forge测试过吗

**Comment by guyue36** [comment]
刚刚才测试了spigot可以一次性攻击多个目标！！

**Comment by guyue36** [comment]
抱歉啊，catsever没有问题，我刚刚相同插件测试了一下，也是可以一次性攻击多个目标的，可能是我某个插件限制了攻击
