### ISSUE TITLE
Not sure if im doing something wrong?

### ISSUE THREAD

**Issue by madwolfpack** [Luohuayu/CatServer#38]
Worldedit and Essentials, are not finding the modded items info not sure if I am doing something wrong here?

plugin/server version
https://i.imgur.com/62NlLnS.png

**Comment by Voltstro** [comment]
I think because Essentials gets its list of items from its own list, from the `items.json` and `items.csv`, in the `plugins/Essentials` folder.
Worldedit I don't know anything about.

**Comment by madwolfpack** [comment]
Would sponge be able to run with this?

**Comment by Voltstro** [comment]
If you are saying will Sponge plugins work with CatServer? No it will not. CatServer can only run Bukkit/Spigot based plugins.

But you could try Sponge's [Sponge Forge](https://www.spongepowered.org/downloads/spongeforge/stable/1.12.2) thing with CatServer. IDK if it works though.
