### ISSUE TITLE
Can't start the server with the mod  Industrial Upgrade 2.0

### ISSUE THREAD

**Issue by Zolonos** [Luohuayu/CatServer#383]
I tried different options, and did not find a solution here is a crash repor
[crash-2021-12-14_04.22.32-server.txt](https://github.com/Luohuayu/CatServer/files/7707560/crash-2021-12-14_04.22.32-server.txt)

**Comment by TheNullablePrototype** [comment]
The mod is not compatible to run on a dedicated server, the author of the mod made a mistake and uses classes on the server side that are designed to work only on the client side.

**Comment by Luohuayu** [comment]
Industrial Upgrade is only client side
