### ISSUE TITLE
[1.12.2] Bug inventories (affichage)

### ISSUE THREAD

**Issue by Heriptik** [Luohuayu/CatServer#384]
Hi, i have 175 players in my server (Pixelmon). Tps are between 12 and 16 overage, some players have a bug with use items in main hands.

Video : [https://drive.google.com/file/d/1KEhY4ywQ91PyI1n0FOhJV5X2SL1joZCM/view?usp=sharing](https://drive.google.com/file/d/1KEhY4ywQ91PyI1n0FOhJV5X2SL1joZCM/view?usp=sharing)

**Comment by Luohuayu** [comment]
Need more information
