### ISSUE TITLE
Crash on loading mod "Fast Workbench"

### ISSUE THREAD

**Issue by yzl210** [Luohuayu/CatServer#39]
The mod "Fast Workbench" caused the StoneBlock 2 modpack server to crash. I was wondering why?

Server Version:
fa590fd

Crash Report:
[crash-2019-12-07_16.40.54-server.txt](https://github.com/Luohuayu/CatServer/files/3934887/crash-2019-12-07_16.40.54-server.txt)

**Comment by Luohuayu** [comment]
https://github.com/Luohuayu/CatServer/issues/30
