### ISSUE TITLE
一个会导致玩家无法进服的致命Bug

### ISSUE THREAD

**Issue by li-yuan-fang** [Luohuayu/CatServer#393]
当一个区块内的方块NBT数据量过大时会出现这个Bug，如果只是玩家背包里的物品，则只是该玩家进不了服务器，如果是已经放置的方块，则加载该区块的玩家都进不了服务器。
该Bug最简单的复现方法就是箱子带NBT复制套娃

目前的唯一解决方法是NBTExplorer打开区块文件删除物品
这个应该是网络通讯的问题（根据 https://wiki.vg/Protocol 里介绍的数据包最大尺寸和报错信息推断，原因应该是NBT数据包尺寸太大了，也许可以试试分包或压缩发送？）

客户端报错信息为：
Internal Exception: io.netty.handler.codec.DecoderException: java.lang.RuntimeException: Tried to read NBT tag that was too big;tried to allocate: 2097191bytes where max allowed: 2097152

**Comment by MoeShimaKaze** [comment]
https://www.mcmod.cn/class/1875.html
尝试使用这个mod看看

**Comment by li-yuan-fang** [comment]
> https://www.mcmod.cn/class/1875.html 尝试使用这个mod看看

谢谢，问题已解决。不过当数据包超出长度限制之后虽然不会掉线，但是会运算量会急剧上升，卡的要命。

**Comment by Dreeam-qwq** [comment]
被nbt ban了，mc的bug
