### ISSUE TITLE
1.12.2 shutupmodelloader mod crash

### ISSUE THREAD

**Issue by rebarakuk** [Luohuayu/CatServer#398]
When I install this mod, this crash happens
(versoin: CatServer-a8b73e9-universal)

the state engine was in incorrect state INITIALIZATION and forced into state SERVER_STOPPED. Errors may have been discarded.

**Comment by ghost** [comment]
发崩溃日志

**Comment by shinefield** [comment]
老外可能不懂中文哈哈

**Comment by rebarakuk** [comment]
> 发崩溃日志

I translated your sentence XD
https://gist.github.com/rebarakuk/e227bee271779acc20a0ac766b2590f0

**Comment by Luohuayu** [comment]
The mod is client side only

> > 发崩溃日志
> 
> I translated your sentence XD https://gist.github.com/rebarakuk/e227bee271779acc20a0ac766b2590f0

The mod is client side only
