### ISSUE TITLE
后台报了奇怪的日志

### ISSUE THREAD

**Issue by superBIAO** [Luohuayu/CatServer#399]
![image](https://user-images.githubusercontent.com/30098014/160570033-2c83adf7-04ed-4c83-a6ce-74b4e408cf41.png)
如图，最后一栏推送了广告，请问是否是服务端的？

**Comment by Remik1r3n** [comment]
![image](https://user-images.githubusercontent.com/62464927/162360922-63d38c75-63d3-4d5b-8b43-12b7f9d26857.png)
同，塞广告我有点不太理解

**Comment by Big-Cake-jpg** [comment]
毕竟作者也要恰饭嘛，人家也是用爱发电的，开源项目也需要有人支持的

**Comment by superBIAO** [comment]
> 毕竟作者也要恰饭嘛，人家也是用爱发电的，开源项目也需要有人支持的

没，恰饭这个我能理解，只是之前一直没有出现，这次就突然出现了，我还以为是哪个mod的原因😂

**Comment by Luohuayu** [comment]
提供一下完整的日志, 截图不完整分析不了是什么问题
另外, 广告确实是服务端的, 不想看到的话可以关闭更新检查或提供ip让这边屏蔽掉

**Comment by superBIAO** [comment]
没关系，能确认广告不是第三方添加的就没问题，广告行为可以接受

**Comment by Luohuayu** [comment]
> 没关系，能确认广告不是第三方添加的就没问题，广告行为可以接受

报错解决了吗 没解决的话提供一下日志看看是不是服务端问题
