### ISSUE TITLE
BQ任务书模组无法使用控制台指令功能

### ISSUE THREAD

**Issue by GoblinCwl** [Luohuayu/CatServer#40]
如题，在我使用CatServer时遇到一个问题，
由于报错日志的比较奇怪，
我不太确定是否是服务端的问题，如果可以，请帮我看下！
模组地址：[https://www.curseforge.com/minecraft/mc-mods/better-questing](url)
报错日志：
[任务书报错日志.log](https://github.com/Luohuayu/CatServer/files/3936489/default.log)

**Comment by Luohuayu** [comment]
Watchdog日志看不出是啥问题,确定每次崩溃日志都是这样?

**Comment by Coloryr** [comment]
每次执行命令都会卡线程，从1月份过来的catserver都这样。

**Comment by GoblinCwl** [comment]
> Watchdog日志看不出是啥问题,确定每次崩溃日志都是这样?

是的，只要一使用那个控制台指令的功能，崩溃就是这样

**Comment by Coloryr** [comment]
每次都这样，我测试1年了

**Comment by Coloryr** [comment]
我都测试1年了

**Comment by Luohuayu** [comment]
已修复
https://github.com/Luohuayu/CatServer/commit/2531e0cc6cbcf5c011e2f073e199b06aba1a26b0

**Comment by GoblinCwl** [comment]
19.12.10 正常启动 进入服务器报错。
[last.log](https://github.com/Luohuayu/CatServer/files/3943292/last.log)

**Comment by Luohuayu** [comment]
已修复
