### ISSUE TITLE
[1.12.2] Remove auto-click for all bukkit / spigot GUI

### ISSUE THREAD

**Issue by Heriptik** [Luohuayu/CatServer#402]
Hi, i have a dup bug in my server (CMI **/invsee** command plugin), it's possible on catserver to block auto-click as it has no protection for that.

Video : [https://drive.google.com/file/d/1Oh9TlHpUPd-mrEiOgbe2OiturV4LiwEn/view?usp=sharing](https://drive.google.com/file/d/1Oh9TlHpUPd-mrEiOgbe2OiturV4LiwEn/view?usp=sharing)

thanks

**Comment by Luohuayu** [comment]
EssentialsX's /invsee and OpenInv's /openinv are working fine.
Since I don't have CMI, I can't analyze and fix it temporarily.

**Comment by Heriptik** [comment]
Hum ok , i have open an issue in CMI plugin github, see the answer : [https://github.com/Zrips/CMI/issues/6835#issuecomment-1105387923](https://github.com/Zrips/CMI/issues/6835#issuecomment-1105387923)

**Comment by Luohuayu** [comment]
Use the latest version and enable `limitFastClickGUI` option
