### ISSUE TITLE
[1.12.2] Can't run properly with java 16

### ISSUE THREAD

**Issue by OpenFlameDmitry** [Luohuayu/CatServer#407]
Mods:
DamageIndicatorsMod-3.5.1
AutoRegLib-1.3-32
Baubles-1.12-1.5.2
BetterPingDisplay_1.12.2_1.0
conarm-1.12.2.1.2.5.1.0
CreativeCore_v1.10.70
DoomlikeDungeons-1.14.11-MC1.12.2
gravestone
JEI
Mantle
Nocubes_srp_addon
OnlinePicFrame
Quark
Ruins
SRParasites
Tconstruct
Thaumcraft
ThaumicAugmentation
ThaumicJEI
TinkersComplement
TwilightForest
Unique+Enchantments+Base
Unique+Enchantments
Xaeros_Minimap
XaerosWorldMap
Plugins: 
EntityControl
EssentialsX-2.19.4
PluginManager
UltimateAlchemy
UltimateAnvil
UltimateCollections
UltimateCoreMenu
UltimateCrafting
UltimateDragon
UltimateEnchantment
UltimateHelper
UltimatePets
UltimateReforge
UltimateRunes
UltimateSkills
Some of the mods and plugins need to be runned with Java 16, but the server is trying to run as java 8 and crashing after this.
logs[https://dropfiles.org/2wvLEvnF](url)

**Comment by Luohuayu** [comment]
Unable to download, please use ubuntu pastebin
