### ISSUE TITLE
[1.16.5] 使用属性插件时，护甲耐久度出现问题

### ISSUE THREAD

**Issue by blankpager** [Luohuayu/CatServer#409]
**运行环境** zulu 11

Minecraft版本(1.16.5)

构建版本: CatServer-1.16.5-c23f23b-server
[Server thread/INFO]: This server is running CatServer version 1.16.5-c23f23b (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT, Forge version 36.2.34)

相关模组/插件: 
测试了3款都存在问题
AttributePlus-3.2.8
WebersRPGItemLoader_v1.5.7_Beta
OriginAttribute-1.5.4.3
（这些插件泥潭都有）

**描述这个BUG**
后台并无报错

**导致的问题**
当安装如上任一属性插件。当受到怪物攻击时，身上的护甲损失的耐久比正常来说更高。

**复现方法**
一、
当安装有如下三个插件时，护甲耐久的单次损失从正常的1，变成3
OriginAttribute-1.5.4.3
PlaceholderAPI-2.9.2
ProtocolLib
二、
当安装有如下两个插件时，护甲耐久的单次损失从正常的1，变成3
AttributePlus-3.2.8
PlaceholderAPI-2.9.2
三、
当安装有如下两个插件时，护甲耐久的单次损失从正常的1，变成5
WebersRPGItemLoader_v1.5.7_Beta
item-nbt-api-plugin-2.9.1

该问题在arclight/spigot/mohist这些核心上并未出现问题。
该问题在loliserver时代反馈过但没有得到解答就合并了

**Comment by Kotori0629** [comment]
是否可以通过 玩家实体 攻击 玩家实体触发？

**Comment by blankpager** [comment]
> 是否可以通过 玩家实体 攻击 玩家实体触发？

尝试了一下，玩家对玩家攻击也同样触发了。耐久损失和受到怪物攻击一样变得不正常，三个插件还是分别从1/1/1变成3/3/5

**Comment by Kotori0629** [comment]
> > 是否可以通过 玩家实体 攻击 玩家实体触发？
> 
> 尝试了一下，玩家对玩家攻击也同样触发了。耐久损失和受到怪物攻击一样变得不正常，三个插件还是分别从1/1/1变成3/3/5

晚一点修

**Comment by Kotori0629** [comment]
> > 是否可以通过 玩家实体 攻击 玩家实体触发？
> 
> 尝试了一下，玩家对玩家攻击也同样触发了。耐久损失和受到怪物攻击一样变得不正常，三个插件还是分别从1/1/1变成3/3/5

麻烦将这些插件的 前置+本体 打包发给我 q 79943751
