### ISSUE TITLE
Players are geting an error joining

### ISSUE THREAD

**Issue by madwolfpack** [Luohuayu/CatServer#41]
Server Console:

`10.12 20:18:44 [Server] User Authenticator #4/INFO UUID of player Starfruit_Yum is 4c9e9eeb-3e7c-4d3e-a6a4-3fd65a8e2abf
10.12 20:18:44 [Server] Server thread/ERROR HandshakeMessageHandler exception
10.12 20:18:44 [Server] INFO java.lang.NoClassDefFoundError: Could not initialize class net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1
10.12 20:18:44 [Server] INFO at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.serverInitiateHandshake(NetworkDispatcher.java:198) ~[NetworkDispatcher.class:git-CatServer-1.12.2-04ce3a8]
10.12 20:18:44 [Server] INFO at net.minecraftforge.fml.common.network.handshake.FMLHandshakeServerState$1.accept(FMLHandshakeServerState.java:50) ~[FMLHandshakeServerState$1.class:git-CatServer-1.12.2-04ce3a8]
10.12 20:18:44 [Server] INFO at net.minecraftforge.fml.common.network.handshake.HandshakeMessageHandler.userEventTriggered(HandshakeMessageHandler.java:65) ~[HandshakeMessageHandler.class:git-CatServer-1.12.2-04ce3a8]
10.12 20:18:44 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:329) [AbstractChannelHandlerContext.class:4.1.9.Final]
10.12 20:18:44 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:315) [AbstractChannelHandlerContext.class:4.1.9.Final]
10.12 20:18:44 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireUserEventTriggered(AbstractChannelHandlerContext.java:307) [AbstractChannelHandlerContext.class:4.1.9.Final]
10.12 20:18:44 [Server] INFO at io.netty.channel.ChannelInboundHandlerAdapter.userEventTriggered(ChannelInboundHandlerAdapter.java:108) [ChannelInboundHandlerAdapter.class:4.1.9.Final]
10.12 20:18:44 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:329) [AbstractChannelHandlerContext.class:4.1.9.Final]
10.12 20:18:44 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:315) [AbstractChannelHandlerContext.class:4.1.9.Final]
10.12 20:18:44 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireUserEventTriggered(AbstractChannelHandlerContext.java:307) [AbstractChannelHandlerContext.class:4.1.9.Final]
10.12 20:18:44 [Server] INFO at io.netty.channel.ChannelInboundHandlerAdapter.userEventTriggered(ChannelInboundHandlerAdapter.java:108) [ChannelInboundHandlerAdapter.class:4.1.9.Final]
10.12 20:18:44 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:329) [AbstractChannelHandlerContext.class:4.1.9.Final]
10.12 20:18:44 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:315) [AbstractChannelHandlerContext.class:4.1.9.Final]
10.12 20:18:44 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.fireUserEventTriggered(AbstractChannelHandlerContext.java:307) [AbstractChannelHandlerContext.class:4.1.9.Final]
10.12 20:18:44 [Server] INFO at io.netty.channel.DefaultChannelPipeline$HeadContext.userEventTriggered(DefaultChannelPipeline.java:1352) [DefaultChannelPipeline$HeadContext.class:4.1.9.Final]
10.12 20:18:44 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:329) [AbstractChannelHandlerContext.class:4.1.9.Final]
10.12 20:18:44 [Server] INFO at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:315) [AbstractChannelHandlerContext.class:4.1.9.Final]
10.12 20:18:44 [Server] INFO at io.netty.channel.DefaultChannelPipeline.fireUserEventTriggered(DefaultChannelPipeline.java:920) [DefaultChannelPipeline.class:4.1.9.Final]
10.12 20:18:44 [Server] INFO at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.insertIntoChannel(NetworkDispatcher.java:183) [NetworkDispatcher.class:git-CatServer-1.12.2-04ce3a8]
10.12 20:18:44 [Server] INFO at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.serverToClientHandshake(NetworkDispatcher.java:154) [NetworkDispatcher.class:git-CatServer-1.12.2-04ce3a8]
10.12 20:18:44 [Server] INFO at net.minecraftforge.fml.common.network.internal.FMLNetworkHandler.fmlServerHandshake(FMLNetworkHandler.java:81) [FMLNetworkHandler.class:git-CatServer-1.12.2-04ce3a8]
10.12 20:18:44 [Server] INFO at net.minecraft.server.network.NetHandlerLoginServer.func_147326_c(NetHandlerLoginServer.java:185) [pc.class:?]
10.12 20:18:44 [Server] INFO at net.minecraft.server.network.NetHandlerLoginServer.func_73660_a(NetHandlerLoginServer.java:70) [pc.class:?]
10.12 20:18:44 [Server] INFO at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:235) [gw.class:?]
10.12 20:18:44 [Server] INFO at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:187) [oz.class:?]
10.12 20:18:44 [Server] INFO at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:935) [MinecraftServer.class:?]
10.12 20:18:44 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:472) [nz.class:?]
10.12 20:18:44 [Server] INFO at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:778) [MinecraftServer.class:?]
10.12 20:18:44 [Server] INFO at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:632) [MinecraftServer.class:?]
10.12 20:18:44 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]`

Players Screen:
https://cdn.discordapp.com/attachments/647549287596556288/654085082172227586/broken.PNG

**Comment by Luohuayu** [comment]
Please update to latest releases (6cdf40f)
