### ISSUE TITLE
[1.18.2] World errors when restarting the server

### ISSUE THREAD

**Issue by XionioXMaster** [Luohuayu/CatServer#411]
**Environment**

Minecraft version(1.12.2/1.16.5/1.18.2):  1.18.2
Build version(Get from /version command): CatServer-1.18.2-2812015-server
Mods/Plugins: Nope

**Describe the bug**
[(If there is an error, please attach the pastebin link)](https://gist.github.com/XionioXMaster/cd0962162926d4b8658de1f41c9d7fcc)

**To Reproduce**
Perhaps you already know about this problem, but anyway I will leave it here, after the first generation of the world I rebooted the server (did not enter the server) after which I found a lot of warnings

**Comment by Kotori0629** [comment]
Oh my dear user, don't rush to test 1.18.2 for now, we're still working on it, so stay tuned for me to send a test invite to your Discord

**Comment by Kotori0629** [comment]
Thank you very much for your high attention to CatServer1.18.2
