### ISSUE TITLE
[1.16.5] Crash on launch using Pterodactyl

### ISSUE THREAD

**Issue by SirOMGitsYOU** [Luohuayu/CatServer#412]
**Environment**
This bug only occurs when running CatServer on pterodactyl in a docker container

Minecraft version(1.12.2/1.16.5/1.18.2): 
Build version(Get from /version command): CatServer-35187d3-universal
Mods/Plugins: n/a

**Describe the bug**

https://paste.loliidc.cn/?67aed7a704d96c75#VVBkbrVYBpK9MyTiKLTnguDKpNBViQuNRWmZkvBhSqP

**Comment by Kotori0629** [comment]
The log you uploaded is CatServer1.12.2
`[11:39:57] [main/INFO]: Forge Mod Loader version 14.23.5.2860 for Minecraft 1.12.2 loading`

**Comment by SirOMGitsYOU** [comment]
> The log you uploaded is CatServer1.12.2 `[11:39:57] [main/INFO]: Forge Mod Loader version 14.23.5.2860 for Minecraft 1.12.2 loading`

Oh right okay - I tried to download the 1.16 through the releases section, as I was unable to build it myself directly.

**Comment by Kotori0629** [comment]
> 

View 1.16.5 branch's README
