### ISSUE TITLE
申请镜像授权

### ISSUE THREAD

**Issue by Mhy278** [Luohuayu/CatServer#413]
CatServer开发团队：

您好！我是[FastMirror.net](https://www.fastmirror.net)服务端核心镜像站的负责人，我站主要向社区用户提供免费且高速的MC服务端核心镜像。CatServer作为目前圈内开发程度最深、维护最稳定的模组服务端，深受广大用户喜爱。为了方便广大用户下载和使用CatServer，我站特此向您团队申请镜像CatServer的授权。届时，我们将会在我站实时同步镜像CatServer的所有构建，并在醒目位置标注并跳转到本仓库的链接（或您团队希望的其他链接），我站承诺将尽最大可能为社区提供长期高速稳定的镜像下载服务。
望您团队同意，感谢。

**Comment by Kotori0629** [comment]
@Luohuayu 看你啦 我觉得没啥问题，可以提高CatServer1.16.5/后续1.18.2用户使用率，目前看来无害

**Comment by Luohuayu** [comment]
可以 遵循LGPLv3协议即可

**Comment by Luohuayu** [comment]
目前暂不要增加1.18版本 因为正在开发中
