### ISSUE TITLE
[1.16.5] 某个空岛插件和世界结构生成类mod导致的问题

### ISSUE THREAD

**Issue by SkyiNcat** [Luohuayu/CatServer#417]
**运行环境**
JAVA8
#
Minecraft版本(1.12.2/1.16.5/1.18.2): 1.16.5

构建版本(从/version指令获取): 
LoliServer version 1.16.5-53f25fa (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT, Forge version 36.2.34)
直到Catserver - 1.16.5-c23f23b 都有这个问题

相关模组/插件: 
IridiumSkyblock

末地：创世 endrem-5.0.2-R-1.16.5.jar
结构变体 repurposed_structures_forge-3.4.7+1.16.5.jar

**描述这个BUG**
(如果有报错请附上pastebin链接或上传日志文件)
这个问题在Catserver - 1.16.5 - c23f23b版本之后就没有了，报告出来留个心眼
也许会在其他的插件和结构生成类mod搭配再现

**导致的问题r**
如果装了结构变体和末地创世这俩生成主世界结构的mod，就会造成这个空岛插件的错误
并且在这个空岛插件的世界里做的任何动作都会记录报错，刷刷刷一大片在后台

**复现方法**
IridiumSkyblock

末地：创世 endrem-5.0.2-R-1.16.5.jar
结构变体 repurposed_structures_forge-3.4.7+1.16.5.jar

一起安装，IridiumSkyblock和这俩任意一个mod安装也会导致这样的问题

**截图/视频**
(如果没有可以忽略)
[https://pic.imgdb.cn/item/626c11ad239250f7c5e58433.png](url)
[https://pic.imgdb.cn/item/626c11ad239250f7c5e58433.png](url)
[https://pic.imgdb.cn/item/626c11ad239250f7c5e58462.png](url)

**Comment by Luohuayu** [comment]
最新构建(652d64c8)是否存在问题?
