### ISSUE TITLE
[1.16.5] 空岛海岛类插件生成地形会导致有其他原版或者mod区块强制加载

### ISSUE THREAD

**Issue by SkyiNcat** [Luohuayu/CatServer#418]
**运行环境**
JAVA8

Minecraft版本(1.12.2/1.16.5/1.18.2):  1.16.5

构建版本(从/version指令获取): 
CatServer version 1.16.5-515381a (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT, Forge version 36.2.34)

相关模组/插件: 
IridiumSkyblock v3.2.8
Bentobox.jar + Acidlsland.jar

**描述这个BUG**
(如果有报错请附上pastebin链接或上传日志文件)
在该插件生成的世界内输入任何的指令会在后台跳出一大串神奇的代码

**导致的问题r**
更新了这个构建版本后会让海岛，空岛这种生成虚空，海水世界类型群系的插件，生成的世界变成普通的世界群系，整体功能可以完好的使用
但是生成出来的世界地形却是原版的区块+mod区块，排查了半天还以为是mod问题，结果是核心问题
换成了之前的核心没有这个问题，但是之前的核心会造成空岛和海岛与末地：创世mod和结构变体 冲突导致整个插件无法使用

而且会导致世界所有的天气无法调节，这个BUG仅在IridiumSkyblock v3.2.8插件上有出现，因为这个插件默认是空岛下雨，然后导致所有的世界都下雨，无法改为晴天，直接天气之子了属于是
不知道其他控制天气的这种世界生成插件有没有这种情况

**复现方法**
装上这个构建版本然后使用海岛或者空岛的mod生存服

**截图/视频**
(如果没有可以忽略)
[https://pic.imgdb.cn/item/626c163e239250f7c5f00ebc.png](url)

**Comment by Kotori0629** [comment]
Fixed
