### ISSUE TITLE
最新CatServer使用JOJO替身mod召唤替身掉线

### ISSUE THREAD

**Issue by GoblinCwl** [Luohuayu/CatServer#42]
之前使用的版本(19.11.26)中不存在这个问题
使用替身箭矢后，通过按键收回替身，再次召唤就会出错
模组地址：https://www.mcmod.cn/class/1466.html
报错日志：[latest.log](https://github.com/Luohuayu/CatServer/files/3948680/latest.log)

**Comment by Luohuayu** [comment]
已修复
https://github.com/Luohuayu/CatServer/commit/972f76298dd10fc74f7373a8d67850245edce14e
