### ISSUE TITLE
[1.16.5] Forge-Carpet模组无法正常生成假人

### ISSUE THREAD

**Issue by jingge1835** [Luohuayu/CatServer#420]
**运行环境**
JDK11
Minecraft版本(1.12.2/1.16.5/1.18.2): 1.16.5
构建版本(从/version指令获取): 
![QQ图片20220430014811](https://user-images.githubusercontent.com/104647311/165996569-c7344d42-416f-4661-aad9-768fc528de39.png)
相关模组/插件: Forge-Carpet-0.1.0.jar

**描述这个BUG**
(如果有报错请附上pastebin链接或上传日志文件)
1.使用指令/player Alex spawn生成假人后,无假人生成,TAB键中有假人Alex
2.再次使用指令后,控制台显示Player Alex  is already logged on
3.使用/player Alex kill,假人被移除,控制台显示Alex left the game
4.若使用forge_server则能正常生成假人
5.尝试过例如fakeplayer等插件也具有相同问题,显示假人加入服务器后,无实体生成

**导致的问题r**
假人功能无法使用 

**复现方法**
使用指令/player Alex spawn

**截图/视频**
![QQ图片20220430014444](https://user-images.githubusercontent.com/104647311/165996264-605beb88-857d-4eed-8124-a5ce3ab76c67.png)
![QQ图片20220430014612](https://user-images.githubusercontent.com/104647311/165996322-820cd8fa-daff-4503-aada-e652cb8e3dbc.png)

**Comment by Luohuayu** [comment]
Forge-Carpet的FakePlayer不是继承FakePlayer类或PlayerEntity类, 而是直接继承ServerPlayerEntity类, 导致服务端无法判断为FakePlayer, 并且调用了一些被CraftBukkit修改过的方法
修复难度有点大, 正在考虑修复方案
https://github.com/Cjsah/forge-carpet/blob/1.16.5/src/main/java/net/cjsah/mod/carpet/patch/EntityPlayerMPFake.java

**Comment by Luohuayu** [comment]
@jingge1835 上传完整的debug.log

**Comment by Luohuayu** [comment]
尝试使用`#40`构建
https://jenkins.rbqcloud.cn:30011/job/CatServer-1.16.5/40/

**Comment by jingge1835** [comment]
已成功解决, 感谢您的努力
