### ISSUE TITLE
[1.16.5] - Crash while starting up

### ISSUE THREAD

**Issue by SirOMGitsYOU** [Luohuayu/CatServer#421]
**Environment**

Minecraft version(1.12.2/1.16.5/1.18.2):  1.16.5
Build version(Get from /version command): CatServer-1.16.5-652d64c8-server
Mods/Plugins: 
https://www.modpackindex.com/modpacks/compare?modpacks=6279
![image](https://user-images.githubusercontent.com/20475516/166105168-ffc9dd0e-ee77-4279-844f-2e7cedb68cf9.png)

**Describe the bug**
https://paste.vcnet.work/47Rc1tERzF

**Expected behavior**
Start-Up correctly

**To Reproduce**
Unsure whats causing the issue.

**Comment by Luohuayu** [comment]
Have you fully downloaded the libraries file?

**Comment by Kotori0629** [comment]
Can you pack a copy of your plugins folder for me to test?

**Comment by Kotori0629** [comment]
Your libraries file is incomplete, i called the BaseComponent class, but it didn't throw me any exception. and I can get to the classloader of BaseComponent.
