### ISSUE TITLE
[1.16.5] 拖动物品放到副手时有几率导致服务器崩溃

### ISSUE THREAD

**Issue by SkyiNcat** [Luohuayu/CatServer#422]
**运行环境**
JAVA8

Minecraft版本(1.12.2/1.16.5/1.18.2): 1.16.5

构建版本(从/version指令获取): CatServer version 1.16.5-652d64c8 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT, Forge version 36.2.34)

相关模组/插件: 暂未知道是什么模组或者插件导致的

**描述这个BUG**
(如果有报错请附上pastebin链接或上传日志文件)
https://pastebin.com/59B7js4R

**导致的问题r**
把任意一种东西，使用鼠标点击拖动的方式放到副手上有一定几率导致服务器崩溃，我还以为是按Ctrl或者Shift拿取替换导致的，结果不是，有时候Shift或者Ctrl拿出来东西后，普通拖放就会导致服务器崩溃，暂未知道是什么mod或者插件导致该问题

**复现方法**

**截图/视频**
(如果没有可以忽略)

**Comment by Kotori0629** [comment]
See: [https://github.com/Yesssssman/epicfightmod/issues/949](https://github.com/Yesssssman/epicfightmod/issues/949)
