### ISSUE TITLE
[1.16.5] JDK11启动服务器失败

### ISSUE THREAD

**Issue by SkyIce0229** [Luohuayu/CatServer#423]
**运行环境**

Minecraft版本(1.12.2/1.16.5/1.18.2): 1.16.5
构建版本(从/version指令获取): CatServer-1.16.5-652d64c8
相关模组/插件: 乡村水域2整合包

**描述这个BUG**
https://paste.ubuntu.com/p/NtfDwyKtM3/

**导致的问题r**
服务器无法正常启动
**复现方法**
将catserver放入乡村水域2整合包的服务端文件并通过start.bat启动
**截图/视频**
(如果没有可以忽略)

**Comment by Kotori0629** [comment]
![image](https://user-images.githubusercontent.com/81866089/166136770-9aaae6c3-cd95-42e2-81fb-92fc272ba5ab.png)
于Dragonwell JDK8环境下测试, 安装corpsecomplex后未崩溃

**Comment by Luohuayu** [comment]
请在Java8环境分别在catserver和forge测试单个mod

**Comment by SkyIce0229** [comment]
我想我的JDK8的版本可能有问题，我选择的是321版本的，能否推荐另一个版本呢？谢谢

**Comment by SkyIce0229** [comment]
我测试的JDK8是321版本的，能否推荐另一个JDK8的版本呢

**Comment by Luohuayu** [comment]
> 我测试的JDK8是321版本的，能否推荐另一个JDK8的版本呢

8u3xx以上都可以, 如果已经排除是Java版本导致的MOD不兼容请反馈MOD作者, 其他问题请新开一个Issues
