### ISSUE TITLE
[1.16.5]服务器突然崩溃，急需解决

### ISSUE THREAD

**Issue by djaiodhyuaw** [Luohuayu/CatServer#425]
运行环境

Minecraft版本(1.12.2/1.16.5/1.18.2): 1.16.5
构建版本(从/version指令获取):
CatServer-1.16.5-652d64c8
相关模组/插件:

描述这个BUG
(如果有报错请附上pastebin链接或上传日志文件)
https://pastebin.com/190WMcpq
https://pastebin.com/As7TYYBJ
导致的问题
服务器崩溃

截图/视频
(如果没有可以忽略)

**Comment by Kotori0629** [comment]
请在Java8下尝试复现这个Bug

**Comment by Luohuayu** [comment]
Java17你是认真的吗

**Comment by ShunL12324** [comment]
> Java17你是认真的吗

地皮插件和FAWE已经最新版本已全面转向Java17，请考虑将Java17纳入支持范围，部分其他插件也开始要求java 16+

**Comment by Kotori0629** [comment]
> > Java17你是认真的吗
> 
> 地皮插件和FAWE已经最新版本已全面转向Java17，请考虑将Java17纳入支持范围，部分其他插件也开始要求java 16+

如果你在使用途中遇到问题, 请在Java8环境下测试后报告给我们, Java16+目前兼容性正常, 但有大量Mod并不兼容。

**Comment by ShunL12324** [comment]
> > > Java17你是认真的吗
> > 
> > 
> > 地皮插件和FAWE已经最新版本已全面转向Java17，请考虑将Java17纳入支持范围，部分其他插件也开始要求java 16+
> 
> 如果你在使用途中遇到问题, 请在Java8环境下测试后报告给我们, Java16+目前兼容性正常, 但有大量Mod并不兼容。

问题在于，java 8无法加载这些插件的最新版，而地皮插件是很难放弃的，同时不能使用FAWE也是一个很大的问题，现在被迫使用老版本的WE才能勉强运行，这意味着用户无法在插件上得到足够的支持...

**Comment by Luohuayu** [comment]
> > Java17你是认真的吗
> 
> 地皮插件和FAWE已经最新版本已全面转向Java17，请考虑将Java17纳入支持范围，部分其他插件也开始要求java 16+

服务端是完全兼容Java8-17的
但MOD和插件的兼容性自行取舍 与服务端无关 不也做评价
