### ISSUE TITLE
[1.16.5] 玩家跑图多次死亡重生后区块无法保存

### ISSUE THREAD

**Issue by Kotori0629** [Luohuayu/CatServer#426]
**运行环境**
Oracle J8

Minecraft版本(1.12.2/1.16.5/1.18.2):  1.16.5
构建版本(从/version指令获取): 
CatServer-1.16.5-652d64c8-server
相关模组/插件: 
无插件, 
![HK 13%Y_%9ZA0N OGDBZ(P6](https://user-images.githubusercontent.com/81866089/166148010-53b40a5c-ae84-482c-8bde-4c3488aaac45.png)

**描述这个BUG**
(如果有报错请附上pastebin链接或上传日志文件)
https://paste.fastmirror.net/?33d7238bb421fdfc#5QLmVaR2P3UCC286VLkqPM3Fo5ZkDtwV7DpZiAyVikzY
**导致的问题r**
区块不加载, 控制台报错, 区块不再保存
**复现方法**
跑图 一个方向  1000格  自杀， 重复操作， 复活点周围就会有区块变成这样
**截图/视频**
(如果没有可以忽略)
![J%$T7P}2FC{@`8H NA1K335](https://user-images.githubusercontent.com/81866089/166148049-c153fbfb-6fc8-48c6-a425-0710855cf7d1.png)

**Comment by Kotori0629** [comment]
Forge bug

**Comment by Luohuayu** [comment]
把那个spigot patch删掉试试

**Comment by Kotori0629** [comment]
> 

无效，这个bug在Forge server依旧复现

**Comment by Kotori0629** [comment]
> 把那个spigot patch删掉试试

无效，这个bug在Forge server依旧复现

**Comment by Kotori0629** [comment]
> 

目测哪个mod注入炸了吧
