### ISSUE TITLE
[1.16.5] PlotSqured cannot pass block place/break event

### ISSUE THREAD

**Issue by ShunL12324** [Luohuayu/CatServer#427]
**运行环境**

版本：CatServer-1.16.5-652d64c8-server; oracle jdk 17/16; windows server 2022
相关模组/插件: 
* worldedit-bukkit-7.2.5-dist
*  PlotSquared-Bukkit-6.6.3-Premium/PlotSquared-Bukkit-6.2.2-Premium

**描述这个BUG**
[PlotSquared-Bukkit-6.2.2-Premium](https://gist.github.com/Eric-liucn/40f583479c73be36c059de2163512cde) 
Error when fake player place/break blocks in the plot world

**导致的问题r**
Error message

**复现方法**
Using any block placer offered by mods will cause this issue, like industrialforegoing:block_placer

**截图/视频**
(如果没有可以忽略)

**Comment by Kotori0629** [comment]
Error message?

**Comment by ShunL12324** [comment]
> Error message?

[error](https://gist.github.com/Eric-liucn/40f583479c73be36c059de2163512cde)

**Comment by Luohuayu** [comment]
这个版本PlotQqured不支持FakePlayer
已增加fakePlayer.eventPass选项(catserver.yml), 但开启该选项可能会造成FakePlayer越权的后果
https://github.com/Luohuayu/CatServer/commit/f8777499df2a6398419b41245da15be36c8c9d44

**Comment by ShunL12324** [comment]
> 这个版本PlotQqured不支持FakePlayer 已增加fakePlayer.eventPass选项(catserver.yml), 但开启该选项可能会造成FakePlayer越权的后果 [f877749](https://github.com/Luohuayu/CatServer/commit/f8777499df2a6398419b41245da15be36c8c9d44)

使用 CatServer-1.16.5-09dbc0f3-server
设置passEvent为true or false 都不能解决这个问题
[log](https://gist.github.com/Eric-liucn/0383309c564ef1377bd41b29d0d14064)
