### ISSUE TITLE
[All] Spigot and forge GUI addition Quark

### ISSUE THREAD

**Issue by XionioXMaster** [Luohuayu/CatServer#428]
**Environment**

Minecraft version(1.12.2/1.16.5/1.18.2): -
Build version(Get from /version command): -
Mods/Plugins: Quark and any plugin that has GUI stuff

**Describe the bug**
Roughly speaking, this bug has been around for many years, it works by collecting things from the GUI of Spigot plugins through the Quark mod or another sorting mod that is on the server side

As you know, the Spigot GUI cannot be transferred to your inventory,
but if you press the button to move to your inventory through the Quark mod, you can bypass the system and dupe anything from any plugin menu.

**Comment by Luohuayu** [comment]
Use the latest version. Enable limitFastClickGUI option, should be fixed.

**Comment by XionioXMaster** [comment]
> Use the latest version. Enable limitFastClickGUI option, should be fixed.

Okay, tomorrow after work I'll check, the version with the edit is 1.12.2?

**Comment by Luohuayu** [comment]
> 1.12.2 only*

Yes, I will add this patch to 1.16.5
