### ISSUE TITLE
[1.16.5] 关于在CatServer中IridiumSkyblock空岛插件与结构类型MOD冲突报错

### ISSUE THREAD

**Issue by SkyiNcat** [Luohuayu/CatServer#429]
**运行环境**
JAVA8
Minecraft版本(1.12.2/1.16.5/1.18.2): 1.16.5

构建版本(从/version指令获取): CatServer-1.16.5-45f4f0a0-server.jar

相关模组/插件: 
IridiumSkyblock

YungsApi-1.16.4-Forge-13
YungsExtras-Forge-1.16.4-1.0
BetterDungeons-1.16.4-1.2.1
BetterStrongholds-1.16.4-1.2.1
repurposed_structures_forge-3.4.7+1.16.5
endrem-5.0.2-R-1.16.5

**描述这个BUG**
(如果有报错请附上pastebin链接或上传日志文件)

**导致的问题r**
装上IridiumSkyblock空岛插件后，装上以上类型的结构生成MOD就会让这个插件无法运作并且报错
但是特定的mod不会导致这个问题出现
不会导致该问题出现的mod
SkyVillage_1.0.0_1.16.5
valhelsia_structures-1.16.5-0.1.6
BYG
DungeonsArise-1.16.5-2.1.47-release
mostructures-forge-1.2.0-1.16.5

**复现方法**
装上就可以复现

**截图/视频**
(如果没有可以忽略)
[https://pic.imgdb.cn/item/6271442209475431292f3b3e.png](url)

**Comment by Luohuayu** [comment]
测试最新构建

**Comment by Kotori0629** [comment]
在最新构建[1.16.5-da0bd165](https://jenkins.rbqcloud.cn:30011/job/CatServer-1.16.5/41/)中测试该Bug不再复现
