### ISSUE TITLE
CatServer is incompatible with BKCommonLib

### ISSUE THREAD

**Issue by FRmaxFR** [Luohuayu/CatServer#43]
OS : CatServer-4e616b8-universal | Debian 9
Java ： 1.8.0_232
BKCommonLib : https://www.spigotmc.org/resources/bkcommonlib.39590/ (Version 1.14.4-v1)
Error logs : https://hastebin.com/buwosequge.css

**Comment by Luohuayu** [comment]
Unable to be compatible

**Comment by liach** [comment]
bkcommonlib有多魔性
