### ISSUE TITLE
[1.12.2] 星辉魔法导致玩家掉线

### ISSUE THREAD

**Issue by MoeShimaKaze** [Luohuayu/CatServer#431]
**运行环境**

Minecraft版本(1.12.2/1.16.5/1.18.2): 1.12.2
构建版本(从/version指令获取): git-CatServer-1.12.2-35187d3 (MC: 1.12.2)
相关模组/插件: 星辉魔法

**描述这个BUG**
玩家在使用星辉魔法的瞭望台时崩溃掉线，导致后台刷出报错
报错如下
https://paste.fastmirror.net/?bb52a182199c0cfa#G1MJaB8J81gnjCKYtCsL3T5ojTe1nyVGkYZk6jNRxPfA
(如果有报错请附上pastebin链接或上传日志文件)

**导致的问题**
后台报错，玩家疯狂掉线
**复现方法**
使用星辉魔法的瞭望台，然后关掉客户端
**截图/视频**
(如果没有可以忽略)

**Comment by Luohuayu** [comment]
星辉自身BUG, 但星辉1.12.2已停更所以提供在服务端的修复方案
