### ISSUE TITLE
[1.16.5] 修改的世界出生点无法正常发挥作用！

### ISSUE THREAD

**Issue by R3Or7eN** [Luohuayu/CatServer#432]
**运行环境**

Minecraft版本(1.12.2/1.16.5/1.18.2): 1.16.5
构建版本(从/version指令获取): 1.16.5-da0bd164
相关模组/插件: 啥也没有

**描述这个BUG**
(如果有报错请附上pastebin链接或上传日志文件)
使用命令setworldspawn修改过世界出生点 用nbt查看level也显示为已更改的坐标 可新用户进入或死亡时仍然会出生在另一个坐标 不过如果用spawnpoint直接修改玩家出生点就能够生效

**导致的问题**
没法让新玩家出生在正确的地点

**复现方法**
用setworldspawn随意设置一个与原出生点不同的坐标即可

**截图/视频**
(如果没有可以忽略)

**Comment by Luohuayu** [comment]
确定没有安装任何插件?
