### ISSUE TITLE
[1.12.2] Async chunk load

### ISSUE THREAD

**Issue by Sylensky** [Luohuayu/CatServer#434]
**Environment**

Minecraft version(1.12.2/1.16.5/1.18.2):  1.12.2
Build version(Get from /version command): git-CatServer-1.12.2-35187d3 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT, Forge version 14.23.5.2860)
Mods/Plugins:
 - OTG/biome bundle, jed, Pams Harvestcraft, Creativecore, Chunkgenlimiter, llibrary, iceandfire, gravestone, elder arsenal, betternether, placeableitems
 - Warpsystem, as its the only one causing issues

**Describe the bug**
https://pastebin.com/HQ95UMSg
When using the random teleport feature the telport request doesnt get through and logs the previously mentioned error.
I assume async chunk load is not working or atleast warpsystem does something different?

**Expected behavior**
Teleporting to calculated location in a different world.

**To Reproduce**
- create 2 worlds
- setup warpsystem with rtp to second world

**Comment by Luohuayu** [comment]
Report plugin report
