### ISSUE TITLE
[1.16.5] 使用itemsadder插件报错

### ISSUE THREAD

**Issue by zfms4188** [Luohuayu/CatServer#438]
**运行环境**

Minecraft版本(1.12.2/1.16.5/1.18.2):   **1.16.5**
构建版本(从/version指令获取):   **1.16.5-b320f11e**
相关模组/插件:   **ItemsAdder**
(未安装其他任何MOD以及插件,仅有ia所需前置)

**描述这个BUG**
进入游戏就会弹出报错,聊天,输入指令,退出游戏也会,测试在纯净paper端是可正常使用该插件的
这是是进入游戏,聊天,输入指令的报错提示 https://pastebin.com/yBk6YvKz
若还需要其他信息或完整日志,我会补上.

**导致的问题r**
无法正常使用和正常进行游戏

**复现方法**
加入游戏就会报错,或者聊天和输入指令

**截图/视频**
(如果没有可以忽略)

**Comment by Luohuayu** [comment]
请关闭ProtocolLib的background compiler选项

**Comment by zfms4188** [comment]
> 请关闭ProtocolLib的后台编译选项

~~关闭后似乎已正常运行~~ 感谢

**Comment by zfms4188** [comment]
进入游戏和正常聊天已无报错 但是退出游戏会有一段错误
https://pastebin.com/DThpSJyN

**Comment by Luohuayu** [comment]
使用最新构建
