### ISSUE TITLE
[1.16.5] 跨服端错误,无法正常跨服

### ISSUE THREAD

**Issue by zfms4188** [Luohuayu/CatServer#439]
**运行环境**

Minecraft版本(1.12.2/1.16.5/1.18.2):  1.16.5
构建版本(从/version指令获取):  1.16.5-b320f11e  和   lightfall-f3cae95.jar
相关模组/插件:  

**描述这个BUG**
(如果有报错请附上pastebin链接或上传日志文件)
已查阅常见问题后,进行操作
https://pastebin.com/WYRKWq5m
这里我看到了时装工坊 于是我尝试删掉了它
删除后:
https://pastebin.com/nC9KCvUc
依旧无法正常跨服
(若是通过bc进入paper等纯净端的大厅,则会提示"不完整标签")

**导致的问题r**
不能正常进行跨服

**复现方法**
跨服会失败

**截图/视频**
(如果没有可以忽略)

**Comment by Luohuayu** [comment]
由于1.13+以上原生Forge不支持跨服, 跨服功能由lightfall提供, 出现任何问题请反馈lightfall或使用其他跨服工具
