### ISSUE TITLE
1.16.5 World guard bug

### ISSUE THREAD

**Issue by SqdGoodlol** [Luohuayu/CatServer#440]
**Environment**

Minecraft version(1.12.2/1.16.5/1.18.2):  1.16.5
Build version(Get from /version command): CatServer-1.16.5-b320f11e-server
Mods/Plugins:  worldguard-bukkit-7.0.5-dist

**Describe the bug**
(If there is an error, please attach the pastebin link)
In a foreign region, even though a person is not a member of the region, he can pour water using a bucket of water
**Expected behavior**

**To Reproduce**

**Screenshot/Video**
(If it doesn't exist you can ignore it)

**Comment by Kotori0629** [comment]
Fixed
