### ISSUE TITLE
[1.12.2] CatServer-746efe0 -u更新为CatServer-4d54207-u  之后崩溃

### ISSUE THREAD

**Issue by mcmso** [Luohuayu/CatServer#442]
**运行环境**

Minecraft版本(1.12.2/1.16.5/1.18.2): 1.12.2
构建版本(从/version指令获取): 
相关模组/插件:       SimplyJetpacks2-1.12.2-2.2.15.69.jar  

**描述这个BUG**
crash里面有关于Simply Jetpacks 2 的字样
https://paste.ubuntu.com/p/gbRyChF5HH/
(如果有报错请附上pastebin链接或上传日志文件)

**导致的问题r**
导致崩溃
**复现方法**
把CatServer-746efe0 -u更新为CatServer-4d54207-u就会崩溃         降版本就没问题了
**截图/视频**
(如果没有可以忽略)

**Comment by Luohuayu** [comment]
先回滚旧版本, 待修复

**Comment by Luohuayu** [comment]
已修复
