### ISSUE TITLE
[1.16.5] SkyCraftUpdater插件与 Plugin Channel 问题

### ISSUE THREAD

**Issue by MapleSugar365** [Luohuayu/CatServer#443]
你好，我遇到了一些问题，需要你的帮助，十分感谢！

**运行环境：** Windows11 / CentOS 7.6
Minecraft版本: 1.16.5
构建版本: CatServer-1.16.5-6480230e (当前最新)
相关模组/插件: [SkyCraftUpdater 2.3.1](https://www.mcbbs.net/thread-1212410-1-1.html) (当前最新)

**这个插件的作用：**
SkyCraftUpdater 在我的服务器中负责客户端的更新，以此帮助客户端同步新的mod或移除多余mod和资源包，以此降低更新维护的劳动和预防客户端作弊。

**描述遇到的问题：**
起因是我看到插件作者的话：**"注意：由于部分1.16.5的服务端核心对plugin channel的支持存在bug，如果你使用的1.16.5的服务端，请在服务端配置中将requireUpdater设置为false，然后在客户端配置中将contactServer设置为false，否则可能会导致无法进入服务器"**，首先requireUpdater和contactServer两个选项的作用是服务器需要客户端安装了SkyCraftUpdater，并等待客户端上的SkyCraftUpdater mod联系服务器，确保客户端文件无误时才会让客户端进入服务器，我十分看好这个反作弊功能，不过我还是对CatServer充满了信心，因为我之前1.12.2就是用的CatServer，其兼容性和稳定性让我十分震撼，但是现实却狠狠的打了我的脸，按照下面的复现方法配置服务器和客户端后就无法进入服务器了，详细现象和日志也在下面，要想进入服务器，就得按照插件作者说的那样，将requireUpdater和contactServer两个选项设置为false，但这样就没有了反作弊功能，客户端如果删除了SkyCraftUpdater，就可以为所欲为了。

**复现方法：**
1.下载并在两端（服务端/客户端）上正确安装SkyCraftUpdater，并运行一次两端，生成配置文件；
2.在客户端的config目录下找到updater-common.toml配置，修改contactServer的值为true；
3.在服务端的plugins->SkyCraftUpdater目录下找到config.yml配置，修改requireUpdater的值为true；
4.在本地计算机上运行两端，然后让客户端连接服务器，即可复现问题，提示channel问题。

**相关日志和截图：**
客户端：[HM-MCM Client Logs.zip](https://github.com/Luohuayu/CatServer/files/8694306/HM-MCM.Client.Logs.zip)
服务端：[HM-MCM Server Logs.zip](https://github.com/Luohuayu/CatServer/files/8694307/HM-MCM.Server.Logs.zip)

再次致谢！
—— HM-MCM

**Comment by MapleSugar365** [comment]
使用的Java版本为 [Alibaba_Dragonwell_11.0.12.8](https://github.com/alibaba/dragonwell11/releases/tag/dragonwell-11.0.12.8_jdk-11.0.12-ga)

**Comment by Luohuayu** [comment]
客户端日志只看出缺少sereneseasons的channel

**Comment by Luohuayu** [comment]
spigot是否复现

**Comment by YhaoMin365** [comment]
> spigot是否复现

已阅，周六进行测试

**Comment by MapleSugar365** [comment]
> spigot是否复现

测试结果：
复现结果不一致，无法满足完全的复现条件

具体原因：
spigot服务端不支持安装mod，因为SkyCraftUpdater是插件与mod结合一体开发，在服务器中放在插件目录，在客户端中放在mods目录，需要插件与mod配合才能生效，我无法确定客户端在加入spigot时是否允许客户端SkyCraftUpdater联系服务器。

这里服务器和客户端只安装SkyCraftUpdater，也进不去。不过结果变为了显示SkyCraftUpdater插件配置的自定义提示
![Snipaste_2022-05-21_15-41-23](https://user-images.githubusercontent.com/48885484/169641421-e9143992-a7b1-4f1a-bad6-6219d55c4517.png)

**Comment by MapleSugar365** [comment]
> spigot是否复现

日志和截图：
[Server logs.zip](https://github.com/Luohuayu/CatServer/files/8747214/Server.logs.zip)
[Client logs.zip](https://github.com/Luohuayu/CatServer/files/8747215/Client.logs.zip)
