### ISSUE TITLE
[Bug] Wrong implementation of bukkit time method.

### ISSUE THREAD

**Issue by TheDarkDnKTv** [Luohuayu/CatServer#45]
I am developing mod under forge, and there is block which uses world.getWorldTime() method. When installing mod on server everything is working, but if intsall EssentialsX plugin, method starting to return values more than 24k ticks... I wrote to essentials devs and they answer:
 ```This discrepancy lies with your server software. Bukkit and MCP/Forge expose different time-related methods to plugins and mods respectively, and your server software doesn't appear to implement the Bukkit methods in a way that works properly with MCP/Forge mods. Please report this to the developer of your server software. EssentialsX does not and will not support hybrid servers.``` 
@Luohuayu pls check whats wrong, why method getting broken after this plugin? May be you need to check implementation of world time methods from bukkitAPI?

**Comment by Luohuayu** [comment]
Vanilla time command resets the time to the first day 0 tick, EssentialsX time command increases the time to the next day 0 tick.
I think it's just different ways, but there are no problems

**Comment by Luohuayu** [comment]
World time does not reset to 0 when it reaches 24000

**Comment by Luohuayu** [comment]
Vanilla time command resets the time to the first day 0 tick, EssentialsX time command increases the time to the next day 0 tick.
I think it's just different ways, but there are no problems.

**Comment by TheDarkDnKTv** [comment]
But why when there is no essentialsx this method returns long [0-24000) but with it it's works like world.getTotalWorldTime(), it just adds tick... This method on our server returns something about 300k fully same like world.getTotalWorldTime() :\

**Comment by Luohuayu** [comment]
Without EssentialsX does not reset at 24000

**Comment by TheDarkDnKTv** [comment]
> Without EssentialsX does not reset at 24000

Resets, i checket it in debug. When entering /time set 0 or just wait, method getWorldTime() resets, method getTotalWorldTime keep value.

**Comment by TheDarkDnKTv** [comment]
It is reason why we have two methods....

**Comment by Luohuayu** [comment]
I did not find the time reset code on Forge server

**Comment by TheDarkDnKTv** [comment]
Maybe because it is minecraft code? I do not know, but you can debug by yourself and make sure method World#getWorldTime value cannot be more than 24000 ticks

**Comment by Luohuayu** [comment]
Debug without any mods and plugins:
https://i.loli.net/2019/12/14/InsrTgLWQMjRZwm.png

**Comment by Luohuayu** [comment]
Vanilla server does not reset time to 0, it just keeps increasing

**Comment by TheDarkDnKTv** [comment]
Yea, checked it twice, you right. If enter /time set 0 then time resets, when essentialsx installed - didn't resets. If just wait, then it is counting more than 24000. Thank you for answer.
