### ISSUE TITLE
[1.16.5] 热力和MEK问题？

### ISSUE THREAD

**Issue by zfms4188** [Luohuayu/CatServer#450]
**运行环境**

Minecraft版本(1.12.2/1.16.5/1.18.2): 1.16.5
构建版本(从/version指令获取): 1.16.5-87a458d6
相关模组/插件: 
热力膨胀 MEK
**描述这个BUG**
(如果有报错请附上pastebin链接或上传日志文件)
[1.16.5-87a458d6](https://pastebin.com/Y4uA7aR2)
后台刷屏报错

**导致的问题r**
导致服务器卡顿
**复现方法**

**截图/视频**
(如果没有可以忽略)

**Comment by Kotori0629** [comment]
删了你的MCMT
