### ISSUE TITLE
[1.16.5] 最新构建中IridiumSkyblock再现冲突问题

### ISSUE THREAD

**Issue by SkyiNcat** [Luohuayu/CatServer#452]
**运行环境**
JAVA8

Minecraft版本(1.12.2/1.16.5/1.18.2):  
1.16.5

构建版本(从/version指令获取): 
 This server is running CatServer version 1.16.5-51084000 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT, Forge version 36.2.35)

相关模组/插件: 
IridiumSkyblock

**描述这个BUG**
(如果有报错请附上pastebin链接或上传日志文件)
IridiumSkyblock插件与之前的结构生成mod一样，在最新的构建中，它们又出现了冲突问题
只有CatServer-1.16.5-da0bd164-server.jar 构建版本是最后一次能够正常运作该插件的版本

因为IridiumSkyblock这个插件VN说作者似乎不打算做Forege支持，所以能修的了是最好的，因为它是一个比较优质的空岛插件，在高版本中它能够代替了很多空岛插件，包含了任务挑战，升级空岛范围机制等有趣玩法，所以能修复就会造福挺多空岛服服主的，或者说空岛mod服服主，如果不能修的好就算了，我还是继续使用旧版本

**导致的问题r**
IridiumSkyblock无法使用，并且疯狂后台弹出报错

**复现方法**
装上IridiumSkyblock以及特定的结构生成mod，与上次一样的冲突

**截图/视频**
(如果没有可以忽略)
【报错截图】
https://pic.imgdb.cn/item/628cc8ee0947543129ff1f9d.png

【插件提交】
链接: https://pan.baidu.com/s/1bTtTnNT4ya4CE8t86-zSAg 提取码: mtjd

**Comment by Kotori0629** [comment]
修正一下 ： 大部分插件作者都不会为混合端做兼容

其次：请附带"特定的结构生成mod"
