### ISSUE TITLE
1.16.5 Project_MMO Crash server

### ISSUE THREAD

**Issue by SqdGoodlol** [Luohuayu/CatServer#453]
**Environment**

Minecraft version(1.12.2/1.16.5/1.18.2): 1.16.5
Build version(Get from /version command): CatServer-1.16.5-b320f11e-server
Mods/Plugins: Project_MMO-1.16.5-3.67.6

**Describe the bug**
You break blocks, you play, and over time it just crashes.

**Expected behavior**

**To Reproduce**

**Screenshot/Video**
[crash-2022-05-25_18.23.17-server.txt](https://github.com/Luohuayu/CatServer/files/8772424/crash-2022-05-25_18.23.17-server.txt)

(If it doesn't exist you can ignore it)

**Comment by Kotori0629** [comment]
Try use JDK8 or JDK11

**Comment by SqdGoodlol** [comment]
Some plugins stop working

**Comment by Kotori0629** [comment]
> Some plugins stop working

Now, first test whether the same problem will occur under jdk8/jdk11, instead of the plugin no longer working

**Comment by SqdGoodlol** [comment]
No, it still crashes

**Comment by Kotori0629** [comment]
> No, it still crashes

How to reproduce problem?

**Comment by SqdGoodlol** [comment]
Install on the mod server. Dig with a wooden pick for 5 minutes
