### ISSUE TITLE
[1.16.5] PlayerDeathEvent does not return data about the player's inventory

### ISSUE THREAD

**Issue by Flareonn** [Luohuayu/CatServer#454]
**Environment**

Minecraft version 1.16.5: 
Mods/Plugins: 
![image](https://user-images.githubusercontent.com/35931685/170563478-1961879c-4c3f-42ca-875d-3c5431c2790e.png)

**Describe the bug**
During the PlayerDeathEvent, data about the player is sent to the method. Players inventory is available, but the inventory turns out to be empty.

**Screenshot/Video**
![image](https://user-images.githubusercontent.com/35931685/170563275-098d4cea-09db-49bc-8573-c3f36bbabcfb.png)

Null comes in this line, although there was an item in this slot at the time of death

**Comment by Flareonn** [comment]
These operations occur due to the fact that the standard two lines for saving inventory do not work.

```
event.setKeepInventory(true)
event.getDrops().clear()
```

**Comment by Flareonn** [comment]
There is also a question: is there any API for accessing the core so that I can get the player's inventory from there?

**Comment by dayd21git** [comment]
EntityDamageByEntityEvent & EntityDamageEvent & PlayerDeathEvent - broken/not working.
My code:
```
@EventHandler
public void onDamage1(EntityDamageEvent e) {
	Bukkit.getConsoleSender().sendMessage("EntityDamageEvent");
}

@EventHandler
public void onDamage2(EntityDamageByEntityEvent e) {
	Bukkit.getConsoleSender().sendMessage("EntityDamageByEntityEvent");
}

@EventHandler
public void onDeath(PlayerDeathEvent e) {
	ItemStack item = e.getEntity().getInventory().getItemInMainHand();
	String name = "PlayerDeathEvent: ";
	Bukkit.getConsoleSender().sendMessage(item == null ? name + "NULL" : name + item.getType().name());
}
```

**Comment by Serega007RU** [comment]
a year later, they finally fixed this bug, we've been waiting for this for a long time

**Comment by Kotori0629** [comment]
> a year later, they finally fixed this bug, we've been waiting for this for a long time

This is a good start, indicating that we are focusing on developing 1.16.5
