### ISSUE TITLE
不能听到别的玩家放置方块的声音

### ISSUE THREAD

**Issue by LDS-XiaoYe** [Luohuayu/CatServer#46]
版本：19.12.12 async版本
在服务器内听不到其他玩家放置方块的声音，自己放置方块的声音可以听到。其他玩家的破坏等声音正常。
经本人验证，使用两个相同的客户端，用大号和小号局域网联机可以听到对方的放置方块的声音。
应该不是Mod原因

模组列表：

Advanced+Solar+Panels-4.3.0.jar
ae2stuff-0.7.0.4-mc1.12.2.jar
AnotherCommonBugFix-1.0.7-1.12.2.jar
appliedenergistics2-rv6-stable-7.jar
Armourers-Workshop-1.12.2-0.49.1.6.jar
Avaritia-1.12.2-3.3.0.33-universal.jar
Baubles-1.12-1.5.2.jar
bdlib-1.14.3.12-mc1.12.2.jar
BetterTitleScreen-1.12-1.4.jar
Botania+r1.10-362.jar
BrandonsCore-1.12.2-2.4.17.208-universal.jar
CodeChickenLib-1.12.2-3.2.3.358-universal.jar
CoFHCore-1.12.2-4.6.3.27-universal.jar
CoFHWorld-1.12.2-1.3.1.7-universal.jar
CookingForBlockheads_1.12.2-6.4.71.jar
CraftTweaker2-1.12-4.1.19.jar
CraftTweakerSync.jar
CreativeCore_v1.9.74_mc1.12.2.jar
CustomMC.jar
CustomNPCs_1.12.2-(01Oct19).jar
CustomSkinLoader_Forge-14.11.jar
Draconic-Evolution-1.12.2-2.3.24.349-universal.jar
environmentaltech-1.12.2-2.0.20.1.jar
ExtraBotany-r1.1-56.jar
ExtraCells-1.12.2-2.6.4.jar
foamfix-0.10.9-1.12.2.jar
forgemod_VoxelMap-1.9.11_for_1.12.2.jar
Galacticraft-Planets-1.12.2-4.0.2.238.jar
GalacticraftCore-1.12.2-4.0.2.238.jar
Gravitation+Suite-3.1.1.jar
Hwyla-1.8.26-B41_1.12.2.jar
ImmersiveEngineering-0.12-92.jar
industrialcraft-2-2.8.170-ex112.jar
InventoryTweaks-1.63.jar
ironchest-1.12.2-7.0.72.847.jar
ItemPhysic+Lite+1.3.7+mc1.12.2.jar
jei_1.12.2-4.15.0.291.jar
JustEnoughCharacters-1.12.0-3.4.5.jar
JustEnoughResources-1.12.2-0.9.2.60.jar
mctitle-1.0.jar
Mekanism-1.12.2-9.8.3.390.jar
MekanismGenerators-1.12.2-9.8.3.390.jar
MekanismTools-1.12.2-9.8.3.390.jar
memory_repo
MicdoodleCore-1.12.2-4.0.2.238.jar
modtweaker-4.0.17.jar
MouseTweaks-2.10-mc1.12.2.jar
MTLib-3.0.6.jar
MultiMine-1.12.2.jar
NotEnoughItems-1.12.2-2.4.3.245-universal.jar
OptiFine_1.12.2_HD_U_F4.jar
RedstoneFlux-1.12-2.1.0.6-universal.jar
Sakura-V0.0.6-MC1.12.2.jar
SlashBlade-mc1.12-r28.jar
SmoothFont-mc1.12.2-2.1.1.jar
ThermalDynamics-1.12.2-2.5.5.21-universal.jar
ThermalExpansion-1.12.2-5.5.4.43-universal.jar
ThermalFoundation-1.12.2-2.6.3.27-universal.jar
valkyrielib-1.12.2-2.0.20.1.jar
VariedCommodities_1.12.2(21nov19).jar
VoxelMods
WailaHarvestability-mc1.12-1.1.12.jar
WanionLib-1.12.2-2.4.jar
worldedit-forge-mc1.12.2-6.1.10-SNAPSHOT-dist.jar

插件列表:
CatIC2LaserBridge.jar               MiaoBind.jar
CatResidenceAssist.jar              MiaoBoard.jar
ChestCommandsPro.jar                Modern-LWC-1.9.6.jar
ChestCommands+v3.2.0.jar            Multiverse-Core-2.5.0.jar
EssentialsX-2.16.0.31.jar           PlaceholderAPI.jar
EssentialsXAntiBuild-2.16.0.31.jar  PlotSquared-Bukkit-19.12.10-b4c257b-788.jar
EssentialsXChat-2.16.0.31.jar       ProtocolLib.jar
EssentialsXProtect-2.16.0.31.jar    QuickShop.jar
EssentialsXSpawn-2.16.0.31.jar      Residence.jar
GroupManager+ [v3.2].jar            Vault-1.6.6.jar
@.jar                               WorldBorder.jar
keepinvandexp.jar                   Yum.jar

**Comment by Luohuayu** [comment]
已修复
