### ISSUE TITLE
[1.16.5] 当进入有宝可梦的世界的时候客户端会失去响应几十秒

### ISSUE THREAD

**Issue by Yyiyun** [Luohuayu/CatServer#463]
**运行环境**
Minecraft版本(1.12.2/1.16.5/1.18.2): 1.16.5
构建版本(从/version指令获取): 
CatServer version 1.16.5-6ca86dd2 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT, Forge version 36.2.35)
相关模组/插件: 
Pixelmon9.0.0
PlotSquared-Bukkit-5.13.12
Multiverse-Core-4.3.1

**描述这个BUG**
(如果有报错请附上pastebin链接或上传日志文件)
当进入有宝可梦的世界的时候客户端会失去响应几十秒，服务端不会卡顿且无报错，客户端查看了日子也没有报错
**导致的问题r**
客户端Time out超时
**复现方法**
只要多世界传送到有宝可梦的世界就会出现，,并且使用地狱门也会出现该情况
**截图/视频**
(如果没有可以忽略)

**Comment by Yyiyun** [comment]
测试了一下单人穿梭世界也不会出现该情况

**Comment by Y-Yuw** [comment]
yysy有没有可能是因为网络传输太慢（路人）

**Comment by Yyiyun** [comment]
> yysy有没有可能是因为网络传输太慢（路人）
传送到地皮世界不会发生卡顿 （因为没有宝可梦）

**Comment by Luohuayu** [comment]
有没有考虑过是服务器网络问题

**Comment by Akita041** [comment]
你应该去神奇宝贝重铸官方反馈这个问题,这真的就是他这个模组的问题,纯forge端切换世界都掉线,单人测试没有说服力

**Comment by Yyiyun** [comment]
> 有没有考虑过是服务器网络问题

测试出来了是mod本身的问题 抱歉！

**Comment by Yyiyun** [comment]
> 你应该去神奇宝贝重铸官方反馈这个问题,这真的就是他这个模组的问题,纯forge端切换世界都掉线,单人测试没有说服力

对的 我今天测试了一天所有端发现就是mod本身的问题

**Comment by Kotori0629** [comment]
宝可梦问题
