### ISSUE TITLE
[1.12.2]LOW TPS  analysis 1

### ISSUE THREAD

**Issue by DarkCarlox** [Luohuayu/CatServer#467]
https://spark.lucko.me/Sxk5WPa9HO

**Comment by Luohuayu** [comment]
1. Modify spigot.yml `max-tick-time.world-settings.tile` and `max-tick-time.world-settings.entity` to below 20/15
2. Replace the CPU with a higher frequency (2.20GHz is too low)

**Comment by XionioXMaster** [comment]
You need a CPU with a good single thread as this game is mostly 1 thread based use this site https://www.cpubenchmark.net/singleThread.html
