### ISSUE TITLE
[1.16.5]与超能物质社区版不兼容

### ISSUE THREAD

**Issue by Nothingness-Void** [Luohuayu/CatServer#469]
如题-加入超能物质社区版后则服务器无法启动
错误报告如下
https://paste.fastmirror.net/?64a97220deb795b9#8jFc7xqi2ej7jLPFbfvBiGZ1xUmHi1xyzHbqC1LS4Xi9

**Comment by Luohuayu** [comment]
java.lang.NoClassDefFoundError: net/minecraft/client/renderer/color/IBlockColor
MOD调用了客户端的类, 请向MOD作者反馈
