### ISSUE TITLE
使用firstaid-1.6.12无法重生

### ISSUE THREAD

**Issue by nainiu233** [Luohuayu/CatServer#47]
使用firstaid-1.6.12后无法重生 客户端点击重生无反应 0血修复插件没有用
![image](https://user-images.githubusercontent.com/36364025/70857577-454e4180-1f2c-11ea-9ea8-06b86dec3efd.png)
在测试情况下 只是用firstaidMOD一样无法重生 使用sponge服务端可以正常重生
版本9fda405-async

**Comment by nainiu233** [comment]
使用了CatServer-6889a5f-universal.jar和CatServer-0da8be1-async.jar进行测试 发生了同样的问题在测试前已经保证删除了playerdata数据

**Comment by Luohuayu** [comment]
服务端无法兼容该MOD,如需解决请QQ或TG私聊
