### ISSUE TITLE
[1.16.5] 宝可梦模组问题

### ISSUE THREAD

**Issue by Hikari0964** [Luohuayu/CatServer#470]
**运行环境**

Minecraft版本(1.12.2/1.16.5/1.18.2): 1.16.5
构建版本(从/version指令获取): 1.16.5-589d8617
相关模组/插件: Pixelmon

**描述这个BUG**
(如果有报错请附上pastebin链接或上传日志文件)
https://pastebin.com/PFkL9NqR
**导致的问题r**

**复现方法**
加载9.0.1版本的宝可梦模组即为复现
**截图/视频**
(如果没有可以忽略)

**Comment by Luohuayu** [comment]
宝可梦MOD本身问题
