### ISSUE TITLE
[1.16.5] 创世神无法使用 和 多世界报错

### ISSUE THREAD

**Issue by zfms4188** [Luohuayu/CatServer#471]
**运行环境**

Minecraft版本(1.12.2/1.16.5/1.18.2):  1.16.5
构建版本(从/version指令获取): 1.16.5-589d8617
相关模组/插件: FastAsyncWorldEdit (使用Java17)  / Multiverse-Core v4.3.1

**描述这个BUG**
(如果有报错请附上pastebin链接或上传日志文件)

创世神 加载时和使用中报错 无法正常使用 无法使用木斧选择点
多世界加载时会有报错,但不影响使用.

创世神:
加载: https://pastebin.com/peqckKdT
加入服务器: https://pastebin.com/y3WhxdwW
使用指令: https://pastebin.com/ahVfBcmx

多世界加载报错: https://pastebin.com/EYXEG2Nv

**导致的问题r**
无法正常使用

**复现方法**
插件下载地址: https://ci.athion.net/job/FastAsyncWorldEdit/
**截图/视频**
(如果没有可以忽略)

**Comment by Luohuayu** [comment]
不支持FastAsyncWorldEdit
请使用WorldEdit
