### ISSUE TITLE
[1.16.5] 保存区块错误

### ISSUE THREAD

**Issue by zfms4188** [Luohuayu/CatServer#475]
**运行环境**

Minecraft版本(1.12.2/1.16.5/1.18.2): 1.16.5
构建版本(从/version指令获取): 589d8617
相关模组/插件: 

**描述这个BUG**
(如果有报错请附上pastebin链接或上传日志文件)
https://pastebin.com/5xkWwZkp
卸载世界保存区块报错 有时还会崩溃
(已尝试去除所有插件,依旧报错)
**导致的问题r**
报错 服务器卡顿 崩溃
**复现方法**

**截图/视频**
(如果没有可以忽略)

**Comment by zfms4188** [comment]
进过逐步排查测试 是 RoadRunner MOD的问题
删除后没有再出现报错
https://www.mcmod.cn/class/4852.html

**Comment by Kotori0629** [comment]
尽可能不要在服务端中添加优化mod, 它们并不适合混合服务端, 它们可能会影响到craftbukkit/spigot的正常工作
