### ISSUE TITLE
[1.16.5] 跨服皮肤兼容问题

### ISSUE THREAD

**Issue by zfms4188** [Luohuayu/CatServer#481]
**运行环境**

Minecraft版本(1.12.2/1.16.5/1.18.2): 1.16.5
构建版本(从/version指令获取): 589d8617
相关模组/插件: 高清修复 跨服核心

**描述这个BUG**
 跨服导致玩家2D/3D皮肤无法显示,变成光溜溜的没有2D/3D皮肤层
 从BC进入大厅时没有这个问题，从大厅传送到子服或反之,皆会出现上面的问题
(打开高清修复的自定义皮肤选项重新加载皮肤,才可以正常显示,但若跨服,又会出现上面的问题)

**导致的问题r**
 跨服导致玩家2D/3D皮肤无法显示

**复现方法**

**截图/视频**
(如果没有可以忽略)
从BC进入大厅 正常
![Minecraft_ 1 16 5 - 多人游戏（第三方服务器） 2022_6_13 7_59_34](https://user-images.githubusercontent.com/86733104/173259049-1d9529f4-166b-4f43-8bfa-53fb2fed6e20.png)

从大厅跨服
![Minecraft_ 1 16 5 - 多人游戏（第三方服务器） 2022_6_13 8_06_11](https://user-images.githubusercontent.com/86733104/173259131-ab1e7f55-b971-4f58-bc3c-e63807e462d1.png)

**Comment by Kotori0629** [comment]
没懂，Spigot/Paper会复现这个问题吗

**Comment by zfms4188** [comment]
> 没懂，Spigot/Paper会复现这个问题吗

(跨服前,我角色是有头发的辫子的,跨服后,没有了)
没有这个问题 纯净端

**Comment by Kotori0629** [comment]
> > 没懂，Spigot/Paper会复现这个问题吗
> 
> (跨服前,我角色是有头发的辫子的,跨服后,没有了) 没有这个问题 纯净端

其他同类型的服务端会复现吗 （Forge+Bukkit）

**Comment by zfms4188** [comment]
刚刚测试,螺端也有该问题  (猫端和螺端测试环境皆为客户端仅有lightfallclient和自定义皮肤mod还有高清修复;服务端未装任何mod)

**Comment by Kotori0629** [comment]
> 

我认为你应该向高清修复/Lightfall发起issues

**Comment by Luohuayu** [comment]
跨服方案由lightfall提供, 这边无法解决, 请反馈lightfall
