### ISSUE TITLE
[1.16.5] watchdog报错 随时能提供相关信息

### ISSUE THREAD

**Issue by mcmso** [Luohuayu/CatServer#482]
**运行环境**

Minecraft版本(1.12.2/1.16.5/1.18.2): 1.16
构建版本(从/version指令获取): CatServer-1.16.5-589d8617-server.jar
相关模组/插件: 

**描述这个BUG**https://paste.ubuntu.com/p/SWsvtycTjP/
(如果有报错请附上pastebin链接或上传日志文件)

**导致的问题r** 服务器突然崩掉
     需要什么信息我最快速度提供
**复现方法**开一段时间服务器就崩了

**截图/视频**
(如果没有可以忽略)

**Comment by mcmso** [comment]
刚才的是log 
这个是crash-reports    https://paste.ubuntu.com/p/fMsk3SRzSC/

**Comment by Kotori0629** [comment]
因长期未回复而被关闭, 如有再次发生, 请更新至最新版本后提交更多完整异常信息
