### ISSUE TITLE
[1.16.5]使用Ensorcellation mod的灵魂绑定附魔时，附魔的装备在死亡后会直接消失

### ISSUE THREAD

**Issue by haiweixi** [Luohuayu/CatServer#483]
**运行环境**

Minecraft版本(1.12.2/1.16.5/1.18.2): 1.16.5
构建版本(从/version指令获取): This server is running CatServer version 1.16.5-66a81f36 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT, Forge version 36.2.35)
相关模组/插件: Ensorcellation-1.5.0.4（前置cofh-core-1.5.0.11）

**描述这个BUG**
(如果有报错请附上pastebin链接或上传日志文件)
灵魂绑定(soulbound)附魔无法正常生效
**导致的问题**
附魔了灵魂绑定的装备会在死亡后直接消失
**复现方法**
将装备附魔灵魂绑定
1、创造模式下直接/kill死亡，装备消失
2、生存模式下摔落死亡，装备消失
**截图/视频**
(如果没有可以忽略)

**Comment by Kotori0629** [comment]
Duplicate of #454

**Comment by Luohuayu** [comment]
与 #454 重复, 待修复
