### ISSUE TITLE
[1.16.5] 多世界卸载世界时ae2导致服务器崩溃

### ISSUE THREAD

**Issue by zfms4188** [Luohuayu/CatServer#485]
**运行环境**

Minecraft版本(1.12.2/1.16.5/1.18.2): 1.16.5
构建版本(从/version指令获取): 66a81f36
相关模组/插件: Multiverse-Core-4.3.2

**描述这个BUG**
(如果有报错请附上pastebin链接或上传日志文件)
崩溃日志:https://pastebin.com/bhXG3rK2
后台:https://pastebin.com/CqtJAsEB

**导致的问题r**
执行 mv多世界插件的卸载功能时 服务器崩溃 且卸载失败

**复现方法**
mv unload 世界ID

**截图/视频**
(如果没有可以忽略)

**Comment by Kotori0629** [comment]
附一下应用能源

**Comment by zfms4188** [comment]
> 附一下应用能源

https://www.curseforge.com/minecraft/mc-mods/applied-energistics-2/files/3608871

**Comment by zfms4188** [comment]
https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/b45c590639a0ed0e6dd2cd60a3263b4546cd53c5/src/main/java/appeng/hooks/ticking/TickHandler.java#L366
群里大伙儿讨论的 dalao瞅瞅喃
