### ISSUE TITLE
[1.16.5] 玩家进入后崩溃

### ISSUE THREAD

**Issue by mcmso** [Luohuayu/CatServer#487]
**运行环境**

Minecraft版本(1.12.2/1.16.5/1.18.2): 
构建版本(从/version指令获取): CatServer-1.16.5-589d8617-server.jar
相关模组/插件:  

**描述这个BUG**玩家进入后崩溃
(如果有报错请附上pastebin链接或上传日志文件)
log https://paste.ubuntu.com/p/xjGkt2VGxG/
debug https://paste.ubuntu.com/p/h5TChJyhxk/
**导致的问题r**
导致服务器崩溃
**复现方法**
玩家进入服务器
**截图/视频**
(如果没有可以忽略)

**Comment by Big-Cake-jpg** [comment]
？

你要开这么多issue干什么？

**Comment by mcmso** [comment]
> ？
> 
> 你要开这么多issue干什么？

问题原因应该是不一样的

**Comment by Kotori0629** [comment]
因长期未回复而被关闭, 如有再次发生, 请更新至最新版本后提交更多完整异常信息
