### ISSUE TITLE
[1.16.5] 服务器运行一段时间崩溃

### ISSUE THREAD

**Issue by mcmso** [Luohuayu/CatServer#493]
**运行环境**

Minecraft版本(1.12.2/1.16.5/1.18.2): 
构建版本(从/version指令获取): CatServer-1.16.5-589d8617-server.jar
相关模组/插件: 

**描述这个BUG**
(如果有报错请附上pastebin链接或上传日志文件)
https://paste.ubuntu.com/p/7zcqStmPnm/
**导致的问题r**
导致服务器崩溃
**复现方法**
开服
**截图/视频**
(如果没有可以忽略)

**Comment by Luohuayu** [comment]
CatServer没有getChunkBlocking这个方法 lithium使用mixin修改区块类导致的崩溃 请关闭相关优化选项或卸载该MOD
