### ISSUE TITLE
[1.12.2] 出现这个错误集体玩家掉线

### ISSUE THREAD

**Issue by yuankun1** [Luohuayu/CatServer#495]
**运行环境**

Minecraft version（1.12.2/1.16.5/1.18.2）： 1.12.2
Build version（Get from /version command）：
Mods/Plugins： CatServer-6eb82ffe-universal / Pixelmon-1.12.2-8.4.2-server
插件列表：https://pastebin.com/YWn2LKWU

错误报告
https://pastebin.com/UkDUg5dE
[log记录.log](https://github.com/Luohuayu/CatServer/files/8942440/log.log)

**Comment by Luohuayu** [comment]
玄学问题
请检查内存是否足够 是否长时间选中控制台

**Comment by yuankun1** [comment]
> 玄学问题 请检查内存是否足够 是否长时间选中控制台

内存应该是足够的 
毕竟之前我开服20左右在线也不会卡顿
主要是我现在全部tps都是19 然后偶然会出现一片红 没隔一段时间就一片红 但是tps依旧是19

**Comment by yuankun1** [comment]
![QQ图片20220623030452](https://user-images.githubusercontent.com/19505154/175116531-da3936f6-bd48-48e0-80a2-9fb5aa95eff3.png)
不正常的时候
![QQ图片20220623030529](https://user-images.githubusercontent.com/19505154/175116636-e064a55e-cef9-4151-a25c-96197b067a39.png)
tps正常的时候同样的是4 ~5人在线

**Comment by Luohuayu** [comment]
检查是否是内存问题
