### ISSUE TITLE
[1.16.5] 使用trmenu检测玩家背包物品时报错

### ISSUE THREAD

**Issue by McAZero** [Luohuayu/CatServer#496]
**Environment**

Minecraft version(1.12.2/1.16.5/1.18.2): 1.16.5
Build version(Get from /version command): CatServer-1.16.5-76952803-server
Mods/Plugins: TrMenu-3.1.12

**Describe the bug**
(If there is an error, please attach the pastebin link)
报错：https://paste.ubuntu.com/p/zGz5x977MF/
菜单：https://paste.ubuntu.com/p/g66HnXGzd3/

**Expected behavior**
无法判断玩家背包是否有要求的物品
**To Reproduce**
使用点击菜单图标时报错，在 paper-1.16.5-794 上使用正常
**Screenshot/Video**
(If it doesn't exist you can ignore it)

**Comment by Kotori0629** [comment]
发我一份测试用菜单，只要能触发报错就可以，QQ发我

**Comment by McAZero** [comment]
> 发我一份测试用菜单，只要能触发报错就可以，QQ发我

此BUG在最新版本的插件和服务端依然存在，我已QQ发给你很久了。

菜单：https://paste.ubuntu.com/p/DqNrFhWGyT/

**Comment by Kotori0629** [comment]
![image](https://user-images.githubusercontent.com/81866089/196430525-559de5c2-d3b9-4bc9-a5ae-e29d0df8d742.png)
哪儿报错了

**Comment by Kotori0629** [comment]
![image](https://user-images.githubusercontent.com/81866089/196430994-95174416-a43d-4890-be0c-fdaa9d49661f.png)
TrMenu版本：https://github.com/TrPlugins/TrMenu/actions/runs/3082840832

**Comment by Kotori0629** [comment]
![image](https://user-images.githubusercontent.com/81866089/196432330-8032ff53-f3e2-4e4f-b54d-69b0f20137af.png)

甚至加上了take-item，它依旧没有报错

**Comment by McAZero** [comment]
> ![image](https://user-images.githubusercontent.com/81866089/196432330-8032ff53-f3e2-4e4f-b54d-69b0f20137af.png)
> 
> 甚至加上了take-item，它依旧没有报错

经过测试在Windows10上不会出现，在Linux系统上运行会有。
我服务器是Ubuntu 20.04.5

**Comment by McAZero** [comment]
演示：https://www.bilibili.com/video/BV1LP411N7SB/

我先zzzzzzzzz了，等审核

**Comment by Kotori0629** [comment]
![image](https://user-images.githubusercontent.com/81866089/196597165-e35cb0b5-a5a2-4152-ac6e-642c9b45dfe2.png)
于Ubuntu18.04依旧无法复现

**Comment by Kotori0629** [comment]
![image](https://user-images.githubusercontent.com/81866089/196597269-e7da1ce7-01c0-4bdc-b683-f79066f287e4.png)

**Comment by Kotori0629** [comment]
于CentOS8/Ubuntu18.04/Debian11/Deepin20.7.1进行了测试，并没有复现你描述的问题

建议移除核心libraries依赖库后重新下载, 并通过FoxLaunch库文件检查后重新运行
有相关开发能力的话, 分支一个CatServer1.16.5后, 在运行时使用类加载器单独加载 `org.openjdk.nashorn.internal.runtime.Context$AnonymousContextCodeInstaller`

参考： https://github.com/Luohuayu/CatServer/blob/1.16.5/src/fmllauncher/java/foxlaunch/FoxServerLauncher.java#L26
这不会是一个好办法, 也未经过相关测试, 这可能并不会解决你的问题

**Comment by McAZero** [comment]
> 于CentOS8/Ubuntu18.04/Debian11/Deepin20.7.1进行了测试，并没有复现你描述的问题
> 
> 建议移除核心libraries依赖库后重新下载, 并通过FoxLaunch库文件检查后重新运行 有相关开发能力的话, 分支一个CatServer1.16.5后, 在运行时使用类加载器单独加载 `org.openjdk.nashorn.internal.runtime.Context$AnonymousContextCodeInstaller`
> 
> 参考： https://github.com/Luohuayu/CatServer/blob/1.16.5/src/fmllauncher/java/foxlaunch/FoxServerLauncher.java#L26 这不会是一个好办法, 也未经过相关测试, 这可能并不会解决你的问题

奇怪的是，他们是同一个文件夹，Windows10上是使用网络驱动器连接到Ubuntu文件夹的，不太可能是依赖库的问题。手上机器不多，刚刚又在CentOS-7.6.1810-x64上测试依然会报错就很奇怪。（依赖库是重新下载的
![27`MANAV8(THL0SDR5G2 MP](https://user-images.githubusercontent.com/52328924/197365772-5675109a-39d0-4225-b530-d553b5d5ddbf.png)
