### ISSUE TITLE
[1.16.5] CatServer热加载插件，出现 找不到主类 报错

### ISSUE THREAD

**Issue by YuaZer** [Luohuayu/CatServer#497]
**运行环境**

Minecraft版本1.16.5: 
构建版本(从/version指令获取): 
This server is running CatServer version 1.16.5-a2ea5769 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT, Forge version 36.2.35)
相关模组/插件: PixelmonReforged 9.0.1(宝可梦重铸)

**描述这个BUG**
在重启后第一次热加载插件时不会有该问题，但第二次及之后对同一个插件进行卸载加载时就会出现 找不到主类 报错

**导致的问题**
插件无法进行热加载
**复现方法**
/plugin load 插件
**截图/视频**
![KZ2RERZBTV`WNTJ{`LF2E B](https://user-images.githubusercontent.com/56108426/175243358-d5fe220f-e7c1-4906-bfd6-a629cff20366.jpg)
![S$NX%DC4D _M(O` P$C CSN](https://user-images.githubusercontent.com/56108426/175243398-0958f825-476e-4fc0-b3a0-f64df05968f8.jpg)

**Comment by YuaZer** [comment]
> 可能跟此问题有关，但是spigot端确实没问题https://hub.spigotmc.org/jira/browse/SPIGOT-5849 ![2GKOYGVHQ6OBG9IL(X8W~55](https://user-images.githubusercontent.com/9004849/176004676-0c094f84-6e51-4c88-8640-6172527aada6.png)

老哥我这是插件加载问题，和雨停不下来有什么关系？

**Comment by Kotori0629** [comment]
经测试并未发现等同问题
