### ISSUE TITLE
[1.12.2] 玩家打开合成台服务器崩溃

### ISSUE THREAD

**Issue by 849025143** [Luohuayu/CatServer#498]
**运行环境**
debian系统
有其他服主说可能跟服务器核心有关，所以就来反馈了。

Minecraft版本(1.12.2/1.16.5/1.18.2): 
构建版本(从/version指令获取): 
相关模组/插件:  1.12.2 AE模组+原版工作台

**描述这个BUG**
(如果有报错请附上pastebin链接或上传日志文件)
https://pastebin.com/hZ5Yz8rX

**导致的问题r**
服务器崩溃

**复现方法**
暂未发现,就是工作台的合成书或者AE的合成面板

**截图/视频**
(如果没有可以忽略)

**Comment by Luohuayu** [comment]
AnotherCommonBugFix 安装了哪些修复包

**Comment by 849025143** [comment]
AE2Transform
ForgeTransform
IC2Transform
TConstructTransform

应该不是这个的问题，我有个宝可梦也是这样。
但是另一个用了远古版本的服主不会有这个问题蹦服。
核心 version.json里的时间是这个：
  "id": "1.12.2-CatServer5d66f2e",
  "time": "2021-12-12T03:00:37+0800",

**Comment by Luohuayu** [comment]
> AE2Transform ForgeTransform IC2Transform TConstructTransform
> 
> 应该不是这个的问题，我有个宝可梦也是这样。 但是另一个用了远古版本的服主不会有这个问题蹦服。 核心 version.json里的时间是这个： "id": "1.12.2-CatServer5d66f2e", "time": "2021-12-12T03:00:37+0800",

尝试删除ForgeTransform
