### ISSUE TITLE
[1.16.5] 桶装液体可无视放置权限在任意位置处放置

### ISSUE THREAD

**Issue by Akita041** [Luohuayu/CatServer#500]
Minecraft版本1.16.5:
构建版本(从/version指令获取):
This server is running CatServer version 1.16.5-0a19868d (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT, Forge version 36.2.35)

相关插件: 
NoBuildPlus-1.1.2
插件地址:https://www.spigotmc.org/resources/nobuildplus.101815/
PlotSquaredV4或V5:
插件地址:
https://www.spigotmc.org/resources/plotsquared-v4-v6-out-now.1177/

相关模组:无服务端模组.

BUG描述:
桶可以在插件禁止建造或者修改的区域放置液体.
例如:水桶可以在地皮的道路上放置水,岩浆桶可以在地皮的道路上放置岩浆,在NoBulidPlus设置禁止建造的世界也可以随意放置水或者岩浆,但是这些问题在Spigot核心中并不会出现.

复现方法:手拿装有水或者岩浆的桶,直接右键即可在不被允许建筑的地方放置水或者岩浆.

问题猜测: 可能是因为forge的加入,导致对于流体的处理顺序产生了影响,将“右键物品”或者“右键方块”这些事件的处理放在了“使用桶”这个事件之后,希望大佬有办法修复.

截图:
https://i-s2.328888.xyz/2022/06/25/62b71c1fe3077.png

**Comment by Kotori0629** [comment]
等待PR合并后更新核心即修复，完结工单，已修复
