### ISSUE TITLE
[1.12.2] Broken Linux terminal

### ISSUE THREAD

**Issue by Weylend** [Luohuayu/CatServer#503]
**Environment**

Minecraft version(1.12.2/1.16.5/1.18.2): 1.12.2
Build version(Get from /version command):  CatServer-1.12.2-6eb82ffe
Mods/Plugins: 

**Describe the bug**

When starting the server in the usual way on Debian 11 with adoptopenjdk 8, with this start script:

```
java -Xmx8096M -Xms8096M -XX:+UseG1GC -XX:MaxGCPauseMillis=50 -XX:+AggressiveOpts -jar CatServer.jar nogui 
```

I can only enter commands in console.
BACKSPACE or UP/DOWN buttons does not work. These characters appear instead:

```tp ^H^H^H^[[D^[[B```

I tried other SSH clients: putty xshell and termius - no changes.

**Expected behavior**

**To Reproduce**

**Screenshot/Video**
(If it doesn't exist you can ignore it)

**Comment by Weylend** [comment]
I have tried magma 1.12.2 and mohist and it works fine for them

**Comment by Luohuayu** [comment]
Have you tried the Forge server?
