### ISSUE TITLE
[1.16.5] 末地设置边界重启后无效

### ISSUE THREAD

**Issue by Yyiyun** [Luohuayu/CatServer#505]
**运行环境**

Minecraft版本(1.12.2/1.16.5/1.18.2): 1.16.5
构建版本(从/version指令获取): 
This server is running CatServer version 1.16.5-2a495504 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT, Forge version 36.2.35)
相关模组/插件: 
Multiverse-Core-4.3.1
PlotSquared-Bukkit-5.13.12
worldedit-bukkit-7.2.10

**描述这个BUG**
(如果有报错请附上pastebin链接或上传日志文件)
当在末地设立边界后/minecraft:worldborder set 20000重启后失效恢复为默认边界。
**导致的问题**
每次重启都得重新设置边界
**复现方法**
当在末地设立边界后/minecraft:worldborder set 20000重启后失效恢复为默认边界。
**截图/视频**
(如果没有可以忽略)

**Comment by Luohuayu** [comment]
因1.16.5的Forge和Bukkit使用不同的存档保存方式, 此为正常现象:
原版和MOD世界按照Forge的保存方式 (所有世界一致)
Bukkit世界按照Bukkit的保存方式 (每个世界可独立)

**Comment by Yyiyun** [comment]
> 因1.16.5的Forge和Bukkit使用不同的存档保存方式, 此为正常现象: 原版和MOD世界按照Forge的保存方式 (所有世界一致) Bukkit世界按照Bukkit的保存方式 (每个世界可独立)

好的 谢谢
