### ISSUE TITLE
[1.16.5] 删除mod之后不断刷屏未知结构 直至timeout

### ISSUE THREAD

**Issue by mcmso** [Luohuayu/CatServer#511]
**运行环境**

Minecraft版本(1.12.2/1.16.5/1.18.2): 
构建版本(从/version指令获取): CatServer-1.16.5-589d8617-server
相关模组/插件: 

**描述这个BUG**
删除mod之后不断刷屏未知结构 直至timeout
https://paste.ubuntu.com/p/7GP2xjVX7k/
(如果有报错请附上pastebin链接或上传日志文件)

**导致的问题**
导致服务器崩溃
**复现方法**

**截图/视频**
(如果没有可以忽略)

**Comment by Kotori0629** [comment]
em 我该怎么回复呢，你安装过这么两个mod，他们以自己的名义生成了结构，现在你删除了这两个mod，mod是删除了，但是地图中已经生成的结构还存在，你应该使用某些地图编辑工具去操作level.dat，删除已经删除的mod生成的结构

**Comment by mcmso** [comment]
> 我该怎么回复你安装过这两个mod，他们以自己的还存在的结构呢，结构，现在你删除了这两个mod，是删除了，但是你应该已经把地图中的生成的使用某些地图编辑工具去操作level.dat，删除已经删除的mod生成的结构

了解  
这边已经重新生成地图解决了
![3LTWNWNU_7)CTCO}9IHG`$8](https://user-images.githubusercontent.com/46519955/176914451-951b9155-f499-45e6-aed1-2e36110b9a4c.png)
但是forge写的是早就修了 所以我很迷惑

**Comment by Kotori0629** [comment]
我去追一下看看
