### ISSUE TITLE
[1.16.5] 不兼容valhelsia-structures

### ISSUE THREAD

**Issue by PoseidonLi0514** [Luohuayu/CatServer#513]
**运行环境**
windows11, java16 (经过测试11也不行)
Minecraft版本(1.12.2/1.16.5/1.18.2): 1.16.5
构建版本(从/version指令获取): This server is running CatServer version 1.16.5-c511165d (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT, Forge version 36.2.35)
相关模组/插件: 仅安装此模组及其前置，加载时崩溃，不涉及到插件
**描述这个BUG**
(如果有报错请附上pastebin链接或上传日志文件)
加载时mixin冲突
https://pastebin.ubuntu.com/p/rGts9Bm2Vm/
**导致的问题r**
玩家需要此模组的装饰物品
**复现方法**
服务端装此模组
**截图/视频**
(如果没有可以忽略)

**Comment by Kotori0629** [comment]
五个小时前修复了, 前往构建站下载最新版本
