### ISSUE TITLE
[1.16.5] 使用CMI自带的合成配方无法使用

### ISSUE THREAD

**Issue by fengyoun** [Luohuayu/CatServer#517]
**运行环境**
JAVA16
Minecraft版本(1.12.2/1.16.5/1.18.2): 1.16.5
构建版本(从/version指令获取): CatServer-1.16.5-876dc9aa-server
相关模组/插件: CMI插件

**描述这个BUG**
(如果有报错请附上pastebin链接或上传日志文件)
https://pastebin.ubuntu.com/p/Cdj3Zy7Jpr/
**导致的问题r**
输入/cmi customrecipe添加合成点击保存会出现报错并且未能使用
**复现方法**
输入/cmi customrecipe添加合成点击保存会出现报错并且未能使用
**截图/视频**
(如果没有可以忽略)

https://user-images.githubusercontent.com/103408725/177537041-264c7be1-0dc1-4798-aca7-8bf90172ab3b.mp4

**Comment by fengyoun** [comment]
插件版本
CMI9.2.1.1
CMILib1.2.1.1

**Comment by Luohuayu** [comment]
暂不支持插件修改合成表, 后续更新可能会支持

**Comment by Kotori0629** [comment]
用最新版本看看
