### ISSUE TITLE
[1.16.5] watchdog报错

### ISSUE THREAD

**Issue by mcmso** [Luohuayu/CatServer#518]
运行环境

Minecraft版本(1.12.2/1.16.5/1.18.2):
构建版本(从/version指令获取): CatServer-1.16.5-589d8617-server.jar
相关模组/插件:
已关闭roadrunner关于chunk的全部选项

描述这个BUG 玩家玩了一段时间 崩服       (如果有报错请附上pastebin链接或上传日志文件)

[debug https://paste.ubuntu.com/p/vMdfDM4TXN/](https://paste.ubuntu.com/p/W8wJRwcTPH/)
导致的问题
导致服务器崩溃
复现方法

截图/视频
(如果没有可以忽略)

**Comment by Luohuayu** [comment]
请勿添加任何称"优化"/"调优"等mod, 例如元素周期表
