### ISSUE TITLE
[1.16.5] 与MOD questsadditions不兼容

### ISSUE THREAD

**Issue by SkyIce0229** [Luohuayu/CatServer#519]
**运行环境**

Minecraft版本(1.12.2/1.16.5/1.18.2): 1.16.5
构建版本(从/version指令获取):  1.16.5-0e99d029
相关模组/插件: questsadditions

**描述这个BUG**
https://paste.ubuntu.com/p/rDb2N8fHGx/

**导致的问题r**
服务器世界构建完后就崩溃

**复现方法**
使用Ultimate Progression整合包
下载地址：https://www.curseforge.com/minecraft/modpacks/ultimate-progression

**Comment by Kotori0629** [comment]
请单独整理出问题模组的前置/本体

**Comment by SkyIce0229** [comment]
经过测试questsadditions 这个mod将导致服务器无法启动，其前置是Architectury API和 FTB Quests

**Comment by Kotori0629** [comment]
> 经过测试questsadditions 这个mod将导致服务器无法启动，其前置是Architectury API和 FTB Quests

打包一下..

**Comment by SkyIce0229** [comment]
这是我用来测试的服务器包：https://www.aliyundrive.com/s/ELSZwTyT3xm

**Comment by Kotori0629** [comment]
> 这是我用来测试的服务器包：https://www.aliyundrive.com/s/ELSZwTyT3xm

... 你把他的前置 还有他的本体mod 拿出来啊... 开发测试 这么些多mod 要测试到啥时候

**Comment by SkyIce0229** [comment]
拿出来了，阿里云这个连接的就是拿出来的

**Comment by SkyIce0229** [comment]
[mods.zip](https://github.com/Luohuayu/CatServer/files/9092821/mods.zip)
不好意思，我理解错了

**Comment by SkyIce0229** [comment]
https://paste.ubuntu.com/p/QQ8bQ2wkPY/
还是这个问题
