### ISSUE TITLE
 Server cannot start

### ISSUE THREAD

**Issue by fantahund** [Luohuayu/CatServer#52]
i use the last Catserver Build.

Modpack: https://www.curseforge.com/minecraft/modpacks/enigmatica2

Logs: 
[debug.log](https://github.com/Luohuayu/CatServer/files/3991244/debug.log)
[latest.log](https://github.com/Luohuayu/CatServer/files/3991245/latest.log)

**Comment by Luohuayu** [comment]
Modpack can only be used for vanilla or specific server. Please report to the modpack author.
