### ISSUE TITLE
[1.16.5] 宝可梦模组错误

### ISSUE THREAD

**Issue by TUCAOEVER** [Luohuayu/CatServer#522]
**运行环境**
CatServer version 1.16.5-0e99d029 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT, Forge version 36.2.35)

Minecraft版本(1.12.2/1.16.5/1.18.2): 
构建版本(从/version指令获取): 
相关模组/插件: 
pixelmon

**描述这个BUG**
https://pastebin.com/J8WPXyeh

**导致的问题r**
暂未发现

**复现方法**

**截图/视频**
(如果没有可以忽略)

**Comment by Luohuayu** [comment]
MOD自身问题, 请反馈MOD作者

**Comment by TUCAOEVER** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
