### ISSUE TITLE
[1.12.2] 潜影盒无法被活塞推动

### ISSUE THREAD

**Issue by scientificworld** [Luohuayu/CatServer#523]
**运行环境**

Minecraft版本(1.12.2/1.16.5/1.18.2): 1.12.2
构建版本(从/version指令获取): CatServer-1.12.2-6eb82ffe (Forge 14.23.5.2860)
相关模组/插件: 
模组：暮色森林（在主世界和暮色森林中出现该问题，其余维度尚未测试）
插件：ShulkerDupe（但移除该插件后问题仍存在）

**描述这个BUG**
服务器上潜影盒无法被激活的活塞推动，在本地存档测试无此问题，可以正常被推动并掉落潜影盒。

**导致的问题**
无法制造某些机器

**复现方法**
使用活塞推动潜影盒

**截图/视频**
无

**Comment by Luohuayu** [comment]
https://github.com/Luohuayu/CatServer/commit/7a564d999743ce0c52922e7e321dd917a56683b9
跟这个有关, 打算加个选项

**Comment by Luohuayu** [comment]
关闭preventPistonPushTileEntity选项即可 (注意防止玩家用活塞刷物品和崩服)

**Comment by scientificworld** [comment]
> 关闭preventPistonPushTileEntity选项即可 (注意防止玩家用活塞刷物品和崩服)

好的，感谢
