### ISSUE TITLE
[1.16.5] 宝可梦导致的线程崩溃

### ISSUE THREAD

**Issue by Redfire-of** [Luohuayu/CatServer#524]
**运行环境**

Minecraft版本(1.12.2/1.16.5/1.18.2): 1.16.5
构建版本(从/version指令获取): CatServer version 1.16.5-0a19868d (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT, Forge version 36.2.35)
相关模组/插件: pixelmon

**描述这个BUG**
https://pastebin.com/wtYgw6qq

**导致的问题r**
暂未发现

**复现方法**
暂未发现

**截图/视频**
无

**Comment by Luohuayu** [comment]
使用最新版本, Watchdog增加了更多异常信息

**Comment by Kotori0629** [comment]
因长期未回复而被关闭, 如有再次发生, 请根据开发者所述更新至最新版本后提交更多完整异常信息
