### ISSUE TITLE
我都没有关注你，你为什么盗我号给你自己点Star？

### ISSUE THREAD

**Issue by 0x8235** [Luohuayu/CatServer#526]
# 小偷！

**Comment by Kotori0629** [comment]
不知道你说的什么情况，但是与问题无关。所以被关闭。因诽谤被锁定话题

**Comment by Luohuayu** [comment]
我们没必要盗你号点Star啊, 你这是被扫号了吧, 建议开2FA验证
![Screenshot_20220717-161201_Via](https://user-images.githubusercontent.com/29095770/179389807-7ace134c-7c24-4042-b820-73bd6f0f915a.jpg)
