### ISSUE TITLE
If you NEED any star, you can ASK me nicely to give, but thou shalt not steal!

### ISSUE THREAD

**Issue by HisStar** [Luohuayu/CatServer#529]
# DO NOT STEAL ME ACCOUNT TO STAR YOUR PROJECT! IT'S A CRIME.

**Comment by Big-Cake-jpg** [comment]
？
怎么又来一个自称账号被作者盗去star的
甚至语法还是错的

**Comment by IAm20cm** [comment]
@CodeCMD @Big-Cake-jpg 你也被盗了？批量安全事件？

**Comment by Big-Cake-jpg** [comment]
> @CodeCMD @Big-Cake-jpg 你也被盗了？批量安全事件？
> 
> 

我没被盗，号还在我手上
给这个项目点star是我自愿的，并非我的号被盗

**Comment by Kotori0629** [comment]
不是第一回了, 上一次也有人发了个issues说被盗号然后来点star了。 目前不太清楚啥情况, 不过有关注到部分交易平台上出售Github 星星。建议开启账号二次验证以保全账号安全性

**Comment by Luohuayu** [comment]
有人盗号给我们项目恶意刷星吧 建议开启2FA保障账号安全
