### ISSUE TITLE
你为什么盗我号给你自己点星星✨？

### ISSUE THREAD

**Issue by IAm20cm** [Luohuayu/CatServer#530]
我都没有关注你们啊，为什么会自动点上你们的星星？

**Comment by Big-Cake-jpg** [comment]
又来了

**Comment by Kotori0629** [comment]
不是第一回了, 上一次也有人发了个issues说被盗号然后来点star了。 目前不太清楚啥情况, 不过有关注到部分交易平台上出售Github 星星。建议开启账号二次验证以保全账号安全性
