### ISSUE TITLE
[1.12.2] 不支持 `StackUp` 修改最大堆叠数量的模组

### ISSUE THREAD

**Issue by Zhang-Wei-666** [Luohuayu/CatServer#531]
**运行环境**

Minecraft版本(1.12.2/1.16.5/1.18.2): 1.12.2
构建版本(从/version指令获取): CatServer-6eb82ffe
相关模组/插件: [StackUp](https://www.curseforge.com/minecraft/mc-mods/stackup)

**描述这个BUG**

修改最大数量无效果

**复现方法**

 - 下载模组 [StackUp](https://www.curseforge.com/minecraft/mc-mods/stackup) 放到 `mods` 文件夹 ( 服务端和客户端都要安装 )
 - 下载 [配置文件](https://github.com/Zhang-Wei-666/Issues/raw/master/CatServer/1/stackup.zip) 解压缩后放到 `config` 文件夹 ( 已修改堆叠数量为 1000 )

**Comment by Kotori0629** [comment]
用Bukkit插件去改

**Comment by Luohuayu** [comment]
无法支持, 该MOD只修改了Forge, 但Bukkit依然有限制
