### ISSUE TITLE
[1.12.2] ContentTweaker无法加载资源

### ISSUE THREAD

**Issue by hanbao233xD** [Luohuayu/CatServer#533]
**运行环境**
win10x64,openjdk8_322

Minecraft版本(1.12.2/1.16.5/1.18.2): 1.12.2
构建版本(从/version指令获取): release最新版(22.07.28)
相关模组/插件: ContentTweaker,ResourceLoader

**描述这个BUG**
ContentTweaker需要通过ResourceLoader加载自定义资源,但ResourceLoader在加载时会被服务端忽略( [Server thread/INFO]: Disabling mod resourceloader it is client side only. )

(如果有报错请附上pastebin链接或上传日志文件)
日志:
[latest.log](https://github.com/Luohuayu/CatServer/files/9216142/latest.log)

**导致的问题r**

**复现方法**

**截图/视频**
(如果没有可以忽略)

**Comment by Kotori0629** [comment]
SideOnly在1.13+有一个新名词 叫OnlyIn  
显示了client side only 表示Resourceloader并不是属于服务端该加载的

建议做法：移除服务端安装ContentTweaker, ResourceLoader. 仅在客户端安装
