### ISSUE TITLE
[1.12.2] RLCraft SimpleDifficulty mod does not work correctly when you die

### ISSUE THREAD

**Issue by kalirenegade** [Luohuayu/CatServer#536]
**Environment**
Windows 10 using official Java Minecraft

Minecraft version(1.12.2/1.16.5/1.18.2): 
1.12.2
Build version(Get from /version command): 
Mods/Plugins: latest version of cat server as of 1/19/22

**Describe the bug**
(If there is an error, please attach the pastebin link)

when using rlcraft with catserver the SimpleDifficulty mod does not work correctly when you die your thirst is suppose to reset back to full instead it stays at the previous level before death using 1.12.2 ( the mod being used is 
SimpleDifficulty-1.12.2-0.3.9.jar) https://www.curseforge.com/minecraft/mc-mods/simpledifficulty/files

**Expected behavior**
your thirst should reset after death. This works while using regular forge but not catserver
**To Reproduce**
Install the mod and run around thill your thirst meter goes down some and the die you will have the same thirst level when you respawn 
**Screenshot/Video**
(If it doesn't exist you can ignore it)

**Comment by Luohuayu** [comment]
Same reason for #204
