### ISSUE TITLE
[1.16.5] Mod FramedBlocks 会导致服务器崩溃

### ISSUE THREAD

**Issue by SkyIce0229** [Luohuayu/CatServer#539]
**运行环境**

Minecraft版本(1.12.2/1.16.5/1.18.2): 1.16.5
构建版本(从/version指令获取): CatServer version 1.16.5-caa59bdd
相关模组/插件: FramedBlocks

**描述这个BUG**
(如果有报错请附上pastebin链接或上传日志文件)
https://paste.ubuntu.com/p/QB4pC8436s/
**导致的问题r**
服务器崩溃
**复现方法**
放置该mod的方块后将其破坏即可崩服
**截图/视频**
(如果没有可以忽略)

**Comment by SkyIce0229** [comment]
[mods.zip](https://github.com/Luohuayu/CatServer/files/9243998/mods.zip)

**Comment by Luohuayu** [comment]
和 #458 重复
