### ISSUE TITLE
[1.12.2] mcmmo1.5.10 不兼容catserver

### ISSUE THREAD

**Issue by yuankun1** [Luohuayu/CatServer#547]
**运行环境**

Minecraft版本(1.12.2/1.16.5/1.18.2): 
构建版本(从/version指令获取): 
相关模组/插件: 
服务端cat最新版本
mcmmo 1.5.10-SNAPSHOT
**描述这个BUG**
(如果有报错请附上pastebin链接或上传日志文件)
[mommo的报错.txt](https://github.com/Luohuayu/CatServer/files/9302048/mommo.txt
**导致的问题r**
不清楚
**复现方法**
无
**截图/视频**
(如果没有可以忽略)

**Comment by Luohuayu** [comment]
开源版本没找到StringUtils.getExplicitConfigMaterialDataString这个方法
