### ISSUE TITLE
关于伪装插件与皮肤修复插件的问题

### ISSUE THREAD

**Issue by benr233** [Luohuayu/CatServer#55]
1.无法使用LibsDisguises对mm怪物进行伪装
两段报错：
  插件载入时：    
![QQ图片20191224214208](https://user-images.githubusercontent.com/16155181/71432377-39286800-2714-11ea-8a4f-eeff4e82b89e.png)
  生成怪物时：
    
![image](https://user-images.githubusercontent.com/16155181/71432387-45acc080-2714-11ea-9ece-0eee62074a3a.png)

插件与怪物配置均在同版本纯净核心测试过了，确定是可用的
2.使用盗版服务器皮肤修复插件后重新上线会自动进入到一个什么都没有的世界，该问题必现无报错

**Comment by Luohuayu** [comment]
1.Forge修改了实体注册,无法兼容LibsDisguises插件
2.请提供具体插件信息和下载地址

**Comment by benr233** [comment]
https://www.spigotmc.org/resources/myskin-1-8-1-15-1.52303/
复现流程：安装此插件后进入服务器内登出后再重新登录

**Comment by Luohuayu** [comment]
已测试,不存在该问题,皮肤也可以正常显示
