### ISSUE TITLE
[1.12.2] Server deadlocks on shutdown with LoliASM

### ISSUE THREAD

**Issue by Zilacon** [Luohuayu/CatServer#555]
As the title states if loliASM is on the server, shutting down deadlocks it, and the process needs to be killed for it to complete the shutdown.

With more testing it seems to do this when you enable the setting to disable forge's security manager.

**Comment by Kotori0629** [comment]
You may need to submit relevant log reports

**Comment by Luohuayu** [comment]
Don't use LoliASM, it conflicts with bukkit
