### ISSUE TITLE
[1.18.2] crash server Quark

### ISSUE THREAD

**Issue by MrJorman** [Luohuayu/CatServer#556]
**Environment**

Minecraft version(1.12.2/1.16.5/1.18.2): 1.18.2
Build version(Get from /version command): CatServer-1.18.2-1943dd22-server.jar
Mods/Plugins: Quark

**Describe the bug**
(If there is an error, please attach the pastebin link)

**Expected behavior**

**To Reproduce**

**Screenshot/Video**
(If it doesn't exist you can ignore it)
[crash-2022-08-15_12.48.08-server.txt](https://github.com/Luohuayu/CatServer/files/9336424/crash-2022-08-15_12.48.08-server.txt)

**Comment by Kotori0629** [comment]
![image](https://user-images.githubusercontent.com/81866089/184625957-1d539b82-f490-4211-a8eb-48716cf6de55.png)
Fixed
