### ISSUE TITLE
[1.18.2] The server is not starting.

### ISSUE THREAD

**Issue by MrJorman** [Luohuayu/CatServer#557]
**Environment**

Minecraft version(1.12.2/1.16.5/1.18.2): 1.18.2
Build version(Get from /version command): CatServer-1.18.2-1943dd22-server.jar
Mods/Plugins: see log

**Describe the bug**
(If there is an error, please attach the pastebin link)

**Expected behavior**

**To Reproduce**

**Screenshot/Video**
(If it doesn't exist you can ignore it)
[latest.log](https://github.com/Luohuayu/CatServer/files/9338558/latest.log)

**Comment by Kotori0629** [comment]
Do you know how to reproduce this problem？

**Comment by MrJorman** [comment]
install all Yungs Mods.

**Comment by MrJorman** [comment]
As I understand it, it cannot generate a map, look at the server log completely, there are many different errors.

**Comment by MrJorman** [comment]
Failed to create mob or install Alex's Mobs.

**Comment by MrJorman** [comment]
https://www.curseforge.com/minecraft/mc-mods/alexs-mobs
https://www.curseforge.com/members/yungnickyoung/projects

**Comment by Kotori0629** [comment]
I'll check and fix asap

**Comment by MrJorman** [comment]
okay, thank!

**Comment by Kotori0629** [comment]
Can you pack it and send it to me? Just need mods

**Comment by MrJorman** [comment]
sec

**Comment by Kotori0629** [comment]
I installed AlexMobs, but the server didn't crash

**Comment by MrJorman** [comment]
https://drive.google.com/file/d/1thOI5zyugkiT9l0_i96ikVKJCBuz3IRW/view?usp=sharing

**Comment by MrJorman** [comment]
maybe mod: idas

**Comment by MrJorman** [comment]
[crash-2022-08-15_21.55.52-server.txt](https://github.com/Luohuayu/CatServer/files/9339237/crash-2022-08-15_21.55.52-server.txt)
new crash

**Comment by Kotori0629** [comment]
![image](https://user-images.githubusercontent.com/81866089/184698320-ddee79ee-9ae7-4367-9ae6-6f39bfa703ea.png)
Hm, I still not crash

**Comment by MrJorman** [comment]
waaaaat

**Comment by MrJorman** [comment]
i use BellSoft java 17, good?

**Comment by MrJorman** [comment]
"C:\Program Files\BellSoft\LibericaJDK-17-Full\bin\java"

**Comment by Kotori0629** [comment]
> i use BellSoft java 17, good?

probably irrelevant

**Comment by MrJorman** [comment]
![image](https://user-images.githubusercontent.com/55187962/184698855-9e493310-0484-4d7c-b851-bb0413f0ada3.png)
hmm no working((

**Comment by MrJorman** [comment]
[crash-2022-08-15_22.02.35-server.txt](https://github.com/Luohuayu/CatServer/files/9339266/crash-2022-08-15_22.02.35-server.txt)

**Comment by MrJorman** [comment]
Now I will try another Java, graavlm17.

**Comment by MrJorman** [comment]
No, it's all in vain, I've already reinstalled the server, but nothing helped.

**Comment by MrJorman** [comment]
[crash-2022-08-15_22.07.05-server.txt](https://github.com/Luohuayu/CatServer/files/9339290/crash-2022-08-15_22.07.05-server.txt)

**Comment by MrJorman** [comment]
use my modpack. https://drive.google.com/file/d/1thOI5zyugkiT9l0_i96ikVKJCBuz3IRW/view?usp=sharing download.

**Comment by MrJorman** [comment]
https://www.curseforge.com/minecraft/mc-mods/idas maybe this mod crashed. Although everything starts on a clean Forge.

**Comment by Kotori0629** [comment]
Ok, wait a moment

**Comment by Kotori0629** [comment]
Fixed, use latest version

**Comment by MrJorman** [comment]
@Kotori0629 no fix
[crash-2022-08-15_22.32.34-server.txt](https://github.com/Luohuayu/CatServer/files/9339424/crash-2022-08-15_22.32.34-server.txt)
[latest.log](https://github.com/Luohuayu/CatServer/files/9339425/latest.log)
.

**Comment by Kotori0629** [comment]
You need to rerun java -jar server.jar

**Comment by MrJorman** [comment]
oh yes, sorry, fixed.

**Comment by MrJorman** [comment]
![image](https://user-images.githubusercontent.com/55187962/184704747-2aec7b7c-a545-48d5-9b39-c958542d5114.png)
:-)

**Comment by Kotori0629** [comment]
> ![image](https://user-images.githubusercontent.com/55187962/184704747-2aec7b7c-a545-48d5-9b39-c958542d5114.png) :-)

Okay

**Comment by MrJorman** [comment]
sorry, man you broken mod :D 
![image](https://user-images.githubusercontent.com/55187962/184706523-66e41e4e-5a78-4a7e-80ab-8bd77b10de44.png)
This is how the generation of the dungeon in the IDAS mod should look like /locate idas:abandonhouse

**Comment by MrJorman** [comment]
![image](https://user-images.githubusercontent.com/55187962/184706643-3a01f4e0-b530-4282-b18a-ec12f14c866b.png)
On the server it looks like this:
![image](https://user-images.githubusercontent.com/55187962/184706674-efc4df30-4571-4732-9d51-af45448498b4.png)

it's no normal..

**Comment by MrJorman** [comment]
All blocks are mixed up, the structure is not generated correctly.

**Comment by MrJorman** [comment]
[latest.log](https://github.com/Luohuayu/CatServer/files/9339491/latest.log)
and check latest.log error spamming.

**Comment by Kotori0629** [comment]
Please re-open an issue, this issue has been closed

**Comment by MrJorman** [comment]
> Please re-open an issue, this issue has been closed

sorry. done.
