### ISSUE TITLE
[1.18.2] Lootr mod it doesn't work correctly

### ISSUE THREAD

**Issue by MrJorman** [Luohuayu/CatServer#560]
**Environment**

Minecraft version(1.12.2/1.16.5/1.18.2): 1.18.2
Build version(Get from /version command): 14 build
Mods/Plugins: https://drive.google.com/file/d/1thOI5zyugkiT9l0_i96ikVKJCBuz3IRW/view?usp=sharing + lootr mod

**Describe the bug**
Sometimes I get an error in the console that is not clear, sometimes when I open the chest, it is not marked that it has already been opened by me, it still remains golden, also for some reason some chests are called barrels and do not open, this can be noticed in many dungeons, but personally I noticed it in /locate repurposed_structures:bastion_underground

**Expected behavior**

**To Reproduce**

**Screenshot/Video**
(If it doesn't exist you c
[latest.log](https://github.com/Luohuayu/CatServer/files/9339525/latest.log)
![image](https://user-images.githubusercontent.com/55187962/184708244-eea1165b-92c1-43e4-b5c6-f57983b24f36.png)
an ignore it)

**Comment by MrJorman** [comment]
It feels like he is trying to generate 2 loot in 1 place at once

**Comment by Kotori0629** [comment]
If the crash still occurs, please reopen an issue
