### ISSUE TITLE
[1.18.2] crash server

### ISSUE THREAD

**Issue by MrJorman** [Luohuayu/CatServer#563]
**Environment**

Minecraft version(1.12.2/1.16.5/1.18.2): 1.18.2
Build version(Get from /version command): 14 build
Mods/Plugins: https://drive.google.com/file/d/1thOI5zyugkiT9l0_i96ikVKJCBuz3IRW/view?usp=sharing + lootr mod

**Describe the bug**
The server just crashes

**Expected behavior**

**To Reproduce**

**Screenshot/Video**
(If it doesn't exist you can ignore it)
[crash-2022-08-16_20.22.20-server.txt](https://github.com/Luohuayu/CatServer/files/9353050/crash-2022-08-16_20.22.20-server.txt)

**Comment by XionioXMaster** [comment]
Загружай репорты в https://mcpaste.com
