### ISSUE TITLE
[1.18.2] 服务器崩溃

### ISSUE THREAD

**Issue by jingerbreadBiliBili** [Luohuayu/CatServer#564]
**运行环境**
AMD R5-3600 3.6Ghz

Minecraft版本(1.12.2/1.16.5/1.18.2): 1.18.2
构建版本(从/version指令获取):  CatServer version 1.18.2 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT, Forge version 40.1.63)
相关模组/插件: 匠魂3

**描述这个BUG**
冶炼炉造16x16x1后激活会导致崩溃

**导致的问题r**
服务器崩溃
**复现方法**

**截图/视频**
(如果没有可以忽略)

**Comment by Kotori0629** [comment]
崩溃报告呢

**Comment by XionioXMaster** [comment]
XD

**Comment by jingerbreadBiliBili** [comment]
[crash-2022-08-18_14.12.21-server.txt](https://github.com/Luohuayu/CatServer/files/9395853/crash-2022-08-18_14.12.21-server.txt)

**Comment by Kotori0629** [comment]
修复过了
