### ISSUE TITLE
[1.16.5] 使用simpleAuth mod导致服务器崩溃

### ISSUE THREAD

**Issue by ShenxPresent** [Luohuayu/CatServer#565]
**运行环境**

Minecraft版本: 1.16.5

构建版本(从/version指令获取): This server is running CatServer version 1.16.5-301aa5f8 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT, Forge version 36.2.35)

相关模组/插件: https://www.curseforge.com/minecraft/mc-mods/SimpleAuth

**描述这个BUG**
日志文件：https://pastebin.com/LkbG4Rtx

**导致的问题r**
服务器崩溃
**复现方法**
使用simpleauth mod

**Comment by Luohuayu** [comment]
请使用authlib-injector

**Comment by ShenxPresent** [comment]
我想要在正版玩家无需额外验证，并保留现在已有正版玩家数据的基础上，让部分非正版玩家可以登录，authlib-injector没法完成我的需求

**Comment by ShenxPresent** [comment]
> 请使用authlib-injector

我需要的是这个mod带来的mixed online mode功能而并非第三方登录系统，希望能重新open本issue
