### ISSUE TITLE
[1.18.2] WARN Startup World Edit

### ISSUE THREAD

**Issue by XionioXMaster** [Luohuayu/CatServer#568]
**Environment**

Minecraft version(1.12.2/1.16.5/1.18.2):  1.8.2 
Build version(Get from /version command): Build 17 https://jenkins.rbqcloud.cn:30011/job/CatServer-1.18.2/17/
Mods/Plugins: World Edit, **Mods: nope**

**Describe the bug**
https://mcpaste.com/b292a1aba04041180a44600ddce8fafe
I decided to take some time to check plugins for 1.18.2, I will check very popular

**Expected behavior**

**To Reproduce**
Put 
[Новий Архив ZIP - WinRAR.zip](https://github.com/Luohuayu/CatServer/files/9365446/ZIP.-.WinRAR.zip)
Start server and see console

**Screenshot/Video**
Nope

**Comment by Kotori0629** [comment]
The rebirth version 1.18.2 will be merged soon, please test after merging, if you find the same problem, please resubmit!
