### ISSUE TITLE
[1.18.2] Error GSit plugin

### ISSUE THREAD

**Issue by XionioXMaster** [Luohuayu/CatServer#569]
**Environment**

Minecraft version(1.12.2/1.16.5/1.18.2):  1.18.2 
Build version(Get from /version command): Build 17 https://jenkins.rbqcloud.cn:30011/job/CatServer-1.18.2/17/
Mods/Plugins: GSit 
Mods: nope

**Describe the bug**
https://mcpaste.com/200fe28bd6e3ff9c7deffff993ac9c97

**Expected behavior**

**To Reproduce**
Put 
[Новий Архив ZIP - WinRAR.zip](https://github.com/Luohuayu/CatServer/files/9365534/ZIP.-.WinRAR.zip)
Start server and see console

**Screenshot/Video**
Nope

**Comment by Kotori0629** [comment]
The rebirth version 1.18.2 will be merged soon, please test after merging, if you find the same problem, please resubmit!
