### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by KubiRemPL** [Luohuayu/CatServer#57]
jvisualvm doesnt see more threds.
For example i incresed this number to 100 and still th sam amount of threads were used.
Can U explain how async chunk generation works.

**Comment by Luohuayu** [comment]
The option in the configuration is the maximum number of threads. The threadpool will only automatically increase threads when needed,

**Comment by KubiRemPL** [comment]
why in thread inspector I dont see some worldgen threads

**Comment by KubiRemPL** [comment]
only hopper threads

**Comment by Luohuayu** [comment]
It's just a test function and has been removed

**Comment by 8qBITs** [comment]
Does async version also async chunk loading? if not is it planned?

**Comment by Luohuayu** [comment]
Chunk loading is async
