### ISSUE TITLE
[1.18.2] Error MCPets plugin

### ISSUE THREAD

**Issue by XionioXMaster** [Luohuayu/CatServer#570]
Environment

Minecraft version(1.12.2/1.16.5/1.18.2): 1.8.2
Build version(Get from /version command): Build 17 https://jenkins.rbqcloud.cn:30011/job/CatServer-1.18.2/17/
Mods/Plugins: MCPets
Mods: nope

Describe the bug
https://mcpaste.com/cd48ea7898524106ce0a3da3e8f16fab

Expected behavior

To Reproduce
Put
[Новий Архив ZIP - WinRAR.zip](https://github.com/Luohuayu/CatServer/files/9365552/ZIP.-.WinRAR.zip)
Start server and see console

Screenshot/Video
Nope

**Comment by Kotori0629** [comment]
Omg...

**Comment by XionioXMaster** [comment]
> Omg...

what?

**Comment by Kotori0629** [comment]
Do you have MythicMobs installed?

**Comment by XionioXMaster** [comment]
> Do you have MythicMobs installed?

oh, no
work
