### ISSUE TITLE
[1.18.2] crash server start

### ISSUE THREAD

**Issue by MrJorman** [Luohuayu/CatServer#572]
**Environment**

Minecraft version(1.12.2/1.16.5/1.18.2): 1.18.2
Build version(Get from /version command): build 17
Mods/Plugins: https://drive.google.com/file/d/1thOI5zyugkiT9l0_i96ikVKJCBuz3IRW/view?usp=sharing + lootr mod

**Describe the bug**
(If there is an error, please attach the pastebin link)

**Expected behavior**

**To Reproduce**

**Screenshot/Video**
(If it doesn't exist you can ignore it)
[latest.log](https://github.com/Luohuayu/CatServer/files/9365573/latest.log)

**Comment by XionioXMaster** [comment]
I don't see a server crash here

**Comment by Kotori0629** [comment]
The rebirth version 1.18.2 will be merged soon, please test after merging, if you find the same problem, please resubmit!
