### ISSUE TITLE
[1.18.2] zAuctionHouseV3 Plugin Error

### ISSUE THREAD

**Issue by XionioXMaster** [Luohuayu/CatServer#574]
Environment

Minecraft version(1.12.2/1.16.5/1.18.2): 1.18.2
Build version(Get from /version command): Build 17 https://jenkins.rbqcloud.cn:30011/job/CatServer-1.18.2/17/
Mods/Plugins: zAuctionHouseV3 
Mods: nope

Describe the bug
https://mcpaste.com/b7dfd428521051bf01e513979cc79f51

Expected behavior

To Reproduce
Put
[Новий Архив ZIP - WinRAR.zip](https://github.com/Luohuayu/CatServer/files/9365623/ZIP.-.WinRAR.zip)
Start server and see console

Screenshot/Video
Nope

**Comment by Kotori0629** [comment]
https://hub.spigotmc.org/stash/projects/SPIGOT/repos/bukkit/diff/src/main/java/org/bukkit/Material.java?until=b93194d14a2bec34b8106d79094c35b10cc18466

enum constant org.bukkit.Material.MUD was added in 1.19
