### ISSUE TITLE
[1.18.2] PlayerQuitEvent to CMI

### ISSUE THREAD

**Issue by XionioXMaster** [Luohuayu/CatServer#577]
**Environment**

Minecraft version(1.12.2/1.16.5/1.18.2): 1.18.2
Build version(Get from /version command): Build 17 https://jenkins.rbqcloud.cn:30011/job/CatServer-1.18.2/17/
Mods/Plugins: CMI,CMIlIB, eco v6.38.2
Mods: nope

**Describe the bug**
[(If there is an error, please attach the pastebin link)
](https://mcpaste.com/085814b12b6128923947b6b432146dfa)

**Expected behavior**
I was supposed to login to the server, but it's not possible due to this error

If you need a test plugin, I'll upload it to your discord PM

**To Reproduce**
Install CMI and CMILib
Join to the server

**Screenshot/Video**
(If it doesn't exist you can ignore it)

**Comment by Kotori0629** [comment]
Test use latest version

**Comment by XionioXMaster** [comment]
> Test use latest version

Lates builds Error

**Comment by XionioXMaster** [comment]
So I can't test it right now, sorry

**Comment by Kotori0629** [comment]
After using the latest version, send me a new bug report

**Comment by XionioXMaster** [comment]
> After using the latest version, send me a new bug report

![image](https://user-images.githubusercontent.com/86433158/185643738-3e7fc894-23a3-4fea-8cba-c75964d85c1d.png)
ok, i'm user 17 Build

**Comment by XionioXMaster** [comment]
![image](https://user-images.githubusercontent.com/86433158/185651423-c6f2a0c8-a344-42ed-b14d-e418f34b8310.png)

Join but: https://mcpaste.com/3490f3de63790c7c3a34bc3001c1420c

**Comment by Kotori0629** [comment]
Try use latest version

**Comment by XionioXMaster** [comment]
yes, fixed
