### ISSUE TITLE
[1.18.2] Problems while logging into the server

### ISSUE THREAD

**Issue by XionioXMaster** [Luohuayu/CatServer#578]
**Environment**

Minecraft version(1.12.2/1.16.5/1.18.2): 1.18.2
Build version(Get from /version command): Build 17 https://jenkins.rbqcloud.cn:30011/job/CatServer-1.18.2/17/
Mods/Plugins: Protocolib, DynamicDifficulty, eco v6.38.2
Mods: nope

**Describe the bug**
[(If there is an error, please attach the pastebin link)
](https://mcpaste.com/a6aa6bf605dd31959bde1e2868a7696f)
**Expected behavior**

**To Reproduce**

**Screenshot/Video**
![image](https://user-images.githubusercontent.com/86433158/185229368-696e344b-4c44-4b7b-9e61-00b8140168a7.png)

**The inscription "Invalid player data"**

**Comment by Kotori0629** [comment]
Same #577
