### ISSUE TITLE
[1.12.2] 使用python库mcstatus获取服务器在线玩家时失败

### ISSUE THREAD

**Issue by half-nothing** [Luohuayu/CatServer#580]
**![image](https://user-images.githubusercontent.com/50048293/185304782-d16b936a-41a5-468a-9711-de610f7bbeb3.png)**
**-Xmx6G -Xms4G**

Minecraft版本(1.12.2/1.16.5/1.18.2):  1.12.2
构建版本(从/version指令获取):  8d58cdb8
相关模组/插件:  
模组列表
![image](https://user-images.githubusercontent.com/50048293/185305253-276b0ba7-a983-4dc8-9bbd-a06fefbf7e83.png)
![image](https://user-images.githubusercontent.com/50048293/185305290-91f10c16-1e7a-4231-8fe3-f07584a420fd.png)
![image](https://user-images.githubusercontent.com/50048293/185305350-3b77b42e-5dd6-408b-bbac-4cf329790118.png)
![image](https://user-images.githubusercontent.com/50048293/185305415-83e3609a-744b-4c39-b7b7-eba66d37e40b.png)
![image](https://user-images.githubusercontent.com/50048293/185305433-1e109235-beae-4cbd-ac6a-693193e93cef.png)
插件列表
![image](https://user-images.githubusercontent.com/50048293/185305468-bcd15fcd-5b3a-4c80-8c1b-4c058efb28d4.png)

**描述这个BUG**
![image](https://user-images.githubusercontent.com/50048293/185305576-df06de6b-5729-4938-a8f7-8443a3849d95.png)
![image](https://user-images.githubusercontent.com/50048293/185305654-c111d0a0-bba6-428b-9b4f-f01962b182ac.png)

**导致的问题r**
无法获取在线玩家数量，其实不是什么大问题

**复现方法**
每次稳定触发，报错为两者之一随机

**Comment by Luohuayu** [comment]
CatServer返回的MOTD和Forge一样的, 应该是py库不兼容Forge的MOTD数据, 请向相应py库的作者反馈
