### ISSUE TITLE
1.16.5 Anticheat

### ISSUE THREAD

**Issue by SqdGoodlol** [Luohuayu/CatServer#581]
**Environment**
 
Minecraft version(1.12.2/1.16.5/1.18.2): 1.16.5
Build version(Get from /version command):  This server is running CatServer version 1.16.5-caa59bdd (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT, Forge version 36.2.35)
Mods/Plugins: Kauri-2.19+Atlas

**Describe the bug**
Can't login to the server
[19:12:16] [Server thread/INFO]: /127.0.0.1:63158 lost connection: Internal Exception: java.lang.ExceptionInInitializerError
![image](https://user-images.githubusercontent.com/86075284/185381487-16b30dd9-26be-4a83-a679-68a317eb5ed5.png)

**Expected behavior**

**To Reproduce**

**Screenshot/Video**
(If it doesn't exist you can ignore it)

**Comment by Kotori0629** [comment]
logs？
