### ISSUE TITLE
[1.16.5] 使用simpleAuth mod导致服务器崩溃

### ISSUE THREAD

**Issue by ShenxPresent** [Luohuayu/CatServer#582]
**运行环境**

Minecraft版本: 1.16.5

构建版本(从/version指令获取): This server is running CatServer version 1.16.5-301aa5f8 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT, Forge version 36.2.35)

相关模组/插件: https://www.curseforge.com/minecraft/mc-mods/SimpleAuth

**描述这个BUG**
日志文件：https://pastebin.com/LkbG4Rtx

**导致的问题**
服务器崩溃
**复现方法**
使用simpleauth mod

**补充说明**
之前的issue被建议使用authlib-injector后close；simpleAuth mod可以提供mixed online mode功能而并非第三方登录系统，authlib-injector并不能成为其替代品，重新open的请求没有得到回应后重新提交了本issue

**Comment by Kotori0629** [comment]
修复可能会打破目前的登陆逻辑, 暂不考虑兼容
