### ISSUE TITLE
[1.16.5] 打盖亚3本我崩溃

### ISSUE THREAD

**Issue by ghost** [Luohuayu/CatServer#586]
**运行环境**

Minecraft版本(1.12.2/1.16.5/1.18.2): 1.16.5
构建版本(从/version指令获取): 1.16.5-6fea1e9d
相关模组/插件: [额外植物学]ExtraBotany-r1.2-68.jar

**描述这个BUG**
(如果有报错请附上pastebin链接或上传日志文件)
打盖亚3本我到约1/3时血量时会触发，猜测为召唤小怪的阶段，服务器直接崩溃
最初是没有这种情况的，突然就出现了，更新到最新构建版本仍会发生
https://pastebin.com/gVzja0zZ
**导致的问题r**
服务器直接崩溃
**复现方法**
打盖亚三本我到约1/3时血量时
**截图/视频**
(如果没有可以忽略)

**Comment by Luohuayu** [comment]
你确定不是MOD自身问题?

**Comment by Kotori0629** [comment]
貌似确实是mod问题）

**Comment by Kotori0629** [comment]
还有问题的话重新发吧
