### ISSUE TITLE
[1.12.2] catserver无法使用 unsafeget

### ISSUE THREAD

**Issue by lidashuai-li** [Luohuayu/CatServer#588]
**运行环境**

Minecraft版本(1.12.2): 
构建版本(从/version指令获取): This server is running CatServer version git-CatServer-1.12.2-8d58cdb8 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT, Forge version 14.23.5.2860)
相关模组/插件: mythicmobs

**描述这个BUG**
cat端无法使用unsafeget，https://pastebin.ubuntu.com/p/ZCspP6QRhb/

**导致的问题r**
mm技能部分失效 刷屏报错
**复现方法**
使用 getentitylocation 时会报错
**截图/视频**
(如果没有可以忽略)

**Comment by Kotori0629** [comment]
@Luohuayu 你看 似曾相识的问题

**Comment by lidashuai-li** [comment]
hello?

**Comment by Luohuayu** [comment]
我这没有MythicMobs v4.11来分析测试和修复
