### ISSUE TITLE
CatServer的FakePlayer无法正常使用

### ISSUE THREAD

**Issue by Coloryr** [Luohuayu/CatServer#59]
在单机下FakePlayer是可以正常使用的
然而在catserver里是不正常的
这导致industrialforegoing的 凋灵生成器 无法正常工作
![NH`TX6I4R_N8%P$NUY}NTQN](https://user-images.githubusercontent.com/26276037/71555701-fc3cd800-2a69-11ea-94a3-3788a54365ea.png)
（凋灵头可以正确放置，但是凋灵不会产生，只有玩家自己放置头颅才可以生成，单机无此问题）

**Comment by Luohuayu** [comment]
已修复
https://github.com/Luohuayu/CatServer/commit/66199ca09dd4bd81313f92305cdcb8a5fd8d5148
