### ISSUE TITLE
[1.18.2] I would like to make it easier to launch

### ISSUE THREAD

**Issue by DonorKrovi** [Luohuayu/CatServer#591]
**Is your feature request related to a problem? Please describe.**
It would be nice if the server started with 1 .bat and without hundreds of arguments

**Describe the solution you'd like**
I propose to start the server with several arguments, without generating a launch for CatServer, this way you can easily bind your client to the server and get around the error problem when adding your launch arguments

For example, I wanted to bind the launcher to CatServer, but due to its initial value, I could not do it.

**Describe alternatives you've considered**
Make it easy to start the server, e.g. Magma or Vanilla server is started using only a few arguments **java -Xmx1024M -Xms1024M -jar server.jar**

**Comment by Kotori0629** [comment]
This is a good proposal, we are improving, the way they start we used at the beginning, you can refer to CatServer in 1.16.5. Due to some concerns, we have separated the launch from the merge, and are currently developing a new launch method

**Comment by XionioXMaster** [comment]
good idea

**Comment by Kotori0629** [comment]
The rebirth version 1.18.2 will be merged soon, please test after merging, if you find the same problem, please resubmit!
