### ISSUE TITLE
[1.18.2] Quark bukkit gui dupes

### ISSUE THREAD

**Issue by XionioXMaster** [Luohuayu/CatServer#592]
**Environment**

Minecraft version(1.12.2/1.16.5/1.18.2): 1.18.2
Build version(Get from /version command): [Server thread/INFO]: This server is running CatServer version 1.18.2 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT, Forge version 40.1.73)←[m
Mods/Plugins: 
![image](https://user-images.githubusercontent.com/86433158/186183927-568cd7ac-49ad-43ce-bb86-d5bad7107e20.png)

**Describe the bug**
As expected in Quark you can dupe things from GUI plugins using move things to backpack, you seem to have fixed this on 1 16 5 and 1 12 2

There were no errors as such in the console.

**To Reproduce**
See Screenshot, i'm use PlayerKits plugin GUI

**Screenshot/Video**
![image](https://user-images.githubusercontent.com/86433158/186183694-becfc8c0-b094-4c9d-99af-917ceab95f1e.png)

**Comment by Kotori0629** [comment]
Fixed in the remake
