### ISSUE TITLE
[1.18.2] Quark map and ancient volumes

### ISSUE THREAD

**Issue by XionioXMaster** [Luohuayu/CatServer#594]
**Environment**

Minecraft version(1.12.2/1.16.5/1.18.2): 1.18.2
Build version(Get from /version command): This server is running CatServer version 1.18.2 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT, Forge version 40.1.73)
Mods/Plugins: 

Plugins (6): ←[0;32;1mChatty←[0;37;1m, ←[0;32;1mLuckPerms←[0;37;1m, ←[0;32;1mFartherViewDistance←[0;37;1m, ←[0;32;1mPlayerKits←[0;37;1m, ←[0;32;1mCMILib←[0;37;1m, ←[0;32;1mCMI

Mod List:
? minecraft server-1.18.2-20220404.173914-srg.jar : minecraft (1.18.2) - 1
? minecraft forge-1.18.2-40.1.73-universal.jar : forge (40.1.73) - 1
? mods_folder flywheel-forge-1.18.2-0.6.5.jar : flywheel (0.6.5) - 1
? mods_folder etched-forge-2.2.0+1.18.2.jar : etched (2.2.0) - 1
? mods_folder pollen-forge-1.4.9+1.18.2.jar : pollen (1.4.9) - 1
? mods_folder create-1.18.2-0.5.0.d.jar : create (0.5.0.d) - 1
? mods_folder architectury-4.9.83-forge.jar : architectury (4.9.83) - 1
? mods_folder minecraft-comes-alive-7.3.19+1.18.2-universal.jar : mca (7.3.19+1.18.2) - 1
? mods_folder AutoRegLib-1.7-53.jar : autoreglib (1.7-53) - 1
? mods_folder Quark-3.2-358.jar : quark (3.2-358) - 1

**Describe the bug**
No error or warn report

**To Reproduce**
Ancient tomes from the mod do not have their properties when found! But on a pure Forge, they have their own enchantments, the same with cards when viewed through the inventory, they do not have a cross with the location of the treasure, but if you take them in hand, it will appear, but not through the inventory

**Screenshot/Video**
**### Forge**
![image](https://user-images.githubusercontent.com/86433158/186194062-912846a9-66e7-444b-ba00-dffd90a605cf.png)
![image](https://user-images.githubusercontent.com/86433158/186194092-c76de7df-4e3e-4fba-88c2-0f06114c9e92.png)

### **Cat**
![Без fимевни](https://user-images.githubusercontent.com/86433158/186194194-af5fdf83-780f-4ab7-94e6-14b27fb6ef8d.png)
![image](https://user-images.githubusercontent.com/86433158/186195337-3b63dbc5-886f-4d86-bb88-9017956c9ece.png)

**Comment by Kotori0629** [comment]
The rebirth version 1.18.2 will be merged soon, please test after merging, if you find the same problem, please resubmit!
