### ISSUE TITLE
[1.18.2] chestcommand

### ISSUE THREAD

**Issue by Adogs1** [Luohuayu/CatServer#595]
**运行环境**

Minecraft版本(1.12.2/1.16.5/1.18.2): 1.18.2
构建版本(从/version指令获取): 710
相关模组/插件: chestcommand

**描述这个BUG**
(如果有报错请附上pastebin链接或上传日志文件)
在1.18.2服务端使用最新版chestcommand插件时,商店(GUI)页面会出错,上面的物品可以直接拿.但是paper1.18.2端可以正常使用这个插件
**导致的问题r**
chestcommand商店gui无法正常使用
**复现方法**
直接使用该插件
**截图/视频**
(如果没有可以忽略)

https://user-images.githubusercontent.com/111733210/186300222-50deec9b-0a5e-43b5-a866-b18c177c16be.mp4

**Comment by Kotori0629** [comment]
fixed in the remake
