### ISSUE TITLE
[1.16.5] Catserver breaks/is missing PermissionAPI.hasPermission

### ISSUE THREAD

**Issue by VOrlando520** [Luohuayu/CatServer#596]
**Environment**

Minecraft version(1.12.2/1.16.5/1.18.2): 1.16.5
Build version(Get from /version command): b2435f6 1.16.5-R0.1-SNAPSHOT

**Describe the bug**
When using any Pixelmon related sidemod or plugin that makes use PermissionAPI.hasPermission event, they no longer work or able to use any commands

**Expected behavior**
For the command to work or at least output why it isnt working

**To Reproduce**
Would need a pixelmon plugin/sidemod which uses PermissionAPI.hasPermission event

**Screenshot/Video**
https://puu.sh/JhMWH.gif

**Comment by Kotori0629** [comment]
Is this command from a mod? You can try giving user minecraft.command.pokenear using Luckperms

**Comment by VOrlando520** [comment]
Yeah it is, https://sdcaptain.gitbook.io/sdlibrary/pokenear this one in particular
I already have that, plus the permissions he lists in his wiki as well. I contacted him and we tested. It works on other hybrids (arc, mohist, etc) but breaks with catserver

**Comment by VOrlando520** [comment]
For reference, this is permissions class of the plugin im talking about. It calls on PermissionAPI and works on other hybrids, something is messed up on cat that is breaking it

Code from pokenear that calls on PermissionAPI 
https://pastebin.com/pbSKHHtj

**Comment by Kotori0629** [comment]
Waiting for the merge, please re-publish an issues if there are still problems
