### ISSUE TITLE
[1.12.2] dimension manager issue

### ISSUE THREAD

**Issue by Proemmis** [Luohuayu/CatServer#597]
**Environment**

Minecraft version(1.12.2/1.16.5/1.18.2): 1.12.2
Build version(Get from /version command): git-CatServer-1.12.2-8d58cdb8 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT, Forge version 14.23.5.2860)

Mods/Plugins: 
Plugins (49): NoFallDamage, PlaceholderAPI, NoSleep, MobStacker, SpawnerSilk, SpigotPlainTell, MobsVegetables, CoreProtect, GhostBuster, LuckPerms, WorldEdit, DropCleaner, spark, WorldBorder, BuycraftX, Votifier, ProtocolLib, MovingDevApi, HungerPlusPlus, NoPortal, VoidGenerator, NightVisionReloaded, DcBanItem, CommandItems, Vault, GCore, HolographicDisplays, RewardPRO, WorldGuard, ChestCommands, AntiVPN, VoidChest, EverNifeCore, AdvancedBan, UpBleuCounterBug, CustomCommands, CrazyCrates, PixelmonEconomyBridge, SecurityLog, AuthMe, ASkyBlock, LockettePro, IslandBorder, Multiverse-Core, DiscordSRV, CMILib, CMI, CMIEInjector, VotingPlugin

**Describe the bug**
good evening, I have this console error that appears only on each starting/restarting server when I configure my plugin (pixelmon-ranking), and I indicate dimension 2 or another dimension to it, I have the impression that CatServer does not detect it when it does exist, I would like to know if there was a possibility to solve the problem, the console error: https://pastebin.com/H4WSQZ16

thanks in Advance for the help :wink:

**Expected behavior**
Just a clear answer giving the most precise idea possible of where the bug can come from and why :)

**To Reproduce**

**Screenshot/Video**
(If it doesn't exist you can ignore it)

edit : error changed with build CatServer-6eb82ffe-universal : https://pastebin.com/j5bytvpb

**Comment by Luohuayu** [comment]
Exception caused by pixelmonranking, it tries to load a dimension that doesn't exist. And should not operate NMS on non-main thread.
