### ISSUE TITLE
[1.18.2] 未知原因崩溃

### ISSUE THREAD

**Issue by jingerbreadBiliBili** [Luohuayu/CatServer#599]
**运行环境**
windows 10 专业工作站版
java17
Minecraft版本(1.12.2/1.16.5/1.18.2): 1.18.2
构建版本(从/version指令获取): CatServer version 1.18.2 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT, Forge version 40.1.73)[m
相关模组/插件: 等价交换 旅行地图 jei CreateYourOwnMenus-0.6.4

**描述这个BUG**
(如果有报错请附上pastebin链接或上传日志文件)
多人联机时朋友找要塞时掉岩浆之后传送上去又被蛮兵打了一下，之后服务器崩溃
**导致的问题r**
服务器崩溃
**复现方法**
不知道
**截图/视频**
(如果没有可以忽略)

**Comment by jingerbreadBiliBili** [comment]
[crash-2022-08-26_11.57.00-server.txt](https://github.com/Luohuayu/CatServer/files/9429724/crash-2022-08-26_11.57.00-server.txt)
[latest.log](https://github.com/Luohuayu/CatServer/files/9429728/latest.log)
一个崩溃报告，一个日志

**Comment by jingerbreadBiliBili** [comment]
[latest.log](https://github.com/Luohuayu/CatServer/files/9430113/latest.log)
[crash-2022-08-26_13.36.58-server.txt](https://github.com/Luohuayu/CatServer/files/9430114/crash-2022-08-26_13.36.58-server.txt)
又一次

**Comment by Kotori0629** [comment]
更新至最新版本后查看, 如仍有问题请重新发issues
