### ISSUE TITLE
[1.18.2] 未知原因崩溃

### ISSUE THREAD

**Issue by jingerbreadBiliBili** [Luohuayu/CatServer#600]
**运行环境**
Windows 10专业工作站版
JAVA17
Minecraft版本(1.12.2/1.16.5/1.18.2): 1.18.2
构建版本(从/version指令获取): CatServer-1.18.2-2d2a4316-server
相关模组/插件: 

**描述这个BUG**
(如果有报错请附上pastebin链接或上传日志文件)
放着的时候就能崩
[crash-2022-08-27_11.07.40-server.txt](https://github.com/Luohuayu/CatServer/files/9437411/crash-2022-08-27_11.07.40-server.txt)
**导致的问题r**
崩溃
**复现方法**
nan
**截图/视频**
(如果没有可以忽略)

**Comment by jingerbreadBiliBili** [comment]
版本是昨天的构建#35

**Comment by Kotori0629** [comment]
不理解， 你康康有没有复现方法

**Comment by jingerbreadBiliBili** [comment]
出事了我再交吧
