### ISSUE TITLE
[1.18.2] 插件无法正常加载，报缺少apache/common类

### ISSUE THREAD

**Issue by gundami** [Luohuayu/CatServer#601]
**运行环境**

Minecraft版本(1.12.2/1.16.5/1.18.2): 1.18.2
构建版本(从/version指令获取):  CatServer version 1.18.2 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT, Forge version 40.1.73)
相关模组/插件: 
Towny，TownyChat，SiegeWar
**描述这个BUG**
(如果有报错请附上pastebin链接或上传日志文件)
加载时候报错找不到org/apache/commons/lang/StringUtils类
完整日志文件：https://pastebin.com/kPdkT0sd
**导致的问题r**
上述插件无法使用
**复现方法**
安装上述插件，启动，报错
**截图/视频**
(如果没有可以忽略)

**Comment by Kotori0629** [comment]
更新最新版本，还有问题就重新发
