### ISSUE TITLE
[1.12.2] Wawla模组与AE2不兼容，报错

### ISSUE THREAD

**Issue by Fossssss** [Luohuayu/CatServer#602]
**运行环境**

Minecraft版本(1.12.2/1.16.5/1.18.2): 
构建版本(从/version指令获取): CatServer-1.12.2-6eb82ffe
相关模组/插件: Wawla，AE2

**描述这个BUG**
服务器报错： Error registering wrapped plugin from appliedenergistics2 at appeng.integration.modules.waila.WailaModule.register
**导致的问题r**
Wawla模组不能查看AE2中的频道数

**Comment by Kotori0629** [comment]
明明服务端就可以不安装Wawla
