### ISSUE TITLE
The server just crashes 1.16.5

### ISSUE THREAD

**Issue by SqdGoodlol** [Luohuayu/CatServer#604]
**Environment**

Minecraft version(1.12.2/1.16.5/1.18.2): 1.16.5
Build version(Get from /version command): CatServer-1.16.5-c9bc6751-server.jar
Mods/Plugins:
![image](https://user-images.githubusercontent.com/86075284/187683979-d337a5ab-8d28-4330-85a0-51d7adb30152.png)
![image](https://user-images.githubusercontent.com/86075284/187684034-df2b9a45-d198-4883-abac-d5850b027877.png)

**Describe the bug**
Server shuts down for no reason
**Expected behavior**

**To Reproduce**
[latest.log](https://github.com/Luohuayu/CatServer/files/9461689/latest.log)

**Screenshot/Video**
(If it doesn't exist you can ignore it)

**Comment by Kotori0629** [comment]
I don't see any crashes
