### ISSUE TITLE
[1.18.2] 服务端自主创建地图时Terraqueous及暮色Mod的方块无法正常显示

### ISSUE THREAD

**Issue by gaobobo** [Luohuayu/CatServer#605]
**运行环境**

Minecraft版本(1.12.2/1.16.5/1.18.2):1.18.2 
构建版本(从/version指令获取): Implementing API version 1.18.2-R0.1-SNAPSHOT, Forge version 40.1.73
相关模组/插件: 暮色森林（V2.2.1a）、地灵云心/海树山花（Terraqueous）（Jul 21, 2022构建版本）、ShetiphianCore（前置）（3.10.10）

**描述这个BUG**
(如果有报错请附上pastebin链接或上传日志文件)

在使用包含以上两个mod的服务端时，会出现上述两个mod方块显示错误错误的问题。如下图1-1、图1-2。此时**方块无法正常互动**，仅能破坏与建造。：

![图1-1](https://user-images.githubusercontent.com/32958058/187702845-a1341a62-edac-4c75-8ed8-64fd75da1163.png)
![图1-2](https://user-images.githubusercontent.com/32958058/187709802-92e6b711-c9b7-4f72-8623-c43ae8243360.png)

将服务器存档导入到**单人模式**时，两个mod的大部分方块均显示正确并**正常互动**，如下图2-2；但仍有**方块换位**（图1中物品栏第二个为Terraqueous中的某种树苗，但在图2中却换位成了暮色森林的物品），如下图2-1：

![图2-1](https://user-images.githubusercontent.com/32958058/187703289-848fcc3e-c376-4f37-9015-ca1a9de312dc.png)
![图2-2](https://user-images.githubusercontent.com/32958058/187710110-9e7b071d-9c59-4343-82e0-0adabae2a54e.png)

后续对此又进行测试，出现了下面的结果：

- 多次测试，对于Terraqueous的所有物品、暮色森林几乎所有物品在实际放置时显示错误并无法正常互动，破坏重新放置后也是如此。

- 多次测试，将CatServer自主生成的存档放入到**单人模式**或者VanillaForge中两个mod的大多数方块均恢复正常显示，小部分方块换位。所有方块均正常互动。

> 客户端Forge版本：40.1.73
> 服务器Forge版本：40.1.73

- 多次测试，将单人模式生成的存档替换掉CatServer自主生成的存档，**在服务器内**方块均显示正常，并且**均能进行互动**。如图3（左下角有服务器独有的TPS命令）。：

![图3](https://user-images.githubusercontent.com/32958058/187708146-571f9c8b-f3f0-4ea0-a971-74df471189c5.png)

- 多次测试，将CatServer自主生成的地图导入到单人模式里并进行方块重新放置后再替换CatServer自主生成的存档，仍无法正常显示并无法进行互动。

- 特别的现象：如果放置Terraqueous中的树苗会有部分树苗生成暮色森林中特有的松鼠，但松鼠的行为和声音均为骷髅声音。拷贝到单人模式中，松鼠变为了骷髅。这表明暮色森林的部分内容正确加载了。；Terraqueous会影响地形的生成，在CatServer自主创建地图时，地形明显受到了影响并自然生成了Terraqueous中的方块，这也表明Terraqueous部分内容也确实正常加载了。

虽然服务端没有出现任何重大问题而停止工作，但为排除潜在问题，下面是CatServer首次新建地图的日志文件

[debug.log](https://github.com/Luohuayu/CatServer/files/9462667/debug.log)

**导致的问题**

Terraqueous及暮色Mod的方块无法正常显示并无法正常互动，仅能够破坏与建造。

**复现方法**

使用包含上述的两个mod的CatServer自主新建存档后进入游戏，即可看见自然生成的Terraqueous中的物品显示错误。

**截图/视频**
![2022-08-31_22 06 47](https://user-images.githubusercontent.com/32958058/187713758-cd30741f-9807-4f6b-8b53-87096b08b7e7.png)
![2022-08-31_22 07 54](https://user-images.githubusercontent.com/32958058/187713780-10beb419-2346-4b21-bf16-fb33d75cdcef.png)
![2022-08-31_21 42 55](https://user-images.githubusercontent.com/32958058/187713959-46e0cdfa-e8c0-4093-9cdc-8e357ecf2e90.png)
![2022-08-31_21 42 23](https://user-images.githubusercontent.com/32958058/187713969-b6e5880c-1f4a-495b-b9ac-08c03479ebef.png)

**Comment by XionioXMaster** [comment]
Dublicate https://github.com/Luohuayu/CatServer/issues/559

**Comment by Kotori0629** [comment]
#559 Same
