### ISSUE TITLE
[1.18.2] 以下mod会导致服务器无法启动

### ISSUE THREAD

**Issue by SkyIce0229** [Luohuayu/CatServer#607]
**运行环境**

Minecraft版本(1.12.2/1.16.5/1.18.2): 1.18.2
构建版本(从/version指令获取): CatServer-1.18.2-a7b30f8e
相关模组/插件: 
apathy
minetogether
Radium Reforged
immersive_weathering
Comforts
CraftTweaker-forge-1.18.2-9.1.185
create

**描述这个BUG**
(如果有报错请附上pastebin链接或上传日志文件)
https://paste.ubuntu.com/p/GGjgBZzkRM/
只是其一，太多了
**导致的问题r**
服务器无法正常启动
**复现方法**
将mod放入mods启动服务器
**截图/视频**
(如果没有可以忽略)
[mod.zip](https://github.com/Luohuayu/CatServer/files/9470750/mod.zip)

**Comment by SkyIce0229** [comment]
这四个应该可以通过更新forge 版本解决。
immersive_weathering
Comforts
CraftTweaker-forge-1.18.2-9.1.185
create

**Comment by XionioXMaster** [comment]
Radium Reforged
**Client mod**

**Comment by Kotori0629** [comment]
The rebirth version 1.18.2 will be merged soon, please test after merging, if you find the same problem, please resubmit!
