### ISSUE TITLE
[1.12.2] 宝可梦mod生成出来的等级BUG

### ISSUE THREAD

**Issue by yuankun1** [Luohuayu/CatServer#608]
**运行环境**

Minecraft版本(1.12.2/1.16.5/1.18.2): 
构建版本(从/version指令获取): 
相关模组/插件: Pixelmon模组
宝可梦配置文件里面的pixelmon.hocon 
这个选项spawnLevelsByDistance=true
服务端打开来是没有任何作用
单机打开来没有任何问题
我已经反复测试过了

**Comment by VOrlando520** [comment]
Looks like catserver is not hooking into other mod events, so things like this will happen. Something catserver has to fix on their side.

**Comment by Luohuayu** [comment]
与 #465 相同

**Comment by Luohuayu** [comment]
合并处理
