### ISSUE TITLE
[1.16.5] biggerstacks模组导致服务器启动失败

### ISSUE THREAD

**Issue by ayakasena** [Luohuayu/CatServer#610]
**运行环境**

Minecraft版本(1.12.2/1.16.5/1.18.2): 
1.16.5

构建版本(从/version指令获取): 
CatServer-1.16.5-c9bc6751-server

相关模组/插件:
 biggerstacks-1.16-2.2.jar

**描述这个BUG**
[debug.log](https://github.com/Luohuayu/CatServer/files/9482402/debug.log)
服务器启动失败

**复现方法**
单独装一个biggerstacks就会报错

**Comment by Kotori0629** [comment]
不敢动ItemStack代码

**Comment by Kotori0629** [comment]
修复了, 等待审查。如果没问题的话一会就能被合并了
