### ISSUE TITLE
[1.16.5] NoSuchFieldError with "WALL_SIGN" obtaining from Material

### ISSUE THREAD

**Issue by Sayakie** [Luohuayu/CatServer#611]
**Environment**

Minecraft version(1.12.2/1.16.5/1.18.2): 1.16.5
Build version(Get from /version command): [Luohuayu/CatServer@`0a19868d`]
Mods/Plugins:

| Type     | Name             | Version                                      |
| -------- | ---------------- | -------------------------------------------- |
| Plugin   | TriggerReactor   | v3.2.5-bukkit-latest or above any versions   |

**Describe the bug**

`NoSuchFieldError: WALL_SIGN` error is thrown when obtaining from `org.bukkit.Material`. For more context, see:
* TriggerReactor/TriggerReactor#500
* [console log]

**Expected behavior**

Obtains `Material.WALL_SIGN` with no errors.

**To Reproduce**

1. Put TriggerReactor plugin any versions at least 3.2.5-bukkit-latest.
2. Break any blocks in-game.
3. See the console log that would be spammed with NoSuchFieldError.

**Screenshot/Video**
![Related embed image. There is a full-screened console is running the Minecraft server. the left side is present that jshader is not compatible with the running Java platform, and the right side is showing an error that could not pass event BlockBreakEvent to TriggerReactor.](https://user-images.githubusercontent.com/18323202/188274520-912071f1-d158-4d23-870c-a9d0dbeeef35.png)
^ Ignore the left side, the main informative log is on the right side.

[console log]: https://mcpaste.io/ef3e53fec75398c6
[Luohuayu/CatServer@`0a19868d`]: https://github.com/Luohuayu/CatServer/commit/0a19868d732c1c38c683be0ef1168f83fad3e0ce

**Comment by Luohuayu** [comment]
WALL_SIGN is removed on 1.16.5

**Comment by Kotori0629** [comment]
Try `LEGACY_WALL_SIGN `

**Comment by Sayakie** [comment]
Tysm, Forgot the Bukkit API had been changed.
