### ISSUE TITLE
[1.16.5] Catserver does not hook into pixelmon spawn reasons, breaking GriefDefender

### ISSUE THREAD

**Issue by VOrlando520** [Luohuayu/CatServer#612]
**Environment**

Minecraft version(1.12.2/1.16.5/1.18.2): 1.16.5
Build version(Get from /version command): 54d7a066
Mods/Plugins: pixelmon 

**Describe the bug**
(If there is an error, please attach the pastebin link)
Using GriefDefender, trying to block pixelmon spawns in certain areas will not work because griefdefender does not read/verify pixelmon spawn reasons, so it can not block pixelmon mob spawns in a claim

**Expected behavior**
To be able to block pixelmon mob spawns in an admin claim

**To Reproduce**
Go into an admin claim and run the command 
/cf entity-spawn #pixelmon:animal false source=spawnreason:default

**Screenshot/Video**
(If it doesn't exist you can ignore it)

**Comment by XionioXMaster** [comment]
Isn't this a plugin issue? He's tailor-made for this release Sponge version

**Comment by VOrlando520** [comment]
> Isn't this a plugin issue? He's tailor-made for this release Sponge version

Not anymore, he has aimed at bukkit/spigot and hybrids now because sponge refuses to let him sell on site.

**Comment by XionioXMaster** [comment]
I remember that it has a bug with fake entities, for example, Create does not work in private because of this

> > Isn't this a plugin issue? He's tailor-made for this release Sponge version
> 
> Not anymore, he has aimed at bukkit/spigot and hybrids now because sponge refuses to let him sell on site.

**Comment by VOrlando520** [comment]
opening a new issue/request instead of this
