### ISSUE TITLE
[1.18.2] Create, Biome'o planty mod

### ISSUE THREAD

**Issue by DonorKrovi** [Luohuayu/CatServer#613]
**Environment**

Minecraft version(1.12.2/1.16.5/1.18.2): 1.18.2
Build version(Get from /version command): CatServer-1.18.2-a7b30f8e-server.jar Build: 37
Mods/Plugins: Create, Biome'o planty

**Describe the bug**
This is a very strange bug, it puts a random block from any mod, and any shape, instead of the desired block!

**Expected behavior**
place normal block

**To Reproduce**
select any block from the mods above

**Screenshot/Video**
(If it doesn't exist you can ignore it)

**Comment by XionioXMaster** [comment]
https://github.com/Luohuayu/CatServer/issues/559
I'm assuming this is a duplicate?

**Comment by Kotori0629** [comment]
#559 Same
