### ISSUE TITLE
[1.16.5] withUnderlined using official mappings is a NoSuchMethodError

### ISSUE THREAD

**Issue by VOrlando520** [Luohuayu/CatServer#614]
**Environment**

Minecraft version(1.12.2/1.16.5/1.18.2): 1.16.5
Build version(Get from /version command): c9bc6751
Mods/Plugins: 

Plugins - https://pastebin.com/k66NYjf6
Mods - Pixelmon 9.0.8

**Describe the bug**
On Minecraft 1.16.5, a Forge mod that calls "Style#setUnderlined(Boolean)" using official mappings (so it maps the function to func_244282_c) throws NoSuchMethodError. It works fine on a Forge environment"

https://pastebin.com/U59zeLRz

**Expected behavior**
Running a command that calls on that function to open gui, run command, etc.

**To Reproduce**
Use any plugin that calls upon that function and it will crash/cause an NPE

**Screenshot/Video**
(If it doesn't exist you can ignore it)

**Comment by Kotori0629** [comment]
`   @OnlyIn(Dist.CLIENT)
   public Style withUnderlined(@Nullable Boolean p_244282_1_) `

**Comment by VOrlando520** [comment]
Is this meant to be fixed client side or is it a more in depth fix in catserver itself?

**Comment by Kotori0629** [comment]
Please package plugins and mods

**Comment by VOrlando520** [comment]
Use that code that you pasted within plug-ins and mods or you want me to upload my plug-ins and mods here?

**Comment by Kotori0629** [comment]
> Use that code that you pasted within plug-ins and mods or you want me to upload my plug-ins and mods here?

Yes, upload your plugins & mods

**Comment by VOrlando520** [comment]
Sorry, there are some custom things in there that I wont upload here for everyone to download and use. Those are the same plugins that are having issue stated above.

**Comment by Kotori0629** [comment]
> Sorry, there are some custom things in there that I wont upload here for everyone to download and use. Those are the same plugins that are having issue stated above.

Only the mod/plugin that reports the error is required

**Comment by VOrlando520** [comment]
[plugins.zip](https://github.com/Luohuayu/CatServer/files/9501040/plugins.zip)

Here you go

**Comment by Kotori0629** [comment]
You should contact the plugin author, please do not call methods annotated with OnlyIn(Dist.CLIENT)
