### ISSUE TITLE
[1.16.5] WorldGuard skips damage to players if PVP is disabled on the region.

### ISSUE THREAD

**Issue by MrJorman** [Luohuayu/CatServer#618]
**Environment**

Minecraft version(1.12.2/1.16.5/1.18.2): 1.16.5
Build version(Get from /version command): latest
Mods/Plugins: WorldGuard, WorldEdit

**Describe the bug**
(If there is an error, please attach the pastebin link) ./rg flag (region) pvp deny and attack other players.. WorldGuard skips damage to players if PVP is disabled on the region.

**Expected behavior**

**To Reproduce**

**Screenshot/Video**
(If it doesn't exist you can ignore it)

**Comment by Kotori0629** [comment]
I think duplicated with #548
