### ISSUE TITLE
[1.16.5] Add tick source

### ISSUE THREAD

**Issue by VOrlando520** [Luohuayu/CatServer#619]
This is a request for support in adding API into retrieving the current ticking block, entity, or tileentity.
This will allow protection plugins, such as GriefDefender, to provide event causes where no source information exists within the event.
An example for this use case is with the mod Pixelmon. When a player throws a pokeball, the EntitySpawnEvent just passes the standard SpawnReason.DEFAULT which is also what is passed for natural spawns. Need to be able to query Catserver for the ticking projectile then it can pass the projectile as a source instead and thus allow admins the ability to control spawns based on a proper source.

**Comment by VOrlando520** [comment]
Something along the lines of a simple TickTracker interface that provides the following methods to start it off

    /**
     * Retrieves the current ticking source.
     *
     * @return The current ticking source
     */
    Object getTickingSource();

    /**
     * Retrieves the current ticking {@link Entity}.
     *
     * @return The current ticking entity, if available
     */
    @Nullable Entity getTickingEntity();

    /**
     * Retrieves the current ticking {@link Block}.
     *
     * @return The current ticking block, if available
     */
    @Nullable Block getTickingBlock();

    /**
     * Retrieves the current ticking {@link TileState}.
     *
     * @return The current ticking tile state, if available
     */
    @Nullable TileState getTickingTileState();

**Comment by Kotori0629** [comment]
Maybe due to language differences, I can't understand in detail from your description. You should be able to initiate a Pull request

**Comment by VOrlando520** [comment]
> Maybe due to language differences, I can't understand in detail from your description. You should be able to initiate a Pull request

It is something like this
https://github.com/ArclightPowered/api/pull/2/files

so that plugins like GriefDefender can hook into it and see forge mod entity spawning sources and blocks to allow more in depth use of their plugin

**Comment by Kotori0629** [comment]
[CatServer-1.16.5-c9bc6751-server.zip](https://github.com/Luohuayu/CatServer/files/9532404/CatServer-1.16.5-c9bc6751-server.zip)

Try this, whether your needs are fulfilled.

Use: catserver.server.CatServer.getTickingTracker()

**Comment by Kotori0629** [comment]
> > Maybe due to language differences, I can't understand in detail from your description. You should be able to initiate a Pull request
> 
> It is something like this https://github.com/ArclightPowered/api/pull/2/files
> 
> so that plugins like GriefDefender can hook into it and see forge mod entity spawning sources and blocks to allow more in depth use of their plugin

Hello?

**Comment by VOrlando520** [comment]
It looks like griefdefender would have to add that to their code?
