### ISSUE TITLE
[1.18.2] Make CATSERVER 1.18.2 based on arclight?

### ISSUE THREAD

**Issue by DonorKrovi** [Luohuayu/CatServer#623]
Arclight is a very stable and convenient core, I think your patches based on this core will create a miracle!

**Comment by Kotori0629** [comment]
Maybe in future versions, we will consider using the same Mixin method as Arclight to implement the Minecraft server, but we will not consider the patch based on Arclight and adding CatServer for the time being. Your proposal is very good, but it will not be accepted for a short time. Thank you Suggest
