### ISSUE TITLE
[1.12.2] 作者是个傻逼！专门盗我号给他自己刷星星！干！

### ISSUE THREAD

**Issue by luluchou** [Luohuayu/CatServer#625]
作者是个傻逼！专门盗我号给他自己刷星星！干！

**Comment by Kotori0629** [comment]
不是第一回了, 上一次也有人发了个issues说被盗号然后来点star了。 目前不太清楚啥情况, 不过有关注到部分交易平台上出售Github 星星。建议开启账号二次验证以保全账号安全性

#530

**Comment by Kotori0629** [comment]
顺便 没搞清事实真相随意网络谩骂, 你是真的没教养
