### ISSUE TITLE
[1.12.2] Server crashes using OpenJ9 updated versions.

### ISSUE THREAD

**Issue by Zilacon** [Luohuayu/CatServer#627]
As ive been discussing here: https://github.com/eclipse-openj9/openj9/issues/15912
The server will crash if i attempt to update the java version to any build they have available thats different from the current build im running.

I am currently running 0.26.0 302, which works, but going down to 292, or anything higher will result in a crash on multiple servers.
On 2 servers the error seems to be similar as both crash from NPE's. One server is caused by ChocolateQuestReforged and another is ThaumicAugmentation.

As stated on the issue to the OJ9 team ive tested both OpenJDK Hotspot (Temurin) and OpenJ9 variations of java.

This is being run on a server using Lubuntu 22.04 x64.
I have provided multiple server logs in the issue posted above.
I am trying to track down what is causing this issue, any help would be appreciated.

Side note: I have updated my java to 0.31.1 8u345b01 on my 1.5.2/1.6.4 MCPC servers and 1.7.10 Crucible servers, and all 13 of them started up and run just fine with the latest version of java. This issue seems to be only with Cat Server.

**Comment by Zilacon** [comment]
Some further testing seems to be an issue with event.getWorld()

**Comment by Zilacon** [comment]
Further further testing reveals it works just fine as long as its a fresh world.
Its only with old worlds that it errors and crashes with...

**Comment by Luohuayu** [comment]
It looks like EnderIO is causing the exception in ThaumicAugmentation. It should have nothing to do with CatServer, please report to the MOD author. Or use other Java.
