### ISSUE TITLE
[1.16.5] Remaining core bugs

### ISSUE THREAD

**Issue by MrJorman** [Luohuayu/CatServer#632]
**Environment**

Minecraft version(1.12.2/1.16.5/1.18.2): 1.16.5
Build version(Get from /version command): Build #33
Mods/Plugins: WorldGuard, WorldEdit 1.16.5 version

**Describe the bug**
**1.** In other region WorldGuard can place beds, doors and long flowers.
**2.** In regions, it is possible to deal damage to players, even if PVP is turned off in the region.
**3.** The border of the world does not work after restart server in other worlds (edge, hell and twilight forest)

**Comment by Kotori0629** [comment]
I know, 

Problem 3 maybe cannot fix.
Problem 2 duplicated with #548 
Problem 1 you can write a plugin to fix this, listening BlockPlaceEvent, deny these things

I will close this issues, because all problem already exsit.
