### ISSUE TITLE
[1.12.2] server crash

### ISSUE THREAD

**Issue by Voncerpero** [Luohuayu/CatServer#635]
Today I cant run my server but yesterday I just play minecraft with my friend
I used this mod https://www.curseforge.com/minecraft/mc-mods/scape-and-run-parasites

This is my crash report
[crash-2565-10-07_09.24.14-server.txt](https://github.com/Luohuayu/CatServer/files/9730306/crash-2565-10-07_09.24.14-server.txt)

**Comment by Kotori0629** [comment]
It looks more like you used ipv6, but the cause of the crash is Unknown host
I think you should check the settings of ipv6

**Comment by Luohuayu** [comment]
Check `server-ip` option of `server.properties` file
