### ISSUE TITLE
[1.16.5] 死亡箱子无法正确获取背包物品

### ISSUE THREAD

**Issue by Baikele** [Luohuayu/CatServer#636]
**运行环境**

Minecraft版本(1.12.2/1.16.5/1.18.2):  1.16.5
构建版本(从/version指令获取): CatServer-1.16.5-ee53094b
相关模组/插件: AngelChest

**描述这个BUG**
(如果有报错请附上pastebin链接或上传日志文件)

**导致的问题r**

**复现方法**
背包东西满了，4行，然后如果副手或者装备栏，有东西会掉在地上，但是spigot测试，会进入箱子

**截图/视频**
(如果没有可以忽略)

https://pan.fastmirror.net/s/K7PTM

**Comment by Luohuayu** [comment]
与 #454 重复 待修复
