### ISSUE TITLE
[1.16.5] Spigot 事件总线 ChunkLoadEvent ChunkUnloadEvent ChunkPopulateEvent 未正常触发

### ISSUE THREAD

**Issue by NattoCB** [Luohuayu/CatServer#639]
**运行环境**
jdk-17.0.1.12-hotspot

Minecraft版本: 1.16.5
构建版本(从/version指令获取): ee53094b Oct 7, 2022 4:11 AM

相关模组/插件: 无mod，单纯插件开发，测试了一下 Chunk相关事件的 Spigot Listener

**描述这个BUG**
Chunk Load / Unload / Populate 时，对应的 Spigot Listener 不触发 
但在官方 spigot 1.16.5 插件核心中测试，三个 Chunk 事件照常触发

**导致的问题r**
插件中 chunk 相关的功能无法正常运行

**复现方法**
1. 下载 spigot 插件服核心
如：https://cdn.getbukkit.org/spigot/spigot-1.16.5.jar
2. 写一个具有 chunk 相关 listener 的插件
```java
public class MyPlugin extends JavaPlugin {
    @Override
    public void onEnable() {
        Bukkit.getPluginManager().registerEvents(new ChunkListener(), this);
    }
}
public class ChunkListener implements Listener {
    @EventHandler
    public void onChunkLoad(ChunkLoadEvent e) {
        // logger output test
    }
    @EventHandler
    public void onChunkUnLoad(ChunkUnloadEvent e) {
        // logger output test
    }
    @EventHandler
    public void onChunkPopulate(ChunkPopulateEvent e) {
        // logger output test
    } 
    /** 其他 WorldEvent 未测试，目前仅测试了上述这几个 */
}
```
3. 分别在 CatServer 和 Spigot 插件端对比运行插件
玩家登录后在世界正常行走。会发现 cat 端无日志输出，spigot端有输出

**Comment by Kotori0629** [comment]
![image](https://user-images.githubusercontent.com/81866089/216815278-5fe69a1b-ea91-4154-90af-f2c4ef0444a8.png)
修复完毕, 请等待更新推送

**Comment by NattoCB** [comment]
强！




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年2月5日(星期天) 晚上7:06
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Luohuayu/CatServer] [1.16.5] Spigot 事件总线 ChunkLoadEvent ChunkUnloadEvent ChunkPopulateEvent 未正常触发 (Issue #639)





 

 修复完毕, 请等待更新推送
