### ISSUE TITLE
作者专门盗我号给他自己刷星星！

### ISSUE THREAD

**Issue by NicoleSherwood** [Luohuayu/CatServer#640]
道德败坏，脑子有问题吧？
道德败坏，脑子有问题吧？
道德败坏，脑子有问题吧？
道德败坏，脑子有问题吧？
道德败坏，脑子有问题吧？
道德败坏，脑子有问题吧？
道德败坏，脑子有问题吧？
道德败坏，脑子有问题吧？
道德败坏，脑子有问题吧？
道德败坏，脑子有问题吧？
道德败坏，脑子有问题吧？
道德败坏，脑子有问题吧？

**Comment by Kotori0629** [comment]
又来了又来了又来了又来了又来了又来了又来了又来了又来了又来了又来了又来了又来了又来了又来了又来了又来了又来了又来了又来了又来了又来了又来了又来了又来了又来了又来了又来了又来了又来了又来了又来了又来了又来了又来了又来了又来了又来了又来了又来了又来了又来了又来了又来了又来了又来了又来了又来了又来了又来了又来了又来了又来了又来了又来了又来了又来了又来了又来了又来了又来了又来了

#530
