### ISSUE TITLE
[1.16.5] cpw 类加载器抢走了 bukkit 的类

### ISSUE THREAD

**Issue by NattoCB** [Luohuayu/CatServer#642]
**运行环境**

Minecraft版本(1.12.2/1.16.5/1.18.2): 1.16.5
构建版本(从/version指令获取):   ee53094b Oct 7, 2022 4:11 AM
相关模组/插件:  无模组，spigot白板插件一个，只有如下代码的功能

**描述这个BUG**
```java
class org.bukkit.craftbukkit.v1_16_R3.block.CraftBlockState
cannot be cast to class org.bukkit.block.Sign
 (
org.bukkit.craftbukkit.v1_16_R3.block.CraftBlockState
and org.bukkit.block.Sign
are in unnamed module of loader
    cpw.mods.modlauncher.TransformingClassLoader @18da4dd
)
```
可以看到是 cpw 的类加载器，把 bukkit 的类抢走去加载了，以至于 spigot 的插件类加载器（SimplePluginClassLoader）认不出这些bukkit 类，而抛出 ClassCastException，导致插件崩溃
我在插件中的代码是：
```java
if (b2.getState() instanceof Sign) {
    String[] lines = ((Sign) b2.state).getLines();
    for (int i = 0; i < lines.length; i++) {
        ((Sign) b1.getState()).setLine(i, lines[i]);
    }
}
```
其中 b1 和 b2 是两个 "org.bukkit.Block" 实例

==================

此外，还有一些严重的ClassCastException问题我不知道是不是与这个也有联系
[Spigot帖子地址](https://www.spigotmc.org/threads/spigot-classloaders-classcastexception-is-so-weird.576353/)

比如某个类无法 cast 成他自己，或者某个子类无法 cast 它父类/接口，因为它们同时被 **两个** Spigot 的 PluginClassLoader 的实例所加载（具体错误信息见帖子）

刚才把这些问题整理发到上面的 spigot 链接去论坛提问了，也是在刚才写提问的时候突然看到 cpw 这个字眼，才想到来这里提 issue 问一问的。

==================

**导致的问题**
插件崩溃

**复现方法**
见描述

**Comment by Kotori0629** [comment]
有相同情况， 类似于MapMeta与ItemMeta也会有转换异常

**Comment by Kotori0629** [comment]
我就先标为Bug了

**Comment by Luohuayu** [comment]
无法复现, 请提供完整的报错信息再重新创建issues
TransformingClassLoader是Forge端类加载器, CatServer的Bukkit相关类也使用该类加载器
