### ISSUE TITLE
[1.16.5] 经验掉进末地传送门时导致服务器崩溃

### ISSUE THREAD

**Issue by McAZero** [Luohuayu/CatServer#643]
**运行环境**

Minecraft版本(1.12.2/1.16.5/1.18.2): 1.16.5
构建版本(从/version指令获取): CatServer-1.16.5-ee53094b-server.jar
相关模组/插件: 

**描述这个BUG**
经验掉进末地传送门时导致服务器崩溃
CatServer-1.16.5-c9bc6751-server.jar 这个版本测试不会
CatServer-1.16.5-ee53094b-server.jar 这个版本会
https://paste.ubuntu.com/p/58XJ3j6StX/
(如果有报错请附上pastebin链接或上传日志文件)

**导致的问题**
null

**复现方法**
经验掉进末地传送门时导致服务器崩溃

**截图/视频**
(如果没有可以忽略)

**Comment by Kotori0629** [comment]
已修复 待合并

**Comment by Kotori0629** [comment]
#641 重复
