### ISSUE TITLE
[1.12.2] bungeeguard not working / 沒有作用

### ISSUE THREAD

**Issue by leonpano2006** [Luohuayu/CatServer#645]
bungeeguard is not working at all
fells like catserver ingored bungeeguard

**Comment by Kotori0629** [comment]
bungeeguard？

bungeecord?

https://github.com/lucko/BungeeGuard It's this?

**Comment by leonpano2006** [comment]
Yes

**Comment by Luohuayu** [comment]
It only works on Paper

**Comment by leonpano2006** [comment]
> It only works on Paper

不可能吧
我指的是那個插件，安裝後沒有作用
不然的話你也可以考慮把bungeeguard的功能整合進去catserver

**Comment by Luohuayu** [comment]
> > It only works on Paper
> 
> 不可能吧 我指的是那個插件，安裝後沒有作用 不然的話你也可以考慮把bungeeguard的功能整合進去catserver

https://github.com/lucko/BungeeGuard/blob/master/bungeeguard-spigot/src/main/java/me/lucko/bungeeguard/spigot/listener/PaperHandshakeListener.java#L67

Paper API

**Comment by leonpano2006** [comment]
> > > It only works on Paper
> 
> > 
> 
> > 不可能吧 我指的是那個插件，安裝後沒有作用 不然的話你也可以考慮把bungeeguard的功能整合進去catserver
> 
> 
> 
> https://github.com/lucko/BungeeGuard/blob/master/bungeeguard-spigot/src/main/java/me/lucko/bungeeguard/spigot/listener/PaperHandshakeListener.java#L67
> 
> 
> 
> Paper API

你根本就沒有回答我完整的問題
能不能把那個插件的功能整合進去?
