### ISSUE TITLE
[1.16.5] dynmap loading error

### ISSUE THREAD

**Issue by Tealwen** [Luohuayu/CatServer#646]
**Environment**

Minecraft version(1.12.2/1.16.5/1.18.2): 1.16.5
Build version(Get from /version command):  This server is running CatServer version 1.16.5-a76056a9 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT, Forge version 36.2.39)
Mods/Plugins: 
Plugins (23): PINPrompt, PlaceholderAPI, AzLink, Vault, UltraPermissions, PvPToggle, ConsoleSpamFix, LoneLibs, ProtocolLib, dynmap, WorldEdit, TheNewEconomy, CMILib, Towny, RedProtect, Dynmap-Towny, CMI, SiegeWar, ItemsAdder, TabList, Shop, SpecializedCrates, RPGMoney

Mod List:
• mods_folder BetterDungeons-1.16.4-1.2.1.jar : betterdungeons (1.16.4-1.2.1) - 1
• mods_folder immersivecooking-1.2.0.jar : immersivecooking (1.2.0) - 1
• mods_folder auudio_forge_1.0.3-1_MC_1.16.2-1.16.5.jar : auudio (1.0.3) - 1
• mods_folder infernal-expansion-1.16.5-2.5.0.jar : infernalexp (2.5.0) - 1
• mods_folder strawgolem-1.16-1.9.jar : strawgolem (1.16-1.9) - 1
• mods_folder Neat 1.7-27.jar : neat (1.7-27) - 1
• mods_folder BetterCaves-Forge-1.16.4-1.1.2.jar : bettercaves (1.16.4-1.1.2) - 1
• mods_folder farmersdelightintegrations-1.16.5-1.2.jar : farmersdelightintegrations (1.16.5-1.2) - 1
• mods_folder YungsApi-1.16.4-Forge-13.jar : yungsapi (1.16.4-Forge-13) - 1
• mods_folder randompatches-2.4.4-forge.jar : randompatches (2.4.4-forge) - 1
• mods_folder Apotheosis-1.16.5-4.8.9A0.jar : apotheosis (4.8.9A0) - 1
• mods_folder abyg-1.2-forge.jar : bygvanillabiomes (1.0.0) - 1
• mods_folder PickUpNotifier-v1.2-1.16.3.jar : pickupnotifier (1.2) - 1
• mods_folder SnowRealMagic-1.16.4-2.9.0.jar : snowrealmagic (2.9.0) - 1
• mods_folder RevampedWolf-1.16.4-0.7.1.jar : revampedwolf (1.16.4-0.7.1) - 1
• mods_folder supplementaries-1.16.5-0.18.4b.jar : supplementaries (0.18.2) - 1
• mods_folder betterendforge-1.16.5-2.5.jar : betterendforge (1.16.5-2.5) - 1
• mods_folder structure_gel-1.16.5-1.7.8.jar : structure_gel (1.7.8) - 1
• mods_folder cleancut-mc1.16-2.2-forge.jar : cleancut (2.2) - 1
• mods_folder repurposed_structures_forge-3.4.7+1.16.5.jar : repurposed_structures (3.4.7+1.16.5) - 1
• mods_folder morevillagers-FORGE-1.16.5-1.5.5.jar : morevillagers (1.5.5) - 1
• mods_folder BetterCompatibilityChecker-1.0.7-build.22+mc1.16.5.jar : bcc (1.0.7-build.22+mc1.16.5) - 1
• mods_folder Aquamirae+3.0.0.jar : ob_aquamirae (3.0.0) - 1
• mods_folder dungeons_plus-1.16.5-1.1.5.jar : dungeons_plus (1.1.5) - 1
• mods_folder YungsBridges-Forge-1.16.4-1.0.1.jar : yungsbridges (1.16.4-1.0.1) - 1
• mods_folder cavesandcliffs-1.16.5-7.2.0.jar : cavesandcliffs (1.16.5-7.2.0) - 1
• mods_folder Divine_Missions-1.16.5-1.0.1.jar : divine_missions (NONE) - 1
• mods_folder Highlighter-1.16.5-1.1.1.jar : highlighter (1.1.1) - 1
• mods_folder textrues_rubidium_options-1.0.3-mc1.16.5.jar : reeses_sodium_options (1.0.3-mc1.16.5) - 1
• mods_folder curios-forge-1.16.5-4.0.8.2.jar : curios (1.16.5-4.0.8.2) - 1
• mods_folder Origins-1.16.5-0.7.3.9-forge.jar : origins (0.7.3.9) - 1
• mods_folder Infinite_Dungeons-1.16.5-1.0.9.jar : infinite_dungeons (NONE) - 1
• mods_folder mutantmore-1.16.5-1.0.1.jar : mutantmore (1.0.3) - 1
• mods_folder forestcraft-1.87.jar : forestcraft (1.87) - 1
• mods_folder Adorn-1.14.3+1.16.5-forge.jar : adorn (1.14.3+1.16.5-forge) - 1
• mods_folder cloth-config-4.16.91-forge.jar : cloth-config (4.16.91) - 1
• mods_folder BetterBurning-1.16.5-6.0.8.jar : betterburning (6.0.8) - 1
• mods_folder CustomStartingGear-1.16.5-2.0.3-universal.jar : customstartinggear (2.0.3.1) - 1
• mods_folder Babel-1.0.5.jar : babel (1.0.5) - 1
• mods_folder BetterMineshafts-Forge-1.16.4-2.0.4.jar : bettermineshafts (1.16.4-2.0.4) - 1
• mods_folder veinmining-forge-1.16.5-0.16.jar : veinmining (1.16.5-0.16) - 1
• mods_folder SimpleDiscordRichPresence-1.4.0-build.3+mc1.16.5.jar : sdrp (1.4.0-build.3+mc1.16.5) - 1
• mods_folder BetterModsButton-v1.0.5-1.16.5-Forge.jar : bettermodsbutton (1.0.5) - 1
• mods_folder DarkPaintings-1.16.5-6.0.11.jar : darkpaintings (6.0.11) - 1
• mods_folder treasure-bags-1.16.5-1.4.1.jar : treasurebags (1.4.1) - 1
• mods_folder Kiwi-1.16.5-3.6.1.jar : kiwi (3.6.1) - 1
• mods_folder mowziesmobs-1.5.25.jar : mowziesmobs (1.5.25) - 1
• mods_folder geckolib-forge-1.16.5-3.0.89.jar : geckolib3 (3.0.89) - 1
• mods_folder humancompanions-1.16.5-1.4.7.jar : humancompanions (1.16.5-1.4.7) - 1
• mods_folder connectiblechains-1.2.0.jar : connectiblechains (NONE) - 1
• mods_folder ConfigMenusForge-v1.2.0-1.16.5-Forge.jar : configmenusforge (1.2.0) - 1
• mods_folder jei-1.16.5-7.7.1.152.jar : jei (7.7.1.152) - 1
• mods_folder VisualWorkbench-v1.1.0-1.16.5.jar : visualworkbench (1.1.0) - 1
• mods_folder The_Graveyard_2.1_(FORGE)_for_1.16.4-1.16.5.jar : graveyard (2.1) - 1
• mods_folder AttributeFix-1.16.5-10.1.4.jar : attributefix (10.1.4) - 1
• mods_folder goblintraders-1.7.3-1.16.5.jar : goblintraders (1.7.3) - 1
• mods_folder caelus-forge-1.16.5-2.1.3.2.jar : caelus (1.16.5-2.1.3.2) - 1
• mods_folder Paxi-Forge-1.16.4-1.0.jar : paxi (1.16.4-1.0) - 1
• mods_folder PassableFoliage-1.16.5-2.4.0.jar : passablefoliage (2.4.0) - 1
• mods_folder Fallingleaves-1.16.3-1.2.4.jar : fallingleaves (1.2.4-alpha+20220121-1744) - 1
• mods_folder NaturesCompass-1.16.5-1.9.1-forge.jar : naturescompass (1.16.5-1.9.1-forge) - 1
• mods_folder SereneSeasons-1.16.5-4.0.1.126-universal.jar : sereneseasons (1.16.5-4.0.1.126) - 1
• mods_folder LibX-1.16.3-1.0.76.jar : libx (1.16.3-1.0.76) - 1
• mods_folder champions-forge-1.16.5-2.0.1.14.jar : champions (1.16.5-2.0.1.14) - 1
• mods_folder curioofundying-forge-1.16.5-5.2.0.0.jar : curioofundying (1.16.5-5.2.0.0) - 1
• mods_folder snowundertrees-1.16.5-v1.3.jar : snowundertrees (v1.3) - 1
• mods_folder sulfuric-1.1.jar : sulfuric (1.0) - 1
• mods_folder crumbs-forge-1.0.7.jar : crumbs (1.0.7) - 1
• maven_libs forge-1.16.5-36.2.39-universal.jar : forge (36.2.39) - 1
• mods_folder Atum-1.16.5-2.2.11.jar : atum (1.16.5-2.2.11) - 1
• mods_folder subwild-1.3.1.jar : subwild (1.3.1) - 1
• minecraft forge-1.16.5-36.2.39-server.jar : minecraft (1.16.5) - 1
• mods_folder added_origins_forgefabric-V2.5.0+-+1.16.5.jar : added_origins_mod (V2.5.0) - 1
• mods_folder MouseTweaks-2.14-mc1.16.2.jar : mousetweaks (2.14) - 1
• mods_folder CavesCliffsBackportAdditions-3.4.jar : cavesandcliffsbackportadditions (3.4) - 1
• mods_folder paintings-1.16.4-7.0.0.1.jar : paintings (1.16.4-6.0.1.5) - 1
• mods_folder gravestone-1.16.5-1.0.6.jar : gravestone (1.16.5-1.0.6) - 1
• mods_folder polymorph-forge-1.16.5-0.40.jar : polymorph (1.16.5-0.40) - 1
• mods_folder AutoRegLib-1.6-49.jar : autoreglib (1.6-49) - 1
• mods_folder backpacked-2.1.8-1.16.5.jar : backpacked (2.1.8) - 1
• mods_folder structurize-1.16.5-1.0.418-ALPHA.jar : structurize (1.16.5-1.0.418-ALPHA) - 1
• mods_folder Library_of_Exile-1.16.5-1.2.3.jar : library_of_exile (NONE) - 1
• mods_folder PuzzlesLib-v1.0.15-1.16.5-Forge.jar : puzzleslib (1.0.15) - 1
• mods_folder byg-1.3.5.jar : byg (1.3.4) - 1
• mods_folder Obscuria's Essentials 3.0.0.jar : ob_core (3.0.0) - 1
• mods_folder tetra-1.16.5-3.20.0.jar : tetra (3.20.0) - 1
• mods_folder tetranomicon-1.3.jar : tetranomicon (1.3) - 1
• mods_folder TreeChop-1.16.4-0.14.6-fixed.jar : treechop (0.14.6) - 1
• mods_folder SkyVillage_1.0.0_1.16.5.jar : skyvillages (1.0.0) - 1
• mods_folder blue_skies-1.16.5-1.1.3.jar : blue_skies (1.1.3) - 1
• mods_folder eidolon-0.2.7.jar : eidolon (0.2.7) - 1
• mods_folder Architects-Palette-1.16.4-1.1.5.jar : architects_palette (1.1.2) - 1
• mods_folder KleeSlabs_1.16.5-9.2.1.jar : kleeslabs (9.2.1) - 1
• mods_folder Afterlight v2.0.jar : the_afterlight (2.0) - 1
• mods_folder Controlling-7.0.0.28.jar : controlling (7.0.0.28) - 1
• mods_folder Prism-1.16.5-1.0.1.jar : prism (1.0.1) - 1
• mods_folder Placebo-1.16.5-4.7.0.jar : placebo (4.7.0) - 1
• mods_folder citadel-1.8.1-1.16.5.jar : citadel (1.8.1) - 1
• mods_folder alexsmobs-1.12.1.jar : alexsmobs (1.12.1) - 1
• mods_folder iceandfire-2.1.11-1.16.5.jar : iceandfire (2.1.11-1.16.5) - 1
• mods_folder MutantBeasts-1.16.4-1.1.3.jar : mutantbeasts (1.16.4-1.1.3) - 1
• mods_folder Bookshelf-Forge-1.16.5-10.4.32.jar : bookshelf (10.4.32) - 1
• mods_folder relics-1.16.5-0.3.4.3.jar : relics (0.3.4.3) - 1
• mods_folder bygonenether-1.2.1-1.16.5.jar : bygonenether (1.2.1) - 1
• mods_folder carryon-1.16.5-1.15.5.22.jar : carryon (1.15.5.22) - 1
• mods_folder MmmMmmMmmMmm-1.16.5-1.3.1.jar : dummmmmmy (1.3.0) - 1
• mods_folder konkrete_forge_1.5.0_MC_1.16.2-1.16.5.jar : konkrete (1.5.0) - 1
• mods_folder EquipmentCompare-1.16.5-1.3.2.jar : equipmentcompare (1.3.2) - 1
• mods_folder chipped-1.16.5-1.2.1-forge.jar : chipped (1.16.5-1.2.1-forge) - 1
• mods_folder chocolate-1.3.0-1.16.4.jar : chocolate (1.3.0-1.16.4) - 1
• mods_folder UndeadExpansion-2.0.0-1.16.5.jar : undead_expansion (2.0.0) - 1
• mods_folder mcw-bridges-2.0.3-mc1.16.5.jar : mcwbridges (2.0.3) - 1
• mods_folder FarmersDelight-1.16.5-0.6.0.jar : farmersdelight (1.16.5-0.6.0) - 1
• mods_folder fd_cookbook-2.0.jar : fd_cookbook (2.0) - 1
• mods_folder culturaldelights-1.16.5-0.9.2.jar : culturaldelights (0.9.2) - 1
• mods_folder farmersdelightintegration-1.16.5-1.0.3.jar : farmersdelightintegration (1.16.5-1.0.3) - 1
• mods_folder farmersrespite-1.16.5-1.1.jar : farmersrespite (1.16.5-1.1) - 1
• mods_folder DustrialDecor-1.3.1.jar : dustrial_decor (1.2.8) - 1
• mods_folder simpleshops-1.1.3.jar : simpleshops (1.1.3) - 1
• mods_folder endrem-5.0.3-R-1.16.5.jar : endrem (5.0.3-R-1.16.5) - 1
• mods_folder dungeons_enhanced-1.16.5-1.8.1.jar : dungeons_enhanced (1.8.1) - 1
• mods_folder Bountiful-1.16.4-3.3.1.jar : bountiful (1.16.4-3.3.1) - 1
• mods_folder playerex-1.1.8-1.16.5.jar : playerex (1.1.8) - 1
• mods_folder Cataclysm-0.20.jar : cataclysm (1.0) - 1
• mods_folder Patchouli-1.16.4-53.3.jar : patchouli (1.16.4-53.3) - 1
• mods_folder Feywild-1.16.5-2.1.3.jar : feywild (1.16.5-2.1.3) - 1
• mods_folder netherhexedkingdom-1.16.5-v1.2.jar : netherhexedkingdom (v1.2) - 1
• mods_folder travelers_index-1.16.4-1.0.2.jar : travelers_index (1.16.4-1.0.2) - 1
• mods_folder cavebiomeapi-1.16.5-1.4.2.jar : cavebiomeapi (1.16.5-1.4.2) - 1
• mods_folder architectury-1.32.66.jar : architectury (1.32.66) - 1
• mods_folder ftb-library-forge-1605.3.4-build.90.jar : ftblibrary (1605.3.4-build.90) - 1
• mods_folder ftb-teams-forge-1605.2.3-build.40.jar : ftbteams (1605.2.3-build.40) - 1
• mods_folder curiouselytra-forge-1.16.5-4.0.2.4.jar : curiouselytra (1.16.5-4.0.2.4) - 1
• mods_folder AI-Improvements-1.16.5-0.5.0.jar : aiimprovements (0.4.0) - 1
• mods_folder AdvancedCompas-forge-1.16.5-1.2.11.jar : advancedcompass (1.2.11) - 1
• mods_folder TradingPost-v1.0.2-1.16.5.jar : tradingpost (1.0.2) - 1
• mods_folder dreadsteel-1.16.5-1.1.1.jar : dreadsteel (1.16.5-1.1.1) - 1
• mods_folder BetterAdvancements-1.16.5-0.1.1.115.jar : betteradvancements (0.1.1.115) - 1
• mods_folder BH-Menu-1.16.5-1.3.jar : bhmenu (1.16.5-1.3) - 1
• mods_folder jmi-1.16.5-0.8.1-47.jar : jmi (1.16.5-0.8.1-47) - 1
• mods_folder woodcuttercompats-1.16-1.2.jar : woodcuttercompats (1.16-1.2) - 1
• mods_folder Shrines-1.16.5-2.3.0.jar : shrines (1.16.5-2.3.0) - 1
• mods_folder NourishedNetherV12-1.16.5Backport.jar : nourished_nether (1.1.3) - 1
• mods_folder item-filters-forge-1605.2.5-build.9.jar : itemfilters (1605.2.5-build.9) - 1
• mods_folder ftb-quests-forge-1605.3.6-build.98.jar : ftbquests (1605.3.6-build.98) - 1
• mods_folder EasyMagic-v1.0.4-1.16.5.jar : easymagic (1.0.4) - 1
• mods_folder NourishedEndV9-1.16.5Backport.jar : nourished_end (1.0.8) - 1
• mods_folder Druidcraft-1.16.5-0.4.54.jar : druidcraft (0.4.52) - 1
• mods_folder the-conjurer-1.16.4-1.0.13.jar : conjurer_illager (1.0.13) - 1
• mods_folder Soaring-Structures-2-1.16.5-2.0.jar : soaringstructures2 (1.16.5 - 2.0) - 1
• mods_folder abnormals_core-1.16.5-3.3.1.jar : abnormals_core (3.3.1) - 1
• mods_folder environmental-1.16.5-1.1.1.jar : environmental (1.1.1) - 1
• mods_folder bamboo_blocks-1.16.5-3.0.1.jar : bamboo_blocks (3.0.1) - 1
• mods_folder copperpot-1.16.5-1.2.0.jar : copperpot (1.16.5-1.2.0) - 1
• mods_folder Bayou-Blues-1.16.5-1.0.5.jar : bayou_blues (1.16.5-1.0.5) - 1
• mods_folder irregularchef-1.16.5-1.0.1.jar : irregularchef (1.16.5-1.0.1) - 1
• mods_folder endergetic-1.16.5-3.0.2.jar : endergetic (3.0.2) - 1
• mods_folder neapolitan-1.16.5-2.2.1.jar : neapolitan (2.2.1) - 1
• mods_folder personality-1.16.5-1.0.3.jar : personality (1.0.3) - 1
• mods_folder savageandravage-1.16.5-3.2.0.jar : savageandravage (3.2.0) - 1
• mods_folder nethers_delight-2.1.jar : nethers_delight (2.1) - 1
• mods_folder buzzier_bees-1.16.5-3.0.3.jar : buzzier_bees (3.0.3) - 1
• mods_folder Waystones_1.16.5-7.6.4.jar : waystones (7.6.4) - 1
• mods_folder MerchantMarkers-1.16.5-1.2.2.jar : merchantmarkers (1.2.2) - 1
• mods_folder Clumps-6.0.0.28.jar : clumps (6.0.0.28) - 1
• mods_folder mgui-1.16.5-3.3.0.jar : mgui (3.3.0) - 1
• mods_folder tetrapak-1.16.5-0.3.4.jar : tetrapak (1.16.5-0.3.4) - 1
• mods_folder journeymap-1.16.5-5.8.5p5.jar : journeymap (5.8.5p5) - 1
• mods_folder SimpleStorageNetwork-1.16.5-1.5.3.jar : storagenetwork (1.16.5-1.5.3) - 1
• mods_folder OuterEnd-0.2.14.jar : outer_end (0.2.9) - 1
• mods_folder decorative_blocks-1.16.4-1.7.2.jar : decorative_blocks (1.7.2) - 1
• mods_folder decorative_blocks_abnormals-1.2.jar : decorative_blocks_abnormals (1.2) - 1
• mods_folder BadMobs-1.16.5-9.1.8.jar : badmobs (9.1.8) - 1
• mods_folder Obscuria's Tooltips 1.0.0.jar : ob_tooltips (1.0.0) - 1
• mods_folder lazydfu-0.1.3.jar : lazydfu (0.1.3) - 1
• mods_folder TroubleRPG_1.16.5_v_0.1.1.jar : trouble_rpg (1.0.0) - 1
• mods_folder ftb-chunks-forge-1605.3.2-build.115.jar : ftbchunks (1605.3.2-build.115) - 1
• mods_folder 3dSkinLayers-forge-1.1.0.jar : skinlayers3d (1.1.0) - 1
• mods_folder TravelersTitles-1.16.4-1.5.jar : travelerstitles (1.16.4-1.5) - 1
• mods_folder twist-1.4.1.jar : twist (4.0.0) - 1
• mods_folder selene-1.16.5-1.9.0.jar : selene (1.16.5-1.0) - 1
• mods_folder BrassAmberBattleTowers-1.16.5-1.6.3.jar : ba_bt (1.16.5-1.6.3) - 1
• mods_folder EnchantmentDescriptions-1.16.5-7.1.20.jar : enchdesc (7.1.20) - 1
• mods_folder silent-lib-1.16.5-4.10.0.jar : silentlib (4.10.0) - 1
• mods_folder Jade-1.16.4-2.8.3.jar : jade (2.8.3) - 2
• mods_folder CreativeCore_v2.2.1_mc1.16.5.jar : creativecore (2.0.0) - 1
• mods_folder atmospheric-1.16.5-3.1.1.jar : atmospheric (3.1.1) - 1
• mods_folder Iceberg-1.16.5-1.0.45.jar : iceberg (1.0.45) - 1
• mods_folder Quark-r2.4-322.jar : quark (r2.4-322) - 1
• mods_folder abnormals_delight-1.16.5-1.2.1.jar : abnormals_delight (1.2.1) - 1
• mods_folder performant-1.16.2-5-3.99m.jar : performant (3.73m) - 1
• mods_folder combustivefishing-forge-1.16.3-4.0.0.1.jar : combustivefishing (1.16.3-4.0.0.1) - 1
• mods_folder fancymenu_forge_2.12.1_MC_1.16.2-1.16.5.jar : fancymenu (2.12.1) - 1
• mods_folder drippyloadingscreen_forge_1.6.4_MC_1.16.2-1.16.5.jar : drippyloadingscreen (1.6.4) - 1
• mods_folder minecolonies-1.16.5-1.0.978-RELEASE.jar : minecolonies (1.16.5-1.0.978-RELEASE) - 1
• mods_folder ferritecore-2.1.0-forge.jar : ferritecore (2.1.0) - 1
• mods_folder enhancedcelestials-2.0.9-1.16.5.jar : enhancedcelestials (2.0.9-1.16.5) - 1
• mods_folder valhelsia_core-16.0.15.jar : valhelsia_core (16.0.15) - 1
• mods_folder forbidden_arcanus-16.2.3.jar : forbidden_arcanus (16.2.3) - 1
• mods_folder drinkbeer-1.16.5-2.3.5.jar : drinkbeer (2.3.5) - 1

**Describe the bug**
[https://mcpaste.com/617f145854717416c498fd63a3abf709](https://mcpaste.com/617f145854717416c498fd63a3abf709)
dynmap loading error and the map is full black and rendering anything
**Expected behavior**

**To Reproduce**

**Screenshot/Video**
link of my dynmap : [Link](http://46.105.233.114:30040/)

**Comment by Kotori0629** [comment]
![image](https://user-images.githubusercontent.com/81866089/196729286-3cdbb918-1f17-4841-b6a8-b189ba31572c.png)
Dynmap work normaly
