### ISSUE TITLE
[1.16.5]divinerpg取不到env了这次又抛空崩服

### ISSUE THREAD

**Issue by haozaizai1** [Luohuayu/CatServer#649]
[crash-2022-10-26_19.18.01-server.txt](https://github.com/Luohuayu/CatServer/files/9887591/crash-2022-10-26_19.18.01-server.txt)
[crash-2022-10-27_15.21.30-server.txt](https://github.com/Luohuayu/CatServer/files/9887599/crash-2022-10-27_15.21.30-server.txt)

**Comment by Kotori0629** [comment]
这会应该是修复了吧
