### ISSUE TITLE
BQ任务完成，命令的执行方式和单机的不一样

### ISSUE THREAD

**Issue by Coloryr** [Luohuayu/CatServer#65]
有个BQ任务是这样写的：
`"rewards:9":{`
`        "0:10": {`
`          "hideCommand:1": 0,`
`          "rewardID:8": "bq_standard:command",`
`          "viaPlayer:1": 0,`
`          "index:3": 0,`
`          "command:8": "/gamestage add @p bot_life_essence"`
`        }`
`      }`
如果需要指令能执行的话需要去掉'/'，希望能修一下这个bug

**Comment by Luohuayu** [comment]
非服务端问题, 请自行修改指令使用
