### ISSUE TITLE
[1.12.2] 玩家进入时会崩服

### ISSUE THREAD

**Issue by OldGodShen** [Luohuayu/CatServer#650]
**运行环境**

Minecraft版本(1.12.2/1.16.5/1.18.2): 1.12.2
构建版本(从/version指令获取): CatServer-dae70adc-universal
相关模组/插件: pokehaan-craft

**描述这个BUG**
(如果有报错请附上pastebin链接或上传日志文件)
https://paste.ubuntu.com/p/6XXh2sRKwg/
https://paste.ubuntu.com/p/zMP39m6b8r/

**导致的问题r**
崩服

**复现方法**
开服完成后有玩家进入

**截图/视频**
(如果没有可以忽略)

**Comment by Kotori0629** [comment]
你装了俩teslacore

**Comment by Luohuayu** [comment]
teslacorelib重复
