### ISSUE TITLE
[1.18.2] 模组 Diet(均衡饮食) 不起作用

### ISSUE THREAD

**Issue by YongAn404** [Luohuayu/CatServer#651]
**运行环境**

Minecraft版本:1.18.2
构建版本: Implementing API version 1.18.2-R0.1-SNAPSHOT, Forge version 40.1.73)
相关模组: Diet

**描述这个BUG**
我觉得是服务端的问题，但是我无法确定
[crafttweaker.log](https://github.com/Luohuayu/CatServer/files/9893502/crafttweaker.log)
[debug.log](https://github.com/Luohuayu/CatServer/files/9893503/debug.log)
[latest.log](https://github.com/Luohuayu/CatServer/files/9893504/latest.log)

**导致的问题**
模组功能无效

**复现方法**
开启服务器开始

**截图/视频**
正常来说会有五个数值条，但是并没有出现
![1](https://user-images.githubusercontent.com/101850798/198827275-420e0cf7-5d7f-4bfa-8871-11b5c70f48fc.png)

**Comment by Kotori0629** [comment]
The rebirth version 1.18.2 will be merged soon, please test after merging, if you find the same problem, please resubmit!
