### ISSUE TITLE
[1.16.5] Double slash commands in mods are not supported

### ISSUE THREAD

**Issue by andriihorpenko** [Luohuayu/CatServer#654]
**Environment**

Minecraft version(1.12.2/1.16.5/1.18.2): **1.16.5**
Build version(Get from /version command): a76056a
Mods/Plugins: **WorldEdit Forge 7.2.5**

**Describe the bug**
WorldEdit (Forge edition) returns `Unknown or incomplete command, see below for error` when trying to use any of its double-slash commands. Everything works fine on the alternative server cores (Mohist, Magma), but won't work on CatServer. It is worth noting that the Bukkit version of WorldEdit works fine.

**Expected behavior**
Double slash commands ae expected to work

**To Reproduce**
- Install WorldEdit Forge 7.2.5
- Launch server and type a few commands (e.x. `//set 0` or `//calc 2+2`)

**Screenshot/Video**
<img width="691" alt="image" src="https://user-images.githubusercontent.com/13716167/201226973-b18aa1b8-70d3-4e93-977c-0fc90af3b89c.png">

**Comment by Kotori0629** [comment]
Use WorldEdit-Bukkit

**Comment by andriihorpenko** [comment]
Or even better: I've created a mixin patch which replaces double slash commands with single slash ones :)
Anyway, thanks!

**Comment by leonpano2006** [comment]
> Use WorldEdit-Bukkit

這個做法已被證實會有問題
尤其是如果要用模組的方塊的話

**Comment by Kotori0629** [comment]
> 

在 CatServer 不会出现相关问题吧

**Comment by Kotori0629** [comment]
> > Use WorldEdit-Bukkit
> 
> 這個做法已被證實會有問題 尤其是如果要用模組的方塊的話

在 CatServer 不会出现相关问题吧

**Comment by leonpano2006** [comment]
> > > Use WorldEdit-Bukkit
> 
> > 
> 
> > 這個做法已被證實會有問題 尤其是如果要用模組的方塊的話
> 
> 
> 
> 在 CatServer 不会出现相关问题吧

Worldedit spigot不支援模組的方塊
只能二選一forge or spigot
別兩個一起裝
