### ISSUE TITLE
[1.12.2] 存在Log4j错误 需紧急修复

### ISSUE THREAD

**Issue by jki135542** [Luohuayu/CatServer#655]
**运行环境**
Java1.8.0
Log4j 2.8.1
Minecraft版本(1.12.2/1.16.5/1.18.2): 
构建版本(从/version指令获取): 
相关模组/插件: 

**描述这个BUG**
|>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> |
需要下载缺少的库文件, 请耐心等待..                               |
正在下载文件 log4j-api-2.8.1.jar 大小: 223.49512 KB      |
正在下载文件 log4j-core-2.8.1.jar 大小: 1.3379335 MB   |
|>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> |
![image](https://user-images.githubusercontent.com/78467768/201449848-5cf6efdc-120b-4143-a686-cbd70f58594b.png)
系统默认下载并使用Log4j 2.8.1 版本
而小于Log4j 2.14.0版本的Log4j会存在严重漏洞
**## 腾讯云报错**
![image](https://user-images.githubusercontent.com/78467768/201450090-19b17f5e-cc37-486d-b687-6b45fb298565.png)

**导致的问题r**
导致存在Log4J漏洞
**复现方法**

**截图/视频**
(如果没有可以忽略)

**Comment by Kansamu** [comment]
有没有可能早就修过了

**Comment by jki135542** [comment]
啊这，那为什么腾讯云还会报错啊。
如果没问题，是否就不需要处理了
| |
不不不我就是
网络运营
|
|
15167792366
***@***.***
|
在2022年11月12日 ***@***.***> 写道：

有没有可能早就修过了

**Comment by jki135542** [comment]
啊这，那为什么腾讯云还会报错啊。
如果没问题，是否就不需要处理了


| |
不不不我就是
网络运营
|
|
15167792366
***@***.***
|
在2022年11月12日 ***@***.***> 写道：

有没有可能早就修过了

**Comment by Kotori0629** [comment]
你是网络运营 你不会自己测试下jndi lookup？

https://github.com/Luohuayu/CatServer/commit/5d66f2e11f4b105112573e72e1a4d36b982b072c
