### ISSUE TITLE
[1.12.2] 使用结构方块时被服务器踢出

### ISSUE THREAD

**Issue by RMSCA** [Luohuayu/CatServer#659]
**运行环境**

Minecraft版本: 1.12.2
构建版本: 

```
This server is running CatServer version git-CatServer-1.12.2-dae70adc (MC: 1.12.2) 
(Implementing API version 1.12.2-R0.1-SNAPSHOT, Forge version 14.23.5.2860)
```

相关插件: 
<img width="227" alt="Screen Shot 2022-11-26 at 8 44 51 PM" src="https://user-images.githubusercontent.com/72942610/204119651-84b2a506-cb77-40c9-afa3-6839cdfb2fd3.png">

相关模组：
<img width="301" alt="Screen Shot 2022-11-26 at 8 45 18 PM" src="https://user-images.githubusercontent.com/72942610/204119662-e3a9a48e-9272-4350-871b-9e6cdbceddf0.png">

**描述这个BUG**
在服务器里使用结构方块会导致玩家被踢出
玩家可以正常通过指令获得结构方块
也可以打开用户界面
但是不管有没有对方块进行操作，都会在退出用户界面的时候被踢出服务器

```
io.netty.handler.codec.DecoderException: The received string length is longer than maximum allowed (24 > 20)
```

**导致的问题**
玩家无法正常使用结构方块

**Comment by Luohuayu** [comment]
需要更多日志信息, 包括服务端debug.log相关部分和客户端的

**Comment by RMSCA** [comment]
服务端debug.log:
https://pastebin.com/4BJas11w
客户端latest.log:
https://pastebin.com/gRX7xta1
客户端貌似并没有关于这部分报错的信息，都是一些别的模组的报错

**Comment by Luohuayu** [comment]
客户端存在不兼容的MOD 发送的自定义数据包长度超过20 已经超出1.12.2的限制

**Comment by RMSCA** [comment]
请问有什么mod或者其他方法可以修复这个问题吗？
还是说只能把mod一个一个删掉来看是哪个出了问题 然后去找作者反馈
谢谢
