### ISSUE TITLE
Problem with chicken chunks

### ISSUE THREAD

**Issue by lnik801l** [Luohuayu/CatServer#66]
Hello, i have problem with ChickenChunks-1.12.2-2.4.2.74 and CatServer-e23e25a-async.
ChunkLoaders doesnt keep chunks loaded. 
In console i haven't any errors

**Comment by Nolij** [comment]
Have you tried universal?

**Comment by lnik801l** [comment]
I check soon

**Comment by Luohuayu** [comment]
Disable `enableSkipTick` option in catserver.yml

**Comment by lnik801l** [comment]
Luohuayu, that option doesnt helps. In universal version all works fine

**Comment by Luohuayu** [comment]
Async version has modified the chunkloading for optimization, it will break the mod. If necessary, it is recommended to use universal version

**Comment by lnik801l** [comment]
But can i hope that you fix that problem? Or in async version chunk loaders can't exists at all?

**Comment by Luohuayu** [comment]
You can try to remove the plugin with unload chunk function, then test if the chunk is unloaded

**Comment by lnik801l** [comment]
Sorry for long reply
i havent any plugins witch can unload chunks

![image](https://user-images.githubusercontent.com/25746591/72024351-41d97c00-3286-11ea-9d22-509679c5ce45.png)

![image](https://user-images.githubusercontent.com/25746591/72024401-67668580-3286-11ea-8712-05edca1b2cc9.png)

correct me if i`m wrong

**Comment by lnik801l** [comment]
today i had some tests with and without plugins (removed all of them). i find that chunkloaders work fine for vanilla (i tested that by command block which write messages to chat).

if i have chunkloader (for example, in overworld) and go far from that and keep staying in overworld, it works for mods fine too

if i go to another world it stop works for all mod mechanisms (i tested that with modded worlds and overworld)

if i leave from server mechanisms stop work (command block still work)

**Comment by Luohuayu** [comment]
Did trying the latest async version resolve the issue?

**Comment by lnik801l** [comment]
tested with 20.01.09 release (CatServer-eb8887a-async.jar)

in few minutes can test with latest version

**Comment by lnik801l** [comment]
no, latest version don`t fix the issue

**Comment by lnik801l** [comment]
all works same as in previous versions (tested without plugins)

**Comment by lnik801l** [comment]
ah, only command block works fine, vanilla furnaces don`t work too (all tile entities i think)

**Comment by Iltotore** [comment]
Hey !
This issue is about chunk loading.

For furnace issues, check: https://github.com/Luohuayu/CatServer/issues/67

**Comment by TheDarkDnKTv** [comment]
Same issue, chickenchunks chunkloaders not working properly, i have disabled all skipTicks in catserver.yml, but looks like it skips anyway ticks. It's looks like it works only when players are on server. 
Is there difference between async and universal, because from my experience two jars working same, only additional bugs on async.

**Comment by Luohuayu** [comment]
Fixed
