### ISSUE TITLE
[1.16.5] 希望能支持带‘/’前缀的指令

### ISSUE THREAD

**Issue by MC-XiaoHei** [Luohuayu/CatServer#667]
**希望能支持带‘/’前缀的指令**
在官方服务端中，我们可以使用带‘/’前缀和不带‘/’前缀的命令，而在CatServer中，带‘/’前缀的命令无法使用

官方服务端：
```
/list
 There are 0 of a max of 20 players online:
list
 There are 0 of a max of 20 players online:
```
CatServer：
```
/list
 Unknown command.
list
 There are 0 of a max of 20 players online:
```
尽管这看起来不是非常必要，但我认为这有助于命令格式的统一。
e.g.
当安装了World Edit，其默认的双//指令前缀将可能导致其在终端输入与在游戏中输入不同。（未测试）

**Comment by Kotori0629** [comment]
WorldEdit本来就不是让你在控制台使用的...

**Comment by MC-XiaoHei** [comment]
好吧，我只是认为这样有助于统一命令格式（
&nbsp;


Lastfilmmaker.JustSay
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年12月11日(星期天) 下午3:05
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Luohuayu/CatServer] [1.16.5] 希望能支持带‘/’前缀的指令 (Issue #667)





 
WorldEdit本来就不是让你在控制台使用的...
