### ISSUE TITLE
[1.16.5] 关于构建库 18 - 最新的核心出现的龙研bug

### ISSUE THREAD

**Issue by tanyuguai** [Luohuayu/CatServer#668]
**运行环境**

Minecraft版本(1.12.2/1.16.5/1.18.2): 1.16.5
构建版本(从/version指令获取): CatServer-1.16.5-876dc9aa-server.jar - 最新版本
相关模组/插件: Draconic-Evolution-1.16.5-3.0.28.500-universal

**描述这个BUG**
(如果有报错请附上pastebin链接或上传日志文件)
这个问题已经有人报过了，我试了一下构建库18之前是没有这个问题的（构建库17不能下载，我无法确定），构建库18-最新都有这个问题，我还去试了下海螺端arclight-forge-1.16.5-1.0.25-SNAPSHOT.jar没有这个问题。
https://github.com/Luohuayu/CatServer/issues/587
**导致的问题r**
模块消失
**复现方法**
https://github.com/Luohuayu/CatServer/issues/587

**截图/视频**
(如果没有可以忽略)

**Comment by Luohuayu** [comment]
与 #587 重复 合并解决
