### ISSUE TITLE
CatServer Async furnace issue

### ISSUE THREAD

**Issue by 8qBITs** [Luohuayu/CatServer#67]
Hey, so whenever you put items in some furnaces they dissapear breaking them sometimes fixes it but they break again after while.

**Comment by 8qBITs** [comment]
Nevermind it also does same thing on non async

**Comment by Luohuayu** [comment]
Vanilla furnace or modded furnace? Please provide mod and item information.

**Comment by 8qBITs** [comment]
Vanilla furnaces

**Comment by 8qBITs** [comment]
Might have something to do with immersive engineering external heater as well

**Comment by Luohuayu** [comment]
Known issue: Asynchronous hopper is not compatible with Immersiveengineering
Do you enable `async.hopper` and use hopper?

**Comment by 8qBITs** [comment]
No hoppers tho i have hopper async enabled.
