### ISSUE TITLE
[1.16.5] Citizens2创建的NPC消失

### ISSUE THREAD

**Issue by xxtx4399** [Luohuayu/CatServer#672]
**运行环境**
java-jdk1.8.0_271
Minecraft版本(1.12.2/1.16.5/1.18.2): 
构建版本(从/version指令获取): 

 | 构建产生文件CatServer-1.16.5-da9654d4-server.jar7.64 MB view |   | CatServer-1.16.5-da9654d4-server.jar | 7.64 MB | view
-- | -- | -- | -- | -- | --
  | CatServer-1.16.5-da9654d4-server.jar | 7.64 MB | view

相关模组/插件: 
Citizens-2.0.30-b2838/LuckPerms-Bukkit-5.4.55/LuckPerms-Bukkit-5.4.55/Vault

**描述这个BUG**

**导致的问题r**

创建的NPC离世界出生点太远重启服务器后实体消失,无报错

**复现方法**

**Comment by xxtx4399** [comment]
也没修复啊兄弟

**Comment by xxtx4399** [comment]
视频地址https://www.bilibili.com/video/BV1s8411H7Yq/

**Comment by Kotori0629** [comment]
别发了烙铁 修不了的

建议换Ady 或者D开头的那个NPC
