### ISSUE TITLE
[1.16.5] Incompatibility with Star Worm Equestrian Mod

### ISSUE THREAD

**Issue by Minecraftine** [Luohuayu/CatServer#674]
**Environment**

Minecraft version(1.16.5): 
Build version: CatServer version 1.16.5-da9654d4 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT, Forge version 36.2.39)
Mods/Plugins: geckolib-forge-1.16.5-3.0.106, player-animation-lib-forge-0.4.0+1.16.5, swem-1.16.5-0.5.3.4

**Describe the bug**
Cat Server is incompatible with Star Worm Equestrian Mod. The server can run, but when we put tack on a horse to ride it and right-click ont it, the server stops responding and crashes.

https://gist.github.com/Minecraftine/dd7bae03af124b4248b19dbb42a5b899

**Expected behavior** You should be able to ride the horse without any problem.

**To Reproduce** In creative mode, type 'SWEM Horse', take the spawn egg. Right-click on the ground to make it appear. Click on it to tame it like a vanilla horse, when it is tamed, open the creative tab and type 'bridle', take any bridle. Right-click on the horse. When it has the bridle on, right-click on it again to ride it. And the server will stop responding.

**Comment by Kotori0629** [comment]
Link status: 404 (xd

**Comment by Minecraftine** [comment]
> Link status: 404 (xd

It should work now. https://gist.github.com/Minecraftine/dd7bae03af124b4248b19dbb42a5b899

**Comment by Kotori0629** [comment]
![image](https://user-images.githubusercontent.com/81866089/218052817-cfe57ff6-a56d-47f2-8eb1-dc3f8a0bec2d.png)
No crash.

**Comment by Kotori0629** [comment]
Yes, the server is no crash. everything is working fine

**Comment by Minecraftine** [comment]
> Yes, the server is no crash. everything is working fine

No, you need to ride a horse with tack on it, as I explained and the server will stop responding.

**Comment by Kotori0629** [comment]
> > Yes, the server is no crash. everything is working fine
> 
> No, you need to ride a horse with tack on it, as I explained and the server will stop responding.

Yes, I tested it. It didn't crash

**Comment by Minecraftine** [comment]
> > > Yes, the server is no crash. everything is working fine
> 
> > 
> 
> > No, you need to ride a horse with tack on it, as I explained and the server will stop responding.
> 
> 
> 
> Yes, I tested it. It didn't crash

I tested it again and it still doesn't work on every computer. What can I do ? Do you want a video? You need to make the horse walk and wait till the server stops responding and crashes.

**Comment by Kotori0629** [comment]
Yes, you can give me a video. i will try again.

**Comment by Minecraftine** [comment]
> Yes, you can give me a video. i will try again.

Ok thank you, I'll do that when I can.

**Comment by Minecraftine** [comment]
> Yes, you can give me a video. i will try again.

https://drive.google.com/file/d/1VVSc_GHHHrd5-p33nbMxKtC4xN9sZenr/view?usp=drivesdk
