### ISSUE TITLE
[1.16.5] 与[MCAR]凡家物语：重生MCA Reborn冲突，导致不能启动

### ISSUE THREAD

**Issue by zoe-may** [Luohuayu/CatServer#675]
**运行环境**

Minecraft版本：1.16.5
构建版本(从/version指令获取):  1.16.5-7ed7fa77 
相关模组: [MCAR]凡家物语：重生MCA

**描述这个BUG**
(如果有报错请附上pastebin链接或上传日志文件)
首先不是前置的问题，就是试图运行这个mod时报错，停止运行
另外我尝试过在mohist端上运行，是能够运行的
[latest.log](https://github.com/Luohuayu/CatServer/files/10309837/latest.log)
[debug.log](https://github.com/Luohuayu/CatServer/files/10309839/debug.log)

**导致的问题r**
崩服

**复现方法**
将mod放入mods文件夹

**截图/视频**
(如果没有可以忽略)
https://www.mcmod.cn/class/5099.html

**Comment by Kotori0629** [comment]
![image](https://user-images.githubusercontent.com/81866089/212120235-00563316-62bd-49f2-b168-bde5be94625d.png)
经测试 貌似能运行吧 
把你所有mod打包上来
