### ISSUE TITLE
[1.16.5] 个别玩家数据保存失败，导致玩家回档

### ISSUE THREAD

**Issue by zoe-may** [Luohuayu/CatServer#676]
**运行环境**

Minecraft版本1.16.5
构建版本(从/version指令获取):  1.16.5-7ed7fa77 
相关模组/插件: 
无

**描述这个BUG**
(如果有报错请附上pastebin链接或上传日志文件)

[latest.log](https://github.com/Luohuayu/CatServer/files/10317234/latest.log)

[debug.log](https://github.com/Luohuayu/CatServer/files/10317233/debug.log)
个别玩家数据无法保存，后台提示保存失败（应该不是mod的问题

**导致的问题r**
导致玩家回档，但是地图不受影响
**复现方法**
未知
**截图/视频**
(如果没有可以忽略)
![image](https://user-images.githubusercontent.com/71170887/209892966-8a108f4c-b8ef-4909-86a2-fe62abf51a2e.png)

**Comment by Kotori0629** [comment]
发crash-report

**Comment by zoe-may** [comment]
> 发crash-report

可是crash-report文件夹并没有生成相应的崩溃报告

**Comment by Kotori0629** [comment]
![image](https://user-images.githubusercontent.com/81866089/210082118-7559f7e3-e489-49ff-a048-0629b4f06000.png)

**Comment by zoe-may** [comment]
> ![image](https://user-images.githubusercontent.com/81866089/210082118-7559f7e3-e489-49ff-a048-0629b4f06000.png)

![86E49165-764B-4EE1-B8F4-30A1FBD1F01E](https://user-images.githubusercontent.com/71170887/210085695-ddffe568-c78e-4c27-ac08-87d1e48995a8.jpeg)
确实是提示了，但是确实没有，我试图在服务器文件夹搜索，也搜索不到相关崩溃记录(~_~;)
