### ISSUE TITLE
[1.12.2] 使用MOD物品无法飞行

### ISSUE THREAD

**Issue by Tan9cb** [Luohuayu/CatServer#678]
**运行环境**

Minecraft版本(1.12.2/1.16.5/1.18.2): 1.12.2
构建版本(从/version指令获取): 
相关模组/插件: 植物魔法

**描述这个BUG**
(如果有报错请附上pastebin链接或上传日志文件)
rt，玩家使用mod物品无法飞行，allow- flight=true也试过了
**导致的问题r**

**复现方法**

**截图/视频**
(如果没有可以忽略)

**Comment by Kotori0629** [comment]
导致的问题？ 

复现方法？

有什么报错吗？

日志放上来瞅瞅？

没有的话可不好解决呀

**Comment by Tan9cb** [comment]
创造可以飞行，但是生存用模组的物品就不行，测试过模组无bug
不是将玩家提出，而是双击空格键后不会有反应

**Comment by Kotori0629** [comment]
> 创造可以飞行，但是生存用模组的物品就不行，测试过模组无bug 不是将玩家提出，而是双击空格键后不会有反应

例如什么mod

**Comment by Tan9cb** [comment]
额外植物学的律者核心
