### ISSUE TITLE
[Suggestion] Add command

### ISSUE THREAD

**Issue by TheDarkDnKTv** [Luohuayu/CatServer#68]
Thank you @Luohuayu for you hard work!
I have suggestion, can you please add server command `/catserver tps`?
Plugins shows not correct tps due forge.
And please do not forget about additing permission to this command `catserver.tps`

**Comment by Luohuayu** [comment]
You can use the command `/tps` or `/forge tps`

**Comment by TheDarkDnKTv** [comment]
plugin's tps command showing around 10, but server not lagging at all...
