### ISSUE TITLE
[1.12.2] Bukkit.getOnlinePlayers()读不到任何在关服插件卸时的在线玩家

### ISSUE THREAD

**Issue by lidashuai-li** [Luohuayu/CatServer#682]
**运行环境**

Minecraft版本(1.12.2/1.16.5/1.18.2): 1.12.2
构建版本(从/version指令获取):  1.12.2-CatServerb050bcad
相关模组/插件:  chemdah star系列插件

**描述这个BUG**
因为某些原因需要监听PluginDisableEvent事件，在这个事件内，Bukkit.getOnlinePlayers()读不到任何在关服插件卸时的在线玩家。而spigot和paper则没有这个问题

**导致的问题r**
玩家的某些数据没办法在关服时正确保存

**复现方法**
监听PluginDisableEvent事件，,在事件内Bukkit.getOnlinePlayers()，会获取不到关服前在线玩家的信息

**截图/视频**
无

**Comment by Luohuayu** [comment]
应在PlayerQuitEvent时保存玩家数据

**Comment by lidashuai-li** [comment]
> 

PlayerQuitEvent确实有写但是不生效不知道为啥

**Comment by lidashuai-li** [comment]
目前有写三种保存方式 一是玩家下线 二是关服 三是每10s自动保存一次。但是似乎关服的时候一和二都不生效

**Comment by Luohuayu** [comment]
调试测试PlayerQuitEvent事件在关服时正常触发

**Comment by lidashuai-li** [comment]
我在tg上私聊你了 github不方便放图片

**Comment by lidashuai-li** [comment]
确实是很多插件都会出现这个问题，目前大部分插件的解决方式都是推荐关服前先kickall。包括怀黑的chemdah dawnstal的star系列和追光者的magicsync。保存的代码啥的发在你tg了

**Comment by lidashuai-li** [comment]
![3AWLI%G~I `NS6O5LDXNNT6](https://user-images.githubusercontent.com/78547426/211967569-42538a44-c029-43ea-aeef-c39115a173d0.png)
代码确实没问题，而且很多插件都会无法保存不是个例

**Comment by lidashuai-li** [comment]
跪求雨giegie修复下

**Comment by lidashuai-li** [comment]
This server is running CatServer version git-CatServer-1.12.2-dae70adc (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT, Forge version 14.23.5.2860)
我尝试了最新版结果是一样的

**Comment by Kotori0629** [comment]
有兴趣的话 你回滚这个commit再测试看看吧
1.16.5同理

https://github.com/Luohuayu/CatServer/commit/ae86f3cb4e3a0fd99b848f676b3bfba75891282a

**Comment by Kotori0629** [comment]
你用下面这个看看 
https://cowtransfer.com/s/bc44834cac734c 输入传输口令b1k1r4 有效期一天

免责: 上方链接内的核心仅供测试使用，不推荐直接生产使用，因为这不是官方版核心。如问题已解决，请回复本条表示问题不再复现并已得到解决后耐心等待稳定版发布更新. @lidashuai-li

**Comment by tclyyds** [comment]
经过测试 此版本正常保存
![BS8944~5LF}D XG2WPC 7Q5](https://user-images.githubusercontent.com/122610207/212442163-fdd13e15-b67f-40be-b25c-f47c84aa63ee.png)

**Comment by lidashuai-li** [comment]
经过测试此版本正常
![BS8944~5LF}D XG2WPC 7Q5](https://user-images.githubusercontent.com/78547426/212442226-ace9206d-d6c9-421a-a939-2964160829ec.png)

**Comment by Kotori0629** [comment]
已提交PR，这个Issues将在PR被合并后关闭。
