### ISSUE TITLE
[1.12.2] 关服时无法正常保存数据

### ISSUE THREAD

**Issue by tclyyds** [Luohuayu/CatServer#684]
**运行环境**

Minecraft版本(1.12.2/1.16.5/1.18.2): 1.12.2
构建版本(从/version指令获取):  git-CatServer-1.12.2-dae70adc (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT, Forge version 14.23.5.2860)
相关模组/插件:  magicsync

**描述这个BUG**
 当使用这个插件的时候，关服的时候无法正确保存数据。而这个问题在paper和spigot上均无此问题

**导致的问题r**
玩家数据无法正确保存
**复现方法**
玩家在服务器内，然后直接/stop关闭服务器
**截图/视频**
无

**Comment by Kotori0629** [comment]
Same #682

**Comment by Kotori0629** [comment]
Same #682
