### ISSUE TITLE
[1.16.5] 插件兼容问题

### ISSUE THREAD

**Issue by 3269199948** [Luohuayu/CatServer#685]
**运行环境**

Minecraft版本(1.16.5): 
构建版本(从/version指令获取): 
相关模组/插件: 
没有模组
插件：https://www.mcbbs.net/forum.php?mod=viewthread&tid=1085872

**描述这个BUG**
(如果有报错请附上pastebin链接或上传日志文件)

没有报错

**导致的问题**
会导致物品消失，不能正确实现插件的功能

**复现方法**

加入插件，输入/invkeep get p default 1
然后去死，背包物品消失，经验条也没了

**截图/视频**
(如果没有可以忽略)

你能兼容这个插件吗，根据网友反馈LoLiServer某个版本之前可以用，之后最新版就不能用了

**Comment by Kotori0629** [comment]
Same #454 

某个版本能用是因为 在那版本期间 我们打破了forge的死亡逻辑，那将导致墓碑/尸体等模组无法正常工作
