### ISSUE TITLE
[Jenkins API] 残留的 cdn.ci.loliidc.cn

### ISSUE THREAD

**Issue by z0z0r4** [Luohuayu/CatServer#686]
https://jenkins.rbqcloud.cn:30011/job/CatServer-1.12.2/api/json?pretty=true
http://cdn.ci.loliidc.cn:30011/job/CatServer-1.12.2/1/
![image](https://user-images.githubusercontent.com/78744121/212457672-4bdd5299-351e-4f6c-85f1-ccc683692e99.png)
![image](https://user-images.githubusercontent.com/78744121/212457682-6def11bc-7006-4663-9265-1a4c403ede50.png)
如图所示，Jenkins 上面的链接域名没换

**Comment by Kotori0629** [comment]
没事儿 问题不大

**Comment by z0z0r4** [comment]
> 没事儿 问题不大

爬虫会寄（2333

**Comment by Kotori0629** [comment]
> > 没事儿 问题不大
> 
> 爬虫会寄（2333

主要是 loliidc.cn这个域名到期了2333
