### ISSUE TITLE
[1.18.2] getPlayer() isn't remapped to a proper forge method name

### ISSUE THREAD

**Issue by silverfox0000** [Luohuayu/CatServer#689]
**Environment**

Minecraft version(1.12.2/1.16.5/1.18.2): 1.18.2
Build version(Get from /version command): `This server is running CatServer version 1.18.2 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT, Forge version 40.1.73)`

Plugins: 
- BKCommonLib
- My_Worlds

**Describe the bug**:  getPlayer() isn't remapped to a proper forge method name

**Expected behavior**
getPlayer() proper remap to the forge method name
**To Reproduce**
- Install BKCommonLib latest version from CI
- Get error `java.lang.NoSuchMethodException: net.minecraft.server.network.ServerPlayerConnection.getPlayer()`

**Screenshot/Video**
(If it doesn't exist you can ignore it)

Response from plugin author: https://github.com/bergerhealer/BKCommonLib/issues/151#issuecomment-1382845429

**Comment by Kotori0629** [comment]
Very sorry, CatServer 1.18.2 is out of support temporarily, this issue will be dealt with when support is restored

**Comment by Kotori0629** [comment]
The rebirth version 1.18.2 will be merged soon, please test after merging, if you find the same problem, please resubmit!
