### ISSUE TITLE
question

### ISSUE THREAD

**Issue by moonlitopal** [Luohuayu/CatServer#69]
Hi i was watching the branch named 1.12.2-sponge and i noticed that it has disappeared is that intended? i was watching for that because i needed sponge plugins for things like prism as core protect doesn't support modded blocks and even the prism i was able to get running on 1.12.2 for spigot did not support modded i assume that its because spigot cant interact with modded blocks but i need the rollback feature that prism/core protect gives and i had hopes for sponge to be working so we could have sponge prism on the server any answers to why the sponge branch is missing would be nice

**Comment by Luohuayu** [comment]
This branch is just an attempt. It turns out that there are many conflicts between bukkit and sponge, and it is impossible to mix them.

**Comment by Luohuayu** [comment]
They each have independent world management, permission system, command system, etc.
