### ISSUE TITLE
[1.16.5] 大哥修一下史诗战斗（epic fight）一打就崩服的问题谢谢

### ISSUE THREAD

**Issue by Y-Yuw** [Luohuayu/CatServer#692]
**运行环境**

Minecraft版本(1.16.5): 
构建版本(从/version指令获取): CatServer version 1.16.5-6d6b2d34
相关模组/插件: epic fight

**描述这个BUG**
开史诗战斗战斗状态打个东西就崩服

![0OIY6JO 1G(NSCAJYKR{1%3](https://user-images.githubusercontent.com/89560808/212557854-c230f838-f623-4894-b2be-eaadd58af5d2.png)

[crash-2023-01-16_01.28.51-server.txt](https://github.com/Luohuayu/CatServer/files/10420826/crash-2023-01-16_01.28.51-server.txt)

**Comment by Kotori0629** [comment]
你更新核心啊

**Comment by Kotori0629** [comment]
https://github.com/Luohuayu/CatServer/commit/da9654d476266d79435eac8b02d262b63ce5a6af

**Comment by Y-Yuw** [comment]
草，从落花雨那边下了
![7GW}Y59{4Z_PG5UD5H{JU%A](https://user-images.githubusercontent.com/89560808/212623156-8c9d13c3-0a0c-40ef-bd56-c73417b1692d.jpg)
坏匹
