### ISSUE TITLE
[1.12.2] ProtocolLib5.x 无法加载

### ISSUE THREAD

**Issue by bliur** [Luohuayu/CatServer#695]
**运行环境**

Minecraft版本(1.12.2/1.16.5/1.18.2): 
构建版本(从/version指令获取): CatServer version git-CatServer-1.12.2-bb6ac525 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT, Forge version 14.23.5.2860)
相关模组/插件: 
ProtocolLib
**描述这个BUG**
(如果有报错请附上pastebin链接或上传日志文件)
ProtocolLib5.x无法正常加载，经测试spigot1.12.2可以正常加载
报错:https://netcut.cn/catserver%20yyds
**导致的问题r**
依赖ProtocolLib的插件，比如Comboeye，grimac无法使用
**复现方法**
加载ProtocolLib 5.x插件
**截图/视频**
(如果没有可以忽略)

**Comment by Kotori0629** [comment]
ProtocolLib 5.0 又不是给1.12用的。。

**Comment by bliur** [comment]
但是1.12能加载5.0

**Comment by bliur** [comment]
spigot 1.12可以加载

**Comment by Kotori0629** [comment]
> spigot 1.12可以加载

那你可以使用spigot

**Comment by bliur** [comment]
> > spigot 1.12可以加载
> 
> 那你可以使用龙头

我只是觉得这属于兼容问题，抱歉...

**Comment by Kotori0629** [comment]
https://github.com/Luohuayu/CatServer/issues/181
