### ISSUE TITLE
[1.16.5] Server instance randomly dies

### ISSUE THREAD

**Issue by Supermarcel10** [Luohuayu/CatServer#697]
### **Environment**

Pterodactyl Panel: 1.11.2
Pterodactyl Node: 1.11.0
Node Specifications:
- 24 CPU Threads
- 128GB RAM
- Swap Disabled
- 900GB NVMe RAID1

Minecraft Version: 1.16.5
Build Version: 1.16.5-53f209b9 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT, Forge version 36.2.39)

Mods:
- Create: Above and Beyond (modpack)
- A few server mods like world border. List can be provided if necessary.

Plugins:
- BanItem v3.4
- ChunkMaster v1.4.2
- CoreProtect v21.3 (DISABLED)
- EssentialsX / Chat / Discord / DiscordLink v2.20.0-dev+40-996285c
- GSit v1.0.7
- InvSee
- LuckPerms v5.4.15-Bukkit
- miniMOTD v2.0.10-Bukkit/Bungeecord
- OfflineTeleporter v0.6
- Vault
- WorldEdit v7.2.10-Bukkit

### **Describe the bug**
Server instance suddenly stops.
No prior TPS drop, no internet packet drops/issues. Other instances on node continue running as normal.
Crash report in crash-reports is not created.
Server instance is force shut down.

### **Expected behavior**
Server continues running.

### **To Reproduce**
Unknown / Unable to reproduce

### **Screenshot/Video**
N/A

**Comment by Kotori0629** [comment]
What? Is there a log?

**Comment by Supermarcel10** [comment]
After inspecting it more, I was unable to find any specific issues that stand out except Issue #699 and what seems to be a serialisation error.

The last ~60 minutes before crash can be found here:
https://pastebin.com/Vx6Jvmkm
I have truncated the oversize error (Issue #699), and removed user's public IPs.

I would like to attempt and fix Issue #699 first and try to reproduce the issue again to rule out the possiblitity of Issue #699 being the direct cause of this.

**Comment by Supermarcel10** [comment]
Closing stale issue.
