### ISSUE TITLE
[1.16.5] Attempted to send packet over maximum protocol size

### ISSUE THREAD

**Issue by Supermarcel10** [Luohuayu/CatServer#699]
### **Environment**

Pterodactyl Panel: 1.11.2
Pterodactyl Node: 1.11.0
Node Specifications:
- 24 CPU Threads
- 128GB RAM
- Swap Disabled
- 900GB NVMe RAID1

Minecraft Version: 1.16.5
Build Version: 1.16.5-53f209b9 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT, Forge version 36.2.39)

Mods:
- Create: Above and Beyond (modpack)
- A few server mods like world border. List can be provided if necessary.

Plugins:
- BanItem v3.4
- ChunkMaster v1.4.2
- CoreProtect v21.3 (DISABLED)
- EssentialsX / Chat / Discord / DiscordLink v2.20.0-dev+40-996285c
- GSit v1.0.7
- InvSee
- LuckPerms v5.4.15-Bukkit
- miniMOTD v2.0.10-Bukkit/Bungeecord
- OfflineTeleporter v0.6
- Vault
- WorldEdit v7.2.10-Bukkit

### **Describe the bug**
When a player joins the server, a log with a few thousand lines is outputted to the console about an oversized packet. It looks like the log doesn't seem to affect the playability/any mods from functioning.

May be direct cause of [Issue #697](https://github.com/Luohuayu/CatServer/issues/697#issue-1565179058).

Is there a viable way to increase the maximum packet size?

### **Expected behavior**
No visible error.

### **Error Logs**
```
[00:03:43] [Netty Epoll Server IO #5/ERROR] [net.minecraft.network.NettyCompressionEncoder]: Attempted to send packet over maximum protocol size: 2476599 > 2097152
Data:
17 14 61 72 63 68 69 74 65 63 74 75 72 79 3a 6e 	..architectury:n
65 74 77 6f 72 6b 15 66 74 62 71 75 65 73 74 73 	etwork.ftbquests
3a 73 79 6e 63 5f 71 75 65 73 74 73 0e 0e 66 74 	:sync_quests..ft
62 71 75 65 73 74 73 3a 69 74 65 6d 01 10 66 74 	bquests:item..ft
62 71 75 65 73 74 73 3a 63 75 73 74 6f 6d 02 0c 	bquests:custom..
.
. (Continued for 154780 lines)
.
67 20 66 61 63 74 6f 72 69 65 73 21 00 00 00 00 	g factories!....
00 02 af 30 00 00 00 00 02 9e 02 00 00 00 02 00 	...0............
89 01 00 00 09 00 00                            	.......
Length: 2476599
```

### **To Reproduce**
1) Clone the server with identical mods/plugins.
2) Join the server.
3) Error will be called on player join event.

### **Screenshot/Video**
N/A

**Comment by Luohuayu** [comment]
https://github.com/Tfarcenim/XLPackets

**Comment by Supermarcel10** [comment]
I have added the XLPackets mod to the server. By the looks of it, the console output is the same, and this has made no change to the issue.

**Comment by Kotori0629** [comment]
[testDev.zip](https://github.com/Luohuayu/CatServer/files/10581447/testDev.zip)
You can try. Please backup your save file first!

**Comment by Kotori0629** [comment]
[testDev.zip](https://github.com/Luohuayu/CatServer/files/10581513/testDev.zip)

You can try. Please backup your save file first! I uploaded again this file, because I modified something! 
You need to extract catserver.yml and CatServer-1.16.5-53f209b9-server.jar to the server at the same time, and run CatServer-1.16.5-53f209b9-server.jar
@Supermarcel10

**Comment by Kotori0629** [comment]
Hello ? fixed?

**Comment by Supermarcel10** [comment]
I have cloned the server and ran it with the same setup.
It seems to have made no effect, still outputting the same error in the logs.

Just to also include (since I haven't included it before), the java version (if it helps):
```
openjdk version "1.8.0_312"
OpenJDK Runtime Environment (Temurin)(build 1.8.0_312-b07)
OpenJDK 64-Bit Server VM (Temurin)(build 25.312-b07, mixed mode)
```

**Comment by Kotori0629** [comment]
Package your server mod and transfer the plugin to me via google drive

**Comment by Kotori0629** [comment]
Please send me the mod and plugin package

**Comment by Supermarcel10** [comment]
To create testing environment:
1. Download the server pack from [CurseForge](https://www.curseforge.com/minecraft/modpacks/create-above-and-beyond/files/3567576).
2. Download the mods and plugins added on my server from [MegaNZ](https://mega.nz/folder/R50DDY5Z#j5NEefjw1IfJdrM5qzzLQQ). Extract into `/plugins` and `/mods`, overwrite all if requested.
3. Set up `CatServer-1.16.5-53f209b9-server.jar` and `catserver.yml` from previous comment.


I have a clone of the server on my panel.
If you'd like access to this for the sake of testing, you can send me your email and I'll give you permissions to access it, and you can test directly on it if you wish.

**Comment by Supermarcel10** [comment]
Closing stale issue.
