### ISSUE TITLE
关于/recipe指令的问题

### ISSUE THREAD

**Issue by TRLWeiss** [Luohuayu/CatServer#70]
近期客户端老是在合成新物品时闪退，发现单人里只要给了/recipe give 玩家 * 就不会，就很离谱
但是在catserver里，貌似/recipe指令被禁用了？输入/recipe时显示 
/recipe is temporaly disabled,please use the recipe book in your inventory.
所以我该怎么使用/recipe指令？

**Comment by Luohuayu** [comment]
EssentialsX会覆盖该指令,请使用/minecraft:recipe
