### ISSUE TITLE
服务器加入mod没加载

### ISSUE THREAD

**Issue by SxiaoliuY** [Luohuayu/CatServer#709]
用的多线程版
中途服务器玩过一段时间后来加mod但是都没有加载mod配置文件
客户端有显示mod的物品，客户端没有什么问题
服务端开创者开背包可以看到mod物品选项但是点开并没有物品

**Comment by SxiaoliuY** [comment]
用的1.12.2

**Comment by Kotori0629** [comment]
无效，请提交日志
