### ISSUE TITLE
冰火龙mod被死亡蠕虫击杀后服务器崩溃

### ISSUE THREAD

**Issue by olcxian** [Luohuayu/CatServer#71]
https://paste.ubuntu.com/p/T2jfkz4Nnj/

**Comment by Luohuayu** [comment]
服务端版本?

**Comment by Luohuayu** [comment]
MOD问题, 作者已修复, 请更新MOD
https://github.com/Alex-the-666/Ice_and_Fire/commit/045df40a40346da944391ae62463fb362a135c55
