### ISSUE TITLE
[1.12.2] 插件取消掉落但是还是掉落了物品

### ISSUE THREAD

**Issue by lidashuai-li** [Luohuayu/CatServer#712]
**运行环境**

Minecraft版本(1.12.2/1.16.5/1.18.2):  1.12.2
构建版本(从/version指令获取):  This server is running CatServer version git-CatServer-1.12.2-bb6ac525 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT, Forge version 14.23.5.2860)
相关模组/插件:  
dragonblock
**描述这个BUG**
(如果有报错请附上pastebin链接或上传日志文件)
 插件取消了物品掉落 但是物品还是掉落
**导致的问题r**
 插件取消了物品掉落 但是物品还是掉落
**复现方法**

**截图/视频**
(如果没有可以忽略)
![H (~TCO0IZJY{%B8M_KS0SJ](https://user-images.githubusercontent.com/78547426/220057043-b9ea5f7f-28be-444d-8fe5-d3c988128d73.png)

**Comment by Kotori0629** [comment]
代码发完整, 事件类事件类没有 毛都没有谁能给你修

**Comment by Luohuayu** [comment]
BlockBreakEvent.isDropItems() 未实现

**Comment by lidashuai-li** [comment]
这个可以整嘛

**Comment by Kotori0629** [comment]
> 这个可以整嘛

不难解决，但是我构建不出来

**Comment by lidashuai-li** [comment]
emmm，行吧
&nbsp;


★·°騩泣;︶︵︶
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月10日(星期一) 下午3:39
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Luohuayu/CatServer] [1.12.2] 插件取消掉落但是还是掉落了物品 (Issue #712)





  
这个可以整嘛
  
不难解决，但是我构建不出来

**Comment by Kotori0629** [comment]
> emmm，行吧 &nbsp; ★·°騩泣;︶︵︶ ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2023年4月10日(星期一) 下午3:39 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [Luohuayu/CatServer] [1.12.2] 插件取消掉落但是还是掉落了物品 (Issue #712) 这个可以整嘛 不难解决，但是我构建不出来 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

你在猫端群里吗，加我一下
