### ISSUE TITLE
[1.16.5] Please modify the title to description

### ISSUE THREAD

**Issue by afaser** [Luohuayu/CatServer#713]
Minecraft version: 1.16.5 
Build version):  CatServer version 1.16.5-6fa4a7c4 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT, Forge version 36.2.39)
ModPack: ATM6
Plugins: 
Luckperms
Chatty
Chunky
EssentialsX
PlaceholderAPI
Plasmovoice
Tab-Premium
WorldEdit

Server is crashing https://pastebin.com/gCYW2N7E

**Comment by Kotori0629** [comment]
Unsupport Java 17.
