### ISSUE TITLE
[1.12.2] 使用异步创世神处理 漏区块 且报错

### ISSUE THREAD

**Issue by LitthoX** [Luohuayu/CatServer#714]
**运行环境**
git-CatServer-1.12.2.dae70abc
Minecraft版本(1.12.2):
构建版本(从/version指令获取): 
相关模组/插件: 
[F][异步创世神]FastAsyncWorldEdit-bukkit-21.03.26-5ff3a9b-1286-22.3.9
[W][创世神]worldedit-bukkit-6.1.9

**描述这个BUG** 异步创世神处理时，有概率会漏区块
(如果有报错请附上pastebin链接或上传日志文件)

**导致的问题r**创世神处理漏区块

**复现方法** 使用异步创世神插件 操作稍微大点的区域就会复现

**截图/视频**
![9438E22CB2DB401C1BF0B20037738A69](https://user-images.githubusercontent.com/125933420/220727716-167e65e7-fbe3-4400-b35d-3994b2707ed3.jpg)
![807F7206F88B6ED77B6C724311301716](https://user-images.githubusercontent.com/125933420/220727773-2aab3fd1-cbb5-4542-a2ec-df7ca3430262.jpg)

(如果没有可以忽略)

**Comment by Kotori0629** [comment]
#181 不过你发的报错貌似可以解决 看luohuayu

**Comment by LitthoX** [comment]
QWQ所以能解决吗，关帖原因是因为我没使用最新版服务端对吧
