### ISSUE TITLE
[1.12.2] 使用FAWE漏区块 并报错

### ISSUE THREAD

**Issue by LitthoX** [Luohuayu/CatServer#716]
**运行环境**
java8 Windows Server 2022 Datacenter 64位
Minecraft版本(1.12.2/1.16.5/1.18.2): 
1.12.2
构建版本(从/version指令获取): 
CatServer-1.12.2-222f2a5f
相关模组/插件: 
[异步创世神]FastAsyncWorldEdit-bukkit-21.03.26-5ff3a9b-1286-22.3.9
[创世神]worldedit-bukkit-6.1.9
**描述这个BUG**
使用异步创世神进行操作时，操作大面积会漏区块，而且漏掉的区块里有生物[实体]，不知道是不是实体导致的
**导致的问题**
操作漏区块，无法完全完成操作[填充、粘贴等]
**复现方法**
使用异步创世神大面积操作即可
**截图/视频**
![2023-02-24_06 17 08](https://user-images.githubusercontent.com/125933420/221048333-9f37c281-a6e8-4a94-93fe-8b2bbbe7d27e.png)

![2023-02-24_06 17 18](https://user-images.githubusercontent.com/125933420/221048337-d08cae3b-d768-4a97-b314-a587a6259155.png)
![报错](https://user-images.githubusercontent.com/125933420/221048438-32fe6ef9-88d1-43dd-8994-16a2e0501911.png)

**Comment by Kotori0629** [comment]
不是给你提过了？

https://github.com/Luohuayu/CatServer/issues/181

![image](https://user-images.githubusercontent.com/81866089/221115064-d9b105f9-fd45-4f79-9f11-0c389f19b843.png)

**Comment by LitthoX** [comment]
啊跟mod方块有关系吗...我放置的不是mod方块啊。。

**Comment by Kotori0629** [comment]
![image](https://user-images.githubusercontent.com/81866089/221237297-12646145-c5a1-475a-9d4b-d60755e51d4f.png)
