### ISSUE TITLE
Server crashes while loading libraries

### ISSUE THREAD

**Issue by Chering031** [Luohuayu/CatServer#72]
Unable to launch server
This happens when I insert these mods
And they work fine on vanilla forge server

https://www.curseforge.com/minecraft/mc-mods/wings
https://www.curseforge.com/minecraft/mc-mods/llibrary

[debug.log](https://github.com/Luohuayu/CatServer/files/4046507/debug.log)
[latest.log](https://github.com/Luohuayu/CatServer/files/4046508/latest.log)

No crash report generated

**Comment by Luohuayu** [comment]
Wings mod patch server with ASM, Conflicts with Bukkit and is not compatible
