### ISSUE TITLE
[1.12.2] 服务器关服后报错 貌似是核心问题

### ISSUE THREAD

**Issue by LitthoX** [Luohuayu/CatServer#720]
运行环境
java8 Windows Server 2022 Datacenter 64位
Minecraft版本(1.12.2/1.16.5/1.18.2):
1.12.2
构建版本
CatServer-1.12.2-222f2a5f
相关模组/插件:
无
描述这个BUG
关服后会卡顿一会并报错
导致的问题
关服卡顿
复现方法
关闭服务器
截图/视频
![QQ图片20230303212127](https://user-images.githubusercontent.com/125933420/222730865-9db222a6-89c8-4fbe-8d72-1ae47ead60fa.png)
[2023-03-03-4.log](https://github.com/Luohuayu/CatServer/files/10882316/2023-03-03-4.log)

**Comment by Kotori0629** [comment]
org.serverct.ersha.attribute.extension.attribute.handle.other.Manager.save(ca:35)

**Comment by LitthoX** [comment]
是下面那个chat的线程和主线程互锁造成死锁了

**Comment by Kotori0629** [comment]
![image](https://user-images.githubusercontent.com/81866089/222775444-ec709149-21a1-45ed-8fb0-8d0e71f62aa1.png)

**Comment by LitthoX** [comment]
![1 (1)](https://user-images.githubusercontent.com/125933420/222776733-d5d76cf2-78b3-4894-9685-da09cc3953cc.jpg)
![1 (2)](https://user-images.githubusercontent.com/125933420/222776739-ca17f3f1-4a69-4582-a96b-1ca20c08fcab.jpg)
![1 (3)](https://user-images.githubusercontent.com/125933420/222776743-3b422ac4-84d0-4a9d-900a-02f00c9dbb6d.jpg)
https://github.com/Luohuayu/CatServer/blob/dae70adc870da7a982529b88ba29062387739d79/src/main/java/catserver/server/threads/AsyncChatThread.java#L16

**Comment by LitthoX** [comment]
改的话其实把这个时间改成3秒等待就好
