### ISSUE TITLE
[1.16.5] 神奇宝贝把这个选项开启玩家服务器会卡到爆炸

### ISSUE THREAD

**Issue by yuankun1** [Luohuayu/CatServer#722]
**运行环境**

Minecraft版本(1.12.2/1.16.5/1.18.2): 
最新版本catserver
构建版本(从/version指令获取): 
相关模组/插件: 
![QQ截图20230304201201](https://user-images.githubusercontent.com/19505154/222900385-a454b59d-6995-434c-a132-e4722de2cd32.png)

**描述这个BUG**
(如果有报错请附上pastebin链接或上传日志文件)
无报错
**导致的问题r**
不清楚
**复现方法**
allow-vanilla-mobs: false 改成allow-vanilla-mobs: true 
**截图/视频**
(如果没有可以忽略)

**Comment by Kotori0629** [comment]
forge端试过不

**Comment by yuankun1** [comment]
> forge端试过不

试试一样 客服端会很卡 生成了很多精灵实体 
它应该是吧刷出来的怪物判定成了精灵
满地遍地都是精灵 如果是服务器改此选项会卡到爆炸
还有玩家个别打末影龙会打不到 不清楚是不是把末影龙判定了精灵
末影龙可以使用远程跟TNT来造成伤害 近战打它就跟打精灵一样不会造成伤害

**Comment by Kotori0629** [comment]
> 

那你应该去反馈给宝可梦 而不是我们
