### ISSUE TITLE
[1.12.2] Please modify the title to description

### ISSUE THREAD

**Issue by fanzth** [Luohuayu/CatServer#724]
**Environment**

Minecraft version(1.12.2/1.16.5/1.18.2):  1.16.5
Build version(Get from /version command):  This server is running CatServer version 1.16.5-7e2679e9 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT, Forge version 36.2.39)
Mods/Plugins: Skript 2.7.0-beta1

**Describe the bug**
(If there is an error, please attach the pastebin link)
Error occurred while enabling Skript v2.7.0-beta1 (Is it up to date?)
https://pastebin.com/7xsyCCsV

**Expected behavior**
i want them can run normally <3

**To Reproduce**
install skript
run server
error while enabling

**Screenshot/Video**
(If it doesn't exist you can ignore it)

**Comment by Kotori0629** [comment]
Try use https://mcpaste.com/

i can't open pastebin

**Comment by Luohuayu** [comment]
The url can not open
