### ISSUE TITLE
[1.18.2] Server Startup error

### ISSUE THREAD

**Issue by stanlystark** [Luohuayu/CatServer#725]
**Environment**

Minecraft version: 1.18.2
Build version: CatServer-1.18.2-40.2.1-3401084f-server.jar
Mods/Plugins: -

**Describe the bug**
Error when starting the server. Also, some files are not downloaded, everything is in the logs.
https://pastebin.com/GvUneWct
https://mcpaste.com/0f784fcd92367efb95cf71bda6e1940a

**Expected behavior**
The server starts without errors

**To Reproduce**
Run the command `java -jar CatServer-1.18.2-40.2.1-3401084f-server.jar`

**Screenshot/Video**
![image](https://user-images.githubusercontent.com/29918992/225548047-704fbff1-0e1f-4398-8044-a237cadff9eb.png)

**Comment by Kotori0629** [comment]
Is it still not working after restarting?

**Comment by stanlystark** [comment]
Does not work, apparently does not download some files.
https://mcpaste.com/676245d2da8c7bca57904f8184d49430

**Comment by Kotori0629** [comment]
Try use latest version, fixed
