### ISSUE TITLE
[1.12.2] GroovyScript模组报错无法正常使用

### ISSUE THREAD

**Issue by zfms4188** [Luohuayu/CatServer#728]
**运行环境**

Minecraft版本(1.12.2/1.16.5/1.18.2): 1.12.2
构建版本(从/version指令获取): CatServer-1.12.2-ab28211f
相关模组/插件:  GroovyScript

**描述这个BUG**
(如果有报错请附上pastebin链接或上传日志文件)
使用指令/gs reload或其他指令
报错连接：https://pastebin.com/PWK2P2H7
mod下载：https://github.com/CleanroomMC/GroovyScript
前置:https://www.curseforge.com/minecraft/mc-mods/mixin-booter/files

等等,刚刚用forge端测试也报错,看来好像是mod本身的问题....大概？

**导致的问题r**
不能正常使用
**复现方法**
玩家使用指令/gs reload
(后台执行指令无反应)

**截图/视频**
(如果没有可以忽略)

**Comment by Luohuayu** [comment]
IntegratedServer类为Client only 推测MOD不支持服务端
