### ISSUE TITLE
[1.16.5] 不知道是宝可梦模组的锅还是cat的锅一直崩溃这段代码

### ISSUE THREAD

**Issue by yuankun1** [Luohuayu/CatServer#734]
**运行环境**

Minecraft版本(1.16.5): 
构建版本(从/version指令获取): 
相关模组9.1.3/插件: 
宝可梦模组/插件null
**描述这个BUG**
(如果有报错请附上pastebin链接或上传日志文件)
[crash-2023-04-16_18.04.47-server.txt](https://github.com/Luohuayu/CatServer/files/11241972/crash-2023-04-16_18.04.47-server.txt)

**导致的问题r**
应该是宝可梦实体把
**复现方法**
不详

**截图/视频**
(如果没有可以忽略)

**Comment by Luohuayu** [comment]
请像pixelmonmod反馈
