### ISSUE TITLE
[1.12.2] AE2非官方版崩服

### ISSUE THREAD

**Issue by Coloryr** [Luohuayu/CatServer#735]
**运行环境**

Minecraft版本(1.12.2/1.16.5/1.18.2): 1.12.2
构建版本(从/version指令获取): This server is running CatServer version git-CatServer-1.12.2-ab28211f (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT, Forge version 14.23.5.2860)
相关模组/插件: E2EU整合包1.2.5.0

**描述这个BUG**
https://github.com/PrototypeTrousers/Applied-Energistics-2/issues/264

**导致的问题r**
崩服

**复现方法**
往AE里面丢东西

**截图/视频**

**Comment by Luohuayu** [comment]
https://github.com/PrototypeTrousers/Applied-Energistics-2/blob/AE2-Omnifactory/src/main/java/appeng/me/GridNode.java#L271-L273
很奇怪的代码

**Comment by KorewaLidesu** [comment]
Just want to ask
Why does catserver load NBT data twice, that isnt normal behaviours when try loading unknown block without context

**Comment by KorewaLidesu** [comment]
Or is it async chunk loading on background?

**Comment by Luohuayu** [comment]
> Just want to ask Why does catserver load NBT data twice, that isnt normal behaviours when try loading unknown block without context

It's for block snapshot, if the bukkit event is cancelled, the block snapshot will be used to restore

**Comment by Rongmario** [comment]
Can you not use Forge's BlockSnapshot system?

**Comment by Coloryr** [comment]
现在不崩服了，我把AE驱动器拆了又装，调了一下磁盘位置就好了，这几天一直都没问题

**Comment by Coloryr** [comment]
如果崩了我再开
