### ISSUE TITLE
[1.12.2] plugin enabled on paper but not on catserver

### ISSUE THREAD

**Issue by rebarakuk** [Luohuayu/CatServer#736]
**Environment**

Minecraft version: 1.12.2
Build version(Get from /version command): git-CatServer-1.12.2-ab28211f (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT, Forge version 14.23.5.2860)
Mods/Plugins: LongerDays 1.0.4
[LongerDays](https://www.spigotmc.org/resources/longerdays.80610/history)

**Describe the bug**
On paper, no error exists on log, but on catserver it just isn't enabled

[error message on latest log](https://gist.github.com/rebarakuk/c5212ea2c2c47a39510a6ae0a725e128)

**Expected behavior**
It's enabled

**To Reproduce**
just put the plugin in plugins folder

**Comment by rebarakuk** [comment]
also, from longerdays 1.0.5, it doesn't support 1.12.2

**Comment by rebarakuk** [comment]
Also I think it's duplicate of #258 , but I've known JDK can't be used commercially maybe.

**Comment by Luohuayu** [comment]
Java version?

**Comment by rebarakuk** [comment]
![java version](https://user-images.githubusercontent.com/97182629/233921757-30137456-a046-49a7-ac19-6bbed56ca019.png)

**Comment by rebarakuk** [comment]
Also, author of #258 said just change JDK 19 to JDK 8. So I'm using OpenJDK 8 now. I downloaded it here.
[openjdk 8](https://adoptium.net/temurin/releases/?version=8)

**Comment by rebarakuk** [comment]
![openjdk 8](https://user-images.githubusercontent.com/97182629/233923838-3181627a-15ce-46e7-8023-cd88a70ba813.png)

**Comment by Luohuayu** [comment]
LongerDays is built with Java9+, but Forge 1.12.2 usually only works with Java8, which is not resolved

**Comment by rebarakuk** [comment]
I got it and compiled it with openjdk 8. It works well now. Thx!
( I didn't understand saying of #258 author)
