### ISSUE TITLE
[1.18.2] 物品在拿取之后就自动消失的问题

### ISSUE THREAD

**Issue by 649493262** [Luohuayu/CatServer#737]
**运行环境**

Minecraft版本(1.18.2): 
f6aa34f2 
相关模组/插件: 无

**描述这个BUG**
物品在拿取之后，重新放下就有几率消失

**导致的问题r**
无法游玩
**复现方法**
进去就有
**截图/视频**

https://user-images.githubusercontent.com/95968145/234549298-9bdafb69-44eb-4027-977c-77a2c3ca428d.mp4

**Comment by 1535514666321** [comment]
不止。如果鼠标手势用右键铺物品还会导致物品变多

**Comment by 1535514666321** [comment]
而且40.2.1版本也有相同的问题

**Comment by Luohuayu** [comment]
已修复
