### ISSUE TITLE
[1.18.2] 服务器无法加载jei

### ISSUE THREAD

**Issue by 649493262** [Luohuayu/CatServer#739]
**运行环境**

Minecraft版本(1.18.2): 
构建版本(从/version指令获取): 45ef1cf0
相关模组/插件: jei

**描述这个BUG**
(如果有报错请附上pastebin链接或上传日志文件)
服务端mod文件夹里有jei，但是服务器里显示未安装jei
**导致的问题r**
无法使用jei的部分功能
**复现方法**

**截图/视频**
(如果没有可以忽略)

**Comment by Luohuayu** [comment]
什么功能

**Comment by 649493262** [comment]
> 什么功能

![QQ截图20230429201759](https://user-images.githubusercontent.com/95968145/235302161-fc95f3e1-3802-4908-85f0-c211952c2328.png)
