### ISSUE TITLE
翅膀模组不兼容问题

### ISSUE THREAD

**Issue by PIPILAN** [Luohuayu/CatServer#74]
模组地址https://www.curseforge.com/minecraft/mc-mods/wings/files/2829351
日志https://paste.ubuntu.com/p/gH7f7vfS3T/

**Comment by Luohuayu** [comment]
插件使用ASM与Bukkit冲突, 无法兼容

**Comment by Luohuayu** [comment]
MOD使用ASM与Bukkit冲突, 无法兼容
