### ISSUE TITLE
[1.18.2] 服务器一打开等价交换的转化桌就会卡退

### ISSUE THREAD

**Issue by 649493262** [Luohuayu/CatServer#741]
**运行环境**

Minecraft版本(1.18.2): 
构建版本(从/version指令获取): 45ef1cf0
相关模组/插件: 等价交换 InventoryClickEvent UltiTools

**描述这个BUG**
[2023-04-28-1.log.gz](https://github.com/Luohuayu/CatServer/files/11354036/2023-04-28-1.log.gz)

**导致的问题r**
无法进行游戏
**复现方法**

**截图/视频**
(如果没有可以忽略)

**Comment by Luohuayu** [comment]
日志无有效信息
