### ISSUE TITLE
[1.18.2]  LuckPerms 无法使用

### ISSUE THREAD

**Issue by rcoplo** [Luohuayu/CatServer#742]
**运行环境**

Minecraft版本(1.12.2/1.16.5/1.18.2): 
构建版本(从/version指令获取): 
[45ef1cf0](https://jenkins.rbqcloud.cn:30011/job/CatServer-1.18.2/83/)
相关模组/插件: 
`LuckPerms` version: `5.4.71`
 整合包: [ATM7S](https://legacy.curseforge.com/minecraft/modpacks/all-the-mods-7-to-the-sky)
**描述这个BUG**
(如果有报错请附上pastebin链接或上传日志文件)
![$_G_$8E1F}ZN5$N5)S$W NT](https://user-images.githubusercontent.com/83597965/235283101-dc24e154-f120-4ab6-a037-0439fff4b7fc.png)

**导致的问题r**
![X4~GRMJ0EO$GQI6QGKQJ7KK](https://user-images.githubusercontent.com/83597965/235283122-0d51caa4-aac1-4478-b1b4-b397d1848a89.png)

**复现方法**

**截图/视频**
(如果没有可以忽略)

**Comment by Kotori0629** [comment]
未复现

**Comment by rcoplo** [comment]
已无法复现
