### ISSUE TITLE
[1.18.2] 服务器将物品放入等价交换转化桌后客户端就会卡退

### ISSUE THREAD

**Issue by 649493262** [Luohuayu/CatServer#743]
**运行环境**

Minecraft版本(1.18.2): 
构建版本(从/version指令获取): a204667e
相关模组/插件: 等价交换重置版

**描述这个BUG**
(如果有报错
[debug-1.log.gz](https://github.com/Luohuayu/CatServer/files/11359168/debug-1.log.gz)
请附上pastebin链接或上传日志文件)
[2023-04-29-1.log.gz](https://github.com/Luohuayu/CatServer/files/11359169/2023-04-29-1.log.gz)
[hmcl-exported-logs-2023-04-29T20-22-01.log](https://github.com/Luohuayu/CatServer/files/11359171/hmcl-exported-logs-2023-04-29T20-22-01.log)
[latest.log](https://github.com/Luohuayu/CatServer/files/11359176/latest.log)

[2023-04-29-1.log.gz](https://github.com/Luohuayu/CatServer/files/11359175/2023-04-29-1.log.gz)

**导致的问题r**
每次都会卡退
**复现方法**

**截图/视频**
(如果没有可以忽略)

**Comment by Luohuayu** [comment]
jei与其他mod冲突, 与服务端无关
