### ISSUE TITLE
[1.16.5] GraveStone在死亡时没有给予玩家讣告

### ISSUE THREAD

**Issue by Beggarfish** [Luohuayu/CatServer#746]
**运行环境**

Minecraft版本(1.12.2/1.16.5/1.18.2): 1.16.5
构建版本(从/version指令获取): https://netcut.cn/1gv82vish
相关模组/插件: gravestone-1.16.5-1.0.6

**描述这个BUG**
(如果有报错请附上pastebin链接或上传日志文件)
玩家死亡时没有给予讣告

**导致的问题r**
玩家没有讣告

**复现方法**

**截图/视频**
(如果没有可以忽略)

**Comment by Luohuayu** [comment]
与 #745 重复
