### ISSUE TITLE
[1.16.5] Boss级生物，以及玩家都会出现无限瞬间回血的问题

### ISSUE THREAD

**Issue by LunarMeal** [Luohuayu/CatServer#748]
**运行环境**

Minecraft版本(1.12.2/1.16.5/1.18.2): 1.16.5
构建版本(从/version指令获取): This server is running CatServer version 1.16.5-f72c98f2 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT, Forge version 36.2.39)
相关模组/插件: 无

**描述这个BUG**
任何Boss级生物都会自动回血，除非秒杀

**导致的问题r**
玩家无法杀死凋灵，砍了半天凋灵还是满血，其他的模组boss也有这个问题

**复现方法**
不用装任何插件和模组，用纯服务端测试，生成凋灵，然后用武器攻击即可

**截图/视频**
(如果没有可以忽略)

**Comment by Kotori0629** [comment]
更新
