### ISSUE TITLE
[1.18.2] 所有物品图标和实物不符

### ISSUE THREAD

**Issue by 649493262** [Luohuayu/CatServer#749]
**运行环境**

Minecraft版本(1.18.2): 
构建版本(从/version指令获取): d634601d
相关模组/插件: AE2WTLib-11.6.3
AEAdditions-1.18.2-3.2.6
Applied-Mekanistics-1.2.2
AEInfinityBooster-1.18.2-1.1.0+9
Avaritia-1.18.2-4.0.1.6-universal
BetterAdvancements-1.18.2-0.2.0.146
Bio Library 1.18.2-1.0.3
Bookshelf-Forge-1.18.2-13.2.53
BotanyPots-Forge-1.18.2-8.1.28
BotanyPotsTiers-Forge-1.18.2-2.2.0
Botany_Pots_Ore_planting-Forge-v3.6+1.18.2
City Craft-1.0.0-Forge-1.18.2
CodeChickenLib-1.18.2-4.1.2.475-universal
CommonCapabilities-1.18.2-2.9.0
CompactVoidMiners-R1.18.2-1.20
Controlling-forge-1.18.2-9.0+22
Cyclic-1.18.2-1.7.14
CyclopsCore-1.18.2-1.17.3
EnchantingInfuser-v3.3.3-1.18.2-Forge
EnchantmentDescriptions-Forge-1.18.2-10.0.12
FastLeafDecay-28
FluxNetworks-1.18.2-7.0.8.12
Iceberg-1.18.2-forge-1.0.49
IntegratedDynamics-1.18.2-1.13.3
IntegratedTunnels-1.18.2-1.8.17
InventoryProfilesNext-forge-1.18.2-1.8.3
JEIEnchantmentInfo-1.17.1-2.0.0
JER-Integration-3.3.2
JustEnoughProfessions-1.18.2-1.3.0
JustEnoughResources-1.18.2-0.14.2.206
LibX-1.18.2-3.2.19
MEGACells-1.4.2-1.18.2
Mekanism-1.18.2-10.2.5.465
MekanismAdditions-1.18.2-10.2.5.465
MekanismGenerators-1.18.2-10.2.5.465
MekanismTools-1.18.2-10.2.5.465
ModernUI-1.18.2-3.5.4.113-universal
MouseTweaks-forge-mc1.18-2.21
OreExcavation-1.10.162
Patchouli-1.18.2-71.1
ProjectE-1.18.2-PE1.0.1
PuzzlesLib-v3.3.6-1.18.2-Forge
RecipesLibrary-1.18.2-2.0.0
StorageDrawers-1.18.2-10.2.1
Torcherino-forge-1.18.2-16.0.3
ae2extras-2-1.18.2
almostunified-forge-1.18.2-0.3.10
appleskin-forge-mc1.18.2-2.4.1
appliedenergistics2-forge-11.7.3
architectury-4.10.86-forge
artifacts-1.18.2-4.2.1
assisted_progression-0.8
buildinggadgets-3.13.2-build.21+mc1.18.2
cloth-config-6.4.90-forge
cofh_core-1.18.2-9.2.1.39
configured-2.0.1-1.18.2
curioofundying-forge-1.18-5.3.0.0
curios-forge-1.18.2-5.0.9.0
emcbaubles-1.18.2-1.1.0
endrem_forge-5.2.0-R-1.18.2
expandability-6.0.0
extendedexchange-1802.2.7
flywheel-forge-1.18.2-0.6.8.a
invhud.forge.1.18.2-3.4.12
itemzoom-1.18.2-2.6.0
jeed-1.18.2-1.11
jei-1.18.2-forge-10.2.1.1004
jeiintegration_1.18.2-9.0.0.37
journeymap-1.18.2-5.9.6-forge
kotlinforforge-3.7.1-obf
lanserverproperties-1.8-forge
lazierae2-1.18.2-3.1.5
libIPN-forge-1.18.2-1.0.4
light-overlay-6.0.5-forge
mcw-bridges-2.0.7-mc1.18.2forge
modnametooltip-1.18.1-1.18.0
nucleus-1.18.2-6.0
polymorph-forge-1.18.2-0.46
projecte-integration-1.18.2-5.4.6
qqp_1.5.0_1.18.2_beta
theoneprobe-1.18-5.1.2
thermal_foundation-1.18.2-9.2.0.46
thermal_innovation-1.18.2-9.2.0.17
topaddons-1.18.2-2.3.1-beta
**描述这个BUG**
(如果有报错请附上pastebin链接或上传日志文件)
举例：奥术转换桌图标成了其他mod中的物品 无报错
**导致的问题r**

**复现方法**
进游戏就复现
**截图/视频**
(如果没有可以忽略)

https://user-images.githubusercontent.com/95968145/236831619-95062727-4c62-4f28-a17c-b3b0134a1dab.mp4

**Comment by Luohuayu** [comment]
特定MOD还是?

**Comment by abaoxg** [comment]
TD



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年05月09日 17:53 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | Re: [Luohuayu/CatServer] [1.18.2] 所有物品图标和实物不符 (Issue #749) |

特定MOD还是?

**Comment by Luohuayu** [comment]
这个GUI是什么MOD的

**Comment by Luohuayu** [comment]
已修复
