### ISSUE TITLE
WowSuchCleaner 和shop

### ISSUE THREAD

**Issue by konglingmingkong** [Luohuayu/CatServer#75]
WowSuchCleaner 和shop这两个插件
游戏内输入价格时会直接掉线
无报错。
> [00:05:02] [Server thread/INFO]: bing issued server command: /shop page edit 商店
> [00:05:16] [Server thread/INFO]: bing  lost connection: Disconnected
> [00:05:17] [Server thread/INFO]: bing  left the game
上面就是我打开商店编辑更改商品价格时的情况
paper核心正常使用

**Comment by Luohuayu** [comment]
请提供掉线时客户端相关log
