### ISSUE TITLE
[1.16.5] rejected vanilla connections

### ISSUE THREAD

**Issue by ATTomatoo** [Luohuayu/CatServer#751]
**运行环境**

Minecraft版本(1.12.2/1.16.5/1.18.2): 
构建版本(从/version指令获取): 
相关模组/插件: [touhou_little_maid:network,mekanism:mekanism,patchouli:main,ironchest:network,curios:main]

**描述这个BUG**
服务器正常运行，然后就突然出现这个报错，也没添加或删除任何MOD和插件
[debug.log](https://github.com/Luohuayu/CatServer/files/11465913/debug.log)

**导致的问题r**
暂无，就是后台一直在报错

**Comment by Luohuayu** [comment]
原版客户端无法进入装有MOD的Forge服务器
