### ISSUE TITLE
[1.16.5]EntityDamageByEntityEvent issue

### ISSUE THREAD

**Issue by msicraft** [Luohuayu/CatServer#752]
**Environment**

Minecraft version(1.12.2/1.16.5/1.18.2): 1.16.5

Build version(Get from /version command): This server is running CatServer version 1.16.5-ab948f4e (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT, Forge version 36.2.39)

Mods/Plugins: 
Mod: no mod
Plugin: plugin for testing using EntityDamageByEntityEvent

**Describe the bug**
EntityDamageByEntityEvent event not received when entity attacks player

**Expected behavior**
When an event is received, event#getEntity() must return the player and event#getDamager() must return the entity that attacked the player.

**To Reproduce**
Plugin using EntityDamageByEntityEvent
Test code: https://pastebin.com/QhrbUhR8

**Screenshot/Video**

**Comment by Luohuayu** [comment]
Fixed
