### ISSUE TITLE
[1.16.5] 服务器不定时会关闭

### ISSUE THREAD

**Issue by ATTomatoo** [Luohuayu/CatServer#756]
**运行环境**

Minecraft版本(1.12.2/1.16.5/1.18.2): 1.16.5
构建版本(从/version指令获取): 1.16.5-02c4d3f3 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT, Forge version 36.2.39)
相关模组/插件: 
![mods](https://github.com/Luohuayu/CatServer/assets/93612024/61f0731b-a4ee-4284-a3ff-d478b3d4d0f4)
![plugin](https://github.com/Luohuayu/CatServer/assets/93612024/e83aa2f5-b02a-4c7e-82b3-c38b4775e229)

**描述这个BUG**
(如果有报错请附上pastebin链接或上传日志文件)
服务器正常运行时，不定时的会自动关闭，玩家在服里挂机也会
[debug-1.log](https://github.com/Luohuayu/CatServer/files/11481037/debug-1.log)

**导致的问题r**
服务器关闭
**复现方法**
无
**截图/视频**
(如果没有可以忽略)

**Comment by Kotori0629** [comment]
无效日志
