### ISSUE TITLE
Issues about FallingBlock

### ISSUE THREAD

**Issue by TUCAOEVER** [Luohuayu/CatServer#76]
SpigotMC link : https://www.spigotmc.org/resources/custom-jumppads-1-8-1-15.44876/

No error.
Player step on the pressure plate,particles and sound features worked fine,but throw player into air
doesn't work as it should be.

**Comment by Iltotore** [comment]
Hi.
What CatServer version are you using?
Universal or the multi threaded one ?

**Comment by TUCAOEVER** [comment]
Universal.

**Comment by Iltotore** [comment]
Ok. This can be related to a velocity issue. I will test it soon.

**Comment by Iltotore** [comment]
Hi,
The problem seems to be related to Falling blocks. They have 1 life time by default and the plugin doesn't seem to set it to a bigger int.
```java
    @Override
    public FallingBlock spawnFallingBlock(Location location, org.bukkit.Material material, byte data) throws IllegalArgumentException {
        Validate.notNull(location, "Location cannot be null");
        Validate.notNull(material, "Material cannot be null");
        Validate.isTrue(material.isBlock(), "Material must be a block");

        EntityFallingBlock entity = new EntityFallingBlock(world, location.getX(), location.getY(), location.getZ(), CraftMagicNumbers.getBlock(material).getBlockData());
        entity.ticksLived = 1;

        world.addEntity(entity, SpawnReason.CUSTOM);
        return (FallingBlock) entity.getBukkitEntity();
    }
```

Are you sure JumpPads works in Spigot 1.12.2 and later ?

**Comment by TUCAOEVER** [comment]
Sure. It works fine and besides i am using skript lang it has “push” usage, it doesn’t work either. Both plugin works fine on Spigot

**Comment by Iltotore** [comment]
Okay. I'll do some test after school

**Comment by TUCAOEVER** [comment]
Hummm? Any ideas?

**Comment by TUCAOEVER** [comment]
After i have tested several times, i assume that it's "on step on" listener issues, even if i have stepped on pressure plate, server didn't respond to my movement, and that is the main reason why "push" function didn't work.

**Comment by Luohuayu** [comment]
Fixed
https://github.com/Luohuayu/CatServer/commit/151e7ccb0c6e04959b33945150572942f03da26c
