### ISSUE TITLE
[1.16.5] EntityDamageByEntityEvent 玩家受到伤害不会触发

### ISSUE THREAD

**Issue by lengzu** [Luohuayu/CatServer#761]
Minecraft版本:  1.16.5
构建版本(从/version指令获取): CatServer-1.16.5-7e2679e9

我监听了EntityDamageByEntityEvent 和EntityDamageEvent 两个类 在玩家受伤后并未触发 其他实体正常
在另一个插件中 取消玩家PVP一直无法触发监听

![image](https://github.com/Luohuayu/CatServer/assets/51105521/e6e582e8-0b52-4bda-9282-8f61a3d11dea)

**Comment by lengzu** [comment]
看到相同提交问题了#752

**Comment by dayd21git** [comment]
EntityDamageByEntityEvent & EntityDamageEvent & PlayerDeathEvent - broken/not working.
My code:
```
@EventHandler
public void onDamage1(EntityDamageEvent e) {
	Bukkit.getConsoleSender().sendMessage("EntityDamageEvent");
}

@EventHandler
public void onDamage2(EntityDamageByEntityEvent e) {
	Bukkit.getConsoleSender().sendMessage("EntityDamageByEntityEvent");
}

@EventHandler
public void onDeath(PlayerDeathEvent e) {
	ItemStack item = e.getEntity().getInventory().getItemInMainHand();
	String name = "PlayerDeathEvent: ";
	Bukkit.getConsoleSender().sendMessage(item == null ? name + "NULL" : name + item.getType().name());
}
```

**Comment by Luohuayu** [comment]
Fix is on plan. Due to some mods conflicting, we developers need to discuss the issue.

**Comment by Luohuayu** [comment]
Fixed
