### ISSUE TITLE
[1.12.2] Compatbility issues with mod TickDynamic

### ISSUE THREAD

**Issue by HaHaWTH** [Luohuayu/CatServer#762]
**Environment**
System: Windows Server 2012R2 
Java: Oracle OpenJDK 8u362 64bit
Minecraft version: 1.12.2
Build version(Get from /version command): dev-ab5ae253, also on stable version
Mods/Plugins: 
Mods:
[TickDynamic-1.12.2-1.0.3](https://www.curseforge.com/minecraft/mc-mods/tick-dynamic)
Plugins:
ProtocolLib 4.8.0

**Describe the bug**
[Log](https://pastebin.ubuntu.com/p/SjzDkk3sXn/)
[Debug](https://pastebin.ubuntu.com/p/dYZxhmFsps/)

**To Reproduce**
1.Install the mod TickDynamic
2.Launch the server
3.When the world is almost loading complete, the error occurred and crashed

**Comment by Luohuayu** [comment]
https://github.com/The-Fireplace-Minecraft-Mods/TickDynamic/blob/1519a0adaf7109706dced55b390fa7a84226c315/src/main/java/com/wildex999/tickdynamic/listinject/ListManager.java#LL374C1-L374C1
The problem is here. You can modify the mod code yourself or don't use the mod

**Comment by Luohuayu** [comment]
The problem was reported to TickDynamic a long time ago, but it has not been fixed until now

**Comment by HaHaWTH** [comment]
Ah okay, thx a lot for your reply! Btw which part of the code should I modify? I didn't know Forge mod code very well :-(

**Comment by Luohuayu** [comment]
Remove `Thread.dumpStack();`, also preferably remove `TickDynamicMod.logDebug("Debug Warning: Using slow remove of objects(Remove by index)!");`, then build the mod

**Comment by HaHaWTH** [comment]
Ohh, that works! thx so much! ❤ from Asia
