### ISSUE TITLE
[1.16.5] 玩家死亡时没有给予讣告

### ISSUE THREAD

**Issue by Beggarfish** [Luohuayu/CatServer#763]
运行环境
Minecraft版本（1.12.2/1.16.5/1.18.2）： 1.16.5
构建版本（从/version指令获取）：1.16.5-9b57815e (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT, Forge version 36.2.39) 
相关模组/插件： gravestone-1.16.5-1.0.6

描述这个BUG
（如果有报错请附上pastebin链接或上传日志文件）
玩家死亡时没有给予讣告

导致的问题r
玩家没有讣告

复现方法

截图/视频
（如果没有可以忽略）

**Comment by Luohuayu** [comment]
测试是正常的

**Comment by Luohuayu** [comment]
手里的那个东西啊

**Comment by Beggarfish** [comment]
确实是没有啊，自杀也没有，怪物杀死也没有，配置文件的也是开着的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年5月22日(周一) 凌晨2:20
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Luohuayu/CatServer] [1.16.5] 玩家死亡时没有给予讣告 (Issue #763)




 
手里的那个东西啊

**Comment by Beggarfish** [comment]
早上给你录个视频



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年5月22日(周一) 凌晨2:20
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Luohuayu/CatServer] [1.16.5] 玩家死亡时没有给予讣告 (Issue #763)




 
手里的那个东西啊

**Comment by Luohuayu** [comment]
修了
