### ISSUE TITLE
CatServer的下一个版本是? (What's the next version of CatServer?)

### ISSUE THREAD

**Issue by Luohuayu** [Luohuayu/CatServer#764]
**请在下方选择相应表情投票 (Please select the emoji to vote below)**

<img src="https://github.githubassets.com/images/icons/emoji/unicode/1f44d.png" height="32" width="32" > = 保持当前版本 (Keep current version)
<img src="https://github.githubassets.com/images/icons/emoji/unicode/1f389.png" height="32" width="32" > = 1.19.2
<img src="https://github.githubassets.com/images/icons/emoji/unicode/2764.png" height="32" width="32" > = 1.19.4
<img src="https://github.githubassets.com/images/icons/emoji/unicode/1f440.png" height="32" width="32" > = 等待1.20+ (Wait for 1.20+)

**↓↓↓表情在这里 (Emoji here)**

**Comment by 3269199948** [comment]
请更新1.19.4，1.19的内容非常令人喜欢，不应该放弃它
你可以放弃1.18，但不能没有1.19

**Comment by Kotori0629** [comment]
> 请更新1.19.4，1.19的内容非常令人喜欢，不应该放弃它 你可以放弃1.18，但不能没有1.19

收到建议，我们会在最短的时间内支持1.19.4

**Comment by Xing-C** [comment]
再次期待，1.19.4是个很需要跟重要的版本，但也许之后1.20还会更期待(就是要等的时间太长了)

**Comment by krau** [comment]
1.19.4 作为在 1.19.2 发布较长时间后、 1.20 发布在即的版本, 不少模组对其没有支持, 我认为应当开发 1.19.2 版本或等待 1.20+

**Comment by yuxxxxxxxx** [comment]
据近日与好友开私人服务器联机的准备情况来看，最后选择了1.19.2forge服务器，很多的有较多的mod都在1.19.2版本，我不知道各位mod开发者是否有正在跟进至1.19.4，从目前来看还是较推荐1.19.2版本，从快照版看，官方更新了樱花木及相关物品，竹子相关物品，更新了考古相关物品以及新生物，悬挂告示等，从新版本物品来看很期待1.20+版本，从mod数量来看更支持1.19.2，catserver能同时兼容插件与forge端mod，个人认为也许挑选更多mod的版本比追逐最新的版本要实在一点。

**Comment by orbitgw** [comment]
1.20

**Comment by ZhangMouQWQ** [comment]
我不是很能理解为什么1.19.4要更优先更新，据我所知 1.19.4目前绝大多数模组都是辅助和体验优化向的 而绝大多数主流模组并没有更新1.19.4这个版本，在我看来这非常不符合我对猫端的高性能模组插件服的印象 但我不会要求其必须开发 毕竟选择权在开发人员手上

**Comment by Kotori0629** [comment]
> 

以投票数决定是等待1.20+，所以1.19.4暂时往后稍稍吧

**Comment by ZhangMouQWQ** [comment]
> > 
> 
> 以投票数决定是等待1.20+，所以1.19.4暂时往后稍稍吧

我有一个不错的建议 为什么不去试试更新1.19.2呢？ 目前这个版本mod更新热度很高,一些主流模组也在持续更新 且可用的高性能模组插件服务端还没有
(墨端最新的更新甚至无模组体验都有问题 A端直接停止更新了)

**Comment by Kotori0629** [comment]
> > > 
> > 
> > 
> > 以投票数决定是等待1.20+，所以1.19.4暂时往后稍稍吧
> 
> 我有一个不错的建议 为什么不去试试更新1.19.2呢？ 目前这个版本mod更新热度很高,一些主流模组也在持续更新 且可用的高性能模组插件服务端还没有 (墨端最新的更新甚至无模组体验都有问题 A端直接停止更新了)

为何要向下更新

**Comment by ZhangMouQWQ** [comment]
> > > > 
> > > 
> > > 
> > > 以投票数决定是等待1.20+，所以1.19.4暂时往后稍稍吧
> > 
> > 
> > 我有一个不错的建议 为什么不去试试更新1.19.2呢？ 目前这个版本mod更新热度很高,一些主流模组也在持续更新 且可用的高性能模组插件服务端还没有 (墨端最新的更新甚至无模组体验都有问题 A端直接停止更新了)
> 
> 为何要向下更新

我需要一个在此热门版本可以使用的高性能模组插件服务端，进而再也不用为各种问题抓狂，虽然我知道这是我自己的一厢情愿，但我仍是猫端忠实的追随者，并期待您一如既往的优秀作品，不管其是否是我想要的版本（如果版本热度不高我并不会游玩更别提开联机服务器了）

**Comment by 3269199948** [comment]
NeoForge 1.20.4

**Comment by Kotori0629** [comment]
没有下一个版本了 RIP (跑

**Comment by wkurumi** [comment]
1.21.4

**Comment by wodeshixiang** [comment]
1.20.1

**Comment by fon11731** [comment]
NeoForge 1.21.1 整合包居多的版本
