### ISSUE TITLE
[1.18.2] 加入模组Shrines Structures无法启动

### ISSUE THREAD

**Issue by BaiYeLoser** [Luohuayu/CatServer#772]
**运行环境**

Minecraft版本: 1.18.2
构建版本: Catserver-Build-134
相关模组: Shrines Structures(https://www.curseforge.com/minecraft/mc-mods/shrines-structures)

**描述这个BUG**
(如果有报错请附上pastebin链接或上传日志文件)
https://pastebin.com/6J7tv0Jt

**导致的问题r**
无法启动

**复现方法**
启动游戏时卡住

**Comment by Kotori0629** [comment]
修过了
