### ISSUE TITLE
[1.18.2] 整合包由于mod加载失败无法启动

### ISSUE THREAD

**Issue by 1535514666321** [Luohuayu/CatServer#773]
**运行环境**

Minecraft版本(1.12.2/1.16.5/1.18.2): 1.18.2
构建版本(从/version指令获取): 1.18.2-6c3f5965 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT, Forge version 40.2.4)
相关模组/插件: Cucumber
**描述这个BUG**
https://pastebin.com/sjzckPTc

**导致的问题r**
服务器无法启动
**复现方法**

**截图/视频**

**Comment by Kotori0629** [comment]
Same #772
