### ISSUE TITLE
[1.12.2] Unable to launch with Censored-ASM 5.13

### ISSUE THREAD

**Issue by Desenrrollado** [Luohuayu/CatServer#774]
**Minecraft:** 1.12.2
**Build:** CatServer-1.12.2-fed56812
**Mods:** 
![Screenshot_1](https://github.com/Luohuayu/CatServer/assets/92115460/a5aa395d-95a5-4e85-b58f-63974b534ef2)
![Screenshot_2](https://github.com/Luohuayu/CatServer/assets/92115460/0efcd358-8f0b-45ad-b2c3-895eb7a82f61)
![Screenshot_3](https://github.com/Luohuayu/CatServer/assets/92115460/6f858c55-fc5d-464c-b713-77972447f0e0)

**Bug:** 
Minecraft Server is unable to launch due to failed injection into CatServer from latest [Censored-ASM](https://www.curseforge.com/minecraft/mc-mods/lolasm)

**Log:** 
[latest.log](https://github.com/Luohuayu/CatServer/files/11801771/latest.log)

**Video:**
https://github.com/Luohuayu/CatServer/assets/92115460/c27d1596-7828-4c9e-b397-f1badd6829f0

* _Edited to correct for the line specifying failed injection check, sorry._
___________________________________________________________________________________________________________________________________

Sidenote: Other possible future conflicts that may arise after the fact, concerning [Vintage-Fix](https://www.curseforge.com/minecraft/mc-mods/vintagefix), [Universal Tweaks](https://www.curseforge.com/minecraft/mc-mods/universal-tweaks), and [Mixin-Booter](https://www.curseforge.com/minecraft/mc-mods/mixin-booter). They all implement unique tweaks which may cause issues along with fixes. 

I also know you addressed similar two-weeks ago with with CensoredASM/LoliASM [#768  ](https://github.com/Luohuayu/CatServer/issues/768) . I just don't know if it's a result of a new version or one of my other mods conflicting. If you need me to remove any other mods feel free to tell me.

In any-case sorry to disturb, and thank you for you hard work on this amazing server software. Along with all the other people who work on it.

**Comment by Luohuayu** [comment]
Update

**Comment by Desoroxxx** [comment]
https://github.com/LoliKingdom/LoliASM/pull/184 This should probably work for you guys too
