### ISSUE TITLE
Issue with Worms from Actually Additions

### ISSUE THREAD

**Issue by lnik801l** [Luohuayu/CatServer#78]
Hello, i find error with mod Actually Additions (ActuallyAdditions-1.12.2-r151) and latest (atm) release of async catserver version.

https://paste.ubuntu.com/p/YqxSfRCfZJ/

no more errors in console occured. Worms can`t be placed

**Comment by Iltotore** [comment]
Hi,
Can you send your version of Actually Addditions ?
Does it works on Forge ?
Does it works on CatServer Universal ?

**Comment by lnik801l** [comment]
I have already sent version in first message..
In forge ofc all works fine
With universal version i check later

**Comment by Luohuayu** [comment]
Add Java parameter `-XX:-OmitStackTraceInFastThrow` and report the error again
