### ISSUE TITLE
[1.18.2] Double disconnect client when a player disconnect

### ISSUE THREAD

**Issue by ferjaisarg** [Luohuayu/CatServer#781]
**Environment**

Minecraft version(1.12.2/1.16.5/1.18.2):  1.18.2
Build version(Get from /version command):  Bukkit: 1.18.2-R0.1-SpigotAPI
Mods/Plugins: 

**Describe the bug**
When a player disconnect to the server send two disconnect client

[12:38:16] [Server thread/INFO]: Test lost connection: Disconnected
[12:38:16] [Server thread/INFO]: Disconnecting client Test
[12:38:16] [Server thread/INFO]: Disconnecting client Test

**Expected behavior**

**To Reproduce**

**Screenshot/Video**
![Screenshot_1](https://github.com/Luohuayu/CatServer/assets/130789887/aa07dd23-22fe-49a5-ac9a-8aff724af731)

**Comment by Kotori0629** [comment]
PlayerQuitEvent?
