### ISSUE TITLE
[1.18.2] 沉浸工程无法使用装配台给工具安装配件

### ISSUE THREAD

**Issue by BlancNeige233** [Luohuayu/CatServer#782]
**运行环境**

Minecraft版本(1.12.2/1.16.5/1.18.2):1.18.2 
构建版本(从/version指令获取): CatServer version 1.18.2-6c3f5965 
相关模组/插件: [沉浸工程] ImmersiveEngineering-1.18.2-8.4.0-161

**描述这个BUG**
(如果有报错请附上pastebin链接或上传日志文件)
正常情况下，在模组的工程师装配台上给工具安装配件后应该得到一个装了配件的工具，在单机中我测试了没有问题，但在服务器中给工具安装配件后只会得到一个没有安装配件的工具，同时配件消失

**导致的问题r**
无法正常使用模组的工具

**复现方法**
1.打开工程师装配台并放入机械钻和钻头（只是举例，该模组所有工具以及蓄电池背包都没法装配件）
2.安装后取回背包，在背包里就可以看到没有被安装上钻头
3.重新打开装配台并放入机械钻，显示没有安装配件

**截图/视频**
(如果没有可以忽略)

**Comment by CalenXwX** [comment]
看起来这是沉浸工程的bug诶 在纯forge服务端试了也是这个情况（
