### ISSUE TITLE
[1.16.5] Player#getVehicle() returned NULL

### ISSUE THREAD

**Issue by dayd21git** [Luohuayu/CatServer#786]
**Minecraft version:** 1.16.5
**Build version:** 1.16.5-9b57815e
**Description:** When I get on the **minecart**, I don't get the right information in the code

**Code:**
```
@EventHandler
public void PlayerInteractAtEntityEvent(PlayerInteractAtEntityEvent e) {
	Player p = e.getPlayer();
	Bukkit.getConsoleSender().sendMessage("VEHICLE: " + (p.getVehicle() == null ? "NULL" : p.getVehicle().getName()));
}
```
**Console:**
```
[09:53:15] [Server thread/INFO]: VEHICLE: NULL
```
P.S. I also remind you of two more mistakes that I ask you to correct.
https://github.com/Luohuayu/CatServer/issues/783 https://github.com/Luohuayu/CatServer/issues/769 https://github.com/Luohuayu/CatServer/issues/766

**Comment by dayd21git** [comment]
I checked the new version of the server. The new version returns the transport, but this does not always happen.
I clicked on the transport 5 times, got NULL 3 times.

**Comment by Kotori0629** [comment]
Have you tried other mods that have vehicles?

**Comment by Kotori0629** [comment]
![image](https://github.com/Luohuayu/CatServer/assets/81866089/54dd03b0-bb1c-4223-9df3-1d5cac27c739)
I tested on Paper1.16.5/Paper1.20.1, the current vehicle always null.
