### ISSUE TITLE
[1.16.5] Citizens2 NPC在寻路时崩服

### ISSUE THREAD

**Issue by zoe-may** [Luohuayu/CatServer#789]
**运行环境**

Minecraft版本：1.16.5
构建版本(从/version指令获取): This server is running CatServer version 1.16.5-1d8d6313 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT, Forge version 36.2.39)

相关模组/插件: Citizens2

**描述这个BUG**
(如果有报错请附上pastebin链接或上传日志文件)
创建 NPC 后，我尝试使用“/npc 路径”命令来设置 NPC 的位置。但是当 NPC 开始寻路时，服务器就崩溃了。
https://paste.denizenscript.com/View/112197

实际上在citizens那边有反馈过，但是因为不是正版，他不受理https://github.com/CitizensDev/Citizens2/issues/3036
然后今天我发现citizens的任意版本在catserver上都有这个bug，所以我感觉也可能是核心的问题
我还找到了1.12.2的类似情况：
#554 

**导致的问题r**
崩服

**复现方法**
使用命令“/npc create [name]”创建 NPC。
使用“/npc path”命令将 NPC 的位置设置为特定位置。
如果 NPC 没有寻路，请使用“/npc tphere”将 NPC 移动到另一个位置。
随后，服务器崩溃。

**截图/视频**
(如果没有可以忽略)

**Comment by zoe-may** [comment]
![image](https://github.com/Luohuayu/CatServer/assets/71170887/d7c7392a-5ffc-45c2-b380-7063772c6c15)
@Luohuayu 
在最新版的CatServer核心也测试过了，依旧崩溃

**Comment by Kotori0629** [comment]
Fixed
