### ISSUE TITLE
Issue with Rough Mobs

### ISSUE THREAD

**Issue by lnik801l** [Luohuayu/CatServer#79]
Here you can find crash report: https://hastebin.com/didemezufe.rb
Crashes occur randomly. Can`t provide more information.
Temp fix is turning off the Horse improvements in config of the mod (parameter hostileHorseFeaturesEnabled)

**Comment by Iltotore** [comment]
Hi, can you send your version of Rough Mobs ?
There is an inconsistency between the field used and the value applied by Rough Mobs.

**Comment by Luohuayu** [comment]
Mod should not reflect to get field using index. Please report to the mod author
