### ISSUE TITLE
[1.18.2] 服务端空指针崩溃

### ISSUE THREAD

**Issue by zimingYS** [Luohuayu/CatServer#799]
**运行环境**

Minecraft版本(1.12.2/1.16.5/1.18.2): 1.18.2
构建版本(从/version指令获取): CatServer-1.18.2-6c3f5965
相关模组/插件: 

**描述这个BUG**
(如果有报错请附上pastebin链接或上传日志文件)
在运行时会时不时崩溃，查看日志发现为：java.lang.NullPointerException: Cannot invoke "net.minecraft.world.entity.Entity.m_20182_()" because the return value of "net.minecraft.world.level.storage.loot.LootContext.m_78953_(net.minecraft.world.level.storage.loot.parameters.LootContextParam)" is null
[crash-2023-07-22_14.05.51-server.txt] (https://github.com/Luohuayu/CatServer/files/12135834/crash-2023-07-22_14.05.51-server.txt)

**导致的问题r**
server closed
直接关闭服务端

**复现方法**

**截图/视频**
(如果没有可以忽略)

**Comment by Kotori0629** [comment]
修过了
