### ISSUE TITLE
[Question] Will CatServer support 1.13?

### ISSUE THREAD

**Issue by Iltotore** [Luohuayu/CatServer#80]
Hi, I would like to know if CatServer will support 1.13 soon. Also, how can I contribute to this project ?

**Comment by TheDarkDnKTv** [comment]
Probably no, because mojang and forge again changed code so much, so Luohuayu need to do all this work from zero again. 1.13 dead version, i will recomend you to move on 1.14 and use Sponge. Sponge was created specially to use mods and plugins, but bukkit never worked properly with any mods.

**Comment by Luohuayu** [comment]
CatServer skips 1.13 and developing version 1.14.4

**Comment by Iltotore** [comment]
> CatServer skips 1.13 and developing version 1.14.4
Ok nice. I'll create a branch for this on my repo. I'm passing a competition. After it, I'll contribute to CatServer =p

>  will recomend you to move on 1.14 and use Sponge. Sponge was created specially to use mods and plugins, but bukkit never worked properly with any mods.
I want to contribute to Cat and create my fork for polyglots plugins/mods so I'll contribute to Cat

Secondly, CatServer supports Bukkit, Forge and Sponge API (tested it and works like a charm).
