### ISSUE TITLE
[1.16.5] 很奇怪的的问题

### ISSUE THREAD

**Issue by yuankun1** [Luohuayu/CatServer#800]
**运行环境**

Minecraft版本(1.16.5): 
构建版本(从/version指令获取): 
相关模组/插件: 
![QQ截图2023
![QQ截图20230722144337](https://github.com/Luohuayu/CatServer/assets/19505154/9b6062c2-38a8-441f-b24a-491b003cd39a)
0722144322](https://github.com/Luohuayu/CatServer/assets/19505154/4fc99b74-8b11-4e70-a0fd-65ce58d98150)
![QQ截图20230722144411](https://github.com/Luohuayu/CatServer/assets/19505154/2d3b6993-0cf2-4f1b-8e06-ed0022a7910e)
![QQ截图20230722144422](https://github.com/Luohuayu/CatServer/assets/19505154/7858195d-f5d3-48fb-aebb-f8e91f82451b)
服务端是cat最新版本
**描述这个BUG**
(如果有报错请附上pastebin链接或上传日志文件)
https://paste.ubuntu.com/p/MBWJvNrSB4/
https://paste.ubuntu.com/p/D4XQs6V9Hk/
log记录
[latest.log](https://github.com/Luohuayu/CatServer/files/12135891/latest.log)

**导致的问题r**
每次重启服务器它都会随机
挑一个world/serverconfig里面的配置文件变成乱码
然后导致崩溃 目前找不到好的办法解决这个问题...
**复现方法**

**截图/视频**
(如果没有可以忽略)

**Comment by Kotori0629** [comment]
或许你可以找找自身原因
