### ISSUE TITLE
[1.18.2] 使用蓝图加农炮加载蓝图时服务端崩溃

### ISSUE THREAD

**Issue by Harvey2433** [Luohuayu/CatServer#803]
**运行环境**

Minecraft版本(1.12.2/1.16.5/1.18.2): 1.18.2
构建版本(从/version指令获取):  CatServer-1.18.2-6c3f5965
相关模组/插件: 机械动力 0.5.1c，无插件

**描述这个BUG**
(如果有报错请附上pastebin链接或上传日志文件)
在游戏内使用蓝图加农炮加载蓝图时服务端崩溃，且导致存档在服务端无法加载
但在Forge官方服务端上，使用蓝图加农炮加载蓝图则运行正常
日志文件：
[latest.log](https://github.com/Luohuayu/CatServer/files/12209259/latest.log)

**导致的问题**
服务端崩溃，存档无法加载
**复现方法**
使用蓝图加农炮加载蓝图
**截图/视频**
(如果没有可以忽略)

https://github.com/Luohuayu/CatServer/assets/109860705/66fe8475-3411-4296-ac8c-b1817c1bc4d7

**Comment by NattoCB** [comment]
遇到同样问题

**Comment by Kotori0629** [comment]
内测已修
