### ISSUE TITLE
[1.18.2] curios未被加载

### ISSUE THREAD

**Issue by Y-Yuw** [Luohuayu/CatServer#805]
**运行环境**
Minecraft版本(1.12.2/1.16.5/1.18.2): 1.18.2
构建版本(从/version指令获取):  1.18.2-6c3f5965
相关模组/插件: 

**描述这个BUG**
(如果有报错请附上pastebin链接或上传日志文件)我会上传服务器mod文件，可以尝试跑一下，之前跑的没问题，就这几天跑不出来curios这个mod了
如果想要服务器本端的话我在二群可以找我要
**导致的问题r**
curios没了我饰品栏被吞了
[**复现方法**]
[logs.txt](https://github.com/Luohuayu/CatServer/files/12314768/logs.txt)
下面是mod
![image](https://github.com/Luohuayu/CatServer/assets/89560808/22520af5-92c6-4b2d-884f-239bbb4f6060)
![image](https://github.com/Luohuayu/CatServer/assets/89560808/075ef1e3-9137-4028-8478-111e87a50ecd)

**Comment by Luohuayu** [comment]
日志没搜到curios加载信息, 只搜到丢失curios相关信息, 检查mod文件

**Comment by Y-Yuw** [comment]
![image](https://github.com/Luohuayu/CatServer/assets/89560808/6b7da427-6d41-49d1-a83c-0a16c53e6bbe)
应该是没问题的，最早刚开服是没问题的，重启之后就不行了，发现问题之后我又从mc客户端拉来的mod，还是开不起来
[curios.zip](https://github.com/Luohuayu/CatServer/files/12337491/curios.zip)
curios文件在这

**Comment by Kotori0629** [comment]
未复现 如还有问题请重新开一个issue
