### ISSUE TITLE
[1.18.2] CMI / EssX 与 Multiverse-Core 联动导致错误发送数据包到客户端

### ISSUE THREAD

**Issue by NattoCB** [Luohuayu/CatServer#809]
**运行环境**

Minecraft版本(1.12.2/1.16.5/1.18.2): 1.18.2
构建版本(从/version指令获取): 6c3f596 当前最新release
相关模组/插件:  仅安装 CMI / EssentialsX & Multiverse-Core，无其他 mod、插件

**描述这个BUG**

没有报错日志，没有栈信息，没有崩溃

但会给客户端错误发包显示另一个世界2，但实际上玩家在另一个世界1

**导致的问题**

客户端收到错误的数据包

**复现方法**

* 安装 CMI 或 EssentialsX 二选一，安装  Multiverse-Core
* 使用 mv 创建一个新世界
* tp 到新世界
* 在新世界中调用 CMI 或 Ess 的 setspawn
* tp 到其他世界
* 死亡一次
* 重生后会发现被传送到了 overworld 世界（客户端side），但实际上是在新世界（服务端side）
* 此时会出现数据包不匹配的问题，玩家看到错误的世界，无法移动和互动，退出服务器也无法修复。除非重新启动 minecraft

**Comment by NattoCB** [comment]
后续尝试写了一个插件，在监测到 onPlayerDeathEvent 时立即 teleport 玩家到另一个世界，也会出现这个问题。但如果我把他改成：在监测到 onPlayerDeathEvent 时创建一个 Bukkit task，在下 1 tick 时才 teleport 玩家到另一个世界，就不会出现上述问题。不知这个情况和 CMI 的 setspawn 问题是否是同一个问题。

**Comment by Kotori0629** [comment]
最新版应该已经正常了，如果还有问题请再提一个issue
