### ISSUE TITLE
URL where to report issues

### ISSUE THREAD

**Issue by Black-Hole** [Luohuayu/CatServer#81]
Watchdog errors will show "Please report this to http://www.spigotmc.org/" which is misleading since there won't be any support for CatServer on the Spigot bug tracker. Like this report:
https://hub.spigotmc.org/jira/browse/SPIGOT-5520

Please change the URL or make it clear that there is no support on Spigot. Thank you.

**Comment by Iltotore** [comment]
Hi, I agree with you about support URL.
Secondly, does your server works without plugins/mods ?

**Comment by Luohuayu** [comment]
https://github.com/Luohuayu/CatServer/commit/116209e70f11b9bdf6cc6b0b1f8063535bfd28d0
