### ISSUE TITLE
[1.18.2] 发射器无法收回液体（岩浆、水等）

### ISSUE THREAD

**Issue by NattoCB** [Luohuayu/CatServer#816]
**运行环境**

Minecraft版本(1.12.2/1.16.5/1.18.2):  1.18.2
构建版本(从/version指令获取):  https://github.com/Luohuayu/CatServer/commit/6c3f59653b3cc3e1528206f1b5998ebeee62f3ba
相关模组/插件: 无

**描述这个BUG**
发射器无法收回液体（岩浆、水等）

**导致的问题**
发射器无法收回液体（岩浆、水等）

**复现方法**
发射器、岩浆桶、拉杆，测试放出、收回，即可

**Comment by AlanHuangKP** [comment]
你好，我也遇到相同的问题，请问你解决了吗？
