### ISSUE TITLE
[1.16.5]  这个能进服报告错误能修吗

### ISSUE THREAD

**Issue by yuankun1** [Luohuayu/CatServer#817]
**运行环境**

Minecraft版本(1.12.2/1.16.5/1.18.2): 
构建版本(从/version指令获取): 
相关模组/插件: 

**描述这个BUG**
(如果有报错请附上pastebin链接或上传日志文件)
https://paste.ubuntu.com/p/ZH7vPx2zj9/
**导致的问题r**
进服玩家获得不到cmi新手礼包物品
**复现方法**
新玩家级进服就报这个错误
**截图/视频**
(如果没有可以忽略)

**Comment by Kotori0629** [comment]
这mod更新1.16了？mod丢上来我看看

**Comment by yuankun1** [comment]
> 这mod更新1.16了？mod丢上来我看看

已经更新很久了
https://www.mcmod.cn/class/531.html

**Comment by yuankun1** [comment]
> 这mod更新1.16了？mod丢上来我看看

我已经基本可以确定百分百触发这个报错了
重启服务器 两个玩家同时进服 tps变成15 直接触发报错
然后玩家被踢出提示连接超时
但是后续后面进服不在回报错 但是会把tps变成15
log完整记录连接:https://paste.ubuntu.com/p/X9fF83ft4Y/

**Comment by Kotori0629** [comment]
意志坚定这mod找不到源码了

**Comment by yuankun1** [comment]
> 意志坚定这mod找不到源码了

那是不是就只能删模组了
每次触发这个东西都会导致我玩家集体掉线
2个也会掉线连接丢失

**Comment by Kotori0629** [comment]
> > 意志坚定这mod找不到源码了
> 
> 那是不是就只能删模组了 每次触发这个东西都会导致我玩家集体掉线 2个也会掉线连接丢失

不如尝试forge是否复现吧

**Comment by yuankun1** [comment]
> > > 意志坚定这mod找不到源码了
> > 
> > 
> > 那是不是就只能删模组了 每次触发这个东西都会导致我玩家集体掉线 2个也会掉线连接丢失
> 
> 不如尝试forge是否复现吧

没办法了 换了一个服务商也是这样
算了算了放弃了
