### ISSUE TITLE
[1.16.5] VehicleEntityCollisionEvent && VehicleEnterEvent doesn't work with mods

### ISSUE THREAD

**Issue by dayd21git** [Luohuayu/CatServer#819]
**Minecraft version**: 1.16.5
**Build version**: 1.16.5-671de43b
**Mods/Plugins:** MrCrayfish's Vehicle, MyPlugin
**Description:** When I use transport from the mod, the event is not called. There is no such problem with a vanilla minecart.

**Code:**
```java
@EventHandler
public void VehicleEntityCollisionEvent(VehicleEntityCollisionEvent e) {
	Bukkit.getConsoleSender().sendMessage("========== VehicleEntityCollisionEvent");
}

@EventHandler
public void VehicleEnterEvent(VehicleEnterEvent e) {
	Bukkit.getConsoleSender().sendMessage("========== VehicleEnterEvent");
}
```
**Log:**
```
Empty
```
I also want to remind you about a related problem: https://github.com/Luohuayu/CatServer/issues/786

**Comment by Kotori0629** [comment]
Have you tried other mods that have vehicles?

**Comment by dayd21git** [comment]
> Have you tried other mods that have vehicles?

No, but I can try if necessary!

**Comment by Kotori0629** [comment]
> > Have you tried other mods that have vehicles?
> 
> No, but I can try if necessary!

You can try.

**Comment by Kotori0629** [comment]
its work fine
