### ISSUE TITLE
铺地毯时自己听声音正常，在附近的其他玩家听声音为放置地毯下面方块的声音

### ISSUE THREAD

**Issue by LDS-XiaoYe** [Luohuayu/CatServer#82]
铺地毯时自己听声音正常，在附近的其他玩家听声音为放置地毯下面方块的声音

**Comment by Iltotore** [comment]
Sorry I'm French and I don't really understand. Did you mean all players in the server hear the carpet sound ?

**Comment by lyzx0220** [comment]
> Sorry I'm French and I don't really understand. Did you mean all players in the server hear the carpet sound ?

When someone place carpet,other players nearby will not hear the carpet sound but the block that under carpet

**Comment by Iltotore** [comment]
uh ok. I'll test this issue.

EDIT: I confirm this is a CatServer issue: I successfully experienced this issue without any mods/plugins.
EDIT 2: This problem occurs for ALL blocks. For example, when I place log on dirt, other players hear the dirt sound.

**Comment by Luohuayu** [comment]
https://github.com/Luohuayu/CatServer/commit/fb5d501d740314eabba22ef4b37fade3a86c89be
