### ISSUE TITLE
[1.16.5] debug纪录这些提示 有几率会导致玩家集体掉线吗？

### ISSUE THREAD

**Issue by yuankun1** [Luohuayu/CatServer#824]
**运行环境**

Minecraft版本(1.12.2/1.16.5/1.18.2): 
构建版本(从/version指令获取): 
相关模组/插件: 
冠军强敌champions-forge-1.16.5-2.0.1.16
魔改CraftTweaker-1.16.5-7.1.2.521
冠军强敌修改了许多boss以及生物
**描述这个BUG**
在本地服务端目录 跟本体mod
里面修改了许多的数据
魔改合成表魔改了许多物品
冠军强敌修改了许多boss以及生物
(如果有报错请附上pastebin链接或上传日志文件)
https://paste.ubuntu.com/p/rxZchjK7M6/
**导致的问题r**
会不会跟我修改
服务端本地文件目录的
合成表跟配置文件有关
导致每次玩家进服都要验证他们的客服端
导致集体掉线
**复现方法**
每个玩家进服偶读会提示只写信息
**截图/视频**
(如果没有可以忽略)

**Comment by Kotori0629** [comment]
并不会导致掉线
