### ISSUE TITLE
[1.16.5] 这个报告跟之前坚定意志报告应该是一样的

### ISSUE THREAD

**Issue by yuankun1** [Luohuayu/CatServer#825]
**运行环境**

Minecraft版本(1.16.5): 
构建版本(从/version指令获取): 
相关模组/插件: 
拔刀2
**描述这个BUG**
(如果有报错请附上pastebin链接或上传日志文件)
https://paste.ubuntu.com/p/yDv4H3w3rq/
**导致的问题r**
我基本可以确定只有 不过需要是不同地区IP地址
新玩家进服 都有几率会触发这段错误都代码
然后再服里面打玩家掉线重连 
**复现方法**

**截图/视频**
(如果没有可以忽略)

**Comment by Kotori0629** [comment]
不一样哈 并发修改异常 这大概往mod上改了

**Comment by yuankun1** [comment]
> 不一样哈 并发修改异常 这大概往mod上改了

那解决办法是？

**Comment by Kotori0629** [comment]
> > 不一样哈 并发修改异常 这大概往mod上改了
> 
> 那解决办法是？

说了啊不是 去改mod

**Comment by yuankun1** [comment]
> > > 不一样哈 并发修改异常 这大概往mod上改了
> > 
> > 
> > 那解决办法是？
> 
> 说了啊不是 去改mod

是吧服务端里面的mods改过的数据和配置文件都复制到 到客户端的配置文件和mods文件里面去吗
还是单单说改拔刀的数据  那脚本魔改的合成数据也要复制到客户端上吗

**Comment by yuankun1** [comment]
> > > > 不一样哈 并发修改异常 这大概往mod上改了
> > > 
> > > 
> > > 那解决办法是？
> > 
> > 
> > 说了啊不是 去改mod
> 
> OK
