### ISSUE TITLE
error fix please

### ISSUE THREAD

**Issue by LeePC** [Luohuayu/CatServer#83]
[latest.log](https://github.com/Luohuayu/CatServer/files/4095909/latest.log)

fix please

**Comment by Luohuayu** [comment]
The problem caused by the EffectWeapon plugin. Please check the plugin.

**Comment by LeePC** [comment]
I asked the manufacturer.
The EffectWeapon plug-in is intact.

**Comment by Luohuayu** [comment]
The plugin is rarely used, CatServer cannot provide support
