### ISSUE TITLE
[1.18.2] 缺少jar依赖

### ISSUE THREAD

**Issue by handy-git** [Luohuayu/CatServer#833]
![WJUU4S$(Y CGZI$CR${R}DR](https://github.com/Luohuayu/CatServer/assets/32837980/e4d46610-db6f-4130-b629-b9640de1514d)

**Comment by CalenXwX** [comment]
我在开服的时候同时安装CustomNPCs和QuickShop也遇到了这个问题QwQ
临时解决办法：从catserver官网下载依赖库[https://catserver.moe/download/libraries](https://catserver.moe/download/libraries)，那个里面有commons-codec-1.10.jar，复制到服务器目录下的 libraries\commons-codec\commons-codec\1.10 文件夹里（需要创建文件夹），然后用压缩软件打开CatServer的jar文件，打开 data 目录下的 libraries-launch.txt，在最后添加
`;libraries/commons-codec/commons-codec/1.10/commons-codec-1.10.jar`
然后保存，再启动就ok了XwX

然后就期待作者更新啦w
