### ISSUE TITLE
[1.18.2] forge模组自定义的指令会被bukkit/spigot拦截而无法使用

### ISSUE THREAD

**Issue by NattoCB** [Luohuayu/CatServer#835]
**运行环境**

Minecraft版本(1.12.2/1.16.5/1.18.2): 1.18.2 
构建版本(从/version指令获取): https://github.com/Luohuayu/CatServer/commit/6c3f59653b3cc3e1528206f1b5998ebeee62f3ba
相关模组/插件: 任意新模组

**描述这个BUG**
模组命令失效

**导致的问题**
模组命令失效

**复现方法**

写一个模组如下：
```java
    private static final Logger LOGGER = LoggerFactory.getLogger(TestMod.class);
    @SubscribeEvent
    public void onServerStarting(ServerStartingEvent event) {
        event.getServer().getCommands().getDispatcher().register(Commands.literal("testmod")
                .then(Commands.literal("test")
                       .executes(TestMod::testLogic)));
    }
    private static int testLogic(CommandContext<CommandSourceStack> context) {
        context.getSource().sendSuccess(new TextComponent("test"), false);
        LOGGER.info("test");
        return Command.SINGLE_SUCCESS;
    }
```
用 `/testmod test` 调用 testLogic 的 LOGGER 输出日志 test ，并给玩家发送信息 “test”

实测结果：
* 单机：成功输出日志并得到信息
* forge 服务器：客户端运行指令，成功输出日志并得到信息
* catserver 服务器：客户端运行指令，仅得到：[Server] Server thread/INFO Unknown command. Type "/help" for help. 而模组的命令并没有被调用

**Comment by Kotori0629** [comment]
经过测试后Create命令正常，若还有问题提供测试mod（我不晓得为什么拉不下来forgemdk）并再开启一个issue
