### ISSUE TITLE
[1.18.2] 唱片无法放入唱片机

### ISSUE THREAD

**Issue by CalenXwX** [Luohuayu/CatServer#836]
**运行环境**
Minecraft版本: 1.18.2 
构建版本(从/version指令获取): 
This server is running CatServer version 1.18.2-6c3f5965 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT, Forge version 40.2.4)
相关模组/插件: 无

**描述这个BUG**
手持唱片右键点击唱片机无法将唱片放入唱片机并播放音乐
推测是`paches/minecraft/net/minecraft/world/item/RecordItem.java.patch`文件中
`+            if (true) return InteractionResult.SUCCESS; // CraftBukkit - handled in ItemStack`
一行出现问题，此处直接结束了唱片的使用，并标注了在Bukkit中有处理，但似乎并没有找到在其他地方有处理。
经Mixin测试，若将此行插入的代码删除，则唱片机可正常使用，暂时未发现恢复原始代码会引发其他问题。

**导致的问题**
无法使用唱片和唱片机

**复现方法**
手持任意唱片右击唱片机 游戏模式不限

**Comment by Kotori0629** [comment]
嗯...原本在ItemStack的那方法else块中是有ItemRecord的处理 后来做CatServerEventHandler的时候被一块移除了应该。类似的问题应该还有不少，如果您有遇上可以帮我测试并提出。感谢

**Comment by CalenXwX** [comment]
> 嗯...原本在ItemStack的那方法else块中是有ItemRecord的处理 后来做CatServerEventHandler的时候被一块移除了应该。类似的问题应该还有不少，如果您有遇上可以帮我测试并提出。感谢

好哦w 如果遇到其他问题我尽量帮忙修改w（刚找到在哪里写回复.jpg）
