### ISSUE TITLE
[1.18.2] swem模组启动崩溃

### ISSUE THREAD

**Issue by BTXueLi** [Luohuayu/CatServer#840]
运行环境
Operating System: Linux (amd64) version 5.15.0-91-generic
Java Version: 17.0.9, Oracle Corporation
Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
Memory: 4676250024 bytes (4459 MiB) / 8589934592 bytes (8192 MiB) up to 8589934592 bytes (8192 MiB)
Minecraft版本(1.12.2/1.16.5/1.18.2):
构建版本(从/version指令获取):
相关模组/插件:
CatServer-1.18.2-bc64e1fc-server.jar
**描述这个BUG**
(如果有报错请附上pastebin链接或上传日志文件)
https://pastebin.ubuntu.com/p/v2kqtKdZFK/
**导致的问题r**
swem模组启动崩溃
**复现方法**
启动服务器
**截图/视频**
(如果没有可以忽略)

**Comment by Kotori0629** [comment]
嗯... 这样修会挨揍

**Comment by Kotori0629** [comment]
修了 最新版本
