### ISSUE TITLE
[1.18.2] 机械动力机械手击杀生物后无法触发 EntityDeathEvent（它该触发吗?

### ISSUE THREAD

**Issue by NattoCB** [Luohuayu/CatServer#845]
**运行环境**

Minecraft版本(1.12.2/1.16.5/1.18.2): 1.18.2
构建版本(从/version指令获取): bc64e1fc
相关模组/插件: **机械动力**

**描述这个BUG**

机械动力机械手击杀生物后无法触发 EntityDeathEvent 

> 先前的cat版本：[6c3f596](https://github.com/Luohuayu/CatServer/commit/6c3f59653b3cc3e1528206f1b5998ebeee62f3ba) 没有这个问题
> 最新的cat版本：[bc64e1fc](https://github.com/Luohuayu/CatServer/commit/bc64e1fcadfebb749df2c8eceff55daefda29f25) 存在这个问题
> 两次实验的 Create 机械动力模组均使用最新版 0.5.1f 进行的测试

**旧版 cat：6c3f596 实验结果：**

![截图20231224134754](https://github.com/Luohuayu/CatServer/assets/36336351/78fc9cea-7df2-42b1-acbe-8fd61efcca24)

**新版 cat：bc64e1fc 实验结果：**

![截图20231224134811](https://github.com/Luohuayu/CatServer/assets/36336351/e98f4065-4bb0-4c2e-9985-8f630185eb04)

**实验代码（插件）：**
```java
    @EventHandler
    public void onMobSpawn(EntitySpawnEvent e) {
        Player p = TestPlugin.getInstance().getServer().getPlayer("Dev");
        if (p != null && e.getEntity().getName().equals("Silverfish")) {
            p.sendMessage("SPAWN: " + e.getEntity().getName());
        }
    }
    @EventHandler
    public void onMobDespawn(EntityDeathEvent e) {
        Player p = TestPlugin.getInstance().getServer().getPlayer("Dev");
        if (p != null) {
            p.sendMessage("DEATH: " + e.getEntity().getName());
        }
    }
```

**导致的问题**

机械手击杀生物后，无法触发 EntityDeathEvent，也未生成经验球

**复现方法**

如上图，放置机械动力三个物品：
* 创造马达、传动杆、机械手
* 用扳手将机械手右键一次，设为攻击模式，去自动攻击玻璃中的生物
* 在玻璃中央放置任何生物

**Comment by Kotori0629** [comment]
masaka... 机械手能是ServerPlayer（？

**Comment by NattoCB** [comment]
> masaka... 机械手能是ServerPlayer（？

我看机械手对应的类是这个：
```java
package com.simibubi.create.content.kinetics.deployer;
...
@EventBusSubscriber
public class DeployerFakePlayer extends FakePlayer {
    ...
}
```
父类是：
```java
package net.minecraftforge.common.util;
...
public class FakePlayer extends ServerPlayer {
    ...
}
```

看起来的确是 ServerPlayer

**Comment by Kotori0629** [comment]
> > masaka... 机械手能是ServerPlayer（？
> 
> 我看机械手对应的类是这个：
> 
> ```java
> package com.simibubi.create.content.kinetics.deployer;
> ...
> @EventBusSubscriber
> public class DeployerFakePlayer extends FakePlayer {
>     ...
> }
> ```
> 
> 父类是：
> 
> ```java
> package net.minecraftforge.common.util;
> ...
> public class FakePlayer extends ServerPlayer {
>     ...
> }
> ```
> 
> 看起来的确是 ServerPlayer

好好好

**Comment by Kotori0629** [comment]
我又做了几遍测试 机械手杀死生物 真的会掉落经验值吗..

**Comment by Kotori0629** [comment]
留存...... 再修就不礼貌了

**Comment by NattoCB** [comment]
牛的
