### ISSUE TITLE
DungeonsXL causes server crash

### ISSUE THREAD

**Issue by WiseRomu** [Luohuayu/CatServer#85]
Hello! 
I'm running DungeonsXL0.18-SNAPSHOT-771 plugin on CatServer-a8d129c-universal
The plugin works fine on paperspigot vanilla server, but causes sever crash on CatServer when two players join two different dungeons. I'll paste the crash report below.
[crash-2020-01-24_15.45.29-server.txt](https://github.com/Luohuayu/CatServer/files/4111609/crash-2020-01-24_15.45.29-server.txt)
It seems that this spigot plugin doesn't work well on CatServer.
I will greatly appreciate it if you could consider this issue.
THX

**Comment by Luohuayu** [comment]
Fixed
