### ISSUE TITLE
[1.16.5]希望更新Forge版本 目前已有更新版本的Forge

### ISSUE THREAD

**Issue by FortyTwoCn** [Luohuayu/CatServer#851]
希望更新Forge版本 目前已有更新版本的Forge
https://files.minecraftforge.net/net/minecraftforge/forge/index_1.16.5.html
目前最新的Forge版本1.16.5 - 36.2.41

经过测试 该版本Forge似乎修复了龙之进化打开创造模式物品栏升级模块丢失的问题 

![370df68ee83f42a7ca5da63041c82439](https://github.com/Luohuayu/CatServer/assets/112876033/8ef9b2bf-6a96-4f28-bdea-155f17d6ef43)
![3a2b7e3386299ef1f396e6ec4ed6ba9e](https://github.com/Luohuayu/CatServer/assets/112876033/d4d65ebb-7a4d-4655-8647-2c07f75463cf)
![d72723ff5265d05946d1570d067cde3d](https://github.com/Luohuayu/CatServer/assets/112876033/0d007768-80b5-4da9-8839-895309626c0c)

**Comment by Kotori0629** [comment]
36.2.42更了

**Comment by FortyTwoCn** [comment]
> 36.2.42更了

catserver 1.18.2 有考虑支持lightfall吗

**Comment by Kotori0629** [comment]
> > 36.2.42更了
> 
> catserver 1.18.2 有考虑支持lightfall吗

有空一定

**Comment by FortyTwoCn** [comment]
> > > 36.2.42更了
> > 
> > catserver 1.18.2 有考虑支持lightfall吗
> 
> 有空一定

谢谢了 如果支持了 麻烦告诉我一下 awa
