### ISSUE TITLE
[1.18.2] spigot插件无法正确监听PlayerDropItemEvent事件

### ISSUE THREAD

**Issue by Daniel9572** [Luohuayu/CatServer#852]
**运行环境**
Minecraft版本(1.18.2): 
构建版本(从/version指令获取): CatServer version 1.18.2-6c3f5965 (MC: 1.18.2) (Implementing API version 1.18.2-R0.1-SNAPSHOT, Forge version 40.2.4) 以及CatServer-1.18.2-d364d488-server版本
相关模组/插件:  
AuthMe-5.6.0-beta2；
以及自研插件；
**描述这个BUG**
确定成功注册监听器Listener后，监听PlayerDropItemEvent的方法不生效，即使是简单的无条件输出日志。
**导致的问题r**
使用AuthMe插件的服务器，可以在玩家未登录的情况下，直接使用按键丢弃手持物品；
无法监听PlayerDropItemEvent将导致自研插件限制玩家丢弃物品的功能失效
**复现方法**
任意实现一个简单的监听器监听PlayerDropItemEvent事件，并确保监听器被成功注册。
注：切换其它服务器核心后，相关插件运行正常，可以排除是插件本身的问题
**截图/视频**

**Comment by NattoCB** [comment]
有同样问题，EntityDropItemEvent 也没有触发
