### ISSUE TITLE
[1.16.5] 貌似是饰品栏跟神秘遗物冲突了 导致崩溃

### ISSUE THREAD

**Issue by yuankun1** [Luohuayu/CatServer#854]
**运行环境**

Minecraft版本(1.12.2/1.16.5/1.18.2): 
构建版本(从/version指令获取): 
相关模组/插件: 
enigmaticlegacy
curios
**描述这个BUG**
(如果有报错请附上pastebin链接或上传日志文件)
https://paste.ubuntu.com/p/BnnVKJJRbP/
**导致的问题r**
不明
**复现方法**
不明
**截图/视频**
(如果没有可以忽略)

**Comment by Kotori0629** [comment]
参考 MC-183518

**Comment by Kotori0629** [comment]
合并之后再测试看看
