### ISSUE TITLE
Improvements for Telegram chat

### ISSUE THREAD

**Issue by DearFox** [Luohuayu/CatServer#856]
Although the chat on Telegram (https://t.me/CatServer) is not particularly active, I think that trusted persons should be given moderation rights.  Since there are not very respectful users (Internet trolls) who can spam the chat.

**Comment by Kotori0629** [comment]
Channel owners are not our developers

**Comment by DearFox** [comment]
> Channel owners are not our developers

yes, Sorry.  It’s just presented and advertised here on github and in the console, so I thought that this was your official chat.
