### ISSUE TITLE
[1.18.2] F3 + G 无法在客户端显示区块边界

### ISSUE THREAD

**Issue by NattoCB** [Luohuayu/CatServer#857]
**运行环境**

Minecraft版本(1.12.2/1.16.5/1.18.2): 1.18.2
构建版本(从/version指令获取): https://github.com/Luohuayu/CatServer/commit/ecf29bc1c0415372734f9fd7de8d6baa19f149b9
相关模组/插件: 无

**描述这个BUG**
原版单机测试 F3+G 可以显示边界
forge单机测试 F3+G 可以显示边界
spigot联机测试 F3+G 可以显示边界
cat 联机测试进服后 F3+G 仅提示边界显示已开启的消息，但并没有显示边界

**复现方法**
客户端进服后尝试 F3+G

**截图/视频**
![image](https://github.com/Luohuayu/CatServer/assets/36336351/3827796a-8507-45f6-b3a2-4f2e3a3666e0)

**Comment by Kotori0629** [comment]
![image](https://github.com/Luohuayu/CatServer/assets/81866089/626b34de-5d2b-4ddd-8ba2-8a4a214e38c1)
已经修复在某个commit里了
