### ISSUE TITLE
[1.18.2] No explosions 

### ISSUE THREAD

**Issue by Lucass27400** [Luohuayu/CatServer#866]
**Environment**

Minecraft version(1.18.2): 
Build version(Get from /version command): CatServer-1.18.2-23cd1bf0-server.jar
Mods/Plugins: TrajanTanks and EssentialsX

**Describe the bug**
I'm trying to make and explosion on server, when I blow up a tnt, it makes no damage, same with tanks on TrajanTanks

**Expected behavior**
Make an explosion damage

**To Reproduce**
Make exploding a tnt and if you want more, try with a mod which is making explosion damage

**Comment by Kotori0629** [comment]
can u try remove the TrajanTanks mod

**Comment by Kotori0629** [comment]
> can u try remove the TrajanTanks mod

Ok wait, i will try

**Comment by Kotori0629** [comment]
After I tried it, TNT and any explosives destroyed and the player took damage
