### ISSUE TITLE
[1.16.5] 玩家重生后重生点丢失

### ISSUE THREAD

**Issue by 1343008086** [Luohuayu/CatServer#868]
**运行环境**

Minecraft版本(1.12.2/1.16.5/1.18.2): 1.16.5
构建版本(从/version指令获取): CatServer version 1.16.5-69069a9c (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT, Forge version 36.2.39)
相关模组/插件: essentialsx

**描述这个BUG**
玩家在使用/tp /world之类的传送指令到非主世界的维度后死亡，复活回到主世界后出生点丢失

**导致的问题r**
玩家丢失出生点

**复现方法**
玩家使用/tp或/world等命令传送到下界
死亡
复活

**截图/视频**
(如果没有可以忽略)

**Comment by Kotori0629** [comment]
新的修了的
