### ISSUE TITLE
DungeonsXL doesn't work well

### ISSUE THREAD

**Issue by WiseRomu** [Luohuayu/CatServer#87]
Hello, It's me again :(
First of all, thank u for your timely update which really fixed the crash problem. Thank u very much.
However, there's still a problem here. I will tell u the whole process of how it happens.  
I let player 1 joins Dungeon 1, and then let player 2 joins Dungeon 2, the two dungeons are totally separated. Then I let both players leave the dungeons. In the earlier version of CatServer, the server would just crash at this point. This time, player 2 is fine but sth goes wrong with player 1. Player 1 is teleported to the main world(yes I mean the world named 'world')but not to the location where he was before he joined the dungeon. Besides that, there are floods of [Server thread/ERROR] popping out on the console. The error message is below. 
[Error.txt](https://github.com/Luohuayu/CatServer/files/4112219/Error.txt)

I guess the problem is not on DungeonsXL's side, because this plugin works perfectly well on paperspigot 1.12.2. 
I really need this plugin running on 1.12.2 modded server. I would appreciate it if u can take a look at it. If u need any other details about this problem, I'll be glad to help :)
Happy Chinese New Year!

**Comment by WiseRomu** [comment]
By the way, I've tried the latest async & universal version. Same problem.

**Comment by Luohuayu** [comment]
The plugin unload world, then delete the world directory. But Forge unload world in the next tick (Bukkit/Paper is unload directly), world files are still being used at this time. May require modifying the plugin.

**Comment by Luohuayu** [comment]
https://github.com/DRE2N/DungeonsXL/blob/master/core/src/main/java/de/erethon/dungeonsxl/world/DGameWorld.java#L474

**Comment by WiseRomu** [comment]
Well thank u very much!
But I’m noob with plugin development. I would like to know if you can help me with it? I really need it fixed. Is it free or not? I can pay if you ask for it. It’s not a problem:)
Thx!

**Comment by Luohuayu** [comment]
https://file.pizza/download/kvasz4mh

**Comment by WiseRomu** [comment]
Many thanks
But I'm not able to download it. The download won't start.
Could you please use other website or just upload it here?
Sorry for bothering you so long.

**Comment by Luohuayu** [comment]
[[Fix]dungeonsxl-dist-0.18-SNAPSHOT-767.zip](https://github.com/Luohuayu/CatServer/files/4112290/Fix.dungeonsxl-dist-0.18-SNAPSHOT-767.zip)
rename .zip to .jar

**Comment by WiseRomu** [comment]
It's so kind of you~really helps!
Thank you so much.

**Comment by WiseRomu** [comment]
I'm sorry but the problem is still here..

**Comment by WiseRomu** [comment]
The player still will be teleported to the main world instead of to their former location, after they leave the dungeons.

**Comment by Luohuayu** [comment]
Did you give me a server pack to test?

**Comment by WiseRomu** [comment]
You mean I send you my server pack to you now?

**Comment by Luohuayu** [comment]
yeah

**Comment by Luohuayu** [comment]
Are there any errors now?

**Comment by WiseRomu** [comment]
yes problem still...:(

**Comment by Luohuayu** [comment]
Fixed
https://github.com/Luohuayu/CatServer/commit/2bc3428b33f70747191ea76af2a34aedb545332a
