### ISSUE TITLE
[1.16.5] 请求兼容biggerstacks

### ISSUE THREAD

**Issue by mcmso** [Luohuayu/CatServer#871]
目前这个biggerstacks会导致超过原版堆叠上限的物品进入箱子堆叠会变成64
但是使用shift进入箱子里的物品正常
但是 使用背包整理也会使超过64+的物品变成64
希望兼容一下

**Comment by Kotori0629** [comment]
修了

**Comment by mcmso** [comment]
> 修了

草 1.16竟然还在维护 牛逼
