### ISSUE TITLE
[1.16.5] 请求更新Forge版本

### ISSUE THREAD

**Issue by FortyTwoCn** [Luohuayu/CatServer#875]
- 36.2.42 Generate SRG named redirects for TransformationMatrix methods in userdev (#9883)
 - 36.2.41 [1.16.5] Update more parts of the toolchain (#9825)
           * ForgeGradle 6, Gradle 8.4, ASM 9.6
           * Apply official mappings to patches (still using MCP classnames)
           * Remove reference to SpecialSource in reobfJar-like tasks
           * Backport modern MDK
           * Rename TransformationMatrix methods to prevent reobf, add back vanilla name via coremod
 - 36.2.40 Add modern TeamCity workflows & checks, backports some gradle stuff from 1.18.x branch (#9821)

**Comment by Kotori0629** [comment]
不敢更库啊

**Comment by Kotori0629** [comment]
更了 36.2.42了

**Comment by FortyTwoCn** [comment]
> 更了 36.2.42了

好的谢谢
