### ISSUE TITLE
开启了死亡掉落 Baubles 的饰品仍然掉落

### ISSUE THREAD

**Issue by LDS-XiaoYe** [Luohuayu/CatServer#88]
开启了死亡掉落 Baubles 的饰品仍然掉落

**Comment by komimoe** [comment]
请确认forge官服是否有这种情况

**Comment by LDS-XiaoYe** [comment]
> 请确认forge官服是否有这种情况

无

**Comment by Luohuayu** [comment]
已测试设置 `/gamerule keepInventory true` 玩家死亡后饰品栏的物品并不会掉落

**Comment by Luohuayu** [comment]
Baubles版本: 1.12-1.5.2
