### ISSUE TITLE
[Feature Request] Use Paper instead of Spigot

### ISSUE THREAD

**Issue by ishland** [Luohuayu/CatServer#90]
I would like CatServer to use Paper instead of Spigot. Paper is much more efficiency than Spigot in my opinion.

**Comment by Iltotore** [comment]
Hey. CatServer don't use the Spigot server but supports the Spigot API. it is based on Forge and not Spigot.

However, we can support the Paper API and the Paper config.

**Comment by ishland** [comment]
Alright and thanks for amazingly fast response.
