### ISSUE TITLE
[1.18.2] 使用BC（lightfall）时候 开启BCconfig 开启 ip_forward: true  spigot.yml  bungeecord: true 时候 子服无法进入 

### ISSUE THREAD

**Issue by FortyTwoCn** [Luohuayu/CatServer#900]
**运行环境**
JAVA17 Windowserver 2022
Minecraft版本(1.12.2/1.16.5/1.18.2):  1.18.2
构建版本(从/version指令获取): CatServer-1.18.2-edda1229-server
相关模组/插件:  Lightfall

**描述这个BUG**
(如果有报错请附上pastebin链接或上传日志文件)
使用BC（lightfall）时候 开启BCconfig 开启 ip_forward: true  spigot.yml  bungeecord: true 时候 子服无法进入 
[16:54:57] [Netty Server IO #2/INFO]: Disconnecting VANILLA connection attempt: This server has mods that require Forge to be installed on the client. Contact your server admin for more details.
下游子服换arclight-forge-1.18.2-1.0.12 无此问题
**导致的问题r**

**复现方法**

**截图/视频**
(如果没有可以忽略)

**Comment by FortyTwoCn** [comment]
//metrics.addCustomChart(new SimplePie("bungeecord", () -> SpigotConfig.bungee ? "true" : "false")); // TODO
                metrics.addCustomChart(new SimplePie("bungeecord", () -> "false"));
这里为啥要这么做

**Comment by Kotori0629** [comment]
因为没有声明过支持Bungee 也选择放弃Bungee
