### ISSUE TITLE
[1.16.5] Update to Forge 36.2.42

### ISSUE THREAD

**Issue by LanceLuckiest** [Luohuayu/CatServer#905]
It would be great if CatServer 1.16.5 would consider updating the forge version to 36.2.42.

This is because recently some mods for 1.16.5 like Corail Tombstone, have been updated and now require this specific Forge version.

**Comment by Kotori0629** [comment]
Updated at branch 1.16.5-patch

**Comment by LanceLuckiest** [comment]
> Updated at branch 1.16.5-patch

Where could I find the downloadable Jar file?

**Comment by Kotori0629** [comment]
> > Updated at branch 1.16.5-patch
> 
> Where could I find the downloadable Jar file?

wait release

**Comment by LanceLuckiest** [comment]
> > > Updated at branch 1.16.5-patch
> > 
> > 
> > Where could I find the downloadable Jar file?
> 
> wait release

Any update of this?
