### ISSUE TITLE
[1.16.5] 添加CMI后，启动时和运行时报错。

### ISSUE THREAD

**Issue by 1425115471** [Luohuayu/CatServer#906]
版本：1.16.5
插件：CMI
MOD：无

问题1：添加CMI后，启动时报错。
问题2：在游戏内使用CMI命令后报错，也无法使用（回家命令，其他还没有试过）。
[latest.log](https://github.com/user-attachments/files/17416270/latest.log)

**Comment by 1425115471** [comment]
![image](https://github.com/user-attachments/assets/95be8123-22e9-4bcc-9c61-36d724b8639b)
![image](https://github.com/user-attachments/assets/842dab6c-c1da-456e-8431-c95a2cb812c0)

**Comment by FortyTwoCn** [comment]
巧了 我也遇到了 这是CMI的问题 
Java 16 and up
PaperSpigot/Spigot/Tuinity - 1.7.10/1.8.x/1.9.x/1.10.x/1.11.x/1.12.x/1.13.x/1.14.x/1.15.x/1.16.x/1.17.x/1.18.x / 1.19.x / 1.20.x
[CMILib](https://www.spigotmc.org/resources/cmilib.87610/)

现在CMI需要java16 但是不清楚java16和低版本是怎么兼容的  换用旧版本CMI可以解决 还有CMIlib

**Comment by Kotori0629** [comment]
老实用旧版或升级你的MC版本
