### ISSUE TITLE
[求助]如何修改内置的forge到我想要的版本？

### ISSUE THREAD

**Issue by ljttty** [Luohuayu/CatServer#92]
在有些整合包中，最新的forge不能够支持就得mod，只能够降forge版本来运行整合包（不太好更新整合包中的mod），这时我应该用旧版本的catserver，还是能够修改配置文件，安装我想要的forge版本，第一次接触catserver，可能有些问题小白了，敬请谅解。

**Comment by Iltotore** [comment]
Sorry I'm french and translators failed to translate your message accurately. Could you explain a bit more your problem ?

Edit: ok I think I understand the problem: you have a forge mod which doesn't work with the latest cat version but did in lower version.

If I'm right, can you test your mod with only forge ?

**Comment by ljttty** [comment]
> Sorry I'm french and translators failed to translate your message accurately. Could you explain a bit more your problem ?
> 
> Edit: ok I think I understand the problem: you have a forge mod which doesn't work with the latest cat version but did in lower version.
> 
> If I'm right, can you test your mod with only forge ?

I don't know of any administrators who don't use Chinese. I'm sorry for the trouble.
I just want to define that I want forge version. There is no modpack in question.

**Comment by Luohuayu** [comment]
CatServer不再提供旧版Forge支持, 可尝试修改ForgeVersion.java并编译
