### ISSUE TITLE
开放式方块的bug

### ISSUE THREAD

**Issue by Coloryr** [Luohuayu/CatServer#93]
1.方块放置机无法正常工作：
![1](https://user-images.githubusercontent.com/26276037/73331730-bf017b00-429f-11ea-9f54-abc4f9ad19cb.png)
2.https://paste.ubuntu.com/p/cKW8RDwrYG/
（我自己找不到这个方法，实在无能为力修）

**Comment by Iltotore** [comment]
您好，您想要哪个版本的catserver？

**Comment by Luohuayu** [comment]
https://github.com/OpenMods/OpenModsLib/blob/264411c7f2204c4a4a3192880d547becec732950/src/main/java/openmods/container/ContainerBase.java#L96-L98
此方法与Bukkit的方法重名, 请反馈MOD作者

**Comment by Coloryr** [comment]
这个自己改了也一样

**Comment by Iltotore** [comment]
ok translators are definitively broken for translate chinese. Sorry for my inapropried awser.
