### ISSUE TITLE
Incompatibility with a few mods.

### ISSUE THREAD

**Issue by Al-Hashis** [Luohuayu/CatServer#95]
**FirstAid (1.6.12):** The player doesn't really respawn. It keeps at the ground with no heal on body parts but all heal on minecraft.

**AdvancedFishing (ver 1.3.3):** The fish hook doesn't show. Seams like the bukkit fishing system is buggy.

**FastWorkbench (ver 1.7.3):** The server crashes because "server" instance is not found.

**Comment by Iltotore** [comment]
Hi, can you send the stacktraces of these mods/plugins ?

**Comment by Al-Hashis** [comment]
Sorry, where can I find them?

**Comment by Iltotore** [comment]
You can find them in the logs. If you cant find them, send the full logs

**Comment by Luohuayu** [comment]
Build and use the fork of FastWorkbench: https://github.com/Luohuayu/FastWorkbench

**Comment by Luohuayu** [comment]
FirstAid is cannot be compatible

**Comment by Iltotore** [comment]
> https://github.com/Luohuayu/CatServer/issues/95#issuecomment-580728541

Why ?
