### ISSUE TITLE
实体导致服务器崩溃

### ISSUE THREAD

**Issue by Jo-maYple** [Luohuayu/CatServer#99]
https://paste.ubuntu.com/p/RvqyDtJgHK/

**Comment by Iltotore** [comment]
Hi, is all of your mods work on ForgeServer ?

**Comment by Jo-maYple** [comment]
yes

**Comment by Luohuayu** [comment]
多线程版的兼容性问题, 如果频繁崩溃请尝试关闭实体异步选项或者更换稳定版

**Comment by Luohuayu** [comment]
https://github.com/Luohuayu/CatServer/commit/20aba101334760b403439f7b9408dc77fdf77c8e
